<?php
$statusList   = Shared_Model_Code::codes('supply_status');
?>
<script type="text/javascript">
var pos = 0;
var reloadFlag = false;

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

$(function() {
    $(document).ready(function(){
    
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/supply-product";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            location.href = '/supply-product/detail?id=' + obj.id;
                            //jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/supply-product/add-post'
				});
        
            } else {
                return false;
            }
        });	
	});
    
	// 商品区分
    $('.uses_sales').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#uses_sales_other_text').prop("disabled", false);
			} else {
				$('#uses_sales_other_text').prop("disabled", true);
			}
		}
    });

    $('.uses_not_sales').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#uses_not_sales_other_text').prop("disabled", false);
			} else {
				$('#uses_not_sales_other_text').prop("disabled", true);
			}
		}
    });
	
	// タグ 選択ポップアップ表示
    $(document).on('click', '#select_tag', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/supply-product/tag-list-select', null, function () {stopSpinner();});
    });
    
	// タグ 条件検索
    $(document).on('click', '#search_tag', function () {
		updateTagList(1);
    });
    
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': 0});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// タグ 一覧ページ切り替え
function pageTag(pageNo) {
	updateTagList(pageNo)
}

// タグ 一覧更新
function updateTagList (pageNo) {
    var $form = $('#tag_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/supply-product/tag-list-select?page=' + pageNo,
    });
}

// タグ 選択完了
function selectTag(id, name) {
	$('#tag_name').html(name);
	$('#tag_id').val(id);
	$('.btn_close').click();
}

</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;margin-right:12px;}
.relation_type_item {margin-right:12px}
table.list_default tr td p.industory_category {background-color:#bae0ff;padding:11px 0 9px 12px}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.add_image_box {padding:13px 0;}
table.list_default tr td.column_value input.target_date, table.list_default tr td.column_value input.datepicker[type="text"] {width:180px;}
a.detail_supplier {display:block;background-color:#64bd63;color:#fff;padding:2px 3px;text-decoration:none;border-radius:5px;width:80px;text-align:center;margin:3px 3px 0 3px;float:left;cursor:pointer;}
.multi_rows_padding {padding:5px 0 5px 6px}
.connection_name_title {}
.status_text {font-size:1.2em;}
.condition_title {background-color:#bae0ff;padding-left:6px;font-weight:bold;}
.condition_label{float:left;}
.condition_row {margin-bottom:5px;border-top:1px solid #ccc;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>原料・製品 - 新規登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-top border-bottom border-right">
                    <p class="label_text strong">概要</p>
                </th>
            </tr>
		</table>
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">一般名称タグ<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="tag_name">---</p>
                    <a class="option" id="select_tag">選択</a>
                    <input type="hidden" id="tag_id" name="tag_id" value="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">原料製品名<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="title" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">原料製品内容</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<textarea name="description" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">用途<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	            	<div class="clearfix">
	            		<p class="industory_category">販売用途</p>
	                	<div class="clearfix">
	                		<?php foreach ($this->usesSalesList as $each) { ?>
			                	<div class="checkbox_item">
				                	<label>
				                    	<input type="checkbox" class="uses_sales" name="uses_sales[]" value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['name']); ?>
				                    </label>
			                    </div>
		                    <?php } ?>
							<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="uses_sales" name="uses_sales[]" value="<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>"><?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER_TITLE; ?>
			                    </label>
		                    </div>
						</div>
						<div class="clearfix" style="padding-bottom:8px;">
		                    <input type="text" id="uses_sales_other_text" name="uses_sales_other_text" placeholder="その他" disabled="disabled" value="" maxlength="" style="width:300px;float:left;" />
						</div>
						
						<p class="industory_category">非売用途</p>
	                	<div class="clearfix">
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="uses_not_sales" name="uses_not_sales[]" value="1">製造用構成品
			                    </label>
		                    </div>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="uses_not_sales" name="uses_not_sales[]" value="2">情報入手のみ
			                    </label>
		                    </div>
		                    
							<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="uses_not_sales" name="uses_not_sales[]" value="<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>"><?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER_TITLE; ?>
			                    </label>
		                    </div>
						</div>
						<div class="clearfix" style="padding-bottom:8px;">
		                    <input type="text" id="uses_not_sales_other_text" name="uses_not_sales_other_text" placeholder="その他" disabled="disabled" value="" maxlength="" style="width:300px;float:left;" />
						</div>
					</div>
					
					
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">用途メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<textarea name="uses_memo" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">調達方法・注意点等メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<textarea name="other_memo" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">ステータス<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="clearfix">
						<select class="short" id="status" name="status">
							<option value="">---</option>
                            <?php foreach ($statusList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>"><?php echo $this->escape($val); ?></option>
                            <?php } ?>
                    	</select>
	            	</div>
	            </td>
	        </tr>
		</table>

	</div><!-- clearfix -->	
    </form>
	
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>
