<?php
$statusList      = Shared_Model_Code::codes('receivable_status');
?>
<script type="text/javascript">
$(function () {
	$(".clear_form").bind("click", function(){
	    $(this.form).find('textarea, :text, :hidden:not("#view_type, #search, #page")').val("");
	    $(this.form).find('select option').removeAttr('selected');
	    $('.target_text').html('');
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
	});
	
    // 会計科目 選択ポップアップ表示
    $(document).on('click', '#select_account_title', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/office/accounting-select', null, function () {stopSpinner();});
    });
    
    // 会計科目 リセット
    $(document).on('click', '#reset_account_title', function () {
		$('#account_title_name_display').html('');
		$('#account_title_name').val('');
		$('#account_title_id').val('');
	});
    
	// 申請者 ポップアップ表示
    $(document).on('click', '#select_applicant_user', function () {
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/user/list-select', null, function () {stopSpinner();});
	});
    
	// 申請者 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    // 申請者 リセット
    $(document).on('click', '#reset_applicant_user', function () {
		$('#applicant_user_name_display').html('');
		$('#applicant_user_name').val('');
		$('#applicant_user_id').val('');
	});

    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });
    
    // 取引先 リセット
    $(document).on('click', '#reset_connection', function () {
		$('#connection_name_display').html('');
		$('#connection_name').val('');
		$('#connection_id').val('');
	});
	
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });

    
    $(document).on('click', '#popup_ok', function () {
    	if (reloadFlag) {
    		location.href = '/transaction-receivable/card-list?page=<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>&pos=' + $(window).scrollTop();
    	}
    });

    $(document).on('click', '.action_menu', function () {
	    var targetId = $(this).attr('target-id');
	    
	    if ($('#action_menu_frame_' + targetId).hasClass('selected')) {
		    $('#action_menu_frame_' + targetId).removeClass('selected');
	    } else {
		    $('.action_menu_frame').removeClass('selected');
		    $('#action_menu_frame_' + targetId).addClass('selected');
	    }
	});
	
    // 下書き
    $(document).on('click', '.update_to_draft', function () {
    	var targetId = $(this).attr('target-id');
		jConfirm('下書きに戻しますか', '　', function(r) {
			if(r) {
				showSpinner();
				$.ajax({
		            type:'POST',
		            dataType:'html',
		            data:'target_id=' + targetId,
		            success:function(res){
		            	stopSpinner();
		                reloadFlag = true;
		                jAlert('下書きに戻しました', '　');
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-receivable/update-to-draft'
		        });
		        
			} else {
			    return false;
			}
		});
    });
    
    // 削除
    $(document).on('click', '.delete', function () {
    	var targetId = $(this).attr('target-id');
		jConfirm('本当に削除にしますか', '　', function(r) {
			if(r) {
				showSpinner();
				$.ajax({
		            type:'POST',
		            dataType:'html',
		            data:'target_id=' + targetId,
		            success:function(res){
		            	stopSpinner();
		                reloadFlag = true;
		                jAlert('削除しました', '　');
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-receivable/delete'
		        });
		        
			} else {
			    return false;
			}
		});
    });
});

// 会計科目 選択完了
function selectAccountTitle(id, title) {
	$('#account_title_name_display').html(title);
	$('#account_title_name').val(title);
	$('#account_title_id').val(id);
	$('.btn_close').click();
}

// 申請者 一覧ページ切り替え
function pageUser(pageNo) {
	updateUserList(pageNo)
}

// 申請者 一覧更新
function updateUserList (pageNo) {
    var $form  = $('#user_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/user/list-select?page=' + pageNo,
    });
}

// 申請者 選択完了
function selectUser(id, departmentName, name, departmentNameEn, nameEn) {
	$('#applicant_user_name_display').html(departmentName + '　' + name);
	$('#applicant_user_name').val(departmentName + '　' + name);
	$('#applicant_user_id').val(id);
	$('.btn_close').click();
}

// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form  = $('#connection_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/connection/list-select?page=' + pageNo,
    });
}

// 取引先 選択完了
function selectConnection(id, displayId, name) {
	$('#connection_name_display').html(name);
	$('#connection_name').val(name);
	$('#connection_id').val(id);
	$('.btn_close').click();
}
</script>
<style type="text/css">
table.list_default tr:hover td {background:#deeeff;}
table.list_default tr.gray_out td {background-color:#eee}
table.list_default tr.gray_out:hover td {background:#eee;}
table.list_default tr th p, table.list_default tr td p {padding-left:5px;}
table.list_default tr th p.align_right, table.list_default tr td p.align_right {text-align:right;padding-left:0;padding-right:5px;}
table.list_default tr th p.align_center, table.list_default tr td p.align_center {text-align:center;padding-left:0;}

table.list_default tr td {overflow:inherit;}
table.list_default tr td a.btn_list_delete {position:absolute;left:60px;z-index:100;margin:5px 0 0px 5px;padding:7px 0 5px 0;line-height:1;display:block;cursor:pointer;background-color:#d90034;color:#fff;text-decoration:none;width:36px;text-align:center}
table.list_default tr td a.btn_list_delete:hover {text-decoration:none;background-color:#e8315d;}

.view_type_list {}
.view_type_list a.view_type {display:block;float:left;padding:11px 20px 0;height:22px;line-height:1;text-decoration:none;background-color: #c0f7fa;text-align:center;font-size: 1.1em;margin-right:5px;}
.view_type_list a.view_type.selected {background-color:#098d94;color:#fff;}
div.total {border:1px solid #ccc;background-color:#fafafa;padding:10px 11px;}
div.total p{font-size:1.2em;font-weight:bold;line-height:1.3}
div.total p.currency {float:left;width:50px;text-align:right}
div.total p.account_count {float:left;width:60px;text-align:right}
div.total p.total_amount {float:left;width:170px;text-align:right}
a.prev, a.next {text-decoration:none;background-color:#42adff;color:#fff;display:block;padding:5px 5px 3px;width:70px;text-align:center;float:left;font-weight:bold}
a.prev:visited, a.next:visited { color:#fff;}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin:5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:5px auto 10px;padding:7px 35px 5px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
table.list_default tr td p.attached {color:#2960f6;padding-left:0;text-align:center;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
		    <?php if ($this->allowEditing === true) { ?>
			<p style="position:absolute;width:76px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/transaction-receivable/card-add">新規登録</a>
            </p>
            <?php } ?> 
	        <span><strong>カード返金予定申請</strong></span>
	    </div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/transaction-receivable/list" method="get">
				<input type="hidden" id="search" name="search" value="1">
				<input type="hidden" id="page" name="page" value="1">
				
				<p class="search_condition_title">絞込条件</p>

				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="payment_status" name="payment_status">
                            <option value="">---</option>
                        	<?php foreach ($paymentStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['payment_status']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">通貨単位：</p>
                        <select id="currency_id" name="currency_id">
                            <option value="">---</option>
                        	<?php foreach ($this->currencyList as $each) { ?>
                                <option value="<?php echo $each['id']; ?>" <?php if ((string)$each['id'] === $this->conditions['currency_id']) echo 'selected="selected"';?>><?php echo $each['name']; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">会計科目：</p>
						<div class="input_box_fake">
							<span class="target_text" id="account_title_name_display"><?php echo $this->conditions['account_title_name']; ?></span>
							<a class="reset_popup" id="reset_account_title" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_account_title" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="account_title_name" name="account_title_name" value="<?php echo $this->conditions['account_title_name']; ?>">
						<input type="hidden" id="account_title_id" name="account_title_id" value="<?php echo $this->conditions['account_title_id']; ?>">
					</div>
					
					<div class="condition_item">
						<p class="condition_label">申請者：</p>
						<div class="input_box_fake">
							<span class="target_text" id="applicant_user_name_display"><?php echo $this->conditions['applicant_user_name']; ?></span>
							<a class="reset_popup" id="reset_applicant_user" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_applicant_user" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="applicant_user_name" name="applicant_user_name" value="<?php echo $this->conditions['applicant_user_name']; ?>">
						<input type="hidden" id="applicant_user_id" name="applicant_user_id" value="<?php echo $this->conditions['applicant_user_id']; ?>">
					</div>	
				</div>

				<div class="condition_items_row clearfix">	
					<div class="condition_item">
						<p class="condition_label">入金元：</p>
						<div class="input_box_fake">
							<span class="target_text" id="connection_name_display"><?php echo $this->conditions['connection_name']; ?></span>
							<a class="reset_popup" id="reset_connection" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_connection" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="connection_name" name="connection_name" value="<?php echo $this->conditions['connection_name']; ?>">
						<input type="hidden" id="connection_id" name="connection_id" value="<?php echo $this->conditions['connection_id']; ?>" />
					</div>
				</div>
				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット">
					<input type="submit" class="submit" style="display:inline-block;width:150px;" value="検索">
				</div>
			</form>
		</div>
	</div>
	

	<div class="clearfix">
		<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
    </div>
    
    
    <div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:7%;"><p>発生日</p></th>
				<th style="width:7%;"><p>入金予定日</p></th>
				<th style="width:6%;"><p>ステータス</p></th>
				<th style="width:7%;"><p>会計科目&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:9%;"><p>摘要&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:7%;"><p>採算コ&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:6%;"><p class="align_center">通貨単位</p></th>
				<th style="width:9%;"><p>金額</p></th>
				<th><p>支払元&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:8%;"><p>登録者&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:5%;"><p class="align_center">詳細</p></th>
			</tr>
				
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr>
						<td>
							<p><?php
								if (!empty($each['accrual_date'])) {
									echo date('Y-m-d', strtotime($each['accrual_date']));
								} else {
									echo '---';
								}
							 ?></p>
						</td>
						
						<td>
							<p><?php echo date('Y-m-d', strtotime($each['receive_plan_date'])); ?></p>
						</td>
						
						<td>
							<?php if ($each['status'] === (string)Shared_Model_Code::RECEIVABLE_STATUS_DRAFT) { ?>
								<p>下書き</p>
							<?php } else { ?>
								<?php if ($each['status'] === (string)Shared_Model_Code::RECEIVABLE_PAYMENT_STATUS_UNRECEIVED) { ?>
									<p><strong class="red"><?php echo $statusList[$each['status']]; ?></strong></p>
								<?php } else if ($each['status'] === (string)Shared_Model_Code::RECEIVABLE_PAYMENT_STATUS_RECEIVED) { ?>
									<p><strong><?php echo $statusList[$each['status']]; ?></strong></p>
								<?php } else { ?>
									<p><?php echo $statusList[$each['status']]; ?></p>
								<?php } ?>
							<?php } ?>
						</td>

						
						<td class="desc" all-content="<?php echo $this->escape($this->accountTitleList[$each['account_title_id']]['title']); ?>">
							<p><?php echo $this->roundText($this->escape($this->accountTitleList[$each['account_title_id']]['title']), 4); ?></p>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['memo']); ?>">
							<p><?php echo $this->roundText($this->escape($each['memo']), 6); ?></p>
						</td>
						
						
						<?php
						$groupTitle = '---';
						if (array_key_exists($each['account_totaling_group_id'], $this->groupList)) {
							$groupTitle = $this->groupList[$each['account_totaling_group_id']];
						}
						?>
						<td class="desc" all-content="<?php echo $this->escape($groupTitle); ?>">
							<p style="padding-left:3px"><?php echo $this->escape($this->roundText($groupTitle, 5)); ?></p>
						</td>
						
						<td>
							<p class="align_center"><?php if (!empty($each['currency_id'])) { echo $this->escape($this->currencyList[$each['currency_id']]['name']); } ?></p>
						</td>
						
						<td>
							<?php
								$totaltext = '';
								if (!empty($each['total_amount'])) {
									$totaltext = $this->escape(number_format($each['total_amount']));
								}	
							?>
							<p class="align_right"><?php echo $totaltext; ?></p>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['company_name']); ?>">
							<p><?php echo $this->roundText($this->escape($each['company_name']), 18); ?></p>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['user_name']); ?>">
							<p><?php echo $this->roundText($this->escape($each['user_name']), 5); ?></p>
						</td>

						<td style="position:relative;">
							<?php if (!empty($this->adminProperty['allow_delete_row_data'])) { ?>
								<div class="action_menu_frame" id="action_menu_frame_<?php echo $this->escape($each['id']); ?>">
									<a class="action_menu" target-id="<?php echo $this->escape($each['id']); ?>"><i class="icon-pencil"></i><i class="icon-down-dir-1"></i></a>
								    <ul>
									    <li><a class="update_to_draft" target-id="<?php echo $this->escape($each['id']); ?>">下書きに戻す</a></li>
								    	<li><a class="delete" target-id="<?php echo $this->escape($each['id']); ?>">削除</a></li>
								    </ul>
								</div>
							<?php } ?>
							<p class="align_center"><a href="/transaction-receivable/card-detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="14">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>
