<?php
$taxDivisionList = Shared_Model_Code::codes('tax_division');
?>
<script type="text/javascript">
var pos = 0;
var reloadFlag = false;
var rowCount = 0;
var targetOrderRow = '';

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

function dragover(e) {
    e.preventDefault();
}
					
function drop(id, e) {
	$('#' + id + '_add_image_box').removeClass('over');
	e.preventDefault();
	var files = e.dataTransfer.files;
  
	if (files.length > 1) {
  		jAlert('ファイルは一枚ずつドロップしてください。', 'エラー');
 	 	return;
	}

    // アップロード処理へ
    fileUpload(id, files[0]);
}

function fileUpload(id, fd) {
    var formData = new FormData();
    formData.append('file', fd);
	
	showSpinner();
	
    $.ajax({
      async: true,
      type:'POST',
      contentType: false,
      processData: false,
      url:'/transaction-receivable/upload',
      data:formData,
      dataType:'json'
    }).done(function(res){
    	stopSpinner();
    	
        var obj = res;
        if (obj.result == 'timeout') {
            location.href = '/login';
            return;            
        } else if(obj.result == true) {
        	$('#' + id + '_file_name_text').html(obj.file_name);
        	$('#' + id + '_file_name').val(obj.file_name);
        	$('#' + id + '_temp_file_name').val(obj.temp_file_name);
        } else {
        	jAlert('予期せぬエラーが発生しました', 'エラー');
        }
    });
}

$(function() {
    $(document).ready(function(){
		$('.datepicker').datepicker();
        $('.datepicker').datepicker("option", "dateFormat", "yy-mm-dd");
        $('.datepicker').datepicker("option", "yearSuffix", '年');
        $('.datepicker').datepicker("option", "monthNames", ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']);
		$('.datepicker').datepicker("option", "showMonthAfterYear", true);
        $('.datepicker').datepicker("option", "dayNames", ['日', '月', '火', '水', '木', '金', '土']);
        $('.datepicker').datepicker("option", "dayNamesMin", ['日', '月', '火', '水', '木', '金', '土']);
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/transaction-receivable/card-list";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
		showSpinner();

        var $form  = $('#register_form');
        var query  = $form.serialize();
        var params = $form.serializeArray();

        $.ajax({
            type:'POST',
            dataType:'json',
            data:params,
            success:function(res){
            	stopSpinner();
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                    
                } else if (obj.result == 'OK') {
                    location.href = '/transaction-receivable/card-detail?id=' + obj.id;
                    return;
                    
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error:function(){
            	stopSpinner();
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url:'/transaction-receivable/card-add-post'
		});
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/transaction-receivable/card-list';
        }
    });
    
    $(".sortable_column").sortable({
        items:"tr:not(.not-sortable)",
        update:function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay:100,
        stop:function (event, ui) {},
        start:function (event, ui) {}
    });

    // 行追加
    $(document).on('click', '.btn_add_column', function () {
    	var categoryId = $(this).attr('target-category');
    	if (categoryId == '4') {
	        var uuid = guid();
	        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', uuid + '_file_name_text').attr('name', uuid + '_file_name_text');
	        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', uuid + '_file_name').attr('name', uuid + '_file_name');
	        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', uuid + '_temp_file_name').attr('name', uuid + '_temp_file_name');
	        $('.column_copy_base_' + categoryId + ' .summary').attr('id', uuid + '_summary').attr('name', uuid + '_summary');
			$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', uuid + '_add_image_box').attr('ondrop', "drop('" + uuid + "',event)");
			$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);
			
	        var $clone = $('.column_copy_base_' + categoryId).clone(true);
	        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));
	        
	        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .summary').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', '');

	        
	        // ファイルのドロップ時エフェクト
			var targetE = document.getElementById(uuid + '_add_image_box');
			var innerFlag = false;
			
			targetE.addEventListener('dragenter', function () {
			    innerFlag = true;
			}, false);
			
			targetE.addEventListener('dragover', function () {
			    innerFlag = false;
			    targetE.className = 'add_image_box over';
			}, false);
			
			targetE.addEventListener('dragleave', function () {
			    if (innerFlag) {
			        innerFlag = false;
			    } else {
			        targetE.className = 'add_image_box';
			    }
			}, false);
		
	        $('.column_copy_base_' + categoryId + ' td.added_row').each(function(){
	            $(this).css('width', $(this).width() +'px');
	        });

	        var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
	    }
    });
    
    // 行削除
    $(document).on('click', '.delete_button', function () {
    	var categoryId = $(this).attr('target-category');
    	var targetId   = $(this).attr('target-row');
		$('tr#' + targetId).remove();
		
        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
    });

    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });

    // 会計科目 選択ポップアップ表示
    $(document).on('click', '#select_account_title', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/office/accounting-select', null, function () {stopSpinner();});
    });

    // 採算コード 選択ポップアップ表示
    $(document).on('click', '#select_account_totaling_group', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/financial-totaling/item-select', null, function () {stopSpinner();});
    });
    
    // 採算コード グループ切り替え
    $(document).on('change', '#account_totaling_group_category_id', function () {
		updateAccountTotalingList($(this).val());
	});
    
    // クレジットカード 選択ポップアップ表示
    $(document).on('click', '#select_card', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/financial/card-list-select', null, function () {stopSpinner();});
    });

    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });

});

// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form = $('#connection_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:param,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/connection/list-select?page=' + pageNo,
    });
}

// 取引先 選択完了
function selectConnection(id, displayId, name) {
	$('#connection_name').html(name);
	$('#target_connection_id').val(id);
	$('.btn_close').click();
}

// 会計科目 選択完了
function selectAccountTitle(id, title) {
	$('#account_title_name').html(title);
	$('#account_title_id').val(id);
	$('.btn_close').click();
}

// 採算コード 一覧更新
function updateAccountTotalingList(categoryId) {
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:null,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/financial-totaling/item-select?category_id=' + categoryId,
    });
}

// 採算コード 選択完了
function selectAccountTotalingGroup(id, groupName, title) {
	$('#account_totaling_group_name').html(groupName + '　＞　' + title);
	$('#account_totaling_group_id').val(id);
	$('.btn_close').click();
}

// クレジットカード 選択完了
function selectCard(id, cardName, last4) {
	$('#recieve_card_name').html(cardName + ' 下4ケタ: ' + last4);
	$('#recieve_card_id').val(id);
	$('.btn_close').click();
}
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:150px;}
table.list_default tr td.column_value select.short {width:300px;}
table.list_default tr td.column_value select.monthly {width:60px;float:left;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.payment_select {padding-top:6px;padding-left:1px;}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_count {border-right:none;background-color:#bae0ff;width:30px;}
table.list_default tr td.td_item_info {border-right:none;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
a.btn_setting#btn_copy {padding:1px 8px 0px;float:left;margin-left:20px;margin-top:5px;margin-bottom:0}
table.list_default tr td p.industory_category {background-color:#bae0ff;padding:11px 0 9px 12px}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1100px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}

.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}
.quote {margin:10px;padding:10px;background-color:#e3f2ff}
table.list_default tr td .quote p {padding:6px 0 8px 12px;height:auto;}

.menu_frame table.list_default tr td.column_value {border-right:none;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:120px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {float:left;width:20px;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding {width:280px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding.long {width:740px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value input[type="text"] {width:240px;display:block;float:left;}
.menu_frame table.list_default tr td textarea{width:620px;height:60px;}
.menu_frame table.list_default tr td.td_action {width:56px;border-right:none;padding-right:5px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
.menu_frame table.list_default.connection_base tr th {background-color:#bae0ff}
.menu_frame table.list_default.connection_base tr:hover td {background:#fff;}
.menu_frame table.list_default .multi_rows_padding {padding:5px 10px 5px 10px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:400px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>カード返金予定申請</strong></span>
        </div>
    </div>

    <form id="register_form" action="javascript:void(0);" method="post">
    <div class="clearfix">
    	
    	<input type="hidden" name="paying_type" value="<?php echo Shared_Model_Code::PAYABLE_PAYING_TYPE_INVOICE;?>" />
	    
	    <?php
        /* 基本情報 */
        $categoryId = 1;
        ?>
        <table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">基本情報</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">会計科目<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="clearfix">
	                	<p id="account_title_name" style="float:left;width:690px;">---</p>
	                    <a class="option" id="select_account_title">選択</a>
	                    <input type="hidden" id="account_title_id" name="account_title_id" value="">
	                </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">摘要<span class="popup_help" id="help_memo">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <textarea name="memo" style="height:100px;margin-bottom:6px;"></textarea>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">採算コード<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="clearfix">
						<p id="account_totaling_group_name" style="float:left;width:690px;">---</p>
						<input type="hidden" id="account_totaling_group_id" name="account_totaling_group_id" value="">
						<a class="option" id="select_account_totaling_group">選択</a>
	                </div>
                </td>
            </tr>
		</table>


		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">概要</p>
                </th>
            </tr>
		</table> 
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">支払元取引先<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="connection_name">---</p>
                    <a class="option" id="select_connection">取引先選択</a>
                    <input type="hidden" id="target_connection_id" name="target_connection_id" value="">
                </td>
            </tr>
            
            <tr class="paying_method_option paying_method_option_card">
                <td class="column_label"><p class="label_text">発生日<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="datepicker" id="accrual_date" name="accrual_date" value="" autocomplete="off" maxlength="">
                </td>
            </tr>
		</table>
		
		
	    <?php
        /* 入金予定情報 */
        $categoryId = 3;
        ?>  
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">入金予定情報</p>
                </th>
            </tr>
		</table> 
		<table class="list_default" style="margin-bottom:13px;">
            <tr class="paying_method_option paying_method_option_card">
                <td class="column_label"><p class="label_text">入金予定日<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="datepicker" id="receive_plan_date" name="receive_plan_date" value="" autocomplete="off" maxlength="">
                </td>
            </tr>
            
            <tr class="paying_method_option paying_method_option_card">
                <td class="column_label"><p class="label_text">入金予定クレジットカード<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="hidden" name="paying_method" value="<?php echo Shared_Model_Code::PAYABLE_PAYING_METHOD_CREDIT ?>" />
                	
					<p id="recieve_card_name">---</p>
                	<div class="clearfix">
                    	<a class="option" id="select_card">カード選択</a>
                    	<input type="hidden" id="recieve_card_id" name="card_id" value="">
                    </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">入金額(税込)<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php if ($this->data['template_type'] == (string)Shared_Model_Code::RECEIVABLE_TEMPLATE_TYPE_FIXED) { ?>
                		<p><?php
                			$currencyText = '';
                			foreach ($this->currencyList as $eachCurrency) {
                				if ($this->data['currency_id'] == $eachCurrency['id']) {
                					$currencyText = $eachCurrency['name'];
                				}
                			}
                			
                			if (!empty($this->data['total_amount'])) {
                				echo number_format($this->data['total_amount']) . '&nbsp;' . $this->escape($currencyText);
                			} else {
                				echo '';
                			}
                		?></p>
                    <?php } else { ?>
		            	<input type="text" style="float:left;width:150px;text-align:right;" id="total_amount" name="total_amount" value="" />
	                    <select style="float:left;width:90px;margin-left:5px;" id="currency_id" name="currency_id">
	                        <option value="">(通貨単位)</option>
	                    	<?php foreach ($this->currencyList as $eachCurrency) { ?>
	                            <option value="<?php echo $eachCurrency['id']; ?>" <?php if ($this->data['currency_id'] == $eachCurrency['id']) { echo 'selected="selected"'; } ?>><?php echo $this->escape($eachCurrency['name']); ?></option>
	                        <?php } ?>
	                    </select>
                    <?php } ?>
                </td>
            </tr> 
		</table>


	    <?php
        /* 添付ファイルアップロード */
        $categoryId = 4;
        ?>  
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">添付ファイルアップロード</p>
                </th>
            </tr>
		</table>   
        <table class="list_default" style="margin-bottom:0;">            
			<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">

        	</tbody>
		</table>
		<div style="border-bottom:1px solid #ccc;height:34px;margin-bottom:13px;">
            <p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
        </div>
		<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="file_list" value="" />

	</div><!-- clearfix -->	
    </form>
	
    <?php
    /*  添付ファイル */
    $categoryId = 4;
    ?> 
    <!-- copy base -->
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base_<?php echo $categoryId; ?>" id="">
			<td class="column_value">
				<div class="clearfix">
					<div style="float:left;width:360px;">
						<div class="clearfix" style="margin-bottom:5px">
							<div style="float:left;width:50px;padding:15px 0 0 10px;">
								<i class="budicon-equal" style="color:#aaa;font-size:48px;"></i>
							</div>
							<div style="float:left;width:300px;">
								<div class="multi_rows_padding" style="padding-left:18px;"><span class="file_name_text" id="##_file_name_text">(ファイル名)</span></div>
								<input type="hidden" class="file_name" id="##_file_name" name="##_file_name" value="" />
								<input type="hidden" class="temp_file_name" id="##_temp_file_name" name="##_temp_file_name" value="" />  
							</div>
						</div>
						<div class="add_image_box" id="##_add_image_box" ondragover="dragover(event)" ondrop="drop(##,event)" style="margin-bottom:13px;">
							<i class="icon-upload-cloud" style="font-size:60px;color:#888;"></i><br>ファイルをドラッグ&amp;ドロップしてください
						</div>
					</div>
					<div style="float:left;margin-left:10px;width:670px;">
						<p>メモ:</p>
						<textarea class="summary" name="##_summary" style="margin-top:9px;height:176px;margin-bottom:6px;"></textarea>
					</div>
				</div>
			</td>
            <td class="td_action">
            	<div class="delete_btn_frame">
            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row=""><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>    
	<!-- copy base -->



		       
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

