<?php
$statusList   = Shared_Model_Code::codes('supply_status');
?>

<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong>製造加工委託</strong></span>
    </div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<div class="condition_items clearfix">
		<form id="supply_production_condition_form" action="javascript:$('#search_supply_production').click();" method="get">
			<p class="search_condition_title">検索条件</p>

			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">XXX：</p>
                    <select id="status" name="status">
                        <option value="">---</option>
                    	<?php foreach ($connectionStatusList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">XXX：</p>
                    <select id="type" name="type">
                        <option value="">---</option>
                    	<?php foreach ($connectionTypeList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>

				<div class="condition_item">
					<p class="condition_label">XXX：</p>
                    <select id="relation_type" name="relation_type">
                        <option value="">---</option>
                    	<?php foreach ($relationTypeList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['relation_type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">XXX：</p>
                    <select id="sales_relation" name="sales_relation">
                        <option value="">---</option>
                    	<?php foreach ($salesRelationList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['sales_relation']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
			</div>	

			<div style="text-align:center">
				<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
				<input type="submit" id="search_supply_production" style="display:inline-block;width:150px;" value="検索" />
			</div>
		</form>
	</div>
</div>	

<div class="clearfix">
	<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:10%;"><p>製造加工委託ID</p></th>
			<th style="width:12%;"><p>ステータス</p></th>
			<th style="width:20%;"><p>目的&nbsp;<i class="icon-info-circle"></i></p></th>
			<th><p>製造加工委託名&nbsp;<i class="icon-info-circle"></i></p></th>
			<th style="width:8%;">
				<p>選択</p>
			</th>
		</tr>
	
		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>
				<tr id="<?php echo $each['id']; ?>">
					<td>
						<p><?php echo $each['display_id']; ?></p>
					</td>

					<td>
						<p><?php echo $statusList[$each['status']]; ?></p>
					</td>
					
					<?php
                		$selected = array();
                		$purposes = unserialize($each['purposes']);
                		if (!empty($purposes)) {
                			foreach ($purposes as $eachSelected) {
		                		foreach($this->purposeList as $eachPurpose) {
			                		if ($eachSelected === $eachPurpose['id']) {
			                			$selected[] = $eachPurpose['name'];
			                		}
		                		}
	                		}
	                	}
                	?>
					<td class="desc" all-content="<?php echo implode(' / ', $selected); ?>">
						<div class="multi_rows_padding"><?php echo $this->roundText(implode(' / ', $selected), 16); ?></div>
					</td>
					
					<td class="desc" all-content="<?php echo $this->escape($each['title']); ?>">
						<div class="multi_rows_padding"><?php echo $this->roundText($this->escape($each['title']),32); ?></a></div>
					</td>

					<td>
						<a class="option" href="javascript:selectSupplyProduction('<?php echo $each['id']; ?>', '<?php echo $this->escape($each['display_id']); ?>', '<?php echo $this->escape($each['title']); ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="5">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding:2.0em 0;">
    <?php echo $this->pager() ?>
    </div>
            
</div>


