<?php echo $this->doctype('HTML5'); ?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
<meta name="viewport" content="user-scalable=no, width=device-width" />
<meta name="format-detection" content="telephone=no" />

<link type="text/css" rel="stylesheet" href="/static/smartphone/front/css/style.css" media="all" />
<style><!--
body {
font-size: 12px;

}
div#body {
padding:0.5em;
}

h1 {
font-size:1.8em;
margin-top:0.5em;
margin-bottom:0.6em;
padding-bottom:0;
}
h2 {
font-size:1.4em;
margin-top:0.4em;
margin-bottom:0.4em;
padding-bottom:0;
}
h3 {
margin-top:0.3em;
margin-bottom:0.3em;
}

ul.bullet_point {
list-style-type:disc; margin-left: 1.8em;
}
ul.decimal {
list-style-type: decimal; margin-left:1.8em;
}
ul.abc {
list-style-type: lower-alpha; margin-left:1.8em;
text-align: left;
}
.indent{
padding-left: 1.0em;
}

--></style>
</head>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>
