<?php
$approvalStatusList = Shared_Model_Code::codes('approval_status');
$approvalTypeList   = Shared_Model_Code::codes('approval_type');
?>
<script type="text/javascript">
$(function () {
	$(".clear_form").bind("click", function(){
	    $(this.form).find("textarea, :text, :hidden, select").val("").end().find(":checked").prop("checked", false);
	    $('.target_text').html('');
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
		$('#condition_form').submit();
	});
	
	// 申請者 ポップアップ表示
    $(document).on('click', '#select_applicant_user', function () {
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/user/list-select', null, function () {stopSpinner();});
	});
    
	// 申請者 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    // 申請者 リセット
    $(document).on('click', '#reset_applicant_user', function () {
		$('#applicant_user_name_display').html('');
		$('#applicant_user_name').val('');
		$('#applicant_user_id').val('');
	});
	
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// 申請者 一覧ページ切り替え
function pageUser(pageNo) {
	updateUserList(pageNo)
}

// 申請者 一覧更新
function updateUserList (pageNo) {
    var $form = $('#user_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/user/list-select?page=' + pageNo,
    });
}

// 作成者 選択完了
function selectUser(id, departmentName, name, departmentNameEn, nameEn) {
	$('#applicant_user_name_display').html(departmentName + '　' + name);
	$('#applicant_user_name').val(departmentName + '　' + name);
	$('#applicant_user_id').val(id);
	$('.btn_close').click();
}
  
</script>
<style type="text/css">
table.list_default tr:hover td {background:#deeeff;}
table.list_default tr th p {padding-left:10px;}
table.list_default tr td p {padding-left:10px;padding-top:8px}
.multi_rows_padding {padding:5px 10px 5px 10px;line-height:1.6}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin:5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:5px auto 10px;padding:7px 35px 5px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <span style=""><strong>全履歴</strong></span>
	    </div>
	</div>


	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/approval/history-list" method="get">
				<p class="search_condition_title">検索条件</p>

				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="status" name="status">
                            <option value="">---</option>
                        	<?php foreach ($approvalStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">種別：</p>
                        <select id="type" name="type">
                            <option value="">---</option>
                        	<?php foreach ($approvalTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">申請者：</p>
						<div class="input_box_fake">
							<span class="target_text" id="applicant_user_name_display"><?php echo $this->conditions['applicant_user_name']; ?></span>
							<a class="reset_popup" id="reset_applicant_user" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_applicant_user" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="applicant_user_name" name="applicant_user_name" value="<?php echo $this->conditions['applicant_user_name']; ?>" />
						<input type="hidden" id="applicant_user_id" name="applicant_user_id" value="<?php echo $this->conditions['applicant_user_id']; ?>" />
					</div>
				</div>	

				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="submit" class="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</form>
		</div>
	</div>

	<div class="clearfix">
		<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
    </div>
	
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:15%;"><p>承認依頼日時</p></th>
				<th style="width:10%;"><p>ステータス</p></th>
				<th style="width:16%;"><p>種別</p></th>
				<th><p>内容&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:18%;"><p>申請者（利用者ID）</p></th>
				<th style="width:5%;">
					<p>操作</p>
				</th>
			</tr>
			
			<?php $costTable = new Shared_Model_Data_Cost(); ?>
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr>
						<td>
							<div class="multi_rows_padding">
								<?php echo date('Y-m-d H:i:s', strtotime($each['created'])); ?><br>
								<span style="color:#7000ff"><?php echo $this->dateTimeHistory($each['created']); ?></span>
							</div>
						</td>
						
						<td>
							<?php if ($each['status'] === (string)Shared_Model_Code::APPROVAL_STATUS_PENDDING) {?>
								<p><strong style="color:#f00;"><?php echo $approvalStatusList[$each['status']]; ?></strong></p>
							<?php } else { ?>
								<p><?php echo $approvalStatusList[$each['status']]; ?></p>
							<?php } ?>
						</td>
						<td><p><strong><?php echo $approvalTypeList[$each['type']]; ?></strong></p></td>
						
						<td class="desc" all-content="<?php echo $this->escape($each['title']); ?>">
							<div class="multi_rows_padding"><?php echo nl2br($this->roundText($this->escape($each['title']), 60)); ?></div>
						</td>
						
						<td>
							<div class="multi_rows_padding">
							<?php echo $this->roundText($this->escape($each['applicant_user_name']), 12); ?><br>
							<?php echo $this->escape($each['display_id']); ?>
							</div>
						</td>
						<td>
							<!--<a class="option"></a>-->
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="6">
						<p style="text-align:center;">承認待ちはありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

