<?php
$statusList   = Shared_Model_Code::codes('estimate_status');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
   		//Tipped.create('#help_keyword', "");
    });
    
	$(".clear_form").bind("click", function(){
	    $(this.form).find("textarea, :text, select").val("").end().find(":checked").prop("checked", false);
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
		$('#condition_form').submit();
	});
});    
</script>
<style type="text/css">
#data_area table.list_default tr th{position:relative;}
#data_area table.list_default tr th i{position:absolute;right:10px;margin-left:5px;font-size:1.2em}
#data_area table.list_default tr:hover td {background:#deeeff;}
#data_area table.list_default tr.deleted td {background:#ccc}
#data_area table.list_default tr.deleted:hover td {background:#bbb;}
#data_area table.list_default tr td p {height:auto;}
</style>

<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong>提出見積選択 - <?php echo $this->escape($this->connectionData['company_name']); ?></strong></span>
    </div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<div class="condition_items clearfix">
		<form id="estimate_condition_form" action="javascript:$('#search_estimate').click();" method="get">
			<p class="search_condition_title">検索条件</p>

			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">XXX：</p>
                    <select id="type" name="type">
                        <option value="">---</option>
                    	<?php foreach ($connectionTypeList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>

				<div class="condition_item" style="padding-top:23px;">
					<input type="button" id="clear_form" style="display:inline-block;width:116x;" value="リセット" />
					<input type="submit" id="search_estimate" style="display:inline-block;width:116px;" value="検索" />
				</div>
				
			</div>
		</form>
	</div>
</div>	

<div class="clearfix">
	<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:13%;"><p>更新日</p></th>
			<th style="width:10%;"><p>見積ID</p></th>
			<th style="width:10%;"><p>見積ステータス</p></th>
			<th style="width:18%;"><p>テンプレート</p></th>
			<th><p>表題<i class="icon-info-circle"></i></p></th>
			<th style="width:5%;"><p>詳細</p></th>
		</tr>

		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>

				<tr id="<?php echo $each['id']; ?>">
					<td>
						<p><?php echo date('Y-m-d H:i', strtotime($each['updated'])); ?></p>
					</td>
					
					<td>
						<p><?php echo $this->escape($each['display_id']); ?></p>
					</td>

					<td>
						<p><?php echo $statusList[$each['status']]; ?></p>
					</td>
					
					<td>
						<p><?php echo $this->templateList[$each['template_id']]['title']; ?></p>
					</td>

					<td class="desc" all-content="<?php echo $this->escape($each['title']); ?>">
						<p><?php echo $this->roundText($this->escape($each['title']), 20); ?></p>
					</td>
					
					<td>
						<p><a class="select_estimate_detail" target-id="<?php echo $this->escape($each['id']); ?>" href="javascript:void(0);">表示</a></p>
					</td>
					
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="8">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding:2.0em 0;">
    <?php echo $this->pager() ?>
    </div>
            
</div>


