<?php
	$isActiveList = Shared_Model_Code::codes('is_active');
?>
<script type="text/javascript">
var reloadFlag  = false;

$(function() {
    $(document).ready(function(){
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->escape($this->posTop); ?>);
        <?php } ?>
    });

    // 編集
    $(document).on('click', '.btn_edit_category', function () {
        var categoryId = $(this).attr('category_id');
        
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
    
        // ×,保存ボタン
        $('#cancel_category_' + categoryId).show();
        $('th#edit_category_' + categoryId).addClass('edit_mode');
        $(this).removeClass('btn_edit_category').addClass('btn_save_category');
        $('#btn_edit_label_' + categoryId).html('保存');
    });
    
    // 保存
    $(document).on('click', '.btn_save_category', function () {
        var button = $(this);
        var categoryId = $(this).attr('category_id');
        var $form  = $('#form_category_' + categoryId);
        var params = $form.serializeArray();
		
		var apiUrl = '';
		
		if (categoryId == '1') {
			apiUrl = '/organization/gmo-update?id=<?php echo $this->escape($this->id); ?>';
		} else {
			return;
		}
		
        $.ajax({
            type:'POST',
            dataType:'json',
            data:params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url:apiUrl,
        });
    });

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/organization/gmo-detail?id=<?php echo $this->escape($this->id); ?>&pos=' + $(window).scrollTop();
        }
    });
    
    // 編集中止
    $(document).on('click', '.btn_cancel_category', function () {
        var categoryId = $(this).attr('category_id');
        location.href = '/organization/gmo-detail?id=<?php echo $this->escape($this->id); ?>&pos=' + $(window).scrollTop();
    });

});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.multi_rows_padding {padding:5px 0 5px 10px}
table.list_default tr td.column_value input.zip {width:130px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title" style="margin-bottom:9px;">
            <span><strong>GMOアカウント - 詳細</strong></span>
        </div>
    </div>

    <div class="clearfix">
	    <?php
        /* 管理情報 */
        $categoryId = 1;
        ?>
		<form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th style="border-left:1px solid #ddd;border-top:1px solid #ddd;border-bottom:1px solid #ddd;"><p class="label_text strong">管理情報</p></th>
                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);">
                    <span>×</span>
                    </a>
                </th>
                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
                </th>
            </tr>
        </table>
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">ステータス</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $isActiveList[$this->data['status']]; ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<select class="short" id="status" name="status">
                            <?php foreach ($isActiveList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->data['status']) echo 'selected="selected"'; ?>><?php echo $val; ?></option>
                            <?php } ?>
                    	</select>
                	</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">最終更新日時</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo date('Y-m-d H:i:s', strtotime($this->data['updated'])); ?></p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">名義<span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['name']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="name" value="<?php echo $this->escape($this->data['name']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">クライアントID<span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['app_client_id']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" name="app_client_id" class="short" value="<?php echo $this->escape($this->data['app_client_id']); ?>" maxlength="" />
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">クライアントSecret<span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['app_client_secret']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;"> 
                    	<input type="text" name="app_client_secret" class="short" value="<?php echo $this->escape($this->data['app_client_secret']); ?>" maxlength="" />
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">アクセストークン</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->escape($this->data['gmo_access_token']); ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">アクセストークン有効期限</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->escape($this->data['gmo_access_token_expired_datetime']); ?></p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">リフレッシュトークン</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->escape($this->data['gmo_reflesh_token']); ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">リフレッシュトークン有効期限</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->escape($this->data['gmo_reflesh_token_expired_datetime']); ?></p>
                </td>
            </tr>

		</table>
		</form>
        
	</div><!-- clearfix -->	                

</div>
</div>
</div>
</div>

