<?php
	$isActiveList = Shared_Model_Code::codes('is_active');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
    });  
});
</script>
<style type="text/css">
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <p style="position:absolute; width:76px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/organization/add">新規登録</a>
            </p>
	        <span style=""><strong>GMOアカウント一覧</strong></span>
	    </div>
	</div>
	
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:10%;"><p>ID</p></th>
				<th style="width:10%;"><p>ステータス</p></th>
				<th style="width:15%;"><p>名義</p></th>
				<th style="width:5%;"><p>詳細</p></th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr>
						<td>
							<p><?php echo $this->escape($each['id']); ?></p>
						</td>

						<td>
							<p><?php echo $isActiveList[$each['status']]; ?></p>
						</td>
						
						<td>
							<p><?php echo $this->escape($each['name']); ?></p>
						</td>

						<td>
							<p><a href="/organization/gmo-detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="4">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

