<?php
$payementConditionList       = Shared_Model_Code::codes('order_payment_condition');
$payementConditionMonthList  = Shared_Model_Code::codes('connection_payment_condition_month');
$payementMonthlyList         = Shared_Model_Code::getPayementMonthlyList();
$timingList                  = Shared_Model_Code::codes('shipment_timing');
$deliveryCostList            = Shared_Model_Code::codes('delivery_cost');
?>
<script type="text/javascript">
var pos = 0;
var reloadFlag = false;
var rowCount = 0;
var targetItemRow = '';

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

function dragover(e) {
    e.preventDefault();
}
					
function drop(id, e) {
	$('#' + id + '_add_image_box').removeClass('over');
	e.preventDefault();
	var files = e.dataTransfer.files;
  
	if (files.length > 1) {
  		jAlert('ファイルは一枚ずつドロップしてください。', 'エラー');
 	 	return;
	}

    // アップロード処理へ
    fileUpload(id, files[0]);
}

function fileUpload(id, fd) {
    var formData = new FormData();
    formData.append('file', fd);
	
	showSpinner();
	
    $.ajax({
      async: true,
      type: 'POST',
      contentType: false,
      processData: false,
      url: '/transaction-order-recieved/upload',
      data: formData,
      dataType :'json'
    }).done(function(res){
    	stopSpinner();
    	
        var obj = res;
        if (obj.result == 'timeout') {
            location.href = '/login';
            return;            
        } else if(obj.result == true) {
        	$('#' + id + '_file_name_text').html(obj.file_name);
        	$('#' + id + '_file_name').val(obj.file_name);
        	$('#' + id + '_temp_file_name').val(obj.temp_file_name);
        } else {
        	jAlert('予期せぬエラーが発生しました', 'エラー');
        }
    });
}

$(function() {
    $(document).ready(function(){
		$('.datepicker').datepicker();
        $('.datepicker').datepicker("option", "dateFormat", "yy-mm-dd");
        $('.datepicker').datepicker("option", "yearSuffix", '年');
        $('.datepicker').datepicker("option", "monthNames", ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']);
		$('.datepicker').datepicker("option", "showMonthAfterYear", true);
        $('.datepicker').datepicker("option", "dayNames", ['日', '月', '火', '水', '木', '金', '土']);
        $('.datepicker').datepicker("option", "dayNamesMin", ['日', '月', '火', '水', '木', '金', '土']);
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/transaction-order-recieved/list";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
		jConfirm('登録しますか', '　', function(r) {
            if(r) {
				showSpinner();
		
		        var $form = $('#register_form');
		        var query = $form.serialize();
		        var param = $form.serializeArray();
		
		        $.ajax({
		            type:'POST',
		            dataType:'json',
		            data:param,
		            success:function(res){
		            	stopSpinner();
		                var obj = res;
		                if (obj.result == 'timeout') {
		                    location.href = '/login';
		                    return;
		                    
		                } else if(obj.result == 'OK') {
                            location.href = '/transaction-order-recieved/detail?id=' + obj.id;
                            return;
		                    
		                } else {
		                    jAlert('' + obj.message, '　');
		                }
		            },
		            error: function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-order-recieved/add-post'
				});
            } else {
                return false;
            }
        });
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/transaction-order-recieved/list';
        }
    });
    
    // 入金条件
    $('.payment_method').change(function() {
    	if ($(this).val()== 10) {
    		$('.payment_condition').show();
    	} else {
    		$('.payment_condition').hide();
    		$('.condition_option_val').hide();
    		$('#other_payment_condition').val('');
    		$('#other_payment_condition_other').hide();
    		$('#other_condition_option_val').hide();
    	}
    });
    
    // 入金条件その他
    $('.payment_condition').change(function() {
    	if ($(this).val() == '<?php echo Shared_Model_Code::CONNECTION_PAYMENT_CONDITION_OTHER; ?>') {
    		$('#other_payment_condition_other').show();
    	} else {
    		$('#other_payment_condition_other').hide();
    	}
    	
    	if ($(this).val() == '<?php echo Shared_Model_Code::CONNECTION_PAYMENT_CONDITION_BASED_DELIVERY; ?>' || $(this).val() == '<?php echo Shared_Model_Code::CONNECTION_PAYMENT_CONDITION_BASED_CLAIM; ?>') {
    		$('#other_condition_option_val').show();
    	} else {
    		$('#other_condition_option_val').hide();
    	}
    });
    
    
    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });

    // 行追加
    $(document).on('click', '.btn_add_column', function () {
    	var categoryId = $(this).attr('target-category');
		if (categoryId == '2') {
	        var uuid = guid();
	        rowCount++;
	        $('.column_copy_base_' + categoryId + ' .td_count p').html(rowCount);
	        
	        $('.column_copy_base_' + categoryId + ' .item_name').attr('id', uuid + '_item_name').attr('name', uuid + '_item_name');
	        $('.column_copy_base_' + categoryId + ' .item_id').attr('id', uuid + '_item_id').attr('name', uuid + '_item_id');
	        $('.column_copy_base_' + categoryId + ' .unit_price').attr('id', uuid + '_unit_price').attr('name', uuid + '_unit_price');
	        $('.column_copy_base_' + categoryId + ' .amount').attr('id', uuid + '_amount').attr('name', uuid + '_amount');
	        $('.column_copy_base_' + categoryId + ' .help_lot_unit').attr('id', uuid + '_help_lot_unit')
	        $('.column_copy_base_' + categoryId + ' .amount_unit').attr('id', uuid + '_amount_unit').attr('name', uuid + '_amount_unit');
	        $('.column_copy_base_' + categoryId + ' .price').attr('id', uuid + '_price').attr('name', uuid + '_price');
	        
	        $('.column_copy_base_' + categoryId + ' .reference_item_title').attr('id', uuid + '_reference_item_title');
	        $('.column_copy_base_' + categoryId + ' .reference_item_target_id').attr('id', uuid + '_reference_item_target_id').attr('name', uuid + '_reference_item_target_id');
	        $('.column_copy_base_' + categoryId + ' .select_item').attr('target-row', uuid);
	        $('.column_copy_base_' + categoryId + ' .clear_reference_item').attr('target-row', uuid);
	        
	        $('.column_copy_base_' + categoryId + ' .reference_estimate_title').attr('id', uuid + '_reference_estimate_title');
	        $('.column_copy_base_' + categoryId + ' .reference_estimate_target_id').attr('id', uuid + '_reference_estimate_target_id').attr('name', uuid + '_reference_estimate_target_id');
	        $('.column_copy_base_' + categoryId + ' .reference_estimate_target_row').attr('id', uuid + '_reference_estimate_target_row').attr('name', uuid + '_reference_estimate_target_row');
	        $('.column_copy_base_' + categoryId + ' .select_estimate').attr('target-row', uuid);
	        $('.column_copy_base_' + categoryId + ' .clear_reference_estimate').attr('target-row', uuid);
	        
			$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);

	        var $clone = $('.column_copy_base_' + categoryId).clone(true);
	        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));
	
	        $('.column_copy_base_' + categoryId + ' .item_name').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .item_id').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .unit_price').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .help_lot_unit').attr('id', '')
	        $('.column_copy_base_' + categoryId + ' .amount').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .amount_unit').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .price').attr('id', '');
			
			$('.column_copy_base_' + categoryId + ' .reference_item_title').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .reference_item_target_id').attr('id', '');
			
			$('.column_copy_base_' + categoryId + ' .reference_estimate_title').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .reference_estimate_target_id').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .reference_estimate_target_row').attr('id', '');
			
	        $('.column_copy_base_' + categoryId + ' td.added_row').each(function(){
	            $(this).css('width', $(this).width() +'px');
	        });

	        var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
		
		} else if (categoryId == '4') {
	        var uuid = guid();
	        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', uuid + '_file_name_text').attr('name', uuid + '_file_name_text');
	        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', uuid + '_file_name').attr('name', uuid + '_file_name');
	        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', uuid + '_temp_file_name').attr('name', uuid + '_temp_file_name');
	        $('.column_copy_base_' + categoryId + ' .summary').attr('id', uuid + '_summary').attr('name', uuid + '_summary');
			$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', uuid + '_add_image_box').attr('ondrop', "drop('" + uuid + "',event)");
			$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);
			
	        var $clone = $('.column_copy_base_' + categoryId).clone(true);
	        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));

	        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .summary').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', '');

	        
	        // ファイルのドロップ時エフェクト
			var targetE = document.getElementById(uuid + '_add_image_box');
			var innerFlag = false;
			
			targetE.addEventListener('dragenter', function () {
			    innerFlag = true;
			}, false);
			
			targetE.addEventListener('dragover', function () {
			    innerFlag = false;
			    targetE.className = 'add_image_box over';
			}, false);
			
			targetE.addEventListener('dragleave', function () {
			    if (innerFlag) {
			        innerFlag = false;
			    } else {
			        targetE.className = 'add_image_box';
			    }
			}, false);
		
	        $('.column_copy_base_' + categoryId + ' td.added_row').each(function(){
	            $(this).css('width', $(this).width() +'px');
	        });

	        var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
	    }
    });
    
    // 行削除
    $(document).on('click', '.delete_button', function () {
    	var categoryId = $(this).attr('target-category');
    	var targetId   = $(this).attr('target-row');
		$('tr#' + targetId).remove();
		
        var result = $("#sortable_column_" + categoryId).sortable("toArray");
        $('input#hidden_contents_order_' + categoryId).val(result);
        
        if (categoryId == '2') {
	        // 番号振り直し
	        var countUp = 0;
	    	$('#sortable_column_' + categoryId + ' tr').each(function(){
	    		countUp++;
	    		$('#sortable_column_' + categoryId + ' tr#' + $(this).attr('id') + ' .td_count p').html(countUp);
	    	});
		    	
	        rowCount = countUp;
        }
    });
    

    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });

    // 納入先拠点 選択ポップアップ表示
    $(document).on('click', '#select_base', function () {
    	console.log('select_base');
    	var connectionId = $('#target_connection_id').val();
    	
    	if (!connectionId) {
    		jAlert('先に「発注元取引先」を選択してください', '　');
    		return;
    	}
    
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/base-select?id=' + connectionId, null, function () {stopSpinner();});
    });
    
    // 出荷元倉庫 選択ポップアップ表示
    $(document).on('click', '#select_warehouse', function () {
    	console.log('select_warehouse');
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/warehouse/list-select', null, function () {stopSpinner();});
    });
    
    // 商品 選択 ポップアップ表示
    $(document).on('click', '.select_item', function () {
    	targetItemRow = $(this).attr('target-row');

   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);

		$('#data_area').load('/product/list-select', null, function () {stopSpinner();});
    });
    
    // 商品 選択 条件検索
    $(document).on('click', '#search_product', function () {
		updateProductList(1);
    });

    // 商品 引用解除
    $(document).on('click', '.clear_reference_item', function () {
    	var targetRow = $(this).attr('target-row');
		$('#' + targetRow + '_reference_item_title').html('---');
		$('#' + targetRow + '_reference_item_target_id').val('');
    });
    
    // 見積 選択ポップアップ表示
    $(document).on('click', '.select_estimate', function () {
    	var connectionId = $('#target_connection_id').val();
    	
    	if (connectionId == '') {
    		jAlert('先に「発注元取引先」を選択してください', '　');
    		return;
    	}
    	
    	targetItemRow = $(this).attr('target-row');
    	
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/price-estimate/list-select?connection_id=' + connectionId, null, function () {stopSpinner();});
    });
    
	// 見積 条件検索
    $(document).on('click', '#search_estimate', function () {
		updateEstimateList(1);
    });
 	
 	// 見積 一覧に戻る
    $(document).on('click', '.btn_back_list', function () {
    	var connectionId = $('#target_connection_id').val();
    	$('#data_area').html('');
    	$('#data_area').load('/price-estimate/list-select?connection_id=' + connectionId);
    });
	
	// 見積 選択
    $(document).on('click', '.select_estimate_detail', function () {
    	var id = $(this).attr('target-id');
    	$('#data_area').html('');
		$('#data_area').load('/price-estimate/detail-select?id=' + id);
    });
    
    // 見積書 行選択
    $(document).on('click', '.select_estimate_item', function () {
		$('#' + targetItemRow + '_reference_estimate_title').html('<strong>' + $(this).attr('estimate-id') + '</strong>&nbsp;' + $(this).attr('item-name'));
		$('#' + targetItemRow + '_reference_estimate_target_id').val($(this).attr('target-id'));
    	$('#' + targetItemRow + '_reference_estimate_target_row').val($(this).attr('target-row'));
    	
		$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
	});

    // 見積書引用解除
    $(document).on('click', '.clear_reference_estimate', function () {
    	var targetRow = $(this).attr('target-row');
		$('#' + targetRow + '_reference_estimate_title').html('---');
		$('#' + targetRow + '_reference_estimate_target_id').val('');
		$('#' + targetRow + '_reference_estimate_target_row').val('');
    });
    
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': 0});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
    
    // 出荷タイミング
    $('#shipment_timing').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::SHIPMENT_TIMING_NONE; ?>') {
			// 発送なしの場合
			$('#shipment_info').hide();
		} else {
			$('#shipment_info').show();
		}
    });
    
	// 通貨選択
    $('#currency_id').change(function() {
		var targetRow = $(this).attr('target-row');
		$('p.currency_unit').html($('#currency_id option:selected').text());
    });
    
	// 納品予定日
    $(document).on('click', '#is_delivery_plan_date_unknown', function () {
		if ($(this).prop('checked')) {
			$('#delivery_plan_date').prop("disabled", true);
			$('#delivery_plan_date').val('');
		} else {
			$('#delivery_plan_date').prop("disabled", false);
		}
    });
});

// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form = $('#connection_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/connection/list-select?page=' + pageNo,
    });
}

// 取引先 選択完了
function selectConnection(id, displayId, name) {
	$('#connection_name').html('<strong>' + displayId + '</strong>　' + name);
	$('#target_connection_id').val(id);
	$('.btn_close').click();
}


// 拠点 選択完了
function selectBase(id, name, address) {
	$('#base_name').html(name);
	$('#base_id').val(id);
	$('.btn_close').click();
}

// 倉庫 選択完了
function selectWarehouse(id, name) {
	$('#warehouse_name').html(name);
	$('#warehouse_id').val(id);
	$('.btn_close').click();
}

// 商品 一覧ページ切り替え
function pageProduct(pageNo) {
	updateProductList(pageNo)
}

// 商品 一覧更新
function updateProductList (pageNo) {
    var $form = $('#product_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/product/list-select?page=' + pageNo,
    });
}

// 商品 選択完了
function selectProduct(id, itemId, name, buyingName) {
	$('#' + targetItemRow + '_item_name').val(name);
	$('#' + targetItemRow + '_reference_item_title').html('<strong>' + itemId + '</strong>&nbsp;'+ name);
	$('#' + targetItemRow + '_reference_item_target_id').val(id);
	$('.btn_close').click();
}

// 見積書 一覧ページ切り替え
function pageEstimate(pageNo) {
	updateEstimateList(pageNo)
}

// 見積書 一覧更新
function updateEstimateList (pageNo) {
	var connectionId = $('#target_connection_id').val();
	
    var $form = $('#estimate_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/price-estimate/list-select?connection_id=' + connectionId + 'page=' + pageNo,
    });
}

</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:150px;}
table.list_default tr td.column_value select.short {width:300px;}
table.list_default tr td.column_value select.monthly {width:60px;float:left;}
table.list_default tr td.column_value p.currency_unit {float:left;margin-left:5px}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.payment_select {padding-top:6px;padding-left:1px;}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_count {border-right:none;background-color:#bae0ff;width:30px;}
table.list_default tr td.td_item_info {border-right:none;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
a.btn_setting#btn_copy {padding:1px 8px 0px;float:left;margin-left:20px;margin-top:5px;margin-bottom:0}
table.list_default tr td p.industory_category {background-color:#bae0ff;padding:11px 0 9px 12px}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1100px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}

.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}
.quote {margin:10px;padding:10px;background-color:#e3f2ff}
table.list_default tr td .quote p {padding:6px 0 8px 12px;height:auto;}

.menu_frame table.list_default tr td.column_value {border-right:none;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:120px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {float:left;width:20px;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding {width:280px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding.long {width:740px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value input[type="text"] {width:240px;display:block;float:left;}
.menu_frame table.list_default tr td textarea{width:620px;height:60px;}
.menu_frame table.list_default tr td.td_action {width:56px;border-right:none;padding-right:5px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
.menu_frame table.list_default.connection_base tr th {background-color:#bae0ff}
.menu_frame table.list_default.connection_base tr:hover td {background:#fff;}
.menu_frame table.list_default tr th.edit_category a.btn_select_uploaded {
background-color: #00469b;color:#fff;display:inline-block;font-size:12px;transition:all 200ms ease-in 0s;width:68px;
height:35px;padding:0;margin:0;cursor:pointer;text-decoration:none;
}
a.btn_edit_category span, a.btn_add_category span, a.btn_select_uploaded span {display:block;padding:11px 0 0 0;line-height:1;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:400px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>新規受注登録</strong></span>
        </div>
    </div>

    <form id="register_form" action="javascript:void(0);" method="post">
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">基本情報</p>
                </th>
            </tr>
		</table>   
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">発注元取引先<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="connection_name">---</p>
                    <a class="option" id="select_connection">取引先選択</a>
                    <input type="hidden" id="target_connection_id" name="target_connection_id" value="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">受注日<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="datepicker" name="order_recieved_date" value="" autocomplete="off" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">出荷タイミング<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
						<select class="short" id="shipment_timing" name="shipment_timing">
							<option value="">---</option>
	                        <?php foreach ($timingList as $key => $val) { ?>
	                            <option value="<?php echo $key; ?>" ><?php echo $this->escape($val); ?></option>
	                        <?php } ?>
	                	</select>
	                </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">入金条件<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="payment_select">
	                	<label>
	                    	<input class="payment_method" type="radio" name="payment_method" value="1">注文時支払（納入前払い）
	                    </label>
                    </div>
                	<div class="payment_select">
	                	<label>
	                    	<input class="payment_method" type="radio" name="payment_method" value="2">納入月末締め 翌月末払い
	                    </label>
                    </div>
                	<div class="payment_select" style="margin-bottom:5px;">
						<label>
	                    	<input class="payment_method" type="radio" name="payment_method" value="10">その他
	                    </label>
                		
                		<div class="clearfix">
		                	<select class="short payment_condition" id="other_payment_condition" name="other_payment_condition" style="float:left;margin-right:20px;display:none;">
	                            <option value="">---</option>
	                            <?php foreach ($payementConditionList as $key => $val) { ?>
	                                <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
	                            <?php } ?>
	                    	</select>
	                    	
	                    	<div class="clearfix condition_option_val" id="other_condition_option_val" style="float:left;display:none;">
	                    		<select class="monthly payment_condition_close" id="other_payment_condition_close" name="other_payment_condition_close">
		                            <option value="">---</option>
		                            <?php foreach ($payementMonthlyList as $key => $val) { ?>
		                                <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
		                            <?php } ?>
		                    	</select>
		                    	<p style="float:left;margin-right:20px;">締め</p>
		                    	<select class="monthly payment_condition_month" id="other_payment_condition_month" name="other_payment_condition_month" style="margin-right:5px;">
		                            <option value="">---</option>
		                            <?php foreach ($payementConditionMonthList as $key => $val) { ?>
		                                <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
		                            <?php } ?>
		                    	</select>
	                    		<select class="monthly payment_condition_pay" id="other_payment_condition_pay" name="other_payment_condition_pay">
		                            <option value="">---</option>
		                            <?php foreach ($payementMonthlyList as $key => $val) { ?>
		                                <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
		                            <?php } ?>
		                    	</select>
	                    		<p style="float:left;margin-right:20px;">払い</p>
	                    	</div>
							<input type="text" class="payment_condition_other" id="other_payment_condition_other" name="other_payment_condition_other" value="" placeholder="その他条件内容" maxlength="" style="width:500px;float:left;display:none;" />
						</div>
                    </div>
                    
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">送料負担<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
	                	<?php foreach ($deliveryCostList as $key => $val) { ?>
		                	<div class="checkbox_item relation_type_item">
			                	<label>
			                    	<input type="radio" name="delivery_cost" value="<?php echo $key; ?>"><?php echo $val; ?>
			                    </label>
		                    </div>
	                    <?php } ?>
	                </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">受注金額(税抜)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
	                	<input type="text" name="subtotal" value="" maxlength="" style="float:left;text-align:right;width:200px;" />
	                	<p class="currency_unit"></p>
	                </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">税額</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
	                	<input type="text" name="tax" value="" maxlength="" style="float:left;text-align:right;width:200px;" />
	                	<p class="currency_unit"></p>
	                </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">受注合計金額(税込)<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
	                	<input type="text" name="total_with_tax" value="" maxlength="" style="float:left;text-align:right;width:200px;" />
	                	<select style="float:left;width:90px;margin-left:5px;" id="currency_id" name="currency_id">
	                        <option value="">(通貨単位)</option>
	                    	<?php foreach ($this->currencyList as $eachCurrency) { ?>
	                            <option value="<?php echo $eachCurrency['id']; ?>" <?php if ($this->data['currency_id'] == $eachCurrency['id']) { echo 'selected="selected"'; } ?>><?php echo $this->escape($eachCurrency['name']); ?></option>
	                        <?php } ?>
	                    </select>
	                </div>
                </td>
            </tr>

            <tr>
	            <td class="column_label"><p class="label_text">納品予定日<span class="require">＊</span></p></td>
	            <td class="colon"><p class="label_text">：</p></td>
	            <td class="column_value">
		            <div class="clearfix">
		            	<label style="margin-top:5px;display:block"><input type="checkbox" id="is_delivery_plan_date_unknown" name="is_delivery_plan_date_unknown">未定（自動的に一週間後に設定されます）</label>
	            		<input type="text" class="datepicker" style="width:120px;margin-bottom:5px;" id="delivery_plan_date" name="delivery_plan_date" value="" autocomplete="off">
					</div>
	            </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">備考</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <textarea name="memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['memo']); ?></textarea>
                </td>
            </tr>
		</table>



	    <?php
	    /* 受注内容 */
	    $categoryId = 2;
	    ?>
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">受注内容<span class="require">&nbsp;＊</span></p>
                </th>
            </tr>
		</table>	
        <table class="list_default" style="margin-bottom:0;">
			<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
			</tbody>
        </table>
        <div style="border-bottom:1px solid #ccc;height:34px;margin-bottom:13px;">
            <p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
        </div>
    	<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="item_list" value="" />


	    <?php
	    /* 出荷指示情報 */
	    $categoryId = 3;
	    ?>
 		<div id="shipment_info">
	 		<table class="list_default" style="margin-bottom:0;">
	            <tr>
	                <th class="border-left border-right border-top border-bottom">
	                    <p class="label_text strong">出荷指示情報</p>
	                </th>
	            </tr>
			</table>
	        <table class="list_default" style="margin-bottom:13px;">
	            <tr>
	                <td class="column_label"><p class="label_text">納入先拠点</p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                	<p id="base_name">---</p>
	                    <a class="option" id="select_base">拠点選択</a>
	                    <input type="hidden" id="base_id" name="base_id" value="" />
	                </td>
	            </tr>
	
	            <tr>
	                <td class="column_label"><p class="label_text" style="padding-left:12px;">出荷元倉庫<span class="require">&nbsp;＊</span></p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                	<p id="warehouse_name">---</p>
	                    <a class="option" id="select_warehouse">倉庫選択</a>
	                    <input type="hidden" id="warehouse_id" name="warehouse_id" value="" />
	                </td>
	            </tr>
	            
	            <tr>
	                <td class="column_label"><p class="label_text">出荷希望日</p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                    <input type="text" class="datepicker" name="shipment_request_date" value="" maxlength="" />
	                </td>
	            </tr>
	              
	            <tr>
	                <td class="column_label"><p class="label_text" style="padding-left:12px;">配送方法指示</p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                    <textarea name="delivery_method" style="height:100px;margin-bottom:6px;"></textarea>
	                </td>
	            </tr>
	            
	            <tr>
	                <td class="column_label"><p class="label_text" style="padding-left:12px;">伝達事項</p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                    <textarea name="shipment_memo" style="height:100px;margin-bottom:6px;"></textarea>
	                </td>
	            </tr>
			</table>
		</div><!-- shipment info -->

	    <?php
	    /* 添付資料 */
	    $categoryId = 4;
	    ?>
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">添付資料</p>
                </th>
            </tr>
		</table>	
        <table class="list_default" style="margin-bottom:0;">
			<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
			</tbody>
        </table>
        <div style="border-bottom:1px solid #ccc;height:34px;margin-bottom:13px;">
            <p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
        </div>
    	<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="file_list" value="" />

	</div><!-- clearfix -->	
    </form>
    
    
    
    <?php
    /* 受注内容 */
    $categoryId = 2;
    ?>
    <!-- copy base -->
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base_<?php echo $categoryId; ?>">
        	<td class="td_count">
        		<p>##</p>
        	</td>
            <td class="td_item_info">
            	<div class="clearfix">
	            	<div style="float:left;width:1000px">
	            		<p style="float:left;width:70px;">商品名<span class="require">&nbsp;＊</span>：</p>
	            		<input type="text" class="item_name" id="##_item_name" name="##_item_name" value="" style="width:900px;float:left;" />
	            		<input type="hidden" class="item_id" id="##_item_id" name="##_item_id" value="" />
	            	</div>
	            </div>	
	            <div class="clearfix">	
	            	<div style="float:left;width:240px">
	            		<p style="float:left;width:70px;">単価<span class="require">&nbsp;＊</span>：</p>
	            		<input type="text" class="unit_price" id="##_unit_price" name="##_unit_price" value="" style="width:100px;float:left;" />
	            		<p class="currency_unit"></p>
	            	</div>
	            	<div style="float:left;width:160px">
	            		<p style="float:left">数量<span class="require">&nbsp;＊</span>：</p>
	            		<input type="text" class="amount" id="##_amount" name="##_amount" value="" style="width:90px;float:left;" />
	            	</div>
	            	<div style="float:left;width:220px">
	            		<p style="float:left">数量単位<span class="require">&nbsp;＊</span><span class="help_lot_unit">&nbsp;<i class="icon-help-circled"></i></span>：</p>
	            		<input type="text" class="amount_unit" id="##_amount_unit" name="##_amount_unit" value="" style="width:90px;float:left;" />
	            	</div>
	            	<div style="float:left;width:240px">
	            		<p style="float:left">小計<span class="require">&nbsp;＊</span>：</p>
	            		<input type="text" class="price" id="##_price" name="##_price" value="" style="width:120px;float:left;" />
	            		<p class="currency_unit"></p>
	            	</div>
            	</div>
            	
            	<div class="quote">
					<div class="clearfix">
						<p>商品引用<span class="require">&nbsp;＊</span>：<span class="reference_item_title"></span></p>
						<input type="hidden" class="reference_item_target_id" id="##_reference_item_target_id" name="##_reference_item_target_id" value="" />
					</div>
					<div class="clearfix">
						<a class="option select_item" target-row="##" style="margin-left:12px;margin-right:6px;">引用選択</a>
						<a class="option clear_reference_item" target-row="##">引用解除</a>
					</div>
				</div>
				
            	<div class="quote">
					<div class="clearfix">
						<p>見積書引用<span class="require">&nbsp;＊</span>：<span class="reference_estimate_title"></span></p>
						<input type="hidden" class="reference_estimate_target_id" id="##_reference_estimate_target_id" name="##_reference_estimate_target_id" value="" />
						<input type="hidden" class="reference_estimate_target_row" id="##_reference_estimate_target_row" name="##_reference_estimate_target_row" value="" />
					</div>
					<div class="clearfix">
						<a class="option select_estimate" target-row="##" style="margin-left:12px;margin-right:6px;">引用選択</a>
						<a class="option clear_reference_estimate" target-row="##">引用解除</a>
					</div>
				</div>
            </td>
            <td class="td_action">
            	<div class="delete_btn_frame">
            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row="##"><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>
	<!-- copy base -->


    <?php
    /* 添付資料 */
    $categoryId = 4;
    ?>
    <!-- copy base -->
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base_<?php echo $categoryId; ?>" id="">
			<td class="column_value">
				<div class="clearfix">
					<div style="float:left;width:360px;">
						<div class="clearfix" style="margin-bottom:5px">
							<div style="float:left;width:50px;padding:15px 0 0 10px;">
								<i class="budicon-equal" style="color:#aaa;font-size:48px;"></i>
							</div>
							<div style="float:left;width:300px;">
								<div class="multi_rows_padding" style="padding-left:18px;"><span class="file_name_text" id="##_file_name_text">(ファイル名)</span></div>
								<input type="hidden" class="file_name" id="##_file_name" name="##_file_name" value="" />
								<input type="hidden" class="temp_file_name" id="##_temp_file_name" name="##_temp_file_name" value="" />  
							</div>
						</div>
						
						<div class="add_image_box" id="##_add_image_box" ondragover="dragover(event)" ondrop="drop(##,event)" style="margin-bottom:13px;">
							<i class="icon-upload-cloud" style="font-size:60px;color:#888;"></i><br>ファイルをドラッグ&amp;ドロップしてください
						</div>
					</div>
					<div style="float:left;margin-left:10px;width:670px;">
						<p>概要:</p>
						<textarea class="summary" name="##_summary" style="margin-top:9px;height:176px;margin-bottom:6px;"><?php echo $this->escape($this->documentData['summary']); ?></textarea>
					</div>
				</div>
			</td>
            <td class="td_action">
            	<div class="delete_btn_frame">
            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row=""><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>    
	<!-- copy base -->
	         
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

