<?php
$statusList   = Shared_Model_Code::codes('item_status');
?>
<script type="text/javascript">
$(function () {

    
});    
</script>
<style type="text/css">
p.action_title {font-size:1.1em;padding-left:11px;padding-top:10px;font-weight:bold;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:90px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:90px;padding:5px 0;margin:0;border:none;" href="/manufacture/sock-add">新規申請</a>
            </p>
	        <span style=""><strong>社販購入申請</strong></span>
	    </div>
	</div>


	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:10%;"><p>申請ID</p></th>
				<th style="width:15%;"><p>ステータス</p></th>
				<th style="width:10%;"><p>申請日時</p></th>
				<th style="width:10%;"><p>引渡日</p></th>
				
				<th><p>商品名(数量)</p></th>
				<th style="width:10%;"><p>支払方法</p></th>
				<th style="width:10%;"><p>合計</p></th>
				<th style="width:5%;"><p>詳細</p></th>
			</tr>


<?php

$items = array();

/*
$items[] = array(
'id'   => 3,
'status' => '申請中',
'apply_datetime' => "2018-09-03",
'recieved_date' => '-',
'items' => array('琉球しまぐわ　健糖値の特桑茶（粉末タイプ・90g入り）  (2個)', 'MOMOこらーげん  (1個)'),
'payment_method' => '銀行振り込み',
'total' => '3,333 円',
);

$items[] = array(
'id'   => 2,
'status' => '承認済み',
'apply_datetime' => "2018-09-03",
'recieved_date' => '-',

'items' => array('琉球しまぐわ　健糖値の特桑茶（粉末タイプ・90g入り）  (2個)', 'MOMOこらーげん(1個)'),
'payment_method' => '給与天引',
'total' => '3,333 円',
);

$items[] = array(
'id'   => 1,
'status' => '引渡済み',
'apply_datetime' => "2018-09-03",
'recieved_date' => '2018-09-10',
'items' => array('琉球しまぐわ　健糖値の特桑茶（粉末タイプ・90g入り）  (2個)', 'MOMOこらーげん(1個)'),
'payment_method' => '給与天引',
'total' => '3,333 円',
);

$this->items = $items;
*/
?>	

			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>">
						<td>
							<p><?php echo $each['id']; ?></p>
						</td>
						
						<td>
							<p><?php echo $each['status']; ?></p>
						</td>

						<td>
							<p><?php echo $each['apply_datetime']; ?></p>
						</td>
						
						<td>
							<p><?php echo $each['recieved_date']; ?></p>
						</td>

						<td>
							<div class="multi_rows_padding">
								<?php foreach ($each['items'] as $eachItem) { ?>
									<?php echo $eachItem; ?><br />
								<?php } ?>
							</div>
						</td>
						
						<td>
							<p><?php echo $each['payment_method']; ?></p>
						</td>

						<td>
							<p><?php echo $each['total']; ?></p>
						</td>
						
						<td>
							<p><a href="/office/payment-detail?id=<?php echo $this->escape($each['id']); ?>">詳細</a></p>
						</td>	
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="8">
						<p style="text-align:center;">現在この機能は使用できません<?php /* データがありません*/ ?></p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

