<?php
$statusList        = Shared_Model_Code::codes('online_purchase_status_search');
$payingMethodList  = Shared_Model_Code::codes('payable_paying_method_purchase');
?>
<script type="text/javascript">

function getTimeStamp() {
	var date = new Date();
	return String(date.getFullYear()) + ("0"+(date.getMonth() + 1)).slice(-2) + ("0"+(date.getDate() + 1)).slice(-2)
                            	+ '_' + ("0"+(date.getHours() + 1)).slice(-2) + ("0"+(date.getMinutes() + 1)).slice(-2) + ("0"+(date.getSeconds() + 1)).slice(-2);
}

$(function () {
	$(document).ready(function(){
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->posTop; ?>);
        <?php } ?>
    });
    
	$(".clear_form").bind("click", function(){
	    $(this.form).find('textarea, :text, :hidden:not("#search, #page")').val("");
	    $(this.form).find('select option').removeAttr('selected');
	    $('.target_text').html('');
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
	});

    // PDFプレビュー
    $('.btn_preview').click( function(){
    	var targetId = $(this).attr('target-id');
    	window.open('/transaction-order/preview/' + targetId + '/発注書_' + getTimeStamp() + '.pdf', '_blank');
    });
    
    // 提出完了
    $(document).on('click', '.btn_submit', function () {    	
    	var targetId = $(this).attr('target-id');
		jConfirm('発注完了にしますか', '　', function(r) {
			if(r) {
				showSpinner();
				$.ajax({
		            type:'POST',
		            dataType:'html',
		            data: 'id=' + targetId,
		            success: function(res){
		            	stopSpinner();
		                reloadFlag = true;
		                jAlert('発注完了にしました', '　');
		            },
		            error: function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url: '/transaction-order/submit'
		        });
		        
			} else {
			    return false;
			}
		});
    });


    // 提出完了
    $(document).on('click', '.btn_reservation', function () {    	
		jAlert('こちらの機能はまだご利用いただけません', 'エラー');
    });
    
    
    $(document).on('click', '#popup_ok', function () {
    	if (reloadFlag) {
    		var $form = $('#register_form');
    		var params = $form.serialize();
    		location.href = '/transaction-order/list?' + params + '&pos=' + $(window).scrollTop();
    	}
    });
    
    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });
    
    // 取引先 リセット
    $(document).on('click', '#reset_connection', function () {
		$('#connection_name_display').html('');
		$('#connection_name').val('');
		$('#connection_id').val('');
	});

	// 申請者 ポップアップ表示
    $(document).on('click', '#select_applicant_user', function () {
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/user/list-select', null, function () {stopSpinner();});
	});
    
	// 申請者 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    // 申請者 リセット
    $(document).on('click', '#reset_applicant_user', function () {
		$('#applicant_user_name_display').html('');
		$('#applicant_user_name').val('');
		$('#applicant_user_id').val('');
	});
	
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
    
    $(document).on('click', '.action_menu', function () {
	    var targetId = $(this).attr('target-id');
	    
	    if ($('#action_menu_frame_' + targetId).hasClass('selected')) {
		    $('#action_menu_frame_' + targetId).removeClass('selected');
	    } else {
		    $('.action_menu_frame').removeClass('selected');
		    $('#action_menu_frame_' + targetId).addClass('selected');
	    }
	}); 

    // 削除
    $(document).on('click', '.delete', function () {
    	var targetId = $(this).attr('target-id');
		jConfirm('本当に削除にしますか', '　', function(r) {
			if(r) {
				showSpinner();
				$.ajax({
		            type:'POST',
		            dataType:'html',
		            data:'target_id=' + targetId,
		            success:function(res){
		            	stopSpinner();
		                reloadFlag = true;
		                jAlert('削除しました', '　');
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-order/online-delete'
		        });
		        
			} else {
			    return false;
			}
		});
    });
});

// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form = $('#connection_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/connection/list-select?page=' + pageNo,
    });
}

// 取引先 選択完了
function selectConnection(id, displayId, name) {
	$('#connection_name_display').html(name);
	$('#connection_name').val(name);
	$('#connection_id').val(id);
	$('.btn_close').click();
}

// 申請者 一覧ページ切り替え
function pageUser(pageNo) {
	updateUserList(pageNo)
}

// 申請者 一覧更新
function updateUserList (pageNo) {
    var $form = $('#user_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/user/list-select?page=' + pageNo,
    });
}

// 申請者 選択完了
function selectUser(id, departmentName, name, departmentNameEn, nameEn) {
	$('#applicant_user_name_display').html(departmentName + '　' + name);
	$('#applicant_user_name').val(departmentName + '　' + name);
	$('#applicant_user_id').val(id);
	$('.btn_close').click();
}
</script>
<style type="text/css">
table.list_default tr:hover td {background:#deeeff;}
table.list_default tr td a.btn_setting {margin:5px 0 0px 5px;padding:7px 15px 5px 15px;line-height:1;display:block;float:left;cursor:pointer;}
.multi_rows_padding {padding:5px 10px 5px 10px}
table.list_default tr td p.completed {color:#04a127;padding-left:0;text-align:center;}
tr.gray_out td {background-color:#eee}
tr.gray_outhover td {background-color:#ccc}
table.list_default tr td {overflow:inherit;}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin:5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:5px auto 10px;padding:7px 35px 5px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
		    <?php if ($this->allowEditing === true) { ?>
				<p style="position:absolute;width:76px;right:0;">
	                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/transaction-order/online-add">新規登録</a>
	            </p>
            <?php } ?>
	        <span style=""><strong>ネット購入委託管理</strong></span>
	    </div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/transaction-order/online-list" method="get">
				<p class="search_condition_title">検索条件</p>
				
				<input type="hidden" id="search" name="search" value="1" />
				<input type="hidden" id="page" name="page" value="1" />
				
				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="status" name="status">
                            <option value="">---</option>
                        	<?php foreach ($statusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">購入委託企業：</p>
						<div class="input_box_fake">
							<span class="target_text" id="connection_name_display"><?php echo $this->conditions['connection_name']; ?></span>
							<a class="reset_popup" id="reset_connection" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_connection" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="connection_name" name="connection_name" value="<?php echo $this->conditions['connection_name']; ?>" />
						<input type="hidden" id="connection_id" name="connection_id" value="<?php echo $this->conditions['connection_id']; ?>" />
					</div>

					<div class="condition_item">
						<p class="condition_label">登録者：</p>
						<div class="input_box_fake">
							<span class="target_text" id="applicant_user_name_display"><?php echo $this->conditions['applicant_user_name']; ?></span>
							<a class="reset_popup" id="reset_applicant_user" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_applicant_user" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="applicant_user_name" name="applicant_user_name" value="<?php echo $this->conditions['applicant_user_name']; ?>" />
						<input type="hidden" id="applicant_user_id" name="applicant_user_id" value="<?php echo $this->conditions['applicant_user_id']; ?>" />
					</div>
					
					<div class="condition_item">
						<p class="condition_label">キーワード：</p>
                        <input type="text" id="keyword" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" disabled="disabled" />
					</div>
				</div>
				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="submit" class="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</form>
		</div>
	</div>	
	
	<div class="clearfix">
		<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
    </div>
    
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:10%;"><p>管理ID</p></th>
				<th style="width:9%;"><p>注文予定日</p></th>
				<th style="width:9%;"><p>ステータス</p></th>
				<th style="width:10%;"><p>納品受領</p></th>
				<th style="width:14%;"><p>購入委託企業名</p></th>
				<th><p>注文内容</p></th>
				<th style="width:10%;"><p>登録者&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:5%;"><p>詳細</p></th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>" <?php if ($each['status'] === (string)Shared_Model_Code::ONLINE_PURCHASE_STATUS_CANCEL) { echo 'class="gray_out"'; } ?>>
						<td>
							<p><?php echo $each['display_id']; ?></p>
						</td>

						<td>
							<p><?php if (!empty($each['order_plan_date'])) { echo date('Y-m-d', strtotime($each['order_plan_date'])); } ?></p>
						</td>

						<td>
							<?php if ($each['status'] === (string)Shared_Model_Code::ONLINE_PURCHASE_STATUS_APPROVED) { ?>
								<p><strong><?php echo $statusList[$each['status']]; ?></strong></p>
							<?php } else {?>
								<p><?php echo $statusList[$each['status']]; ?></p>
							<?php } ?>
						</td>
						
						<td>
							<?php if ($each['status'] == Shared_Model_Code::ONLINE_PURCHASE_STATUS_APPROVED) { ?>
								<?php if (empty($each['deliveried_status'])) { ?>
									<?php if ($this->allowEditing) { ?>
										<a class="btn_setting" style="background-color:#02ad00" href="/transaction-order/online-deliveried?id=<?php echo $this->escape($each['id']); ?>">納品完了</a>
									<?php } ?>
								<?php } else { ?>
									<div class="multi_rows_padding">納品受領済<br><?php echo $this->escape($each['deliveried_date']); ?></div>
								<?php } ?>
							<?php } ?>
						</td>
							
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['company_name']); ?></div>
						</td>

						<?php
							$text = '';
							$itemList = json_decode($each['item_list'], true);

							if (!empty($itemList)) {
								$textList = array();
								foreach ($itemList as $eachItem) {
									$exploded = explode("\n", $eachItem['item_name']);
									if (!empty($exploded[0])) {
										$textList[] = str_replace("\n", '', $exploded[0]);
									}
								}
								
								$text = $this->escape(implode(" ● ", $textList));
							}
							
							$text .= '<br><strong>合計金額(税込)：' . $this->escape(number_format($each['total_with_tax'])) . '&nbsp;' . $this->currencyList[$each['currency_id']]['name'] . '</strong>';
						?>
						<td>
							<div class="multi_rows_padding">
								<?php echo $text; ?>
							</div>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['user_name']); ?>">
							<p><?php echo $this->roundText($this->escape($each['user_name']), 7); ?></p>
						</td>

						<td style="position:relative;">
							<?php if (!empty($this->adminProperty['allow_delete_row_data'])) { ?>
								<div class="action_menu_frame" id="action_menu_frame_<?php echo $this->escape($each['id']); ?>">
									<a class="action_menu" target-id="<?php echo $this->escape($each['id']); ?>"><i class="icon-pencil"></i><i class="icon-down-dir-1"></i></a>
								    <ul>
									    <li><a class="delete" target-id="<?php echo $this->escape($each['id']); ?>">削除</a></li>
								    </ul>
								</div>
							<?php } ?>
							<p><a href="/transaction-order/online-detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="8">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

