<?php
$statusList   = Shared_Model_Code::codes('order_form_status');
?>

<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong><?php echo $this->escape($this->connectionData['company_name']); ?> ネット購入委託管理</strong></span>
    </div>
</div>


<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<div class="condition_items clearfix">
		<form id="order_condition_form" action="#" method="get">
			<p class="search_condition_title">検索条件</p>

			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">XXX：</p>
                    <select id="type" name="type">
                        <option value="">---</option>
                    	<?php foreach ($connectionTypeList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>

				<div class="condition_item" style="padding-top:23px;">
					<input type="button" id="clear_form" style="display:inline-block;width:116x;" value="リセット" />
					<input type="button" id="search_order" style="display:inline-block;width:116px;" value="検索" />
				</div>
				
			</div>
		</form>
	</div>
</div>	


<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:10%;"><p>管理ID</p></th>
			<th style="width:9%;"><p>注文予定日</p></th>
			<th style="width:9%;"><p>ステータス</p></th>
			<th style="width:14%;"><p>購入委託企業名</p></th>
			<th><p>注文内容</p></th>
			<th style="width:10%;"><p>登録者&nbsp;<i class="icon-info-circle"></i></p></th>
			<th style="width:8%;"><p>詳細</p></th>
		</tr>

		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>

				<tr id="<?php echo $each['id']; ?>">
					<td>
						<p><?php echo $each['display_id']; ?></p>
					</td>

					<td>
						<p><?php if (!empty($each['order_plan_date'])) { echo date('Y-m-d', strtotime($each['order_plan_date'])); } ?></p>
					</td>

					<td>
						<?php if ($each['status'] === (string)Shared_Model_Code::ONLINE_PURCHASE_STATUS_APPROVED) { ?>
							<p><strong><?php echo $statusList[$each['status']]; ?></strong></p>
						<?php } else {?>
							<p><?php echo $statusList[$each['status']]; ?></p>
						<?php } ?>
					</td>
						
					<td>
						<div class="multi_rows_padding"><?php echo $this->escape($each['company_name']); ?></div>
					</td>

					<?php
						$text = '';
						$textWithTotal = '';
						$itemList = json_decode($each['item_list'], true);

						if (!empty($itemList)) {
							$textList = array();
							foreach ($itemList as $eachItem) {
								$exploded = explode("\n", $eachItem['item_name']);
								if (!empty($exploded[0])) {
									$textList[] = str_replace("\n", '', $exploded[0]);
								}
							}
							
							$text = $this->escape(implode(" ● ", $textList));
						}
						
						$textWithTotal .= '<br><strong>合計金額(税込)：' . $this->escape(number_format($each['total_with_tax'])) . '&nbsp;' . $this->currencyList[$each['currency_id']]['name'] . '</strong>';
					?>
					<td>
						<div class="multi_rows_padding">
							<?php echo $textWithTotal; ?>
						</div>
					</td>

					<td class="desc" all-content="<?php echo $this->escape($each['user_name']); ?>">
						<p><?php echo $this->roundText($this->escape($each['user_name']), 7); ?></p>
					</td>

					<td>
						<a class="option" href="javascript:selectOnline('<?php echo $each['id']; ?>', '<?php echo $this->escape($each['display_id']); ?>', '<?php echo $text; ?>', '<?php echo $this->escape(number_format($each['total_with_tax'])) . '&nbsp;' . $this->currencyList[$each['currency_id']]['name'] ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="7">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding:2.0em 0;">
    <?php echo $this->pager() ?>
    </div>
            
</div>


