<div class="select_type_list">
<p class="select_type_title">種別選択</p>
<a class="select_type" target-type="supply-product" href="javascript:void(0);">調達管理 原料・製品</a>
<a class="select_type" target-type="supply-production" href="javascript:void(0);">調達管理 製造加工委託</a>
<a class="select_type" target-type="supply-subcontracting" href="javascript:void(0);">調達管理 業務委託</a>
<a class="select_type" target-type="supply-fixture" href="javascript:void(0);">調達管理 備品・資材</a>
<a class="btn_close select_type_close" href="javascript:void(0);">閉じる</a>
</div>