<?php
?>
<link rel="stylesheet" href="/resource/js/switchery-0.8.0/dist/switchery.css" />
<script src="/resource/js/switchery-0.8.0/dist/switchery.js"></script>
<script type="text/javascript"><!--
$(function() {
    $(document).ready(function(){
		var elems = Array.prototype.slice.call(document.querySelectorAll('.switch'));
		                
		elems.forEach(function(html) {
		  var switchery = new Switchery(html, { size: 'small' });
		});
    });

	<?php 
		$confirmMessage = '登録しますか';
		$succeedMessage = '登録しました';
		$backmessage    = '登録せずに中止しますか';
		if (!empty($this->id)) {
			$confirmMessage = '保存しますか';
			$succeedMessage = '保存しました';
			$backmessage    = '保存せずに中止しますか';
        }
	?>
			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
       jConfirm('<?php echo $backmessage; ?>', '　', function(r) {
            if(r) {
               location.href = "/user/department-list";
            } else {
                return false;
            }
        });
	});
		
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('<?php echo $confirmMessage; ?>', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if (obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('<?php echo $succeedMessage; ?>', '　'); 
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/user/department-add-post'
                });
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/user/department-list';
        }
    });
      
});
--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.multi_rows_padding {padding:5px 0 5px 10px}
--></style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong><?php echo $this->escape($this->groupData['organization_name']); ?> / 部署・事業部門 - <?php if (!empty($this->id)) { echo '編集'; } else { echo '登録'; } ?></strong></span>
        </div>
    </div>
    
    <div class="clearfix">
	    <form id="register_form" action="#" method="post"> 
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">部門情報</p>
                </th>
            </tr>
		</table>
         
		<table class="list_default" style="margin-bottom:13px;">            
            <tr>
                <td class="column_label"><p class="label_text">部署・事業部門名&nbsp;<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="department_name" value="<?php echo $this->escape($this->data['department_name']); ?>" maxlength="" autocomplete="off" style="dispaly:block;" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">部署・事業部門名(英語)&nbsp;<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="department_name_en" value="<?php echo $this->escape($this->data['department_name_en']); ?>" maxlength="" autocomplete="off" style="dispaly:block;" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">会計事務所</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
            		<div style="float:left;width:50px;">
						<input type="checkbox" id="is_accountants_office" class="switch" name="is_accountants_office" style="display:none;" <?php if (!empty($this->data['is_accountants_office'])) echo 'checked="checked"'; ?> />
					</div>    
                </td>
            </tr>
                       
            <tr>
                <td class="column_label"><p class="label_text">通知用メールアドレス</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="mailing_list_address" value="<?php echo $this->escape($this->data['mailing_list_address']); ?>" maxlength="" autocomplete="off" style="dispaly:block;" />
                </td>
            </tr>

        </table>


<!--
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">メール受信対象</p>
                </th>
            </tr>
		</table>
		
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">原価計算</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_cost" class="switch" name="mail_cost" style="display:none;" <?php if (!empty($this->data['mail_cost'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>
	        
            <tr>
                <td class="column_label"><p class="label_text">提出見積</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_estimate" class="switch" name="mail_estimate" style="display:none;" <?php if (!empty($this->data['mail_estimate'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">調達管理</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_supply" class="switch" name="mail_supply" style="display:none;" <?php if (!empty($this->data['mail_supply'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>
			
			<tr>
                <td class="column_label"><p class="label_text">受注管理</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_order" class="switch" name="mail_order" style="display:none;" <?php if (!empty($this->data['mail_order'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">発注管理</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_order_form" class="switch" name="mail_order_form" style="display:none;" <?php if (!empty($this->data['mail_order_form'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">支払申請</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_payable" class="switch" name="mail_payable" style="display:none;" <?php if (!empty($this->data['mail_payable'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">毎月支払申請</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_payable_monthly" class="switch" name="mail_payable_monthly" style="display:none;" <?php if (!empty($this->data['mail_payable_monthly'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">請求書発行</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_invoice" class="switch" name="mail_invoice" style="display:none;" <?php if (!empty($this->data['mail_invoice'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>
            
			<tr>
                <td class="column_label"><p class="label_text">請求書発行</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:50px;">
							<input type="checkbox" id="mail_receivable_monthly" class="switch" name="mail_receivable_monthly" style="display:none;" <?php if (!empty($this->data['mail_receivable_monthly'])) echo 'checked="checked"'; ?> />
						</div>
					</div>
                </td>
            </tr>
		</table>
-->

	</form>		
	</div><!-- clearfix -->

                
</div>
</div>
</div>
</div>
