<?php
$statusList = Shared_Model_Code::codes('user_status');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
    });  
});    
</script>
<style type="text/css">
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <span style=""><strong><?php echo $this->escape($this->groupData['organization_name']); ?> / 利用者一覧</strong></span>
	    </div>
	</div>
	
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:10%;">
					<p>利用者ID</p>
				</th>

				<th style="width:14%;">
					<p>ステータス</p>
				</th>
				
				<th>
					<p>所属</p>
				</th>
				
				
				<th>
					<p>氏名</p>
				</th>

				<th tyle="width:30%;">
					<p>最終ログイン</p>
				</th>

				<th style="width:5%;">
					<p>詳細</p>
				</th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr>
						<td>
							<p><?php echo $this->escape($each['display_id']); ?></p>
						</td>
		
						<td>
							
							<p <?php if ($each['status'] === (string)Shared_Model_Code::USER_STATUS_ACTIVE) { echo 'class="status_active"'; } ?>><?php echo $statusList[$each['status']]; ?></p>
						</td>
						
						<td>
							<p><?php echo $each['department_name']; ?></p>
						</td>
						
						
						<td>
							<p><?php echo $this->escape($each['user_name']); ?></p>
						</td>
		
						<td>
							<p><?php echo date('Y-m-d H:i:s', strtotime($each['last_logined'])); ?></p>
						</td>
						
						<td>
							<p><a href="/user/develop-detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="6">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

