<?php
$userStatusList = Shared_Model_Code::codes('user_status');
?>
<link rel="stylesheet" href="/resource/js/switchery-0.8.0/dist/switchery.css" />
<script src="/resource/js/switchery-0.8.0/dist/switchery.js"></script>
<script type="text/javascript"><!--
var reloadFlag  = false;
var deletedFlag = false;

function dragover(e) {
    e.preventDefault();
}
					
function drop(e) {
	$('#add_image_box').removeClass('over');
	
	e.preventDefault();
	var files = e.dataTransfer.files;
  
	if (files.length > 1) {
  		jAlert('画像は一枚ずつドロップしてください。', 'エラー');
 	 	return;
	}

    // アップロード処理へ
    fileUpload(files[0]);
}

function fileUpload(fd) {
    var formData = new FormData();
    formData.append('image', fd);

    $.ajax({
      async:true,
      type:'POST',
      contentType:false,
      processData:false,
      url:'/user/upload-image',
      data:formData,
      dataType:'json'
    }).done(function(res){
        var obj = res;
        if (obj.result == 'timeout') {
            location.href = '/login';
            return;
            
        } else if(obj.result == true) {
        	$('#add_image_box').removeClass('over');
        	$('#photo_image').attr('src', '/resource/temp/' + obj.temp_file_name);
        	$('#temp_file_name').val(obj.temp_file_name);
        	
        }
    });
}


$(function() {
    $(document).ready(function(){
		var elems = Array.prototype.slice.call(document.querySelectorAll('.switch'));
		                
		elems.forEach(function(html) {
		  var switchery = new Switchery(html, { size: 'small' });
		});
		
        // ファイルのドロップ時エフェクト
		var targetE = document.getElementById('add_image_box');
		var innerFlag = false;
		
		targetE.addEventListener('dragenter', function () {
		    innerFlag = true;
		}, false);
		
		targetE.addEventListener('dragover', function () {
		    innerFlag = false;
		    targetE.className = 'over';
		}, false);
		
		targetE.addEventListener('dragleave', function () {
		    if (innerFlag) {
		        innerFlag = false;
		    } else {
		        targetE.className = '';
		    }
		}, false);
    });

	<?php 
		$confirmMessage = '登録しますか';
		$succeedMessage = '登録しました';
		$backmessage    = '登録せずに中止しますか';
		if (!empty($this->id)) {
			$confirmMessage = '保存しますか';
			$succeedMessage = '保存しました';
			$backmessage    = '保存せずに中止しますか';
        }
	?>
			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
       jConfirm('<?php echo $backmessage; ?>', '　', function(r) {
            if(r) {
               location.href = "/user/develop-index";
            } else {
                return false;
            }
        });
	});
		
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('<?php echo $confirmMessage; ?>', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data:param,
                    success:function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if (obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('<?php echo $succeedMessage; ?>', '　'); 
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error:function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url:'/user/update<?php if (!empty($this->id)) echo '?id=' . $this->id; ?>'
                });
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/user';
        }
    });
      
});
--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.multi_rows_padding {padding:5px 0 5px 10px}
--></style>
<div class="section anchor">
    <div class="light-wrapper">
        <div class="container inner" style="min-height:900px;margin-bottom:100px;">
            <div class="row text-left">
        
                <div class="col-xs-12">
                    <div class="page_title">
                        <span><strong><?php echo $this->escape($this->groupData['organization_name']); ?> / アカウント管理 - <?php if (!empty($this->id)) { echo '編集'; } else { echo '登録'; } ?></strong></span>
                    </div>
                </div>
                
                
                <form id="register_form" action="#" method="post"> 
                <div class="clearfix">
					<table class="list_default" style="margin-bottom:0;">
                        <tr>
                            <th class="border-left border-right border-top border-bottom">
                                <p class="label_text strong">管理者情報</p>
                            </th>
                        </tr>
					</table>
                     
					<table class="list_default" style="margin-bottom:13px;">
                        <tr>
                            <td class="column_label"><p class="label_text">利用者ID&nbsp;<span class="require">&nbsp;＊</span></p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                                <input type="text" name="display_id" value="<?php echo $this->escape($this->data['display_id']); ?>" maxlength="" autocomplete="off" style="width:300px;display:block;" />
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="column_label"><p class="label_text">氏名&nbsp;<span class="require">&nbsp;＊</span></p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                                <input type="text" name="user_name" value="<?php echo $this->escape($this->data['user_name']); ?>" maxlength="" autocomplete="off" style="width:300px;display:block;" />
                            </td>
                        </tr>

                        <tr>
                            <td class="column_label"><p class="label_text">氏名(英語・ローマ字)&nbsp;<span class="require">&nbsp;＊</span></p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                                <input type="text" name="user_name_en" value="<?php echo $this->escape($this->data['user_name_en']); ?>" maxlength="" autocomplete="off" style="width:300px;display:block;" />
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="column_label"><p class="label_text">メールアドレス&nbsp;<span class="require">&nbsp;＊</span></p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                                <input type="text" name="mail" value="<?php echo $this->escape($this->data['mail']); ?>" maxlength="" autocomplete="off" style="width:300px;display:block;" />
                            </td>
                        </tr>

                        <tr>
                            <td class="column_label"><p class="label_text">パスワード&nbsp;<span class="require">&nbsp;＊</span></p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                                <input type="password" name="password" value="<?php echo $this->escape($this->data['password']); ?>" maxlength="" autocomplete="off" style="width:300px;display:block;" />
                            </td>
                        </tr>
                        
                        <tr>
	                        <td class="column_label"><p class="label_text">所属&nbsp;<span class="require">&nbsp;＊</span></p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
		                        <select class="user_department_id" id="user_department_id" name="user_department_id" style="width:300px;">
		                            <option value="">---</option>
		                            <?php foreach ($this->departmentList as $each) { ?>
		                                <option value="<?php echo $each['id']; ?>" <?php if ($each['id'] == $this->data['user_department_id']) echo 'selected="selected"'; ?>><?php echo $this->escape($each['department_name']); ?></option>
		                            <?php } ?>
		                    	</select>
	                    	</td>
                        </tr>
                        
                        <?php if (!empty($this->data)) { ?>
                        <tr>
                            <td class="column_label"><p class="label_text">ステータス&nbsp;<span class="require">&nbsp;＊</span></p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
	                            <select name="status" style="width:300px;">
		                            <?php foreach ($userStatusList as $key => $val) { ?>
		                            	<option value="<?php echo $this->escape($key); ?>" <?php if ($this->data['status'] === (string)$key) { echo 'selected="selected"'; } ?>><?php echo $this->escape($val); ?></option>
		                            <?php } ?>
	                            </select>
                            </td>
                        </tr>
                        <?php } ?>
                    </table>
                    

					<table class="list_default" style="margin-bottom:0;">
                        <tr>
                            <th class="border-left border-right border-top border-bottom">
                                <p class="label_text strong">権限</p>
                            </th>
                        </tr>
					</table>
					
					<table class="list_default" style="margin-bottom:13px;">            
                        <tr>
                            <td class="column_label"><p class="label_text">アカウント管理</p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                            	<div class="clearfix">
									<div style="float:left;width:50px;">
										<input type="checkbox" id="is_master" class="switch" name="is_master" style="display:none;" <?php if (!empty($this->data['is_master'])) echo 'checked="checked"'; ?> />
									</div>
									<p style="float:left;">&nbsp;アカウントの追加・編集を許可します</p>
								</div>
                            </td>
                        </tr>

                        <tr>
                            <td class="column_label"><p class="label_text">会計科目編集権限</p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                            	<div class="clearfix">
									<div style="float:left;width:50px;">
										<input type="checkbox" id="allow_editing_accounting_title" class="switch" name="allow_editing_accounting_title" style="display:none;" <?php if (!empty($this->data['allow_editing_accounting_title'])) echo 'checked="checked"'; ?> />
									</div>
									<p style="float:left;">&nbsp;会計科目・採算コードの追加・編集を許可します</p>
								</div>
                            </td>
                        </tr>

                        <tr>
                            <td class="column_label"><p class="label_text">会計割当完了解除権限</p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                            	<div class="clearfix">
									<div style="float:left;width:50px;">
										<input type="checkbox" id="allow_cancel_finish_attach" class="switch" name="allow_cancel_finish_attach" style="display:none;" <?php if (!empty($this->data['allow_cancel_finish_attach'])) echo 'checked="checked"'; ?> />
									</div>
									<p style="float:left;">&nbsp;取引処理におけるCSV取込データの割当完了の解除を許可します</p>
								</div>
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="column_label"><p class="label_text">検索用タグ編集権限</p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                            	<div class="clearfix">
									<div style="float:left;width:50px;">
										<input type="checkbox" id="allow_editing_search_tag" class="switch" name="allow_editing_search_tag" style="display:none;" <?php if (!empty($this->data['allow_editing_search_tag'])) echo 'checked="checked"'; ?> />
									</div>
									<p style="float:left;">&nbsp;検索用タグの編集を許可します</p>
								</div>
                            </td>
                        </tr>


                        <tr>
                            <td class="column_label"><p class="label_text">データ削除権限</p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                            	<div class="clearfix">
									<div style="float:left;width:50px;">
										<input type="checkbox" id="allow_delete_row_data" class="switch" name="allow_delete_row_data" style="display:none;" <?php if (!empty($this->data['allow_delete_row_data'])) echo 'checked="checked"'; ?> />
									</div>
									<p style="float:left;">&nbsp;各種データの削除を許可します</p>
								</div>
                            </td>
                        </tr>
  
                        <tr>
                            <td class="column_label"><p class="label_text">営業案件定義管理権限</p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                            	<div class="clearfix">
									<div style="float:left;width:50px;">
										<input type="checkbox" id="allow_connection_progress_master" class="switch" name="allow_connection_progress_master" style="display:none;" <?php if (!empty($this->data['allow_connection_progress_master'])) echo 'checked="checked"'; ?> />
									</div>
									<p style="float:left;">&nbsp;シート管理・エリア定義・進捗定義・見積後ヒア定義を許可します</p>
								</div>
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="column_label"><p class="label_text">営業案件発足名称管理権限</p></td>
                            <td class="colon"><p class="label_text">：</p></td>
                            <td class="column_value">
                            	<div class="clearfix">
									<div style="float:left;width:50px;">
										<input type="checkbox" id="allow_connection_progress_tag" class="switch" name="allow_connection_progress_tag" style="display:none;" <?php if (!empty($this->data['allow_connection_progress_tag'])) echo 'checked="checked"'; ?> />
									</div>
									<p style="float:left;">&nbsp;発足名称管理を許可します</p>
								</div>
                            </td>
                        </tr>

                        <?php /*
                        <tr>
                            <td class="column" style="width:200px;"><p class="label_text">会員情報閲覧：</p></td>
                            <td class="column">
                            	<div class="clearfix">
									<div style="float:left; width:50px;">
										<input type="checkbox" id="access_member_data" class="switch" name="access_member_data" style="display:none;" <?php if (!empty($this->data['access_member_data'])) echo 'checked="checked"'; ?> />
										&nbsp;
									</div>
									<p style="float:left;">&nbsp;会員メニューとお問い合わせメニューを表示します</p>
								</div>
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="column" style="width:200px;"><p class="label_text">カテゴリ・用途定義：</p></td>
                            <td class="column">
                            	<div class="clearfix">
									<div style="float:left; width:50px;">
										<input type="checkbox" id="access_member_data" class="switch" name="access_definition" style="display:none;" <?php if (!empty($this->data['access_definition'])) echo 'checked="checked"'; ?> />
										&nbsp;
									</div>
									<p style="float:left;">&nbsp;コンテンツのカテゴリ・用途メニューを表示します</p>
								</div>
                            </td>
                        </tr>
                        */ ?>
					</table>			
				</div><!-- clearfix -->



		        <table class="list_default" style="margin-bottom:0;">
		            <tr>
		                <th style="border:1px solid #ddd;">
		                	<p class="label_text strong" style="float:left;">印鑑画像(正方形・png)</p>
		                	<p style="float:right;padding-right:13px;">変更するには画像ファイルをドラッグ&amp;ドロップ</p>
		                </th>
		            </tr>
		        </table>
		
		        
				<div id="add_image_box" ondragover="dragover(event)" ondrop="drop(event)" style="margin-bottom:13px;">
					<img id="photo_image" style="width:56px;height:56px" src="<?php echo Shared_Model_Resource_Stamp::getResourceUrl($this->data['id']); ?>" />
					<input type="hidden" id="temp_file_name" name="temp_file_name" value="">
				</div>
			


				<table class="list_default" style="margin-bottom:0;">
                    <tr>
                        <th class="border-left border-right border-top border-bottom">
                            <p class="label_text strong">raw</p>
                        </th>
                    </tr>
				</table>
				
				<table class="list_default" style="margin-bottom:13px;">
					<?php foreach ($this->data as $key => $val) { ?>        
                    <tr>
                        <td class="column" style="width:200px;"><p class="label_text"><?php echo $this->escape($key); ?>：</p></td>
                        <td class="column">
							<div class="multi_rows_padding">
								<?php echo $this->escape($val); ?>
							</div>
                        </td>
                    </tr>
                    <?php } ?>
                </table>
		
				
                </form>
                
            </div>
        </div>
    </div>
</div>
