<?php
$statusList = Shared_Model_Code::codes('user_status');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
    });

    $(document).on('click', '.btn_switch', function () {
    	var targetId = $(this).attr('target-id');
    	showSpinner();
    	
		$.ajax({
            type:'POST',
            dataType:'json',
            data:'target_id=' + targetId,
            success:function(res){
            	stopSpinner();
				var obj = res;
                if (obj.result == 'OK') {
	                location.href = '/';
                } else {
	            	stopSpinner();
	                jAlert('予期せぬエラーが発生しました', 'エラー');
                }                
            },
            error:function(){
            	stopSpinner();
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url:'/user/switch'
        });
    });  
});    
</script>
<style type="text/css">
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <span><strong>アカウント切替</strong></span>
	    </div>
	</div>
	
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:30%;"><p>組織名</p></th>
				<th style="width:30%;"><p>ユーザーID</p></th>
				<th><p>最終ログイン</p></th>
				<th style="width:15%;"><p>切替</p></th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr>
						<td>
							<p><?php echo $this->escape($each['organization_name']); ?></p>
						</td>

						<td>
							<p><?php echo $this->escape($each['display_id']); ?></p>
						</td>
						
						<td>
							<p><?php  ?></p>
						</td>
						
						<td>
							<a class="btn_setting btn_switch" style="background-color:#02ad00;margin-top:3px;margin-left:3px;margin-bottom:3px;" target-id="<?php echo $this->escape($each['id']); ?>">アカウント切替</a>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="6">
						<p style="text-align:center;">切り替え可能なアカウントはありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

