<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong>担当者 選択</strong></span>
    </div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:10%;">
				<p>利用者ID</p>
			</th>

			<th>
				<p>所属</p>
			</th>
						
			<th>
				<p>氏名</p>
			</th>

			<th style="width:8%;">
				<p>選択</p>
			</th>		
		</tr>
		
		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>
				<tr>
					<td>
						<p><?php echo $this->escape($each['display_id']); ?></p>
					</td>
	
					<td>
						<p><?php echo $this->escape($each['department_name']);?></p>
					</td>
					
					<td>
						<p><?php echo $this->escape($each['user_name']); ?></p>
					</td>
	
					<td>
						<a class="option" href="javascript:selectUser('<?php echo $each['id']; ?>', '<?php echo $this->escape($each['department_name']);?>', '<?php echo $this->escape($each['user_name']); ?>', '<?php echo $this->escape($each['department_name_en']);?>', '<?php echo $this->escape($each['user_name_en']); ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="4">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding:2.0em 0;">
    <?php echo $this->pager() ?>
    </div>
            
</div>



