<?php
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
    });
});    
</script>
<style type="text/css">
table.list_default tr:hover td {background:#deeeff;}
table.list_default tr.deleted td {background:#ccc}
table.list_default tr.deleted:hover td {background:#bbb;}
table.list_default tr td p {height:auto;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
	
<div class="clearfix">
	<div style="float:left;width:200px;">
		<?php
	        echo $this->partial('system/define-menu.phtml', array(
				'action'    => $this->action,
			));
	    ?>
	</div>
	<div style="float:right;width:890px;">
		<div class="col-xs-12">
		    <div class="page_title" style="position:relative;">
		        <span style=""><strong>国定義リスト</strong></span>
		    </div>
		</div>
	    
		<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	       <table class="list_default" style="margin-bottom:0px;">
	            <tr>
	                <th class="border-left border-top border-bottom"><p class="label_text strong">国名</p></th>
	                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
	            </tr>
	        </table>
			<table class="list_default">
				<tr>
					<th>
						<p>国名</p>
					</th>
					
					<th style="width:5%;">
						<p>詳細</p>
					</th>
				</tr>
				<?php if (!empty($this->items)) { ?>
					<?php foreach ($this->items as $each) { ?>
						<tr>
							<td>
								<p><?php echo $this->escape($each['name']); ?></p>
							</td>
								
							<td>
								<p><a href="">編集</a></p>
							</td>
						</tr>
					<?php } ?>
				<?php } else { ?>
					<tr>
						<td colspan="7">
							<p style="text-align:center;">データがありません</p>
						</td>
					</tr>
				<?php } ?>
			</table>          
		</div>
	</div>
</div>

</div>
</div>
</div>
</div>


