<?php
?>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){
    });

	<?php 
		$confirmMessage = '登録しますか';
		$succeedMessage = '登録しました';
		$backmessage    = '登録せずに中止しますか';
		if (!empty($this->id)) {
			$confirmMessage = '保存しますか';
			$succeedMessage = '保存しました';
			$backmessage    = '保存せずに中止しますか';
        }
	?>
			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
       jConfirm('<?php echo $backmessage; ?>', '　', function(r) {
            if(r) {
               location.href = '/system/industry-category-detail?category_id=<?php echo $this->categoryId ?>';
            } else {
                return false;
            }
        });
	});
		
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('<?php echo $confirmMessage; ?>', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if (obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('<?php echo $succeedMessage; ?>', '　'); 
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/system/industry-type-update?category_id=<?php echo $this->categoryId ?><?php if (!empty($this->id)) echo '&id=' . $this->id; ?>'
                });
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/system/industry-category-detail?category_id=<?php echo $this->categoryId ?>';
        }
    });
});
--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
#horizontalwrap {display:inline;white-space:nowrap;}
span.note {display:block;margin:4px 0 3px;padding:0 4px;}
table.list_default tr td.column {border-right:none;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column p {padding-left:12px;}
table.list_default tr td.column input {width:99%}
table.list_default tr td.column select.short {width:200px}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
--></style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>業種 - <?php if (!empty($this->id)) { echo '編集'; } else { echo '登録'; } ?></strong></span>
        </div>
    </div>
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">
	    <?php
        /* 業種情報 */
        $categoryId = 1;
        ?>
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">業種情報</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">業種名：</p></td>
                <td class="column">
                	<input type="text" style="width:400px;" name="name" value="<?php echo $this->escape($this->data['name']); ?>" maxlength="">
                </td>
            </tr>
        </table>
	</div><!-- clearfix -->				
    </form>


</div>
</div>
</div>
</div>
