<div style="padding:20px; margin-bottom:5px;">

    <h2 style="padding-left:10px; font-size:36px; margin-bottom:24px; color:#979695;"><?php echo $this->title ?></h2>
    
   
	<div style="font-size:1.09em; color:#979695; padding-left:10px; margin-bottom:24px;">
    <?php foreach ($this->messages as $message) : ?>
      <p class="message"><?php echo $this->escape($message) ?></p>
    <?php endforeach ?>
    </div>

</div>