<?php
$userTypeList  = Shared_Model_Code::codes('user_type');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
   		Tipped.create('#help_keyword', "");
    });

	$(".clear_form").bind("click", function(){
	    $(this.form).find("textarea, :text, select").val("").end().find(":checked").prop("checked", false);
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
		$('#condition_form').submit();
	});
	
	$(document).on('click', '.show_more', function () {
		var targetId = $(this).attr('target-id');
	
		$('#part_' + targetId).hide();
		$('#all_' + targetId).show();
	});
});    
</script>
<style type="text/css">
table.list_default tr:hover td {background:#deeeff;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <?php /*
	        <p style="position:absolute;width:76px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/management/supplier/add">新規登録</a>
            </p>
            */ ?>
	        <span style=""><strong>ログ履歴</strong></span>
	    </div>
	</div>


	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/management/develop/log-list" method="get">
				<p class="search_condition_title">検索条件</p>

				<input type="hidden" name="search" value="1">
				<input type="hidden" name="page" value="1">
				
				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="status" name="status">
                            <option value="">---</option>
                        	<?php foreach ($statusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">種別：</p>
                        <select id="company_type" name="company_type">
                            <option value="">---</option>
                        	<?php foreach ($companyTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['company_type']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>			

					<div class="condition_item">
						<p class="condition_label">デモ：</p>
                        <select id="is_for_demo" name="is_for_demo">
                            <option value="">---</option>
                        	<?php foreach ($yesNoList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['is_for_demo']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>	
				</div>	
						
				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">キーワード：<span class="popup_help" id="help_keyword">&nbsp;<i class="icon-help-circled"></i></span></p>
						<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
					</div>
				</div>
				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="button" class="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</form>
		</div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	    <div class="clearfix" style="margin:2.0em 0;">
			<p style="float:left;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
		    <?php echo $this->pager() ?>
	    </div>
	    
		<table class="list_default">
			<tr>
				<th style="width:28%;"><p>created / target</p></th>
				<th style="width:30%;"><p>params</p></th>
				<th><p>message</p></th>
			</tr>
			<?php $userTable = new Shared_Model_Data_User(); ?>
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr>
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['created']); ?><br><?php echo $this->escape($each['target']); ?></div>
						</td>
						
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['params']); ?></div>
						</td>
							
						<td>
							<div class="multi_rows_padding" id="part_<?php echo $this->escape($each['id']); ?>"><?php 
								if (substr($each['message'], 0, 1) === '{') {
									$this->roundText(var_export(json_decode($each['message'], true)), 200);
								} else {
									echo $this->roundText(nl2br($this->escape($each['message'])), 200);
								}
							 ?></div>
							 
							 <div class="multi_rows_padding" id="all_<?php echo $this->escape($each['id']); ?>" style="display:none;"><?php 
								if (substr($each['message'], 0, 1) === '{') {
									var_export(json_decode($each['message'], true));
								} else {
									echo nl2br($this->escape($each['message']));
								}
							 ?></div>
							 
							 <a class="btn_setting show_more" target-id="<?php echo $this->escape($each['id']); ?>">全て表示</a>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="6">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div class="clearfix" style="margin:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

