<?php
$statusList   = Shared_Model_Code::codes('item_status');
?>
<script type="text/javascript">
$(function () {

    
});    
</script>
<style type="text/css"><!--
.multi_rows_padding {padding:5px 5px 5px 10px}
--></style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:76px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/including/add">新規登録</a>
            </p>
	        <span style=""><strong>同梱施策</strong></span>
	    </div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:10%;"><p>施策ID</p></th>
				<th style="width:40%;"><p>施策名</p></th>
				<th style="width:60%;"><p>データ</p></th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>">
						<td>
							<p><?php echo $each['id']; ?></p>
						</td>

						<td>
							<p><a href="/including/detail?id=<?php echo $each['id'] ?>"><?php echo $each['name']; ?></a></p>
						</td>
						
						<td>
							<div class="multi_rows_padding">
								商品名：<br>
								<?php
						    		$each['condition_item_ids'] = json_decode($each['condition_item_ids'], true);
									$each['including_items']    = json_decode($each['including_items'], true);
								?>
								<?php if (!empty($each['condition_item_ids'] )) { ?>
									<?php foreach ($each['condition_item_ids']  as $eachConditionItem) { ?>
										<?php echo $this->escape($this->productItems[$eachConditionItem['condition_item_id']]['item_name']); ?><br>

						            <?php } ?>
					            <?php } ?>
					            
								同梱品：<br>
								<?php if (!empty($each['including_items'] )) { ?>
									<?php foreach ($each['including_items']  as $eachConditionItem) { ?>
										<?php echo $this->escape($this->includingItemList[$eachConditionItem['item_id']]['item_name']); ?><br>

						            <?php } ?>
					            <?php } ?>
						
							</div>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="4">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

