<?php
$confidentialityList = Shared_Model_Code::codes('manual_confidentiality');
?>
<script type="text/javascript"><!--
var pos = 0;
var reloadFlag = false;

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

$(function() {
    $(document).ready(function(){
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
	            <?php if ($this->from === 'search') { ?>
	            	location.href = "/office-manual/search";
	            <?php } else { ?>
	            	location.href = "/office-manual";
	            <?php } ?>
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/office-manual/add-post'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            <?php if ($this->from === 'search') { ?>
            	location.href = "/office-manual/search";
            <?php } else { ?>
            	location.href = "/office-manual";
            <?php } ?>
        }
    });
    
    // 自社担当 ポップアップ表示
    $(document).on('click', '#select_user', function () {
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/user/list-select', null, function () {stopSpinner();});
    });
    
	// 自社担当 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(0);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// 自社担当 一覧ページ切り替え
function pageUser(pageNo) {
	updateUserList(pageNo)
}

// 自社担当 一覧更新
function updateUserList (pageNo) {
    var $form = $('#user_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/user/list-select?page=' + pageNo,
    });
}

// 自社担当 選択完了
function selectUser(id, departmentName, name, departmentNameEn, nameEn) {
	$('#manager_name').html(departmentName + '　' + name);
	$('#manager_user_id').val(id);
	$('.btn_close').click();
}

--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default.main tr td {border-right:none}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:280px;}
table.list_default tr td.column_value select.short {width:300px;}
a.option {
float:right;
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;font-size:12px;margin:3px 9px;padding:3px 35px 1px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1;}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default.base tr:hover td {background:#fff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>マニュアル - 新規登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">
		
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-top border-bottom border-right">
                    <p class="label_text strong">内容</p>
                </th>
            </tr>
		</table>

        <table class="list_default main" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">タイトル<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<input type="text" id="title" name="title" value="">
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">マニュアル区分<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <select name="manual_category_id" style="width:300px;">
		                <option value="">---</option>
		                <?php foreach ($this->categoryList as $eachCategory) { ?>           
		                    <option value="<?php echo $this->escape($eachCategory['id']); ?>"><?php echo $this->escape($eachCategory['category_name']); ?></option>
	                    <?php } ?>
                    </select>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">機密レベル<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <select name="confidentiality" style="width:300px;">
		                <option value="">---</option>
		                <?php foreach ($confidentialityList as $key => $val) { ?>           
		                    <option value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($val); ?></option>
	                    <?php } ?>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">管理責任者<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<div class="clearfix">
						<p id="manager_name" style="float:left;width:690px;">---</p>
						<input type="hidden" id="manager_user_id" name="manager_user_id" value="">
						<a class="option" id="select_user">選択</a>
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">備考</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <textarea name="memo" style="height:200px;margin-bottom:6px;"></textarea>
                </td>
            </tr>
        </table>
        
	</div><!-- clearfix -->	
    </form>


</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

