<?php

?>
<script type="text/javascript">
$(function () {
	$(document).ready(function(){
	    $('#sortable_column td').each(function(){
            $(this).css('width', $(this).width() +'px');
        });
        
        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	$(document).on('click', '.edit_content_order', function () {
        $('.display_value').hide();
        $('.edit_value').show();
    
        // ×,保存ボタン
        $(this).removeClass('edit_content_order').addClass('save_content_order');
        $(this).html('並び順保存');

        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	
	$(document).on('click', '.save_content_order', function () {
        var button = $(this);
        var $form = $('#register_form');
        var params = $form.serializeArray();
		
		var apiUrl = '';

        $.ajax({
            type:'POST',
            dataType:'json',
            data: params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url: '/office-manual/chapter-update-order',
        });
	});

    $(document).on('click', '#popup_ok', function () {
        location.href = '/office-manual/chapter-list?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
    });
    
    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });
});    
</script>
<style type="text/css">
a.edit_item {display:block;background-color:#64bd63;color:#fff;padding:2px 3px;text-decoration:none;border-radius:5px;width:80px;text-align:center;margin:3px 0 0 3px;float:left;cursor:pointer;}
.multi_rows_padding {padding:5px 10px 5px 10px;}
.order_btn_frame {float:left;margin:6px 0 0 14px;}
.order_btn_frame .icon-up-dir-1 {font-size:14px;color:#000;line-height:1;display:block;}
.order_btn_frame .icon-down-dir-1 {font-size:14px;margin-top:-6px;color:#000;line-height:1;display:block;}
a.btn_setting.save_content_order {background-color:#64bd63}
.sortable_column tr td {background-color:#fff;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:230px;right:0;">
				<a class="btn_setting edit_content_order" style="display:block;float:left;width:92px;padding:5px 0;margin:0;border:none;margin-right:5px" href="javascript:void(0);">並び順変更</a>
                <a class="btn_setting" style="display:block;float:left;width:132px;padding:5px 0;margin:0;border:none;" href="/office-manual/chapter-detail?id=<?php echo $this->escape($this->id); ?>">新規チャプター登録</a>
            </p>
	        <span><strong>チャプター管理</strong></span>
	    </div>
	</div>
	
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<form id="register_form" action="#" method="post"> 
		<table class="list_default">
			<tr>
				<th><p>チャプター名</p></th>
				<th style="width:9%;"><p>編集</p></th>
			</tr>
			<tbody class="sortable_column" id="sortable_column">
			<?php if (!empty($this->chapterList)) { ?>
				<?php foreach ($this->chapterList as $each) { ?>
					<tr id="<?php echo $this->escape($each['id']); ?>">
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['chapter_name']); ?></div>
						</td>
						<td>
							<div class="display_value">
								<a class="edit_item" href="/office-manual/chapter-detail?id=<?php echo $this->escape($this->id); ?>&chapter_id=<?php echo $this->escape($each['id']); ?>">編集</a>
							</div>
							<div class="edit_value">
			                    <div class="order_btn_frame edit_value" style="display:none;">
			                        <i class="icon-up-dir-1"></i>
			                        <i class="icon-down-dir-1"></i>
			                    </div>
							</div>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="2">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
		<input type="hidden" id="hidden_contents_order" name="item_list" value="" />
		</form>
		
        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

