<?php
$confidentialityList = Shared_Model_Code::codes('manual_confidentiality');
?>
<script type="text/javascript">
$(function () {
	$(document).ready(function(){
	    $('#sortable_column td').each(function(){
            $(this).css('width', $(this).width() +'px');
        });
        
		var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	$(document).on('click', '.edit_content_order', function () {
        $('.display_value').hide();
        $('.edit_value').show();
    
        // ×,保存ボタン
        $(this).removeClass('edit_content_order').addClass('save_content_order');
        $(this).html('並び順保存');

        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	
	$(document).on('click', '.save_content_order', function () {
        var button = $(this);
        var $form = $('#register_form');
        var params = $form.serializeArray();
		
		var apiUrl = '';

        $.ajax({
            type:'POST',
            dataType:'json',
            data:params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error:function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url:'/office-manual/manual-update-order',
        });
	});

    $(document).on('click', '#popup_ok', function () {
        location.href = '/office-manual/';
    });
    
    $(".sortable_column").sortable({
        items:"tr:not(.not-sortable)",
        update:function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay:100,
        stop:function (event, ui) {},
        start:function (event, ui) {}
    });
});    
</script>
<style type="text/css">
p.action_title {font-size:1.1em;padding-left:11px;padding-top:10px;font-weight:bold;}
.multi_rows_padding {padding:5px 5px 5px 5px}

a.edit_item {display:block;background-color:#64bd63;color:#fff;padding:2px 3px;text-decoration:none;border-radius:5px;width:80px;text-align:center;margin:3px 0 0 3px;float:left;cursor:pointer;}
.multi_rows_padding {padding:5px 10px 5px 10px;}
.order_btn_frame {float:left;margin:6px 0 0 14px;}
.order_btn_frame .icon-up-dir-1 {font-size:14px;color:#000;line-height:1;display:block;}
.order_btn_frame .icon-down-dir-1 {font-size:14px;margin-top:-6px;color:#000;line-height:1;display:block;}
a.btn_setting.save_content_order {background-color:#64bd63}
.sortable_column tr td {background-color:#fff;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:278px;right:0;">
				<a class="btn_setting" style="display:block;float:left;width:100px;padding:5px 0;margin:0;border:none;margin-right:5px;background-color:#000;" href="/office-manual/category-list">区分定義</a>
				<a class="btn_setting edit_content_order" style="display:block;float:left;width:92px;padding:5px 0;margin:0;border:none;margin-right:5px" href="javascript:void(0);">並び順変更</a>
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/office-manual/add">新規登録</a>
            </p>
	        <span style=""><strong>マニュアル</strong></span>
	    </div>
		<div class="menu_list clearfix">
		<a class="menu <?php if($this->action == 'index') echo "selected"; ?>" href="/office-manual/index">一覧</a>
		<a class="menu <?php if($this->action == 'search') echo "selected"; ?>" href="/office-manual/search">検索</a>
		</div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<form id="register_form" action="#" method="post"> 
		<table class="list_default">
			<tr>
				<th style="width:9%;"><p>最終更新日</p></th>
				<th style="width:26%;"><p>タイトル</p></th>
				<th style="width:14%;"><p>区分</p></th>
				<th style="width:14%;"><p>機密度/権限グループ</p></th>
				<th><p>備考</p></th>
				<th style="width:5%;"><p>詳細</p></th>
			</tr>

			<?php if (!empty($this->items)) { ?>
				<tbody class="sortable_column" id="sortable_column">
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>">
						<td>
							<div class="multi_rows_padding"><?php echo date('Y-m-d', strtotime($each['updated'])); ?><br><?php echo date('H:i', strtotime($each['updated'])); ?></div>
						</td>
						
						<td>
							<div class="multi_rows_padding"><?php echo $each['title']; ?></div>
						</td>

						<td>
							<div class="multi_rows_padding">
								<?php
									if (!empty($each['manual_category_id'])) {
										echo $this->categoryList[$each['manual_category_id']]['category_name'];
									} else {
										echo '---';
									}
								?>
							</div>
						</td>			

						<td>
							<?php if (!empty($each['confidentiality'])) { ?>
								<p><?php echo $confidentialityList[$each['confidentiality']]; ?></p>
							<?php } else { ?>
								<p>---</p>
							<?php } ?>
						</td>

						<td>
							<div class="multi_rows_padding">
							管理責任者：<?php if (!empty($each['user_name'])) { echo $this->escape($each['user_name']); } else { echo '---'; } ?><br>
							<?php echo $this->roundText($this->escape($each['memo']), 70); ?>
							</div>
						</td>

						<td>
							<div class="display_value">
								<p><a href="/office-manual/top?id=<?php echo $this->escape($each['id']) ?>">詳細</a></p>
							</div>
							<div class="edit_value">
			                    <div class="order_btn_frame edit_value" style="display:none;">
			                        <i class="icon-up-dir-1"></i>
			                        <i class="icon-down-dir-1"></i>
			                    </div>
							</div>
						</td>
					</tr>
				<?php } ?>
				</tbody>
			<?php } else { ?>
				<tr>
					<td colspan="6">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>
		<input type="hidden" id="hidden_contents_order" name="item_list" value="">
		</form>
		
        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

