<?php
	$contentTypeList = Shared_Model_Code::codes('manual_content_type');

    if ($this->data['content_type'] !== (string)Shared_Model_Code::MANUAL_CONTENT_TYPE_TEXT) {
    	$fileList = json_decode($this->data['content'], true);
    }
?>
<script type="text/javascript">
var reloadFlag = false;
var pos = 0;
var editing = false;

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

function dragover(e) {
    e.preventDefault();
}
					
function drop(id, e) {
	$('#' + id + '_add_image_box').removeClass('over');
	e.preventDefault();
	var files = e.dataTransfer.files;
  
	if (files.length > 1) {
  		jAlert('ファイルは一枚ずつドロップしてください。', 'エラー');
 	 	return;
	}

    // アップロード処理へ
    fileUpload(id, files[0]);
}

function fileUpload(id, fd) {
    var formData = new FormData();
    formData.append('file', fd);
	
	showSpinner();
	
    $.ajax({
    	async:true,
		type:'POST',
		contentType:false,
		processData: false,
		url:'/office-manual/upload',
		data:formData,
		dataType:'json'
    }).done(function(res){
    	stopSpinner();
    	
        var obj = res;
        if (obj.result == 'timeout') {
            location.href = '/login';
            return;            
        } else if(obj.result == true) {
        	$('#' + id + '_file_name_text').html(obj.file_name);
        	$('#' + id + '_file_name').val(obj.file_name);
        	$('#' + id + '_temp_file_name').val(obj.temp_file_name);
        } else {
        	jAlert('予期せぬエラーが発生しました', 'エラー');
        }
    });
}

$(function() {
    $(document).ready(function(){
        var result = $("#sortable_column_1").sortable("toArray");
        $('input#hidden_contents_order_1').val(result);
        
		<?php if (!empty($fileList)) { ?>
	    <?php foreach ($fileList as $each) { ?>
			<?php $uid = uniqid(); ?>
			
	        // ファイルのドロップ時エフェクト
			var targetE<?php echo $uid; ?> = document.getElementById('<?php echo $this->escape($each['id']); ?>_add_image_box');
			var innerFlag<?php echo $uid; ?> = false;
			
			targetE<?php echo $uid; ?>.addEventListener('dragenter', function () {
			    innerFlag<?php echo $uid; ?> = true;
			}, false);
			
			targetE<?php echo $uid; ?>.addEventListener('dragover', function () {
			    innerFlag<?php echo $uid; ?> = false;
			    targetE<?php echo $uid; ?>.className = 'add_image_box over';
			}, false);
			
			targetE<?php echo $uid; ?>.addEventListener('dragleave', function () {
			    if (innerFlag<?php echo $uid; ?>) {
			        innerFlag<?php echo $uid; ?> = false;
			    } else {
			        targetE<?php echo $uid; ?>.className = 'add_image_box';
			    }
			}, false);
		<?php } ?>
		<?php } ?>
    });

	<?php 
		$confirmMessage = '登録しますか';
		$succeedMessage = '登録しました';
		$backmessage    = '登録せずに中止しますか';
		if (!empty($this->id)) {
			$confirmMessage = '保存しますか';
			$succeedMessage = '保存しました';
			$backmessage    = '保存せずに中止しますか';
        }
	?>
			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
    	jConfirm('<?php echo $backmessage; ?>', '　', function(r) {
            if(r) {
               location.href = '/office-manual/top?id=<?php echo $this->escape($this->chapterData['manual_id']); ?>&chapter_id=<?php echo $this->escape($this->chapterId); ?>';
            } else {
                return false;
            }
        });
	});
		
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('<?php echo $confirmMessage; ?>', '　', function(r) {
            if(r) {
                var $form  = $('#register_form');
                var query  = $form.serialize();
                var params = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data:params,
                    success:function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if (obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('<?php echo $succeedMessage; ?>', '　'); 
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url:'/office-manual/item-update?chapter_id=<?php echo $this->escape($this->chapterId); ?><?php if (!empty($this->itemId)) echo '&item_id=' . $this->itemId; ?>'
                });
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/office-manual/top?id=<?php echo $this->escape($this->chapterData['manual_id']); ?>&chapter_id=<?php echo $this->escape($this->chapterId); ?>';
        }
    });
    
	// コンテンツタイプ
    $('#content_type').change(function() {
		if ($(this).val() == <?php echo Shared_Model_Code::MANUAL_CONTENT_TYPE_TEXT; ?>) {
			$('#content_text').show();
			$('#content_file').hide();
			
		} if ($(this).val() == <?php echo Shared_Model_Code::MANUAL_CONTENT_TYPE_IMAGE; ?> || $(this).val() == <?php echo Shared_Model_Code::MANUAL_CONTENT_TYPE_FILE; ?>) {
			$('#content_text').hide();
			$('#content_file').show();

		}
    });

    $(".sortable_column").sortable({
        items:"tr:not(.not-sortable)",
        update:function(event, ui){
        	var categoryId = $(this).attr('target-category');
            var result = $("#sortable_column_" + categoryId).sortable("toArray");
            $('input#hidden_contents_order_' + categoryId).val(result);
        },
        handle:'.order_btn_frame',
        delay:100,
        stop:function (event, ui) {},
        start:function (event, ui) {}
    });
    
    // 行追加
    $(document).on('click', '.btn_add_column', function () {
	    var categoryId = $(this).attr('target-category');
        var uuid = guid();
        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', uuid + '_file_name_text').attr('name', uuid + '_file_name_text');
        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', uuid + '_file_name').attr('name', uuid + '_file_name');
        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', uuid + '_temp_file_name').attr('name', uuid + '_temp_file_name');
        $('.column_copy_base_' + categoryId + ' .summary').attr('id', uuid + '_summary').attr('name', uuid + '_summary');
		$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', uuid + '_add_image_box').attr('ondrop', "drop('" + uuid + "',event)");
		$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);
		
        var $clone = $('.column_copy_base_' + categoryId).clone(true);
        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));
		$('.column_copy_base_' + categoryId + ' .target_date').attr('id', '');
        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', '');
        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', '');
        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', '');
		$('.column_copy_base_' + categoryId + ' .summary').attr('id', '');
		$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', '');


        // ファイルのドロップ時エフェクト
		var targetE = document.getElementById(uuid + '_add_image_box');
		var innerFlag = false;
		
		targetE.addEventListener('dragenter', function () {
		    innerFlag = true;
		}, false);
		
		targetE.addEventListener('dragover', function () {
		    innerFlag = false;
		    targetE.className = 'add_image_box over';
		}, false);
		
		targetE.addEventListener('dragleave', function () {
		    if (innerFlag) {
		        innerFlag = false;
		    } else {
		        targetE.className = 'add_image_box';
		    }
		}, false);
	
        $('.column_copy_base_' + categoryId + ' td.added_row').each(function(){
            $(this).css('width', $(this).width() +'px');
        });

        var result = $("#sortable_column_" + categoryId).sortable("toArray");
        $('input#hidden_contents_order_' + categoryId).val(result);

    });

    // 行削除
    $(document).on('click', '.delete_button', function () {
    	var categoryId = $(this).attr('target-category');
    	var targetId   = $(this).attr('target-row');
		$('tr#' + targetId).remove();
		
        var result = $("#sortable_column_" + categoryId).sortable("toArray");
        $('input#hidden_contents_order_' + categoryId).val(result);
    });
});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
#horizontalwrap {display:inline;white-space:nowrap;}
span.note {display:block;margin:4px 0 3px;padding:0 4px;}
table.list_default tr td.column {border-right:none;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column p {padding-left:12px;}
table.list_default tr td.column input {width:99%}
table.list_default tr td.column select.short {width:200px}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>コンテンツ管理 - <?php if (!empty($this->itemId)) { echo '編集'; } else { echo '登録'; } ?></strong></span>
        </div>
    </div>
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">
	    <?php
        /* コンテンツ情報 */
        $categoryId = 1;
        ?>
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">種別選択</p>
                </th>
            </tr>
		</table>
		
		<input type="hidden" name="pos" value="<?php if (!empty($this->pos)) { echo $this->escape($this->pos); } ?>">

		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">タイトル：</p></td>
                <td class="column">
					<input type="text" name="title" value="<?php if (!empty($this->data['title'])) { echo $this->escape($this->data['title']); } ?>" style="width:80%;">
                </td>
            </tr>
            
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">コンテンツ種別：</p></td>
                <td class="column">
                	<select id="content_type" name="content_type" style="width:300px">
	                	<?php foreach ($contentTypeList as $key => $val) { ?>
	                		<option value="<?php echo $this->escape($key); ?>" <?php if ($this->data['content_type'] === (string)$key) { echo 'selected="selected"'; } ?>><?php echo $this->escape($val); ?></option>
	                	<?php } ?>
                	</select>
                </td>
            </tr>
            
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">キーワード：</p></td>
                <td class="column">
	                <div class="clearfix" style="margin-top:0.3em;">
						<input type="text" name="keyword_1" value="<?php if (!empty($this->data['keyword_1'])) { echo $this->escape($this->data['keyword_1']); } ?>" style="float:left;width:30%;margin:0 0.9em 0.3em 0;">
						<input type="text" name="keyword_2" value="<?php if (!empty($this->data['keyword_2'])) { echo $this->escape($this->data['keyword_2']); } ?>" style="float:left;width:30%;margin:0 0.9em 0.3em 0;">
						<input type="text" name="keyword_3" value="<?php if (!empty($this->data['keyword_3'])) { echo $this->escape($this->data['keyword_3']); } ?>" style="float:left;width:30%;margin:0 0.9em 0.3em 0;">
						<input type="text" name="keyword_4" value="<?php if (!empty($this->data['keyword_4'])) { echo $this->escape($this->data['keyword_4']); } ?>" style="float:left;width:30%;margin:0 0.9em 0.3em 0;">
						<input type="text" name="keyword_5" value="<?php if (!empty($this->data['keyword_5'])) { echo $this->escape($this->data['keyword_5']); } ?>" style="float:left;width:30%;margin:0 0.9em 0.3em 0;">
						<input type="text" name="keyword_6" value="<?php if (!empty($this->data['keyword_6'])) { echo $this->escape($this->data['keyword_6']); } ?>" style="float:left;width:30%;margin:0 0.9em 0.3em 0;">
	                </div>
                </td>
            </tr>
            <?php /*
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">content_order：</p></td>
                <td class="column">
					<input type="text" name="content_order" value="<?php if (!empty($this->data['content_order'])) { echo $this->escape($this->data['content_order']); } ?>" style="width:6em;">
                </td>
            </tr>
            */ ?>
        </table>
        
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">コンテンツ</p>
                </th>
            </tr>
		</table> 
        <div id="content_text" <?php if ($this->data['content_type'] !== (string)Shared_Model_Code::MANUAL_CONTENT_TYPE_TEXT) { ?>style="display:none;"<?php } ?>>
       		<div style="background-color:#ebf6ff;font-size:1.2em;padding:1.0em;">
	        	<strong>文字の装飾について</strong><br>
	        	サイズ大　　　　：　[*強調する文字*]<br>
	        	太文字表示　　　：　[[強調する文字]]<br>
	        	赤色表示　　　　：　{{強調する文字}}<br>
				太文字＋赤色表示：　{{[[強調する文字]]}}<br>
	        </div>
       		<table class="list_default" style="margin-bottom:0;">
                <td class="column" style="width:200px;"><p class="label_text">内容：</p></td>
                <td class="column">
	                <textarea name="content_text" style="height:600px;margin-bottom:6px;"><?php if ($this->data['content_type'] === (string)Shared_Model_Code::MANUAL_CONTENT_TYPE_TEXT) { echo $this->escape($this->data['content']); } ?></textarea>
                </td>
       		</table>
       	</div>
	    <div id="content_file" <?php if ($this->data['content_type'] !== (string)Shared_Model_Code::MANUAL_CONTENT_TYPE_IMAGE && $this->data['content_type'] !== (string)Shared_Model_Code::MANUAL_CONTENT_TYPE_FILE) { ?>style="display:none;"<?php } ?>>  
		<table class="list_default" style="margin-bottom:0;">
			<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
		        <?php if (!empty($fileList)) { ?>
			        <?php foreach ($fileList as $each) { ?>
				        <tr id="<?php echo $this->escape($each['id']); ?>">
							<td class="column_value">
								<div class="clearfix">
									<div style="float:left;width:360px;">
										<div class="clearfix" style="margin-bottom:5px">
											<div style="float:left;width:50px;padding:15px 0 0 10px;">
												<i class="budicon-equal" style="color:#aaa;font-size:48px;"></i>
											</div>
											<div style="float:left;width:300px;">
												<div class="multi_rows_padding" style="padding-left:18px;"><span class="file_name_text" id="<?php echo $this->escape($each['id']); ?>_file_name_text"><?php echo $this->escape($each['file_name']); ?></span></div>
												<p style="padding-left:18px;">file size：<?php echo $this->byteFormat(Shared_Model_Resource_Manual::getFileSize($this->data['manual_id'], $this->data['id'], $each['file_name']), 2); ?></p>
												<input type="hidden" class="file_name" id="<?php echo $this->escape($each['id']); ?>_file_name" name="<?php echo $this->escape($each['id']); ?>_file_name" value="<?php echo $this->escape($each['file_name']); ?>" />
												<input type="hidden" class="temp_file_name" id="<?php echo $this->escape($each['id']); ?>_temp_file_name" name="<?php echo $this->escape($each['id']); ?>_temp_file_name" value="" />  
											</div>
										</div>
										<div class="display_value_<?php echo $categoryId; ?>">
											<a class="btn_setting" style="margin-left:12px;" target="_blank" href="<?php echo Shared_Model_Resource_Manual::getResourceUrl($this->data['manual_id'], $this->data['id'], $each['file_name']); ?>">ダウンロード</a>
										</div>
										<div class="edit_value_<?php echo $categoryId; ?> clearfix">
											<div class="add_image_box" id="<?php echo $this->escape($each['id']); ?>_add_image_box" ondragover="dragover(event)" ondrop="drop('<?php echo $this->escape($each['id']); ?>',event)" style="margin-bottom:13px;">
												<i class="icon-upload-cloud" style="font-size:60px;color:#888;"></i><br>ファイルをドラッグ&amp;ドロップしてください
											</div>
										</div>
									</div>
									<div style="float:left;margin-left:10px;width:770px;">
										<p>説明:</p>
					                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" >
					                    	<textarea class="summary" name="<?php echo $this->escape($each['id']); ?>_summary" style="margin-top:9px;height:50em;margin-bottom:6px;"><?php echo $this->escape($each['summary']); ?></textarea>
					                    </div>	
									</div>
								</div>
							</td>
				            <td class="td_action">
				            	<div class="edit_value_<?php echo $categoryId; ?> delete_btn_frame clearfix">
				            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row="<?php echo $this->escape($each['id']); ?>"><i class="icon-cancel"></i></a>
				            	</div>
				            </td>
				        </tr>
			        <?php } ?>
		        <?php } ?>
        	</tbody>
    	</table>
    	<div class="edit_value_<?php echo $categoryId; ?>" style="border-bottom:1px solid #ccc;height:34px;">
            <p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
        </div>
    	<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="file_list" value="" />	
	    </div>
	</div><!-- clearfix -->				
    </form>

    <!-- copy base -->
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base_<?php echo $categoryId; ?>" id="">
			<td class="column_value">
				<div class="clearfix">
					<div style="float:left;width:360px;">
						<div class="clearfix" style="margin-bottom:5px">
							<div style="float:left;width:50px;padding:15px 0 0 10px;">
								<i class="budicon-equal" style="color:#aaa;font-size:48px;"></i>
							</div>
							<div style="float:left;width:300px;">
								<div class="multi_rows_padding" style="padding-left:18px;"><span class="file_name_text" id="##_file_name_text">(ファイル名)</span></div>
								<input type="hidden" class="file_name" id="##_file_name" name="##_file_name" value="" />
								<input type="hidden" class="temp_file_name" id="##_temp_file_name" name="##_temp_file_name" value="" />  
							</div>
						</div>
						<div class="add_image_box" id="##_add_image_box" ondragover="dragover(event)" ondrop="drop(##,event)" style="margin-bottom:13px;">
							<i class="icon-upload-cloud" style="font-size:60px;color:#888;"></i><br>ファイルをドラッグ&amp;ドロップしてください
						</div>
					</div>
					<div style="float:left;margin-left:10px;width:670px;">
						<p>説明:</p>
						<textarea class="summary" name="##_summary" style="margin-top:9px;height:142px;margin-bottom:6px;"><?php echo $this->escape($this->documentData['summary']); ?></textarea>
					</div>
				</div>
			</td>
            <td class="td_action">
            	<div class="delete_btn_frame">
            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row=""><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>    
	<!-- copy base -->
    
        
</div>
</div>
</div>
</div>
