<?php
$statusList         = Shared_Model_Code::codes('direct_order_status_search');
$shipmentStatusList = Shared_Model_Code::codes('direct_order_shipment_status');

$payementConditionList       = Shared_Model_Code::codes('order_payment_condition');
?>
<script type="text/javascript">
$(function () {
	$(".clear_form").bind("click", function(){
	    $(this.form).find('textarea, :text, :hidden:not("#search, #page")').val("");
	    $(this.form).find('select option').removeAttr('selected');
	    $('.target_text').html('');
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
	});
	
    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });
    
    // 取引先 リセット
    $(document).on('click', '#reset_connection', function () {
		$('#connection_name_display').html('');
		$('#connection_name').val('');
		$('#connection_id').val('');
	});

	// 申請者 ポップアップ表示
    $(document).on('click', '#select_applicant_user', function () {
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/user/list-select', null, function () {stopSpinner();});
	});
    
	// 申請者 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    // 申請者 リセット
    $(document).on('click', '#reset_applicant_user', function () {
		$('#applicant_user_name_display').html('');
		$('#applicant_user_name').val('');
		$('#applicant_user_id').val('');
	});
	
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    }); 
});

// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}
// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form = $('#connection_condition_form');
    var query = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/connection/list-select?page=' + pageNo,
    });
}
// 取引先 選択完了
function selectConnection(id, displayId, name) {
	$('#connection_name_display').html(name);
	$('#connection_name').val(name);
	$('#connection_id').val(id);
	$('.btn_close').click();
}

// 申請者 一覧更新
function updateUserList (pageNo) {
    var $form = $('#user_condition_form');
    var query = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/user/list-select?page=' + pageNo,
    });
}

// 申請者 選択完了
function selectUser(id, departmentName, name, departmentNameEn, nameEn) {
	$('#applicant_user_name_display').html(departmentName + '　' + name);
	$('#applicant_user_name').val(departmentName + '　' + name);
	$('#applicant_user_id').val(id);
	$('.btn_close').click();
}
</script>
<style type="text/css">
table.list_default tr:hover td {background:#deeeff;}
.multi_rows_padding {padding: 5px 10px 5px 10px;}
table.list_default tr td a.btn_setting {margin:5px 5px 0px 5px;padding:7px 0 5px 0;line-height:1;display:block;cursor:pointer;text-align:center;}
table.list_default tr.gray_out td {background-color:#eee}
table.list_default tr.gray_out:hover td {background:#eee;}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin:5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:5px 0 10px 5px;padding:3px 5px 1px 5px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}

.prepay {font-weight:bold;color:#e513a3}
.month {font-weight:bold;color:#1364e5}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<?php if ($this->allowEditing) { ?>
				<p style="position:absolute;width:76px;right:0;">
	                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/transaction-order-recieved/add">新規登録</a>
	            </p>
            <?php } ?>
	        <span style=""><strong>受注管理</strong></span>
	    </div>
	</div>


	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/transaction-order-recieved/list" method="get">
				<p class="search_condition_title">検索条件</p>
				
				<input type="hidden" id="search" name="search" value="1">
				<input type="hidden" id="page" name="page" value="1">
				
				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="status" name="status">
                            <option value="">---</option>
                        	<?php foreach ($statusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">出荷状況：</p>
                        <select id="shipment_status" name="shipment_status">
                            <option value="">---</option>
                        	<?php foreach ($shipmentStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">取引先企業：</p>
						<div class="input_box_fake">
							<span class="target_text" id="connection_name_display"><?php echo $this->conditions['connection_name']; ?></span>
							<a class="reset_popup" id="reset_connection" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_connection" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="connection_name" name="connection_name" value="<?php echo $this->conditions['connection_name']; ?>">
						<input type="hidden" id="connection_id" name="connection_id" value="<?php echo $this->conditions['connection_id']; ?>">
					</div>

					<div class="condition_item">
						<p class="condition_label">登録者：</p>
						<div class="input_box_fake">
							<span class="target_text" id="applicant_user_name_display"><?php echo $this->conditions['applicant_user_name']; ?></span>
							<a class="reset_popup" id="reset_applicant_user" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_applicant_user" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="applicant_user_name" name="applicant_user_name" value="<?php echo $this->conditions['applicant_user_name']; ?>">
						<input type="hidden" id="applicant_user_id" name="applicant_user_id" value="<?php echo $this->conditions['applicant_user_id']; ?>">
					</div>

					<div class="condition_item">
						<p class="condition_label">キーワード：</p>
                        <input type="text" id="keyword" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" disabled="disabled">
					</div>
				</div>
				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット">
					<input type="submit" class="submit" style="display:inline-block;width:150px;" value="検索">
				</div>
			</form>
		</div>
	</div>

	<div class="clearfix">
		<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
    </div>
    
    <?php $invoiceTable = new Shared_Model_Data_Invoice(); ?>
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:8%;">
					<p style="float:left;">受注ID</p>
			    	<?php
			            echo $this->partial('column_order.phtml', array(
			    			'columnName'       => 'id',
			    			'conditionColumn'  => $this->column,
			    			'conditionOrder'   => $this->order,
			    		));
			        ?>
				</th>
				<th style="width:8%;">
					<p style="float:left;">受注日</p>
					<?php
			            echo $this->partial('column_order.phtml', array(
			    			'columnName'       => 'recieved_date',
			    			'conditionColumn'  => $this->column,
			    			'conditionOrder'   => $this->order,
			    		));
			        ?>	
				</th>
				<th style="width:10%;"><p>ステ/入金条件</p></th>
				<th style="width:7%;"><p>請求書発行</p></th>
				<th style="width:13%;"><p>出荷状況/納品予定日</p></th>
				
				<th style="width:14%;"><p>取引先企業名</p></th>	
				<th><p>受注内容/金額</p></th>
				<th style="width:8%;"><p>登録者&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:5%;"><p>詳細</p></th>
			</tr>

			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $this->escape($each['id']); ?>" <?php if ($each['status'] === (string)Shared_Model_Code::DIRECT_ORDER_STATUS_CANCELED) { echo 'class="gray_out"'; } ?>>
						<td>
							<p><?php echo $this->escape($each['display_id']); ?></p>
						</td>

						<td>
							<p><?php echo date('Y-m-d', strtotime($each['order_recieved_date'])); ?></p>
						</td>

						<td>
							<div class="multi_rows_padding">
							<?php if ($each['status'] === (string)Shared_Model_Code::DIRECT_ORDER_STATUS_INVOICE_COMPLETED) { ?>
								<!-- 承認済み -->
								<strong><?php echo $statusList[$each['status']]; ?></strong><br>
							<?php } else {?>
								<?php echo $statusList[$each['status']]; ?><br>
							<?php } ?>
							
							
							<?php if ($each['payment_method'] == '1') { ?>
			                	<span class="prepay">前払</span>
			                <?php } else if ($each['payment_method'] == '2') { ?>
			                	<span class="month">末締め翌月末</span>
			                <?php } else if ($each['payment_method'] == '10') { ?>
			                	<?php 
			                		$otherCondition = '';
			                		if ($this->data['other_payment_condition'] === (string)Shared_Model_Code::CONNECTION_PAYMENT_CONDITION_BASED_DELIVERY
									|| $this->data['other_payment_condition'] === (string)Shared_Model_Code::CONNECTION_PAYMENT_CONDITION_BASED_CLAIM) {
										$otherCondition .= $payementConditionList[$this->data['other_payment_condition']] . '　　';
			                			$otherCondition .= $payementMonthlyList[$this->data['other_payment_condition_close']] . '締め' . $payementConditionMonthList[$this->data['other_payment_condition_month']]
			                			 . $payementMonthlyList[$this->data['other_payment_condition_pay']] . '払い';
			                		} else {
			                			$otherCondition .= $this->data['other_payment_condition_other'];
			                		}
			                	?>
			                	<span>その他　　<?php echo $this->escape($otherCondition); ?></span>
			                <?php } ?>
							</div>
						</td>
						

						<td>
							<?php /*DIRECT_ORDER_STATUS_INVOICE_COMPLETED*/ ?>
							<p style="text-align:right;padding-right:11px;"><?php echo $invoiceTable->getCountByDirectOrderId($this->adminProperty['management_group_id'], $each['id']); ?></p>
						</td>
						
						<td>
	    					<?php if ($each['status'] === (string)Shared_Model_Code::DIRECT_ORDER_STATUS_APPROVED || $each['status'] === (string)Shared_Model_Code::DIRECT_ORDER_STATUS_INVOICE_COMPLETED) { ?>
								<?php if ($each['status'] === (string)Shared_Model_Code::DIRECT_ORDER_STATUS_NO_SHIPPING) { ?>
									<div class="multi_rows_padding">出荷なし</div>
								<?php } else { ?>
									<?php if (empty($each['shipment_status'])) { ?>
										<div class="multi_rows_padding">
											<strong style="color:#f00;">未納品</strong><br>
											<?php if (!empty($each['is_delivery_plan_date_unknown'])) { ?>
								            	予定日未定<br>（<?php echo date('Y-m-d', strtotime($each['delivery_plan_date'])); ?>）
								            <?php } else { ?>
								            	<?php if (empty($each['delivery_plan_date'])) { ?>
								            		予定日：---
								            	<?php } else { ?>
								            		予定日：<?php echo date('Y-m-d', strtotime($each['delivery_plan_date'])); ?>
								            	<?php } ?>
								            <?php } ?>
										</div>
										
										<a class="btn_setting" style="display:inline-block;background-color:#02ad00;margin-bottom:0.6em;font-weight:bold;padding-left:0.6em;padding-right:0.6em;" href="/transaction-order-recieved/deliveried?id=<?php echo $this->escape($each['id']); ?>">納品完了入力</a>
									<?php } else { ?>
										<div class="multi_rows_padding"><strong>納品済</strong><br>納品日：<?php echo $this->escape($each['deliveried_date']); ?></div>
									<?php } ?>
								<?php } ?>
							<?php } ?>
						</td>

						<td>
							<div class="multi_rows_padding"><?php echo $this->roundText($this->escape($each['company_name']), 24); ?></div>
						</td>

						<?php
							/* 注文内容 */
							$text = '';
							if (!empty($each['items'])) {
								$itemList = json_decode($each['items'], true);
								
								$textList = array();
								foreach ($itemList as $eachItem) {
									$exploded = explode("\n", $eachItem['item_name']);
									if (!empty($exploded[0])) {
										$textList[] = str_replace("\n", '', $exploded[0]);
									}
								}
								
								$text = $this->escape(implode(" ● ", $textList));
							}
							
							$text .= '<br><strong>受注合計金額(税込)：' . $this->escape(number_format($each['total_with_tax'])) . '&nbsp;' . $this->currencyList[$each['currency_id']]['name'] . '</strong>';			
						?>
						<td>
							<div class="multi_rows_padding"><?php echo $text; ?></div>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['user_name']); ?>">
							<p><?php echo $this->roundText($this->escape($each['user_name']), 7); ?></p>
						</td>

						<td>
							<p><a href="/transaction-order-recieved/detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="9">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

