<?php
$connectionTypeList  = Shared_Model_Code::codes('connection_type');
$relationTypeList    = Shared_Model_Code::codes('relation_type');
$salesRelationList   = Shared_Model_Code::codes('sales_relation');
$dutyList            = Shared_Model_Code::codes('duty');
$companyFormList     = Shared_Model_Code::codes('company_form');
?>
<script type="text/javascript"><!--
var reloadFlag = false;

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

$(function() {
    $(document).ready(function(){
        Tipped.create('#help_company_name', "正式名称");
        Tipped.create('#help_company_name_kana', "正式名称");
        Tipped.create('#help_industry_type', "複数選択可。たとえば外資の食品メーカーであれば「海外企業」「飲食品メーカー」を選択");
        Tipped.create('#help_relation_types', "「役務提供先／役務委託先」は「業務提供先／業務委託先」と「サービス提供先／サービス供給元」の両方の意味を含む");
        Tipped.create('#help_sales_relations', "サプライヤーはOEMを含む。サービス利用者は卸サイトの利用者。サービス提供者は加工受託者・広告・マッチング業者を含む");
        
        
        Tipped.create('#help_zip', "半角数字ハイフンあり");
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/connection/list";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/connection/add-post'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/connection/list';
        }
    });
    
    $('.relation_types').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::RELATION_TYPE_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#relation_type_other_text').prop("disabled", false);
			} else {
				$('#relation_type_other_text').prop("disabled", true);
			}
		}
    });
    
    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });

    // カラム追加
    $(document).on('click', '.btn_add_column', function () {

        var uuid = guid();
        $('.column_copy_base .financial_closing_year').attr('id', uuid + '_financial_closing_year').attr('name', uuid + '_financial_closing_year');
        $('.column_copy_base .financial_closing_sales').attr('id', uuid + '_financial_closing_sales').attr('name', uuid + '_financial_closing_sales');
        $('.column_copy_base .financial_closing_profit').attr('id', uuid + '_financial_closing_profit').attr('name', uuid + '_financial_closing_profit');
        $('.column_copy_base .delete_button').attr('target-row', uuid);

        var $clone = $('.column_copy_base').clone(true);
        $('tbody#sortable_column').append($clone.attr('class', '').attr('id', uuid).css('display', ''));
        
        $('.column_copy_base .financial_closing_year').attr('id', '');
        $('.column_copy_base .financial_closing_sales').attr('id', '');
        $('.column_copy_base .financial_closing_profit').attr('id', '');

        $('.column_copy_base td.added_row').each(function(){
            $(this).css('width', $(this).width() +'px');
        });

        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);

    });

    // カラム削除
    $(document).on('click', '.delete_button', function () {
    	var targetId   = $(this).attr('target-row');
		$('tr#' + targetId).remove();
		
        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
    });

});
--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.zip {width:130px;}

a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}

table.list_default tr td p.financial_closing_label {float:left;margin-right:10px;}
table.list_default tr td.td_financial_closing_year {width:250px;border-right:none;}
table.list_default tr td.td_financial_closing_year {border-right:none;}
table.list_default tr td.td_financial_closing_year input.product_item_amount {width:130px;}

table.list_default tr td.td_financial_closing_amount {width:350px;border-right:none;}
table.list_default tr td.td_financial_closing_amount {border-right:none;}
table.list_default tr td.td_financial_closing_amount input {width:230px;}

table.list_default tr td.td_financial_closing_profit {border-right:none;}
table.list_default tr td.td_financial_closing_profit {border-right:none;}
table.list_default tr td.td_financial_closing_profit input {width:230px;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
a.btn_setting#btn_copy {padding:1px 8px 0px;float:left;margin-left:20px;margin-top:5px;margin-bottom:0}
table.list_default tr td p.industory_category {background-color:#bae0ff;padding:11px 0 9px 12px}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>取引先 - 新規登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">管理情報</p>
                </th>
            </tr>
		</table>
         
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">企業・機関名<span class="popup_help" id="help_company_name">&nbsp;<i class="icon-help-circled"></i></span><span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="company_name" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">企業・機関名カナ<span class="popup_help" id="help_company_name_kana">&nbsp;<i class="icon-help-circled"></i></span><span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="company_name_kana" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">種別<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
	                	<?php foreach ($connectionTypeList as $key => $val) { ?>
		                	<div class="checkbox_item relation_type_item">
			                	<label>
			                    	<input type="radio" name="type" value="<?php echo $this->escape($key); ?>"><?php echo $val; ?>
			                    </label>
		                    </div>
	                    <?php } ?> 
	                </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">関連当社事業区分<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($this->ourBusinessList as $each) { ?>
		                	<div class="checkbox_item relation_type_item">
			                	<label>
			                    	<input type="checkbox" name="types_of_our_business[]" value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['name']); ?>
			                    </label>
		                    </div>
	                    <?php } ?>
                    </div>
                </td>
            </tr>
               
            <tr>
                <td class="column_label"><p class="label_text">当社との取引関係<span class="popup_help" id="help_relation_types">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($relationTypeList as $key => $val) { ?>
		                	<div class="checkbox_item relation_type_item">
			                	<label>
			                    	<input type="checkbox" class="relation_types" name="relation_types[]" value="<?php echo $this->escape($key); ?>"><?php echo $val; ?>
			                    </label>
		                    </div>
	                    <?php } ?> 
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="relation_type_other_text" name="relation_type_other_text" placeholder="その他取引関係" disabled="disabled" value="" maxlength="" style="width:300px;float:left;" />
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">当社に対する先方役割&nbsp;<span class="popup_help" id="help_sales_relations"><i class="icon-help-circled"></i></span><span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($salesRelationList as $key => $val) { ?>
		                	<div class="checkbox_item relation_type_item">
			                	<label>
			                    	<input type="checkbox" name="sales_relations[]" value="<?php echo $this->escape($key);; ?>"><?php echo $val; ?>
			                    </label>
		                    </div>
	                    <?php } ?>
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">業種<span class="popup_help" id="help_industry_type">&nbsp;<i class="icon-help-circled"></i></span><span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($this->industryCategoryList as $eachCatgory) { ?>
	                		<div class="clearfix">
	                			<p class="industory_category"><?php echo $this->escape($eachCatgory['name']); ?></p>
		                		<?php foreach ($eachCatgory['items'] as $each) { ?>
				                	<div class="checkbox_item relation_type_item">
					                	<label>
					                    	<input type="checkbox" name="industry_types[]" value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['name']); ?>
					                    </label>
				                    </div>
			                    <?php } ?>
		                    </div>
	                    <?php } ?>
                    </div>
                </td>
            </tr>


            
            <tr>
                <td class="column_label"><p class="label_text">事業内容<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<textarea name="description" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">法人番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="corporate_number" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">国<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<select class="short" id="country" name="country">
                            <option value="">---</option>
                            <?php foreach ($this->countryList as $each) { ?>
                                <option value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['name']); ?></option>
                            <?php } ?>
                    	</select>
                    </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">本社・郵便番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="zip" name="head_office_postal_code" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">本社・都道府県<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="head_office_prefecture" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">本社・市区町村<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="head_office_city" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">本社・丁番地<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="head_office_address" value="" maxlength="" />
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text">建物名・階／号室</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="head_office_building" value="" maxlength="" />
                </td>
            </tr>  
            
            <tr>
                <td class="column_label"><p class="label_text">代表者名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="representative_name" class="short" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">代表者名カナ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="representative_name_kana" class="short" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">代表電話番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="tel" class="short" value="" maxlength="" />
                </td>
            </tr>
                    
            <tr>
                <td class="column_label"><p class="label_text">FAX番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="fax" class="short" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">企業URL</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="web_url" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">課税・免税</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
	                	<?php foreach ($dutyList as $key => $val) { ?>
		                	<div class="checkbox_item relation_type_item">
			                	<label>
			                    	<input type="radio" name="duty" value="<?php echo $key; ?>"><?php echo $val; ?>
			                    </label>
		                    </div>
	                    <?php } ?>
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">取引先情報メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<textarea name="memo" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>
        </table>
		
		
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">信用情報</p>
                </th>
            </tr>
		</table>
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">会社設立年月日</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="foundation_date" value="" maxlength="" />
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">会社形態</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
						<select class="short" id="company_form" name="company_form">
                            <option value="0">---</option>
                            <?php foreach ($companyFormList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
                            <?php } ?>
                    	</select>
	                </div>
                </td>
            </tr>   
            
			<tr>
                <td class="column_label"><p class="label_text">資本金</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="capital" value="" maxlength="" />
					</div>
                </td>
            </tr>
            
			<tr>
                <td class="column_label"><p class="label_text">従業員数</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="employees" value="" maxlength="" />
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">営業店舗数</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="branch_offices" value="" maxlength="" />
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">主な株主</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="main_stockholder" value="" maxlength="" />
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">主要取引銀行</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="main_bank" value="" maxlength="" />
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">主要取引先企業</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="main_connection" value="" maxlength="" />
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">興信所・調査時期</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="detective_season" value="" maxlength="" />
					</div>
                </td>
            </tr>
                 
			<tr>
                <td class="column_label"><p class="label_text">興信所・調査機関名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="detective_name" value="" maxlength="" />
					</div>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">興信所・信用格付結果</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="detective_result" value="" maxlength="" />
					</div>
                </td>
            </tr>
            
 			<tr>
                <td class="column_label"><p class="label_text">当社信用格付</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<input type="text" name="detective_own" value="" maxlength="" />
					</div>
                </td>
            </tr>
            
 			<tr>
                <td class="column_label"><p class="label_text">他信用特記メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<textarea name="detective_memo" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>
             
		</table>
		
        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th class="border-left border-right border-top border-bottom"><p class="label_text strong">決算情報</p></th>
            </tr>
        </table>
	    <table class="list_default" style="margin-bottom:0;">
	    	<tbody class="sortable_column" id="sortable_column">
			</tbody>
	    </table>
        <div style="border-bottom:1px solid #dfdfdf;height:34px;">
            <p style="text-align:center;"><a class="btn_add_column" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
        </div>
    	<input type="hidden" id="hidden_contents_order" name="financial_closing_list" value="" />

        
	</div><!-- clearfix -->	
    </form>


    <?php
    /* 決算情報 追加用
    決算期年度
	決算期売上高
	決算期経常利益
	*/
    ?>
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base" id="">
            <td class="td_financial_closing_year">
            	<p class="financial_closing_label">決算期年度：</p>
            	<input type="text" class="financial_closing_year" name="" value="" />
            </td>
            <td class="td_financial_closing_amount">
            	<p class="financial_closing_label">決算期売上高：</p>
            	<input type="text" class="financial_closing_sales" name="" value="" />
            </td>
            <td class="td_financial_closing_profit">
            	<p class="financial_closing_label">決算期経常利益：</p>
            	<input type="text" class="financial_closing_profit" name="" value="" />
            </td>
            <td class="td_action">
            	<div class="delete_btn_frame">
            		<a class="delete_button" href="javascript:void(0);" target-row=""><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>
               
</div>
</div>
</div>
</div>

