<?php
$staffStatusList = Shared_Model_Code::codes('connection_staff_status');
?>
<link rel="stylesheet" href="/resource/js/switchery-0.8.0/dist/switchery.css" />
<script src="/resource/js/switchery-0.8.0/dist/switchery.js"></script>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){
		var elems = Array.prototype.slice.call(document.querySelectorAll('.switch'));
		                
		elems.forEach(function(html) {
		  var switchery = new Switchery(html, { size: 'small' });
		});
    });

	<?php 
		$confirmMessage = '登録しますか';
		$succeedMessage = '登録しました';
		$backmessage    = '登録せずに中止しますか';
		if (!empty($this->id)) {
			$confirmMessage = '保存しますか';
			$succeedMessage = '保存しました';
			$backmessage    = '保存せずに中止しますか';
        }
	?>
			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
       jConfirm('<?php echo $backmessage; ?>', '　', function(r) {
            if(r) {
               location.href = "/connection/base?id=<?php echo $this->escape($this->id); ?>";
            } else {
                return false;
            }
        });
	});
		
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('<?php echo $confirmMessage; ?>', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if (obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('<?php echo $succeedMessage; ?>', '　'); 
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/connection/update-base?id=<?php echo $this->escape($this->id); ?>'
                     + '<?php if (!empty($this->baseId)) echo '&base_id=' . $this->baseId; ?>'
                });
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/connection/base?id=<?php echo $this->escape($this->id); ?>';
        }
    });

});
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:300px;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:120px;}
table.list_default tr td.column_value select.short {width:300px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:500px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>納入先拠点 - <?php if (!empty($this->baseId)) { echo '編集'; } else { echo '登録'; } ?></strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
                    <p class="label_text strong">拠点情報</p>
                </th>
            </tr>
		</table>
         
        <table class="list_default" style="margin-bottom:13px;"> 
            <tr>
                <td class="column_label"><p class="label_text">拠点名<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<input type="text" name="base_name" value="<?php echo $this->escape($this->baseData['base_name']); ?>" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">ステータス<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<select class="short" id="status" name="status">
                        <option value="">---</option>
                        <?php foreach ($staffStatusList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ($key == $this->baseData['status']) echo 'selected="selected"'; ?>><?php echo $this->escape($value); ?></option>
                        <?php } ?>
                	</select>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">法人名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<input type="text" name="company_name" value="<?php echo $this->escape($this->baseData['company_name']); ?>" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">郵便番号<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="zipcode" value="<?php echo $this->escape($this->baseData['zipcode']); ?>" maxlength="" />
                </td>
            </tr> 

            <tr>
                <td class="column_label"><p class="label_text">都道府県<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="prefecture" value="<?php echo $this->escape($this->baseData['prefecture']); ?>" maxlength="" />
                </td>
            </tr> 
            
            <tr>
                <td class="column_label"><p class="label_text">住所<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="address1" value="<?php echo $this->escape($this->baseData['address1']); ?>" maxlength="" />
                </td>
            </tr> 
            
            <tr>
                <td class="column_label"><p class="label_text">建物名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="address2" value="<?php echo $this->escape($this->baseData['address2']); ?>" maxlength="" />
                </td>
            </tr> 
            
            
            <tr>
                <td class="column_label"><p class="label_text">電話番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="tel" value="<?php echo $this->escape($this->baseData['tel']); ?>" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">FAX番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="fax" value="<?php echo $this->escape($this->baseData['fax']); ?>" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">担当者 氏名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="person_in_charge" value="<?php echo $this->escape($this->baseData['person_in_charge']); ?>" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">担当者 氏名(カナ)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="person_in_charge_kana" value="<?php echo $this->escape($this->baseData['person_in_charge_kana']); ?>" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">担当者メールアドレス</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="mail" value="<?php echo $this->escape($this->baseData['mail']); ?>" maxlength="" />
                </td>
            </tr> 
            
            <tr>
                <td class="column_label"><p class="label_text">担当者携帯</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="mobile" value="<?php echo $this->escape($this->baseData['mobile']); ?>" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<textarea name="memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->baseData['memo']); ?></textarea>
                </td>
            </tr>
                         
        </table>
        
	</div><!-- clearfix -->	
    </form>

               
</div>
</div>
</div>
</div>

