<?php
$connectionStatusList  = Shared_Model_Code::codes('connection_status');
$connectionTypeList    = Shared_Model_Code::codes('connection_type');
$relationTypeList      = Shared_Model_Code::codes('relation_type');
$salesRelationList     = Shared_Model_Code::codes('sales_relation');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
   		Tipped.create('#help_keyword', "取引先ID / 企業・機関名 / 企業・機関名カナ / 事業内容 / 企業URL / 本社(郵便番号・都道府県・市区町村・丁番地・建物名・階／号室) <br> 代表者名 / FAX番号 / 担当者名");
    });

	$(".clear_form").bind("click", function(){
	    $(this.form).find("textarea, :text, select").val("").end().find(":checked").prop("checked", false);
	});
});    
</script>
<style type="text/css">
table.list_default tr th{position:relative;}
table.list_default tr th i{position:absolute;right:10px;margin-left:5px;font-size:1.2em}
table.list_default tr:hover td {background:#deeeff;}
table.list_default tr.deleted td {background:#ccc}
table.list_default tr.deleted:hover td {background:#bbb;}
table.list_default tr td p {height:auto;}
table.list_default tr td p.imported {color:#f00;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:162px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin-right:10px;border:none;" href="/connection/add">新規登録</a>
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/connection/import">取込</a>
            </p>
	        <span style=""><strong>取引先一覧</strong></span>
	    </div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form action="#" method="get">
				<p class="search_condition_title">検索条件</p>

				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="status" name="status">
                            <option value="">---</option>
                        	<?php foreach ($connectionStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">種別：</p>
                        <select id="type" name="type">
                            <option value="">---</option>
                        	<?php foreach ($connectionTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">当社との取引関係：</p>
                        <select id="relation_type" name="relation_type">
                            <option value="">---</option>
                        	<?php foreach ($relationTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['relation_type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">当社に対する先方役割：</p>
                        <select id="sales_relation" name="sales_relation">
                            <option value="">---</option>
                        	<?php foreach ($salesRelationList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['sales_relation']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
				</div>	
						
				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">業種：</p>
                        <select id="industry_type" name="industry_type">
                            <option value="">---</option>
                        	<?php foreach ($this->industryTypeList as $each) { ?>
                                <option value="<?php echo $each['id']; ?>" <?php if ($each['id'] == $this->conditions['industry_type']) echo 'selected="selectd"';?>><?php echo $each['name']; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">国：</p>
                        <select id="country" name="country">
                            <option value="">---</option>
                        	<?php foreach ($this->countryList as $each) { ?>
                                <option value="<?php echo $each['id']; ?>" <?php if ($each['id'] == $this->conditions['country']) echo 'selected="selectd"';?>><?php echo $each['name']; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">キーワード：&nbsp;<span class="popup_help" id="help_keyword"><i class="icon-help-circled"></i></span></p>
						<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
					</div>
				</div>
				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</form>
		</div>
	</div>	

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:14%;">
					<p>最終更新</p>
				</th>

				<th style="width:11%;">
					<p>ステータス</p>
				</th>		

				<th style="width:12%;">
					<p>取引先ID</p>
				</th>

				<th>
					<p>企業名<i class="icon-info-circle"></i></p>
				</th>
				
				<th style="width:20%;">
					<p>当社取引関係<i class="icon-info-circle"></i></p>
				</th>
				
				<th style="width:5%;">
					<p>詳細</p>
				</th>
			</tr>

			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>" <?php if ($each['status'] == Shared_Model_Code::CONNECTION_STATUS_REMOVE) { echo 'class="deleted"'; } ?>>
						<td>
							<p><?php echo date('Y-m-d H:i:s', strtotime($this->escape($each['updated']))); ?></p>
						</td>

						<td>
							<p <?php if ($each['status'] == Shared_Model_Code::CONNECTION_STATUS_IMPORTED) { echo 'class="imported"'; } ?>><?php echo $connectionStatusList[$each['status']]; ?></p>
						</td>			

						<td>
							<p><?php echo $this->escape($each['display_id']); ?></p>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['company_name']); ?>">
							<p><?php echo $this->roundText($this->escape($each['company_name']), 25); ?></p>
						</td>

						<?php
	                		$selected = array();
	                		$relationTypes = unserialize($each['relation_types']);
	                		if (!empty($relationTypes)) {
	                			foreach ($relationTypeList as $key => $val) {
			                		foreach($relationTypes as $eachSelected) {
				                		if ($eachSelected === (string)$key) {
				                			$selected[] = $val;
				                		}
			                		}
		                		}
		                	}
	                	?>
						<td class="desc" all-content="<?php echo implode(' / ', $selected); ?>">
							<p><?php echo $this->roundText(implode(' / ', $selected), 16); ?></p>
						</td>
							
						<td>
							<p><a href="/connection/history?id=<?php echo $each['id']; ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="7">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>


