<?php
$logTypeList = Shared_Model_Code::codes('connection_log_type');
?>
<script type="text/javascript"><!--
$(function() {
    $(document).ready(function(){

    });
});
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:180px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
.multi_rows_padding {padding:5px 0 5px 10px}
table.list_default tr td hr{border-color:#008cff}
table.list_default tr td i.icon-down-circled-1{color:#008cff;font-size:1.3em;}
table.list_default tr td b{color:#008cff;font-size:1.3em;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title" style="margin-bottom:9px;">
            <span><strong>取引先 - <?php echo $this->escape($this->data['company_name']); ?></strong></span>
        </div>
    	<?php
            echo $this->partial('connection/menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->id,
    			'direct'    => $this->direct,
    		));
        ?>   
    </div>


	<div class="condition_items clearfix" style="margin-bottom:13px;">
		<form action="#" method="get">
			<p class="search_condition_title">検索条件</p>

			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">登録・更新者：</p>
                    <input type="text" name="" value="" />
				</div>
				
				<div class="condition_item">
					<p class="condition_label">内容：</p>
	                <select id="type" name="type">
	                    <option value="">---</option>
	                	<?php foreach ($logTypeList as $key => $value) { ?>
	                        <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
	                    <?php } ?>
	                </select>
				</div>
				
				<div class="condition_item" style="width:400px;padding-top:23px;">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
				
			</div>
			<input type="hidden" name="id" value="<?php echo $this->escape($this->id); ?>" />
			<div style="text-align:center">

			</div>
		</form>
	</div>


    <div class="clearfix">
		<table class="list_default">
			<tr>
				<th style="width:14%;">
					<p>日時</p>
				</th>

				<th style="width:20%;">
					<p>作業者名(利用者ID)</p>
				</th>	
				
				<th style="width:13%;">
					<p>内容</p>
				</th>

				<th>
					<p>詳細</p>
				</th>
			</tr>

			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr id="<?php echo $each['id']; ?>">
						<td>
							<p><?php echo date('Y-m-d H:i:s', strtotime($each['created'])); ?></p>
						</td>

						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['user_name']); ?><br>(<?php echo $this->escape($each['display_id']); ?>)</div>
						</td>

						<td>
							<p><?php echo $logTypeList[$each['type']]; ?></p>
						</td>
										
						<td>
							<div class="multi_rows_padding"><?php echo nl2br($each['message']); ?></div>
						</td>

					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="7">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div><!-- clearfix -->

</div>
</div>
</div>
</div>

