<?php
$connectionStatusList  = Shared_Model_Code::codes('connection_status');
$connectionTypeList    = Shared_Model_Code::codes('connection_type');
$relationTypeList      = Shared_Model_Code::codes('relation_type');
$salesRelationList     = Shared_Model_Code::codes('sales_relation');
?>

<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span><strong>取引先選択</strong></span>
    </div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<div class="condition_items clearfix">
		<form id="connection_condition_form" action="javascript:$('#search_connection').click();" method="get">
			<p class="search_condition_title">検索条件</p>

			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">ステータス：</p>
                    <select id="status" name="status">
                        <option value="">---</option>
                    	<?php foreach ($connectionStatusList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">種別：</p>
                    <select id="type" name="type">
                        <option value="">---</option>
                    	<?php foreach ($connectionTypeList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>

				<div class="condition_item">
					<p class="condition_label">当社取引関係：</p>
                    <select id="relation_type" name="relation_type">
                        <option value="">---</option>
                    	<?php foreach ($relationTypeList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['relation_type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">主な商談ポジション：</p>
                    <select id="sales_relation" name="sales_relation">
                        <option value="">---</option>
                    	<?php foreach ($salesRelationList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['sales_relation']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
			</div>	
					
			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">業種：</p>
                    <select id="industry_type" name="industry_type">
                        <option value="">---</option>
                    	<?php foreach ($this->industryTypeList as $each) { ?>
                            <option value="<?php echo $each['id']; ?>" <?php if ($each['id'] == $this->conditions['industry_type']) echo 'selected="selectd"';?>><?php echo $each['name']; ?></option>
                        <?php } ?>
                    </select>
				</div>

				<div class="condition_item">
					<p class="condition_label">国：</p>
                    <select id="country" name="country">
                        <option value="">---</option>
                    	<?php foreach ($this->countryList as $each) { ?>
                            <option value="<?php echo $each['id']; ?>" <?php if ($each['id'] == $this->conditions['country']) echo 'selected="selectd"';?>><?php echo $each['name']; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">キーワード：</p>
					<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
				</div>
			</div>
			
			<input id="search_connection" type="button" value="検索" />
		
		</form>
	</div>
</div>	

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:14%;">
				<p>最終更新</p>
			</th>

			<th style="width:12%;">
				<p>ステータス</p>
			</th>		

			<th style="width:12%;">
				<p>取引先ID</p>
			</th>

			<th>
				<p>企業名<i class="icon-info-circle"></i></p>
			</th>
			
			<th style="width:18%;">
				<p>当社取引関係<i class="icon-info-circle"></i></p>
			</th>
			
			<th style="width:8%;">
				<p>選択</p>
			</th>
		</tr>

		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>

				<tr id="<?php echo $each['id']; ?>" <?php if ($each['status'] == Shared_Model_Code::CONNECTION_STATUS_REMOVE) { echo 'class="deleted"'; } ?>>
					<td>
						<p><?php echo date('Y-m-d H:i', strtotime($this->escape($each['updated']))); ?></p>
					</td>

					<td>
						<p <?php if ($each['status'] == Shared_Model_Code::CONNECTION_STATUS_IMPORTED) { echo 'class="imported"'; } ?>><?php echo $connectionStatusList[$each['status']]; ?></p>
					</td>			

					<td>
						<p><?php echo $this->escape($each['display_id']); ?></p>
					</td>

					<td class="desc" all-content="<?php echo $this->escape($each['company_name']); ?>">
						<p><?php echo $this->roundText($this->escape($each['company_name']), 18); ?></p>
					</td>

					<?php
                		$selected = array();
                		$relationTypes = unserialize($each['relation_types']);
                		if (!empty($relationTypes)) {
                			foreach ($relationTypeList as $key => $val) {
		                		foreach($relationTypes as $eachSelected) {
			                		if ($eachSelected === (string)$key) {
			                			$selected[] = $val;
			                		}
		                		}
	                		}
	                	}
                	?>
					<td class="desc" all-content="<?php echo implode(' / ', $selected); ?>">
						<p><?php echo $this->roundText(implode(' / ', $selected), 13); ?></p>
					</td>
						
					<td>
						<a class="option" href="javascript:selectConnection('<?php echo $each['id']; ?>', '<?php echo $this->escape($each['display_id']); ?>', '<?php echo $this->escape($each['company_name']); ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="7">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding: 2.0em 0 5.0em;">
    <?php echo $this->pager() ?>
    </div>
            
</div>


