<?php
$logTypeList = Shared_Model_Code::codes('connection_log_type');
?>
<script type="text/javascript">
$(function() {
	$(".clear_form").bind("click", function(){
	    $(this.form).find("textarea, :text, select").val("").end().find(":checked").prop("checked", false);
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
		$('#condition_form').submit();
	});;
});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:180px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
.multi_rows_padding {padding:5px 10px 5px 10px}
table.list_default tr td hr{border-color:#008cff}
table.list_default tr td i.icon-down-circled-1{color:#008cff;font-size:1.3em;}
table.list_default tr td b{color:#008cff;font-size:1.3em;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title clearfix">
            <span><strong>更新履歴</strong></span>
        </div>
    </div>


	<div class="condition_items clearfix" style="margin-bottom:13px;">
		<form id="condition_form" action="/connection/list-history" method="get">
			<p class="search_condition_title">検索条件</p>

			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">作業者名(利用者ID)：</p>
                    <input type="text" name="excutor" value="<?php echo $this->conditions['excutor']; ?>">
				</div>
				
				<div class="condition_item">
					<p class="condition_label">企業・機関名(取引先ID)：</p>
                    <input type="text" name="connection" value="<?php echo $this->conditions['connection']; ?>">
				</div>
				
				<div class="condition_item">
					<p class="condition_label">内容：</p>
	                <select id="type" name="type">
	                    <option value="">---</option>
	                	<?php foreach ($logTypeList as $key => $value) { ?>
	                        <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
	                    <?php } ?>
	                </select>
				</div>
				
				<div class="condition_item" style="padding-top:23px;">
					<input type="button" class="clear_form" style="display:inline-block;width:116px;" value="リセット" />
					<input type="button" class="submit" style="display:inline-block;width:116px;" value="検索" />
				</div>
				
			</div>
			<input type="hidden" name="id" value="<?php echo $this->escape($this->id); ?>" />
			<div style="text-align:center">

			</div>
		</form>
	</div>
	
	<div class="clearfix">
		<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
    </div>
    
    <div class="clearfix">
		<table class="list_default">
			<tr>
				<th style="width:14%;"><p>日時/作業者名(利用者ID)</p></th>
				<th style="width:20%;"><p>企業・機関名</p></th>
				<th style="width:13%;"><p>内容</p></th>
				<th><p>詳細</p></th>
			</tr>

			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr id="<?php echo $each['id']; ?>">
						<td>
							<div class="multi_rows_padding">
								<?php echo date('Y-m-d H:i:s', strtotime($each['created'])); ?>
								<?php echo $this->escape($each['user_name']); ?><br>
								(<?php echo $this->escape($each['display_id']); ?>)
							</div>
						</td>

						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['company_name']); ?></div>
						</td>

						<td>
							<p><?php echo $logTypeList[$each['type']]; ?></p>
						</td>
										
						<td>
							<div class="multi_rows_padding"><?php echo nl2br($each['message']); ?></div>
						</td>

					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="7">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>
		
        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	</div><!-- clearfix -->

</div>
</div>
</div>
</div>

