<?php
$payementTypeList       = Shared_Model_Code::codes('connection_payment_type');
$payementConditionList  = Shared_Model_Code::codes('connection_payment_condition');
?>

<script type="text/javascript"><!--
var reloadFlag  = false;
var deletedFlag = false;

$(function() {
    $(document).ready(function(){
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->posTop; ?>);
        <?php } ?>
    });

    // 編集
    $(document).on('click', '.btn_edit_category', function () {
        var categoryId = $(this).attr('category_id');
        
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
    
        // ×,保存ボタン
        $('#cancel_category_' + categoryId).show();
        $('th#edit_category_' + categoryId).addClass('edit_mode');
        $(this).removeClass('btn_edit_category').addClass('btn_save_category');
        $('#btn_edit_label_' + categoryId).html('保存');
    });
    
    // 保存
    $(document).on('click', '.btn_save_category', function () {
        var button = $(this);
        var categoryId = $(this).attr('category_id');
        var $form = $('#form_category_' + categoryId);
        var params = $form.serializeArray();
		
		var apiUrl = '';
		
		if (categoryId == '1') {
			apiUrl = '/connection/update-sales-info?id=<?php echo $this->id ?>';
		} else {
			return;
		}
		
        $.ajax({
            type:'POST',
            dataType:'json',
            data: params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url: apiUrl,
        });
    });
    
    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
        	if (deletedFlag == true) {
        		location.href = '<?php echo $this->backUrl; ?>';
        	} else {
            	location.href = '/connection/sales-info?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
            }
        }
    });

    // 編集中止
    $(document).on('click', '.btn_cancel_category', function () {
        var categoryId = $(this).attr('category_id');
        location.href = '/connection/sales-info?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
    });
    
});
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:180px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
table.list_default tr td.column_value select.short {width:280px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.multi_rows_padding {padding:5px 0 5px 10px}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title" style="margin-bottom:9px;">
            <span><strong>取引先 - <?php echo $this->escape($this->data['company_name'] . ' ' . $this->data['base_name']); ?></strong></span>
        </div>
    	<?php
            echo $this->partial('connection/menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->id,
    		));
        ?>   
    </div>

    <div class="clearfix">

	    <?php
        /* 基本情報 */
        $categoryId = 1;
        ?>
		<form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th style="border-left:1px solid #ddd;border-top:1px solid #ddd;border-bottom:1px solid #ddd;"><p class="label_text strong">担当者</p></th>
                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                    <span>×</span>
                    </a>
                </th>
                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
                </th>
            </tr>
        </table>
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">氏名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['stuff_name'])) { echo nl2br($this->data['stuff_name']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="stuff_name" value="<?php echo $this->escape($this->data['stuff_name']); ?>" maxlength="" />
					</div>
                </td>
            </tr>
               
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">氏名カナ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['stuff_name_kana'])) { echo nl2br($this->data['stuff_name_kana']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="stuff_name_kana" value="<?php echo $this->escape($this->data['stuff_name_kana']); ?>" maxlength="" />
					</div>
                </td>
            </tr>
                 
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">部署</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['stuff_department'])) { echo nl2br($this->data['stuff_department']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="stuff_department" value="<?php echo $this->escape($this->data['stuff_department']); ?>" maxlength="" />
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">役職</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['stuff_position'])) { echo nl2br($this->data['stuff_position']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="stuff_position" value="<?php echo $this->escape($this->data['stuff_position']); ?>" maxlength="" />
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">電話番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['stuff_tel'])) { echo nl2br($this->data['stuff_tel']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="stuff_tel" value="<?php echo $this->escape($this->data['stuff_tel']); ?>" maxlength="" />
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">FAX番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['stuff_fax'])) { echo nl2br($this->data['stuff_fax']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="stuff_fax" value="<?php echo $this->escape($this->data['stuff_fax']); ?>" maxlength="" />
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">メールアドレス</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['stuff_mail'])) { echo nl2br($this->data['stuff_mail']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="stuff_mail" value="<?php echo $this->escape($this->data['stuff_mail']); ?>" maxlength="" />
					</div>
                </td>
            </tr>
            
        </table>
        </form>
          

	</div><!-- clearfix -->	                

</div>
</div>
</div>
</div>

