<?php
$statusList   = Shared_Model_Code::codes('payable_status');
$payingMethodList = Shared_Model_Code::codes('payable_paying_method_invoice');
$taxDivisionList = Shared_Model_Code::codes('tax_division');
$bankAccountType = Shared_Model_Code::codes('bank_account_type');

$basicbankList       = Shared_Model_Code::codes('basic_bank');
$bankCodeList        = Shared_Model_Code::codes('basic_bank_code');

$bankAccountTypeList = Shared_Model_Code::codes('shop_fee_bank_account_type');

$bankRegisteredType  = Shared_Model_Code::codes('bank_registered_type');

?>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:150px;}
table.list_default tr td.column_value select.short {width:300px;}
table.list_default tr td.column_value select.monthly {width:60px;float:left;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.payment_select {padding-top:6px;padding-left:1px;}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_count {border-right:none;background-color:#bae0ff;width:30px;}
table.list_default tr td.td_item_info {border-right:none;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
a.btn_setting#btn_copy {padding:1px 8px 0px;float:left;margin-left:20px;margin-top:5px;margin-bottom:0}
table.list_default tr td p.industory_category {background-color:#bae0ff;padding:11px 0 9px 12px}
table.list_default tr td .multi_rows_padding {padding:5px 6px 5px 6px;}
a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1100px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}

.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}
.quote {margin:10px;padding:10px;background-color:#e3f2ff}
table.list_default tr td .quote p {padding:6px 0 8px 12px;height:auto;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:400px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>CSV出力エラー</strong></span>
        </div>
    </div>

    <div class="clearfix">
	    <h2 style="margin-bottom:0.6em;">以下のデータの振込先が未登録です</h2>
	    

	    <?php
        /* 基本情報 */
        $categoryId = 1;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0;">
            <tr>
            	<?php if ($this->allowEditing === true 
	            	&& ($this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_DRAFT || $this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_MOD_REQUEST)) {
		        ?>
	                <th class="border-left border-top border-bottom">
	                    <p class="label_text strong">基本情報</p>
	                </th>
	                <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php } else { ?>
	                <th class="border-left border-top border-bottom border-right">
	                    <p class="label_text strong">基本情報</p>
	                </th>
                <?php } ?>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">ステータス</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $statusList[$this->data['status']]; ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">会計科目<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="account_title_name" style="float:left;width:690px;"><?php 
                		if (!empty($this->accountTitleData)) {
                			echo $this->escape($this->accountTitleData['title']);
                		} else {
                			echo '---';
                		}
                	?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<a class="option" id="select_account_title">選択</a>
                    	<input type="hidden" id="account_title_id" name="account_title_id" value="<?php echo $this->escape($this->data['account_title_id']); ?>" />
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">摘要<span class="popup_help" id="help_memo">&nbsp;<i class="icon-help-circled"></i></span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php echo nl2br($this->escape($this->data['memo'])); ?>
                	</div>
                    <textarea class="edit_value_<?php echo $categoryId; ?>" name="memo" style="height:100px;margin-bottom:6px;display:none;"><?php echo $this->escape($this->data['memo']); ?></textarea>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">採算コード<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <?php
	                	$groupData = NULL;
	                	if (!empty($this->data['account_totaling_group_id'])) {
		                	$totalingGroupTable = new Shared_Model_Data_AccountTotalingGroup();
		                	$groupData = $totalingGroupTable->getById($this->adminProperty['management_group_id'], $this->data['account_totaling_group_id']);
		                }
			        ?>
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
	                	<?php
			                if (!empty($groupData)) {
			                	echo $this->escape($groupData['category_name'] . '　＞　' . $groupData['title']);
		                	} else {
			                	echo '---';
		                	}
		                ?>
	                </div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<p id="account_totaling_group_name" style="float:left;width:690px;">
						<?php
							if (!empty($groupData)) {
			                	echo $this->escape($groupData['category_name'] . '　＞　' . $groupData['title']);
		                	} else {
			                	echo '---';
		                	}
		                ?>
						</p>
						<input type="hidden" id="account_totaling_group_id" name="account_totaling_group_id" value="<?php echo $this->escape($this->data['account_totaling_group_id']); ?>">
						<a class="option" id="select_account_totaling_group">選択</a>
					</div>
                </td>
            </tr>
		</table>
		</form>
		
		
	    <?php
        /* 概要 */
        $categoryId = 2;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0;">
            <tr>
            	<?php if ($this->allowEditing === true 
	            	&& ($this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_DRAFT || $this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_MOD_REQUEST)) {
		        ?>
	                <th class="border-left border-top border-bottom">
	                    <p class="label_text strong">概要</p>
	                </th>
	                <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php } else { ?>
	                <th class="border-left border-top border-bottom border-right">
	                    <p class="label_text strong">概要</p>
	                </th>
                <?php } ?>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">支払先取引先<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="connection_name"><?php 
                		if (!empty($this->connectionData)) {
                			echo $this->escape($this->connectionData['company_name']);
                		} else {
                			echo '---';
                		}
                	?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<a class="option" id="select_connection">取引先選択</a>
                    	<input type="hidden" id="target_connection_id" name="target_connection_id" value="<?php echo $this->escape($this->data['target_connection_id']); ?>" />
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">支払総額(税込)<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php
                			$currencyText = '';
                			foreach ($this->currencyList as $eachCurrency) {
                				if ($this->data['currency_id'] == $eachCurrency['id']) {
                					$currencyText = $eachCurrency['name'];
                				}
                			}
                			
                			if (!empty($this->data['total_amount'])) {
                				echo number_format($this->data['total_amount']) . '&nbsp;' . $this->escape($currencyText);
                			} else {
                				echo '';
                			}
                		?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
		            	<input type="text" style="float:left;width:150px;text-align:right;" id="total_amount" name="total_amount" value="<?php echo $this->escape($this->data['total_amount']); ?>" />
	                    <select style="float:left;width:90px;margin-left:5px;" id="currency_id" name="currency_id">
	                        <option value="">(通貨単位)</option>
	                    	<?php foreach ($this->currencyList as $eachCurrency) { ?>
	                            <option value="<?php echo $eachCurrency['id']; ?>" <?php if ($this->data['currency_id'] == $eachCurrency['id']) { echo 'selected="selected"'; } ?>><?php echo $this->escape($eachCurrency['name']); ?></option>
	                        <?php } ?>
	                    </select>
                    </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">税区分<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <p class="display_value_<?php echo $categoryId; ?>">
                    	<?php if (!empty($this->data['tax_division'])) { echo $taxDivisionList[$this->data['tax_division']]; } ?>
                    </p>
                    <select class="edit_value_<?php echo $categoryId; ?>" style="width:300px;display:none;" id="tax_division" name="tax_division">
                        <option value="">---</option>
                    	<?php foreach ($taxDivisionList as $key => $val) { ?>
                            <option value="<?php echo $key; ?>" <?php if ($this->data['tax_division'] == $key) { echo 'selected="selected"'; } ?>><?php echo $this->escape($val); ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
 
             <tr>
                <td class="column_label"><p class="label_text">消費税</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <p class="display_value_<?php echo $categoryId; ?>"><?php
                		if (!empty($this->data['tax'])) {
            				echo number_format($this->data['tax']) . '&nbsp;' . $currencyText;
            			} else {
            				echo '';
            			}
                    ?></p>
                    <div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" style="float:left;width:150px;text-align:right;" id="tax" name="tax" value="<?php echo $this->escape($this->data['tax']); ?>" />
                    	<p style="float:left;"><?php echo $currencyText; ?></p>
                    </div>
                </td>
            </tr>
            
            <?php if (!empty($this->data['online_purchase_id'])) { ?>
	            <tr>
	                <td class="column_label"><p class="label_text">ネット購入委託管理ID</p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                	<p style="float:left">
	                		<?php
		                		$onlinePurchaseTable  = new Shared_Model_Data_OnlinePurchase();
		                		$onlinePurchaseData = $onlinePurchaseTable->getById($this->adminProperty['management_group_id'], $this->data['online_purchase_id']);
		                		echo nl2br($this->escape($onlinePurchaseData['display_id']));
		                	?>
	                	</p>
	                	<a class="option" style="float:right;padding:3px 35px 1px 35px;margin-right:5px;" href="/transaction-order/online-detail?id=<?php echo $this->escape($this->data['online_purchase_id']); ?>&direct=1" target="_blank">表示</a>
	                </td>
	            </tr>
            <?php } ?>
            
            <tr>
                <td class="column_label "><p class="label_text">発生日<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php
                			if (!empty($this->data['purchased_date'])) {
                				echo date('Y-m-d', strtotime($this->data['purchased_date']));
                			} else {
                				echo '---';
                			}
                		?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="datepicker" id="purchased_date" name="purchased_date" value="" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>
		</table>
		</form>


        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th class="border-left border-top border-bottom"><p class="label_text strong">取引先振込先登録</p></th>
            </tr>
        </table>
        <table class="list_default" style="margin-bottom:13px;">       
	         <?php /*
	         <tr>
                <td class="column_label"><p class="label_text">ステータス</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div>
						<p style="float:left;"><?php 
							if ($this->connectionData['gs_bank_confirmed'] === (string)Shared_Model_Code::BANK_CONFIRM_STATUS_CONFIRMED) {
								echo '確認済み';
								
								if (!empty($this->confirmedUser)) {
									echo '　　確認者：' . $this->escape($this->confirmedUser['user_name']);
								}
							} else if ($this->data['gs_bank_confirmed'] === (string)Shared_Model_Code::BANK_CONFIRM_STATUS_RENEWALED) {
								echo '<span class="red">未確認</span>';
							} else {
								echo '---';
							}
						?></p>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">振込先</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="multi_rows_padding">
						<?php 
							if ($this->connectionData['gs_basic_bank_select'] !== (string)Shared_Model_Code::BASIC_BANK_OTHER) {
								echo $basicbankList[$this->connectionData['gs_basic_bank_select']] . '　(銀行コード：' . $this->connectionData['gs_bank_code'] . ')';
							} else {
								echo $this->connectionData['gs_other_bank_name'] . '　(銀行コード：' . $this->connectionData['gs_bank_code'] . ')';
							}
						?><br>
						<?php echo $this->escape($this->connectionData['gs_bank_branch_name'])  . '　(支店コード：' . $this->connectionData['gs_bank_branch_id'] . ')'; ?><br>
						<?php echo $bankAccountTypeList[$this->connectionData['gs_bank_account_type']]; ?>　<?php echo $this->escape($this->connectionData['gs_bank_account_no']); ?><br>
						<?php echo $this->escape($this->connectionData['gs_bank_account_name']); ?><br>
						<?php echo $this->escape($this->connectionData['gs_bank_account_name_kana']); ?>
					</div>
                </td>
            </tr>
            */ ?>
            
            <tr>
                <td class="column_label"><p class="label_text">振込先</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="multi_rows_padding">
                        <?php if (!empty($this->data['bank_registered_type'])) { ?>
						    <strong>登録種別：<?php echo $bankRegisteredType[$this->data['bank_registered_type']]; ?>　<span class="red">未登録</span></strong>
						<?php } else { ?>
						    (旧データ)
						<?php } ?>
					</div>
                </td>
            </tr>
            
		</table>

	    <?php
        /* 個別振込先情報 */
        $categoryId = 6;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
		<table class="list_default" style="margin-bottom:0;">
            <tr>
            	<?php if ($this->allowEditing === true 
	            		&& ($this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_DRAFT || $this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_MOD_REQUEST)) {
		        ?>
	                <th class="border-left border-top border-bottom">
	                    <p class="label_text strong">個別振込先情報</p>
	                </th>
	                <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php } else { ?>
	                <th class="border-left border-top border-bottom border-right">
	                    <p class="label_text strong">個別振込先情報</p>
	                </th>
                <?php } ?>
            </tr>
		</table>   
        <table class="list_default" style="margin-bottom:13px;">
        	<tr>
                <td class="column_label"><p class="label_text">金融機関コード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['transfer_to_bank_code']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" id="transfer_to_bank_code" name="transfer_to_bank_code" value="<?php echo $this->escape($this->data['transfer_to_bank_code']); ?>" style="width:300px;" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>
            
        	<tr>
                <td class="column_label"><p class="label_text">金融機関名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['transfer_to_bank_name']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" id="transfer_to_bank_name" name="transfer_to_bank_name" value="<?php echo $this->escape($this->data['transfer_to_bank_name']); ?>" style="width:300px;" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>
            
        	<tr>
                <td class="column_label"><p class="label_text">支店コード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['transfer_to_branch_code']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" id="transfer_to_branch_code" name="transfer_to_branch_code" value="<?php echo $this->escape($this->data['transfer_to_branch_code']); ?>" style="width:300px;" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>    
            
        	<tr>
                <td class="column_label"><p class="label_text">支店名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['transfer_to_branch_name']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" id="transfer_to_branch_name" name="transfer_to_branch_name" value="<?php echo $this->escape($this->data['transfer_to_branch_name']); ?>" style="width:300px;" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>
            
        	<tr>
                <td class="column_label"><p class="label_text">口座種別</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php if (!empty($this->data['transfer_to_account_type'])) { echo $bankAccountType[$this->data['transfer_to_account_type']]; } ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<select class="short" name="transfer_to_account_type">
	                    	<?php foreach ($bankAccountType as $key => $val) { ?>
	                    		<option value="<?php echo $this->escape($key); ?>" <?php if ($this->data['transfer_to_account_type'] === (string)$key) { echo 'selected="selected";'; } ?>><?php echo $this->escape($val); ?></option>
	                    	<?php } ?>
                    	</select>
                    </div>
                </td>
            </tr>

        	<tr>
                <td class="column_label"><p class="label_text">口座番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['transfer_to_account_no']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" id="transfer_to_account_no" name="transfer_to_account_no" value="<?php echo $this->escape($this->data['transfer_to_account_no']); ?>" style="width:300px;" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>
            
        	<tr>
                <td class="column_label"><p class="label_text">口座名義(全角カナ)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['transfer_to_account_name']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" id="transfer_to_account_name" name="transfer_to_account_name" value="<?php echo $this->escape($this->data['transfer_to_account_name']); ?>" style="width:300px;" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>
        </table>
        </form>

    </div>
     
</div>
</div>
</div>
</div>

