<?php
$productNameTypeList      = Shared_Model_Code::codes('product_name_type');
$productMarketList        = Shared_Model_Code::codes('product_market');
$productSalesStatusList   = Shared_Model_Code::codes('product_sales_status');
$supplyMethodList         = Shared_Model_Code::codes('supply_method');
$productionProcessList    = Shared_Model_Code::codes('production_process');
$strategyList             = Shared_Model_Code::codes('strategy');
?>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){
        Tipped.create('#help_product_classes', "①「～自社名商品or原料」は、自社ブランド名・自社独自名称の商品（原料）のこと。同じく、「～自他社名商品（原料）」は、他社ブランド、他社商品（原料）名称のまま取り扱うもの。<br>②役務とは、「サービス提供」と「業務受託対応」の両方を意味する。<br>③OEM先製は当社がOEM委託先に製造委託しているもの。なお、粉砕等、一部の加工を個別委託する原料は「自社製」扱いで良い。");
        Tipped.create('#help_product_categories', "当社内の各商品の「説明」ページの区分");
        Tipped.create('#help_product_markets', "重要。上長確認必要。");
        Tipped.create('#help_production_process', "重要。販売しないものは不要");
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/product/list?category_id=";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {                            
                            location.href = '/product/basic?id=' + obj.id;
                    		return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/product/add-post'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/product/list';
        }
    });
    
    // 商品名の区分
    $('#product_name_type').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SALES; ?>' || $(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SALES_AND_SUPPLY; ?>') {
			$('.row_sales_name').show();
		} else {
			$('.row_sales_name').hide();
		}
		
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SUPPLY; ?>' || $(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SALES_AND_SUPPLY; ?>') {
			$('.row_supply_name').show();
		} else {
			$('.row_supply_name').hide();
		}
    });
	
	// 調達製造区分
    $('.product_classes').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_CLASS_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#product_class_other_text').prop("disabled", false);
			} else {
				$('#product_class_other_text').prop("disabled", true);
			}
		}
    });

	// 商品区分
    $('.product_categories').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#product_category_other_text').prop("disabled", false);
			} else {
				$('#product_category_other_text').prop("disabled", true);
			}
		}
    });
    
    // 仕入・調達方法
    $('.supply_methods').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::SUPPLY_METHOD_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#supply_method_other_text').prop("disabled", false);
			} else {
				$('#supply_method_other_text').prop("disabled", true);
			}
		}
    });
    
    // 製品化の手順
    $('#production_process').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCTION_PROCESS_OTHER; ?>') {
			$('#production_process_other_text').prop("disabled", false);
		} else {
			$('#production_process_other_text').prop("disabled", true);
		}
    });

    // 後継品商品 商品選択 ポップアップ表示
    $(document).on('click', '#select_item', function () {
    	pos = $(window).scrollTop();
    	
    	var targetItemId = $('#next_generation_item_id').val();

    	$('#data_area').html('');
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
			
    	if (targetItemId != '' && targetItemId != '0') {
			$('#data_area').load('/product/detail-selected?id=' + targetItemId);
    	} else {
			$('#data_area').load('/product/list-select');
		}
    });
    
    // 商品選択 条件検索
    $(document).on('click', '#search_product', function () {
		updateProductList(1);
    });

    // 商品選択 選択解除
    $(document).on('click', '.btn_reset_selected', function () {
		$('#next_generation_item_name').html('---');
		$('#next_generation_item_id').val('');
		$('.btn_close').click();
    });
      
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': 0});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// 商品一覧ページ切り替え
function pageProduct(pageNo) {
	updateProductList(pageNo)
}

// 商品選択
function selectProduct(id, itemId, name, buyingName) {
	var itemName = '';
	if (name != '') {
		itemName += "<span class='product_name'>商品名</span>&nbsp;" + name + '&nbsp;&nbsp;';
	}

	if (buyingName != '') {
		itemName += "<span class='import_name'>仕入名</span>&nbsp;" + buyingName + '&nbsp;&nbsp;';
	}
	$('#next_generation_item_name').html('<strong>' + itemId + '</strong>&nbsp;'+ itemName);
	$('#next_generation_item_id').val(id);
	$('.btn_close').click();
}

// 商品一覧更新
function updateProductList (pageNo) {
    var $form = $('#product_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/product/list-select?page=' + pageNo,
    });
}

--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;margin-right:12px;}
.multi_rows_padding {padding:5px 0 5px 10px}
.product_name {background-color:#ed8c14;color:#fff;padding:3px 0.2em 1px 0.2em}
.import_name {background-color:#008cff;color:#fff;padding:3px 0.2em 1px 0.2em}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>商品管理 - 新規登録</strong></span>
        </div>
    </div>
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
                    <p class="label_text strong">基本情報</p>
                </th>
            </tr>
		</table>     	
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">商品名の区分<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<select class="short" id="product_name_type" name="product_name_type">
						<option value="">---</option>
						<?php foreach ($productNameTypeList as $key => $val) { ?>
							<option value="<?php echo $key; ?>"><?php echo $this->escape($val); ?></option>
						<?php } ?>
                	</select>
                </td>
            </tr>
            
            <tr class="row_sales_name" style="display:none">
                <td class="column_label"><p class="label_text">販売商品名(日本語)<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            
            <tr class="row_sales_name" style="display:none">
                <td class="column_label"><p class="label_text">販売商品名(英語)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name_en" value="" maxlength="" />
                </td>
            </tr>

            <tr class="row_supply_name" style="display:none">
                <td class="column_label"><p class="label_text">仕入商品名<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="buying_item_name" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">調達製造区分<span class="popup_help" id="help_product_classes">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($this->productClassList as $each) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="product_classes" name="product_classes[]" value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['name']); ?>
			                    </label>
		                    </div>
	                    <?php } ?>
						<div class="checkbox_item">
		                	<label>
		                    	<input type="checkbox" class="product_classes" name="product_classes[]" value="<?php echo Shared_Model_Code::PRODUCT_CLASS_OTHER; ?>"><?php echo Shared_Model_Code::PRODUCT_CLASS_OTHER_TITLE; ?>
		                    </label>
	                    </div>
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="product_class_other_text" name="product_class_other_text" placeholder="その他調達製造区分" disabled="disabled" value="<?php echo $this->escape($this->data['product_class_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">商品区分<span class="popup_help" id="help_product_categories">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($this->productCategoryList as $each) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="product_categories" name="product_categories[]" value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['name']); ?>
			                    </label>
		                    </div>
	                    <?php } ?> 
						<div class="checkbox_item">
		                	<label>
		                    	<input type="checkbox" class="product_categories" name="product_categories[]" value="<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>"><?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER_TITLE; ?>
		                    </label>
	                    </div>
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="product_category_other_text" name="product_category_other_text" placeholder="その他商品区分" disabled="disabled" value="<?php echo $this->escape($this->data['product_category_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">商品戦略<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<select class="short" id="strategy" name="strategy">
							<option value="">---</option>
                            <?php foreach ($strategyList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>" <?php if ($this->data['strategy'] == (string)$key) echo 'selected="selected"'; ?>><?php echo $this->escape($val); ?></option>
                            <?php } ?>
                    	</select>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">商品概要</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <div class="clearfix">
						<textarea name="memo" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">販売商品JANコード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="jan_code" class="short" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">販売状況<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<select class="short" id="product_sales_status" name="product_sales_status">
							<option value="">---</option>
                            <?php foreach ($productSalesStatusList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>" <?php if ($this->data['product_sales_status'] == (string)$key) echo 'selected="selected"'; ?>><?php echo $this->escape($val); ?></option>
                            <?php } ?>
                    	</select>
					</div>
                </td>
            </tr>

            <?php /* GS商品ID */ ?>
            <?php /* GS登録・更新日 */ ?>
            
            <tr>
                <td class="column_label"><p class="label_text">販売可能範囲<span class="popup_help" id="help_product_markets">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($productMarketList as $key => $val) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="product_markets" name="product_markets[]" value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($val); ?>
			                    </label>
		                    </div>
	                    <?php } ?> 
					</div>
                </td>
            </tr>

	        <tr>
	            <td class="column_label"><p class="label_text">後継品商品</p></td>
	            <td class="colon"><p class="label_text">：</p></td>
	            <td class="column_value">
	            	<div class="clearfix">
	                	<div id="next_generation_item_name" class="multi_rows_padding">---</div>
	                    <a class="option" id="select_item">商品選択</a>
	                    <input type="hidden" id="next_generation_item_id" name="next_generation_item_id" value="" />
	            	</div>
	            </td>
	        </tr>
        
        
            
            <tr>
                <td class="column_label"><p class="label_text">仕入・調達方法</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<?php foreach ($this->supplyMethodList as $each) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="supply_methods" name="supply_methods[]" value="<?php echo $this->escape($each['id']); ?>" <?php if (in_array($each['id'], $this->data['supply_methods'])) { echo 'checked="checked"'; } ?>><?php echo $each['name']; ?>
			                    </label>
		                    </div>
	                    <?php } ?>
	                	<div class="checkbox_item">
		                	<label>
		                    	<input type="checkbox" class="supply_methods" name="supply_methods[]" value="<?php echo Shared_Model_Code::SUPPLY_METHOD_OTHER; ?>" <?php if (in_array($each['id'], $this->data['supply_methods'])) { echo 'checked="checked"'; } ?>><?php echo Shared_Model_Code::SUPPLY_METHOD_OTHER_TITLE; ?>
		                    </label>
	                    </div>
	                    
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="supply_method_other_text" name="supply_method_other_text" placeholder="その他調達方法" <?php if (!in_array(Shared_Model_Code::SUPPLY_METHOD_OTHER, $this->data['supply_methods'])) { echo 'disabled="disabled"'; } ?> value="<?php echo $this->escape($this->data['supply_method_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">製品化の手順<span class="popup_help" id="help_production_process">&nbsp;<i class="icon-help-circled"></i></span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
  						<select class="short" id="production_process" name="production_process">
							<option value="">---</option>
                            <?php foreach ($productionProcessList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>" <?php if ($this->data['production_process'] == (string)$key) echo 'selected="selected"'; ?>><?php echo $this->escape($val); ?></option>
                            <?php } ?>
                		</select>
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="production_process_other_text" name="production_process_other_text" placeholder="その他製品化の手順" <?php if (Shared_Model_Code::PRODUCTION_PROCESS_OTHER != $this->data['product_process']) { echo 'disabled="disabled"'; } ?> value="<?php echo $this->escape($this->data['production_process_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
                </td>
            </tr>
            
		</table>
		
		
		<?php /*販売条件*/ ?>
		
		<?php /*原価(引用)*/ ?>
		
		<?php /*
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
                    <p class="label_text strong">入手見積</p>
                </th>
            </tr>
		</table>
		 
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">入手見積書日付</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">入手見積書・補足資料アップロード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">見積メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <textarea name=""></textarea>
                </td>
            </tr>
        </table>
        
        
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
                    <p class="label_text strong">メーカー指定販売条件</p>
                </th>
            </tr>
		</table>	

        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">希望小売価格</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">希望卸価格</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">販売価格制約</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">販売条件メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <textarea name=""></textarea>
                </td>
            </tr>
        </table>
        
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
                    <p class="label_text strong">購入条件</p>
                </th>
            </tr>
		</table>

        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">購入ロット1</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">仕入価格１</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">物流費1</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr> 
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">条件メモ1</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <textarea name=""></textarea>
                </td>
            </tr> 
		</table>
		*/ ?>
        



	</div><!-- clearfix -->	
    </form>
                
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;"><div class="menu_frame"><div id="data_area"></div></div></div>
</div>
</div>
</div>


