<?php
$noYesList                = Shared_Model_Code::codes('no_yes');
$productNameTypeList      = Shared_Model_Code::codes('product_name_type');
$statusList               = Shared_Model_Code::codes('item_status');
$productMarketList        = Shared_Model_Code::codes('product_market');
$productSalesStatusList   = Shared_Model_Code::codes('product_sales_status');
$supplyMethodList         = Shared_Model_Code::codes('supply_method');
$productionProcessList    = Shared_Model_Code::codes('production_process');
$productRelationalConnectionList = Shared_Model_Code::codes('product_relational_connection');
$strategyList             = Shared_Model_Code::codes('strategy');
?>
<script type="text/javascript"><!--
var reloadFlag  = false;
var deletedFlag = false;
var pos = 0;
var editing = false;
var rowCount    = <?php echo count($this->data['purchasing_list']); ?>;
var targetConnectionRow = '';

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

$(function() {
    $(document).ready(function(){
        Tipped.create('#help_product_classes', "①「～自社名商品or原料」は、自社ブランド名・自社独自名称の商品（原料）のこと。同じく、「～自他社名商品（原料）」は、他社ブランド、他社商品（原料）名称のまま取り扱うもの。<br>②役務とは、「サービス提供」と「業務受託対応」の両方を意味する。<br>③OEM先製は当社がOEM委託先に製造委託しているもの。なお、粉砕等、一部の加工を個別委託する原料は「自社製」扱いで良い。");
        Tipped.create('#help_product_categories', "当社内の各商品の「説明」ページの区分");
        Tipped.create('#help_product_markets', "重要。上長確認必要。");
        Tipped.create('#help_production_process', "重要。販売しないものは不要");
        
        Tipped.create('#help_method_restriction_for_customer', "通販不可、転売不可");
        Tipped.create('#help_price_restriction_from_supplier', "割引なし価格");
        Tipped.create('#help_method_restriction_from_supplier', "通販不可、転売不可、○○契約書締結");
		
		Tipped.create('#help_strategy', "標準設定品は、「卸価格／goosa価格」と「取引前提条件」を商品区分／カテゴリーごとの標準ルールに沿って設定する。<br>特別戦略品はそれらを商材毎に決定する");
		
		
		<?php if (!empty($this->data['purchasing_list'])) { ?>
		<?php foreach ($this->data['purchasing_list'] as $each) { ?>
			Tipped.create('#' + uuid + '_help_lot_unit', "例） kg、pcs、袋、個、本など");
		<?php } ?>
		<?php } ?>
		
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->posTop; ?>);
        <?php } ?>
    });

    // 編集
    $(document).on('click', '.btn_edit_category', function () {
    	if (editing == true) {
    		jAlert('複数のカテゴリを同時に編集することはできません', 'エラー');
    		return false;
    	}
        var categoryId = $(this).attr('category_id');
        
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
    
        // ×,保存ボタン
        $('#cancel_category_' + categoryId).show();
        $('th#edit_category_' + categoryId).addClass('edit_mode');
        $(this).removeClass('btn_edit_category').addClass('btn_save_category');
        $('#btn_edit_label_' + categoryId).html('保存');
        
        if (categoryId =='2' || categoryId =='5') {
        	var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
	    }
	    
	    editing = true;
    });
    
    // 保存
    $(document).on('click', '.btn_save_category', function () {
        var button = $(this);
        var categoryId = $(this).attr('category_id');
        var $form = $('#form_category_' + categoryId);
        var params = $form.serializeArray();
		
		var apiUrl = '';
		
		if (categoryId == '1') {
			apiUrl = '/product/update-basic?id=<?php echo $this->id ?>';
		} else if (categoryId == '2') {
			apiUrl = '/product/update-connection-list?id=<?php echo $this->id ?>';
		} else if (categoryId == '3') {
			apiUrl = '/product/update-sales-condition?id=<?php echo $this->id ?>';
		} else if (categoryId == '4') {
			apiUrl = '/product/update-cost?id=<?php echo $this->id ?>';	
		} else if (categoryId == '5') {
			apiUrl = '/product/update-purchasing-list?id=<?php echo $this->id ?>';
		} else {
			return;
		}
		
        $.ajax({
            type:'POST',
            dataType:'json',
            data: params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url: apiUrl,
        });
    });
    
    $(document).on('click', '#popup_ok', function () {
    	if (reloadFlag) {
    		location.href = '/product/basic?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
    	}
    });

    // 編集中止
    $(document).on('click', '.btn_cancel_category', function () {
        var categoryId = $(this).attr('category_id');
        location.href = '/product/basic?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
    });

    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
        	var categoryId = $(this).attr('target-category');
            var result = $("#sortable_column_" + categoryId).sortable("toArray");
            $('input#hidden_contents_order_' + categoryId).val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });
    
    // カラム追加
    $(document).on('click', '.btn_add_column', function () {
    	var categoryId = $(this).attr('target-category');

    	if (categoryId == '2') {
	        var uuid = guid();
			$('.column_copy_base_' + categoryId + ' .relational_connection_type').attr('id', uuid + '_relational_connection_type').attr('name', uuid + '_relational_connection_type');
	        $('.column_copy_base_' + categoryId + ' .connection_name').attr('id', uuid + '_connection_name').attr('name', uuid + '_connection_name');
	        $('.column_copy_base_' + categoryId + ' .target_connection_id').attr('id', uuid + '_target_connection_id').attr('name', uuid + '_target_connection_id');
			$('.column_copy_base_' + categoryId + ' .select_connection').attr('target-row', uuid);
			$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);
			
	        var $clone = $('.column_copy_base_' + categoryId).clone(true);
	        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));
	        
			$('.column_copy_base_' + categoryId + ' .relational_connection_type').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .connection_name').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .target_connection_id').attr('id', '');

	        $('.column_copy_base_' + categoryId + ' td.added_row').each(function(){
	            $(this).css('width', $(this).width() +'px');
	        });

	        var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
	        
		} else if (categoryId == '5') {
	        var uuid = guid();
	        rowCount++;
	        $('.column_copy_base_' + categoryId + ' .td_count p').html(rowCount);
	        
			$('.column_copy_base_' + categoryId + ' .lot_amount').attr('id', uuid + '_lot_amount').attr('name', uuid + '_lot_amount');
	        $('.column_copy_base_' + categoryId + ' .lot_unit').attr('id', uuid + '_lot_unit').attr('name', uuid + '_lot_unit');
	        $('.column_copy_base_' + categoryId + ' .help_lot_unit').attr('id', uuid + '_help_lot_unit');
	        $('.column_copy_base_' + categoryId + ' .unit_price').attr('id', uuid + '_unit_price').attr('name', uuid + '_unit_price');
	        $('.column_copy_base_' + categoryId + ' .total_price').attr('id', uuid + '_total_price').attr('name', uuid + '_total_price');
	        $('.column_copy_base_' + categoryId + ' .delivery_cost').attr('id', uuid + '_delivery_cost').attr('name', uuid + '_delivery_cost');
	        $('.column_copy_base_' + categoryId + ' .purchasing_memo').attr('id', uuid + '_purchasing_memo').attr('name', uuid + '_purchasing_memo');
			$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);
			
	        var $clone = $('.column_copy_base_' + categoryId).clone(true);
	        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));
	        
			$('.column_copy_base_' + categoryId + ' .lot_amount').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .lot_unit').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .unit_price').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .total_price').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .delivery_cost').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .purchasing_memo').attr('id', '');

	        $('.column_copy_base_' + categoryId + ' td.added_row').each(function(){
	            $(this).css('width', $(this).width() +'px');
	        });

	        var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
	        
	        Tipped.create('#' + uuid + '_help_lot_unit', "例） kg、pcs、袋、個、本など");
        }
    });

    // カラム削除
    $(document).on('click', '.delete_button', function () {
    	var categoryId = $(this).attr('target-category');
    	var targetId   = $(this).attr('target-row');
		$('tr#' + targetId).remove();
		
        var result = $("#sortable_column_" + categoryId).sortable("toArray");
        $('input#hidden_contents_order_' + categoryId).val(result);
        
        var countUp = 0;
    	$('#sortable_column tr').each(function(){
    		countUp++;
    		$('#sortable_column_' + categoryId + ' tr#' + $(this).attr('id') + ' .td_count p').html(countUp);
    	});
    });

    // 商品名の区分
    $('#product_name_type').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SALES; ?>' || $(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SALES_AND_SUPPLY; ?>') {
			$('.row_sales_name').show();
		} else {
			$('.row_sales_name').hide();
		}
		
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SUPPLY; ?>' || $(this).val() == '<?php echo Shared_Model_Code::PRODUCT_NAME_TYPE_SALES_AND_SUPPLY; ?>') {
			$('.row_supply_name').show();
		} else {
			$('.row_supply_name').hide();
		}
    });
    
	// 調達製造区分
    $('.product_classes').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_CLASS_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#product_class_other_text').prop("disabled", false);
			} else {
				$('#product_class_other_text').prop("disabled", true);
			}
		}
    }); 

	// 商品区分
    $('.product_categories').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#product_category_other_text').prop("disabled", false);
			} else {
				$('#product_category_other_text').prop("disabled", true);
			}
		}
    });
    
    // 仕入・調達方法
    $('.supply_methods').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::SUPPLY_METHOD_OTHER; ?>') {
			if ($(this).prop('checked')) {
				$('#supply_method_other_text').prop("disabled", false);
			} else {
				$('#supply_method_other_text').prop("disabled", true);
			}
		}
    });
    
    // 製品化の手順
    $('#production_process').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::PRODUCTION_PROCESS_OTHER; ?>') {
			$('#production_process_other_text').prop("disabled", false);
		} else {
			$('#production_process_other_text').prop("disabled", true);
		}
    });

	$('.price_restriction_from_supplier').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::CONTENT_STATUS_ACTIVE; ?>') {
			$('#price_restriction_from_supplier_price').prop("disabled", false);
		} else {
			$('#price_restriction_from_supplier_price').prop("disabled", true);
		}
	});
	
    // 後継品商品 商品選択 ポップアップ表示
    $(document).on('click', '#select_item', function () {
    	pos = $(window).scrollTop();
    	
    	var targetItemId = $('#next_generation_item_id').val();

    	$('#data_area').html('');
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
			
    	if (targetItemId != '' && targetItemId != '0') {
			$('#data_area').load('/product/detail-selected?id=' + targetItemId);
    	} else {
			$('#data_area').load('/product/list-select');
		}
    });
    
    // 商品選択 条件検索
    $(document).on('click', '#search_product', function () {
		updateProductList(1);
    });
    
    // 商品選択 選択解除
    $(document).on('click', '.btn_reset_selected', function () {
		$('#next_generation_item_name').html('---');
		$('#next_generation_item_id').val('');
		$('.btn_close').click();
    });

    // 取引先選択ポップアップ表示
    $(document).on('click', '.select_connection', function () {
    	targetConnectionRow = $(this).attr('target-row');
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select');
    });
    
	// 取引先条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });
    
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': 0});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// 商品一覧ページ切り替え
function pageProduct(pageNo) {
	updateProductList(pageNo)
}

// 商品選択
function selectProduct(id, itemId, name, buyingName) {
	var itemName = '';
	if (name != '') {
		itemName += "<span class='product_name'>商品名</span>&nbsp;" + name + '&nbsp;&nbsp;';
	}

	if (buyingName != '') {
		itemName += "<span class='import_name'>仕入名</span>&nbsp;" + buyingName + '&nbsp;&nbsp;';
	}
	$('#next_generation_item_name').html('<strong>' + itemId + '</strong>&nbsp;'+ itemName);
	$('#next_generation_item_id').val(id);
	$('.btn_close').click();
}

// 商品一覧更新
function updateProductList (pageNo) {
    var $form = $('#product_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/product/list-select?page=' + pageNo,
    });
}


// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form = $('#connection_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/connection/list-select?page=' + pageNo,
    });
}

// 取引先選択
function selectConnection(id, displayId, name) {
	$('#' + targetConnectionRow + '_connection_name').html(name);
	$('#' + targetConnectionRow + '_target_connection_id').val(id);
	$('.btn_close').click();
}
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;margin-right:12px;}
.multi_rows_padding {padding:5px 10px 5px 10px}
.condition_label{float:left;}
a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
table.list_default tr td.td_count {border-right:none;background-color:#bae0ff;width:30px;}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}
.product_name {background-color:#ed8c14;color:#fff;padding:3px 0.2em 1px 0.2em}
.import_name {background-color:#008cff;color:#fff;padding:3px 0.2em 1px 0.2em}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
<div class="clearfix">    
	<?php
		$titleName = '';
		if ($this->data['product_name_type'] === (string)Shared_Model_Code::PRODUCT_NAME_TYPE_SUPPLY) {
			$titleName = $this->escape($this->data['buying_item_name']);
		} else {
			$titleName = $this->escape($this->data['item_name']);
		}
	?>
	<div class="col-xs-12">
	    <div class="page_title">
	        <span><strong>商品管理 - <?php echo $titleName; ?></strong></span>
	    </div>
		<?php
	        echo $this->partial('product/menu.phtml', array(
				'action'    => $this->action,
				'id'        => $this->id,
				'direct'    => $this->direct,
			));
	    ?>
	</div>

    <?php
    /* 基本情報 */
    $categoryId = 1;
    ?>
	<form id="form_category_<?php echo $categoryId; ?>">
    <table class="list_default" style="margin-bottom:0px;">
        <tr>
            <th class="border-left border-top border-bottom"><p class="label_text strong">基本情報</p></th>
            <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
                <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                <span>×</span>
                </a>
            </th>
            <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
            </th>
        </tr>
    </table>
    <table class="list_default" style="margin-bottom:13px;">            
        <tr>
            <td class="column_label"><p class="label_text">商品ID</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p><?php echo $this->data['display_id']; ?></p>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">商品名の区分<span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
				<p class="display_value_<?php echo $categoryId; ?>"><?php echo $productNameTypeList[$this->data['product_name_type']]; ?></p>
				<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
				<select class="short" id="product_name_type" name="product_name_type">
					<option value="">---</option>
					<?php foreach ($productNameTypeList as $key => $val) { ?>
						<option value="<?php echo $key; ?>" <?php if ($this->data['product_name_type'] == $key) { echo 'selected="selected"'; } ?>><?php echo $this->escape($val); ?></option>
					<?php } ?>
            	</select>
            	</div>
            </td>
        </tr>
                 
        <tr class="row_sales_name" <?php if ($this->data['product_name_type'] == Shared_Model_Code::PRODUCT_NAME_TYPE_SUPPLY) { echo 'style="display:none"'; } ?>>
            <td class="column_label"><p class="label_text">販売商品名(日本語)<span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="multi_rows_padding display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['item_name']); ?></div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<input type="text" name="item_name" value="<?php echo $this->escape($this->data['item_name']); ?>" maxlength="" />
            	</div>
            </td>
        </tr>
		
        <tr class="row_sales_name" <?php if ($this->data['product_name_type'] == Shared_Model_Code::PRODUCT_NAME_TYPE_SUPPLY) { echo 'style="display:none"'; } ?>>
            <td class="column_label"><p class="label_text">販売商品名(英語)</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="multi_rows_padding display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['item_name_en']); ?></div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<input type="text" name="item_name_en" value="<?php echo $this->escape($this->data['item_name_en']); ?>" maxlength="" />
            	</div>
            </td>
        </tr>

        <tr class="row_supply_name" <?php if ($this->data['product_name_type'] == Shared_Model_Code::PRODUCT_NAME_TYPE_SALES) { echo 'style="display:none"'; } ?>>
            <td class="column_label"><p class="label_text">仕入商品名<span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="multi_rows_padding display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['buying_item_name']); ?></div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<input type="text" name="buying_item_name" value="<?php echo $this->escape($this->data['buying_item_name']); ?>" maxlength="" />
            	</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">調達製造区分<span class="popup_help" id="help_product_classes">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<?php
            		$displayString = '';
            		foreach ($this->productClassList as $each) {
            			if (!empty($this->data['product_classes'])) {
	                		foreach($this->data['product_classes'] as $eachSelected) {
	                			if ($eachSelected == $each['id']) {
			                		$displayString .= $each['name'] . '<br>';
		                		}
	                		}
                		}
                	}
                	if (!empty($this->data['product_classes'])) {
	                	foreach($this->data['product_classes'] as $eachSelected) {
	                		if ($eachSelected == Shared_Model_Code::PRODUCT_CLASS_OTHER) {
				            	$displayString .= Shared_Model_Code::PRODUCT_CLASS_OTHER_TITLE . '　（' . $this->data['product_class_other_text'] . '） <br>';
				            }
				        }
			        }
            	?>
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo $displayString; ?></div>
            	
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                	<div class="clearfix">
                		<?php foreach ($this->productClassList as $each) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="product_classes" name="product_classes[]" value="<?php echo $this->escape($each['id']); ?>" <?php if (in_array($each['id'], $this->data['product_classes'])) { echo 'checked="checked"'; } ?>><?php echo $this->escape($each['name']); ?>
			                    </label>
		                    </div>
	                    <?php } ?>
						<div class="checkbox_item">
		                	<label>
		                    	<input type="checkbox" class="product_classes" name="product_classes[]" value="<?php echo Shared_Model_Code::PRODUCT_CLASS_OTHER; ?>" <?php if (in_array(Shared_Model_Code::PRODUCT_CLASS_OTHER, $this->data['product_classes'])) { echo 'checked="checked"'; } ?>><?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER_TITLE; ?>
		                    </label>
	                    </div>
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="product_class_other_text" name="product_class_other_text" placeholder="その他調達製造区分" <?php if (!in_array(Shared_Model_Code::PRODUCT_CLASS_OTHER, $this->data['product_classes'])) { echo 'disabled="disabled"'; } ?> value="<?php echo $this->escape($this->data['product_class_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
				</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">商品区分<span class="popup_help" id="help_product_categories">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<?php
            		$displayString = '';
            		foreach ($this->productCategoryList as $each) {
            			if (!empty($this->data['product_categories'])) {
	                		foreach($this->data['product_categories'] as $eachSelected) {
	                			if ($eachSelected == $each['id']) {
			                		$displayString .= $each['name'] . '<br>';
		                		} 
	                		}
                		}
                	}
                	if (!empty($this->data['product_categories'])) {
	                	foreach($this->data['product_categories'] as $eachSelected) {
	                		if ($eachSelected == Shared_Model_Code::PRODUCT_CATEGORY_OTHER) {
				            	$displayString .= Shared_Model_Code::PRODUCT_CATEGORY_OTHER_TITLE . '　（' . $this->data['product_category_other_text'] . '） <br>';
				            }
				        }
			        }
            	?>
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo $displayString; ?></div>
            	
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                	<div class="clearfix">
                		<?php foreach ($this->productCategoryList as $each) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="product_categories" name="product_categories[]" value="<?php echo $this->escape($each['id']); ?>" <?php if (in_array($each['id'], $this->data['product_categories'])) { echo 'checked="checked"'; } ?>><?php echo $this->escape($each['name']); ?>
			                    </label>
		                    </div>
	                    <?php } ?>
						<div class="checkbox_item">
		                	<label>
		                    	<input type="checkbox" class="product_categories" name="product_categories[]" value="<?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER; ?>" <?php if (in_array(Shared_Model_Code::PRODUCT_CATEGORY_OTHER, $this->data['product_categories'])) { echo 'checked="checked"'; } ?>><?php echo Shared_Model_Code::PRODUCT_CATEGORY_OTHER_TITLE; ?>
		                    </label>
	                    </div>
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="product_category_other_text" name="product_category_other_text" placeholder="その他商品区分" <?php if (!in_array(Shared_Model_Code::PRODUCT_CATEGORY_OTHER, $this->data['product_categories'])) { echo 'disabled="disabled"'; } ?> value="<?php echo $this->escape($this->data['product_category_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
				</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">商品戦略<span class="popup_help" id="help_strategy">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="clearfix">
	            	<p class="display_value_<?php echo $categoryId; ?>">
	            		<?php
		            		if (!empty($this->data['strategy'])) {
			            		if ($this->data['strategy'] === (string)Shared_Model_Code::PRODUCT_STRATEGY_SPECIAL) {
		            				echo '<strong>' . $strategyList[$this->data['strategy']] . '</strong>';
		            			} else {
			            			echo $strategyList[$this->data['strategy']];
		            			}
		            		} else {
			            		echo '---';
		            		}
		            	?>
	            	</p>
	            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<select class="short" id="strategy" name="strategy">
							<option value="">---</option>
	                        <?php foreach ($strategyList as $key => $val) { ?>
	                            <option value="<?php echo $key; ?>" <?php if ($this->data['strategy'] == (string)$key) echo 'selected="selected"'; ?>><?php echo $this->escape($val); ?></option>
	                        <?php } ?>
	                	</select>
	            	</div>
				</div>
            </td>
        </tr>
            
        <tr>
            <td class="column_label"><p class="label_text">商品概要</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
            		<?php echo nl2br($this->escape($this->data['memo'])); ?>
            	</div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<textarea name="memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['memo']); ?></textarea>
				</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">販売商品JANコード</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->data['jan_code']; ?></p>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                	<input type="text" class="short" name="jan_code" value="<?php echo $this->escape($this->data['jan_code']); ?>" maxlength="" />
                </div>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">配送向け内容品表記(日本語)</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['delivery_item_name']); ?></p>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<input type="text" name="delivery_item_name" value="<?php echo $this->escape($this->data['delivery_item_name']); ?>" maxlength="" />
            	</div>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">配送向け内容品表記(英語)</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['delivery_item_name_en']); ?></p>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<input type="text" name="delivery_item_name_en" value="<?php echo $this->escape($this->data['delivery_item_name_en']); ?>" maxlength="" />
            	</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">販売状況<span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p class="display_value_<?php echo $categoryId; ?>">
            		<?php
                		$displayString = '';
                		foreach ($productSalesStatusList as $key => $val) {
                			if (!empty($this->data['product_sales_status'])) {
		                		if ($this->data['product_sales_status'] == (string)$key) {
		                			$displayString .= $val . '<br>';
		                		}
	                		}
	                	}
	                	echo $displayString;
            		?>
            	</p>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<select class="short" id="product_sales_status" name="product_sales_status">
						<option value="">---</option>
                        <?php foreach ($productSalesStatusList as $key => $val) { ?>
                            <option value="<?php echo $key; ?>" <?php if ($this->data['product_sales_status'] == (string)$key) echo 'selected="selected"'; ?>><?php echo $this->escape($val); ?></option>
                        <?php } ?>
                	</select>
				</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">GS商品ID</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p>---</p>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">GS登録・更新日</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p>---</p>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">販売可能範囲<span class="popup_help" id="help_product_markets">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<?php
            		$displayString = '';
            		foreach ($productMarketList as $key => $val) {
            			if (!empty($this->data['product_markets'])) {
	                		foreach($this->data['product_markets'] as $eachSelected) {
	                			if ($eachSelected == $key) {
				                	$displayString .= $val . '<br>';
		                		}
	                		}
                		}
                	}
            	?>
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo $displayString; ?></div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                	<div class="clearfix">
                		<?php foreach ($productMarketList as $key => $val) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="product_markets" name="product_markets[]" value="<?php echo $this->escape($key); ?>" <?php if (in_array($key, $this->data['product_markets'])) { echo 'checked="checked"'; } ?>><?php echo $this->escape($val); ?>
			                    </label>
		                    </div>
	                    <?php } ?> 
					</div>
				</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">後継品商品</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
				<?php
					$itemName = '---';
            		if (!empty($this->data['next_generation_item_id'])) {
            			$itemTable = new Shared_Model_Data_Item();
            			$itemData = $itemTable->getById($this->adminProperty['management_group_id'], $this->data['next_generation_item_id']);
            			
            			$itemName = '<strong>' . $this->escape($itemData['display_id']) . '</strong>&nbsp;';
            			
            			if (!empty($itemData['item_name'])) {
            				$itemName .= "<span class='product_name'>商品名</span>&nbsp;" . $this->escape($itemData['item_name']) . '&nbsp;&nbsp;';
            			}
            			
            			if (!empty($itemData['buying_item_name'])) {
            				$itemName .= "<span class='import_name'>仕入名</span>&nbsp;" . $this->escape($itemData['buying_item_name'])  . '&nbsp;&nbsp;';
            			}	
            		}
            	?>
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo $itemName; ?></div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                	<div id="next_generation_item_name" class="multi_rows_padding"><?php echo $itemName; ?></div>
                    <a class="option" id="select_item">商品選択</a>
                    <input type="hidden" id="next_generation_item_id" name="next_generation_item_id" value="<?php echo $this->escape($this->data['next_generation_item_id']); ?>" />
            	</div>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">仕入・調達方法</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<?php
            		$displayString = '';
            		foreach ($this->supplyMethodList as $each) {
            			if (!empty($this->data['supply_methods'])) {
	                		foreach($this->data['supply_methods'] as $eachSelected) {
	                			if ($eachSelected == $each['id']) {
				                	$displayString .= $each['name'] . '<br>';
		                		}
	                		}
                		}
                	}
                	if (!empty($this->data['supply_methods'])) {
	                	foreach($this->data['supply_methods'] as $eachSelected) {
	                		if ($eachSelected == Shared_Model_Code::SUPPLY_METHOD_OTHER) {
	                			$displayString .= Shared_Model_Code::SUPPLY_METHOD_OTHER_TITLE . '　（' . $this->data['supply_method_other_text'] . '） <br>';
	                		}
	                	}
                	}
            	?>
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo $displayString; ?></div>
            	
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                	<div class="clearfix">
                		<?php foreach ($this->supplyMethodList as $each) { ?>
		                	<div class="checkbox_item">
			                	<label>
			                    	<input type="checkbox" class="supply_methods" name="supply_methods[]" value="<?php echo $this->escape($each['id']); ?>" <?php if (in_array($each['id'], $this->data['supply_methods'])) { echo 'checked="checked"'; } ?>><?php echo $each['name']; ?>
			                    </label>
		                    </div>
	                    <?php } ?>
	                	<div class="checkbox_item">
		                	<label>
		                    	<input type="checkbox" class="supply_methods" name="supply_methods[]" value="<?php echo Shared_Model_Code::SUPPLY_METHOD_OTHER; ?>" <?php if (in_array($each['id'], $this->data['supply_methods'])) { echo 'checked="checked"'; } ?>><?php echo Shared_Model_Code::SUPPLY_METHOD_OTHER_TITLE; ?>
		                    </label>
	                    </div>
	                    
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="supply_method_other_text" name="supply_method_other_text" placeholder="その他調達方法" <?php if (!in_array(Shared_Model_Code::SUPPLY_METHOD_OTHER, $this->data['supply_methods'])) { echo 'disabled="disabled"'; } ?> value="<?php echo $this->escape($this->data['supply_method_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
				</div>
            </td>
        </tr>     
        
        <tr>
            <td class="column_label"><p class="label_text">製品化の手順<span class="popup_help" id="help_production_process">&nbsp;<i class="icon-help-circled"></i></span></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<?php
            		$displayString = '';
            		foreach ($productionProcessList as $key => $val) {
            			if (!empty($this->data['production_process'])) {
                			if ($this->data['production_process'] == $key) {
		                		if ($key == Shared_Model_Code::PRODUCTION_PROCESS_OTHER) {
			                		$displayString .= $val . '　（' . $this->data['production_process_other_text'] . '） <br>';
			                	} else {
			                		$displayString .= $val . '<br>';
		                		}
	                		}
                		}
                	}
            	?>
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo $displayString; ?></div>
            	
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                	<div class="clearfix">
  						<select class="short" id="production_process" name="production_process">
							<option value="">---</option>
                            <?php foreach ($productionProcessList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>" <?php if ($this->data['production_process'] == (string)$key) echo 'selected="selected"'; ?>><?php echo $this->escape($val); ?></option>
                            <?php } ?>
                		</select>
					</div>
					<div class="clearfix" style="padding-bottom:8px;">
	                    <input type="text" id="production_process_other_text" name="production_process_other_text" placeholder="その他製品化の手順" <?php if (Shared_Model_Code::PRODUCTION_PROCESS_OTHER != $this->data['product_process']) { echo 'disabled="disabled"'; } ?> value="<?php echo $this->escape($this->data['production_process_other_text']); ?>" maxlength="" style="width:300px;float:left;" />
					</div>
				</div>
            </td>
        </tr>
	</table>
	</form>

    <?php
    /* 仕入先・製造委託先 */
    $categoryId = 2;
    ?>
    <?php /*
    <div style="margin-bottom:13px;">
    <form id="form_category_<?php echo $categoryId; ?>">
    <table class="list_default" style="margin-bottom:0px;">
        <tr>
            <th class="border-left border-top border-bottom"><p class="label_text strong">仕入先・製造委託先</p></th>
            <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
                <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                <span>×</span>
                </a>
            </th>
            <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
            </th>
        </tr>
    </table>
    <?php
    	$connectionTable = new Shared_Model_Data_Connection();
    ?>
    <table class="list_default" style="margin-bottom:0;">
    	<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
	        <?php if (!empty($this->data['relational_connection_list'])) { ?>
		        <?php foreach ($this->data['relational_connection_list'] as $each) { ?>
					<?php
	            		$connecionData = array('company_name' => '');
	            		if (!empty($each['target_connection_id'])) {
	            			$connecionData = $connectionTable->getById($this->adminProperty['management_group_id'], $each['target_connection_id']);
	            		}
	            	?> 
			        <tr id="<?php echo $this->escape($each['id']); ?>">
			            <td class="column_label">
			            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $productRelationalConnectionList[$each['relational_connection_type']]; ?></p>
			            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
				            	<select name="<?php echo $this->escape($each['id']); ?>_relational_connection_type" style="padding-left:12px;width:260px">
				            		<option value="">---</option>
				            		<?php foreach ($productRelationalConnectionList as $key => $val) { ?>
				            			<option value="<?php echo $key; ?>" <?php if ($key == $each['relational_connection_type']) { echo 'selected="selected"'; } ?>><?php echo $val; ?></option>
				            		<?php } ?>
				            	</select>
			            	</div>
			            </td>
			            <td class="colon"><p class="label_text">：</p></td>
			            <td class="column_value">
			            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($connecionData['company_name']); ?></p>
			            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
			                	<p style="float:left;" id="<?php echo $this->escape($each['id']); ?>_connection_name"><?php echo $this->escape($connecionData['company_name']); ?></p>
			                    <a style="float:right;" class="option select_connection" target-row="<?php echo $this->escape($each['id']); ?>">取引先選択</a>
			                    <input type="hidden" id="<?php echo $this->escape($each['id']); ?>_target_connection_id" name="<?php echo $this->escape($each['id']); ?>_target_connection_id" value="<?php echo $this->escape($each['target_connection_id']); ?>" />
			            	</div>
			            </td>
			            <td class="td_action">
			            	<div class="delete_btn_frame edit_value_<?php echo $categoryId; ?>" style="display:none;">
			            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row="<?php echo $this->escape($each['id']); ?>"><i class="icon-cancel"></i></a>
			            	</div>
			            </td>
			        </tr>
		        <?php } ?>
	        <?php } ?>
	    </tbody>
	</table>
	<div class="edit_value_<?php echo $categoryId; ?>" style="border-bottom:1px solid #ccc;height:34px;display:none;">
    	<p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
    </div>
	<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="relational_connection_list" value="" />	
	</form>
	
    <!-- copy base -->
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base_<?php echo $categoryId; ?>">
            <td class="column_label">
            	<select class="relational_connection_type" name="##_relational_connection_type" style="padding-left:12px;width:260px">
            		<option value="">---</option>
            		<?php foreach ($productRelationalConnectionList as $key => $val) { ?>
            			<option value="<?php echo $key; ?>"><?php echo $val; ?></option>
            		<?php } ?>
            	</select>
            </td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="clearfix">
                	<p style="float:left;" class="connection_name" id="##_connection_name">---</p>
                    <a style="float:right;" class="option select_connection" target-row="##">取引先選択</a>
                    <input type="hidden" class="target_connection_id" id="##_target_connection_id" name="##_target_connection_id" value="" />
            	</div>
            </td>
            <td class="td_action">
            	<div class="delete_btn_frame edit_value_<?php echo $categoryId; ?>" style="display:none;">
            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row="##"><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>    
	<!-- copy base -->
	</div>
	*/ ?>

    <?php
    /* 販売条件 */
    $categoryId = 3;
    ?>
    <form id="form_category_<?php echo $categoryId; ?>">
    <table class="list_default" style="margin-bottom:0px;">
        <tr>
            <th class="border-left border-top border-bottom"><p class="label_text strong">販売条件</p></th>
            <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                <span>×</span>
                </a>
            </th>
            <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
            </th>
        </tr>
    </table>
    <table class="list_default" style="margin-bottom:13px;">
        <tr>
            <td class="column_label"><p class="label_text">当社国内小売価格</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p><?php echo nl2br($this->escape('(連動)')); ?></p>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">顧客向け当社販売価格制約</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p class="display_value_<?php echo $categoryId; ?>">
            		<?php
            			if (array_key_exists($this->data['price_restriction_for_customer'], $noYesList)) {
            				echo $noYesList[$this->data['price_restriction_for_customer']];
            			}
            		?>
            	</p>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;padding-left:9px;">
                	<?php foreach ($noYesList as $key => $val) { ?>
	                	<div class="checkbox_item relation_type_item">
		                	<label>
		                    	<input type="radio" name="price_restriction_for_customer" value="<?php echo $key; ?>" <?php if ((string)$key === $this->data['price_restriction_for_customer']) { echo 'checked="checked"'; } ?>><?php echo $val; ?>
		                    </label>
	                    </div>
                    <?php } ?>
                </div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">顧客向け当社販売方法制約<span class="popup_help" id="help_method_restriction_for_customer">&nbsp;<i class="icon-help-circled"></i></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
            		<?php echo nl2br($this->escape($this->data['method_restriction_for_customer_text'])); ?>
            	</div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<textarea name="method_restriction_for_customer_text" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['method_restriction_for_customer_text']); ?></textarea>
				</div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">仕入先上代遵守ルール有無<span class="popup_help" id="help_price_restriction_from_supplier">&nbsp;<i class="icon-help-circled"></i></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p class="display_value_<?php echo $categoryId; ?>">
            		<?php
            			if (array_key_exists($this->data['price_restriction_from_supplier'], $noYesList)) {
            				echo $noYesList[$this->data['price_restriction_from_supplier']];
            			}
            			
            			if ((string)Shared_Model_Code::CONTENT_STATUS_ACTIVE == $this->data['price_restriction_from_supplier']) {
            				echo '　（指定小売価格：&nbsp;' . number_format($this->escape($this->data['price_restriction_from_supplier_price'])) . '&nbsp;円）';	
            			}
            		?>
            	</p>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;padding-left:9px;">
                	<?php foreach ($noYesList as $key => $val) { ?>
	                	<div class="checkbox_item relation_type_item">
		                	<label>
		                    	<input type="radio" class="price_restriction_from_supplier" name="price_restriction_from_supplier" value="<?php echo $key; ?>" <?php if ((string)$key === $this->data['price_restriction_from_supplier']) { echo 'checked="checked"'; } ?>><?php echo $val; ?>
		                    </label>
	                    </div>
                    <?php } ?>
                    <div class="clearfix">
                    	<p style="float:left;margin-right:10px;">指定小売価格</p>
                    	<input type="text" id="price_restriction_from_supplier_price" name="price_restriction_from_supplier_price" <?php if ((string)Shared_Model_Code::CONTENT_STATUS_ACTIVE !== $this->data['price_restriction_from_supplier']) { echo 'disabled="disabled"'; } ?> value="<?php echo $this->escape($this->data['price_restriction_from_supplier_price']); ?>" maxlength="" style="width:100px;float:left;" />
                		<p style="float:left">円</p>
                	</div>
                </div>
            </td>
        </tr>

        <tr>
            <td class="column_label"><p class="label_text">仕入先指定販売条件<span class="popup_help" id="help_method_restriction_from_supplier">&nbsp;<i class="icon-help-circled"></i></p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
            		<?php echo nl2br($this->escape($this->data['method_restriction_from_supplyer_text'])); ?>
            	</div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<textarea name="method_restriction_from_supplyer_text" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['method_restriction_from_supplyer_text']); ?></textarea>
				</div>
            </td>
        </tr>

        
        <tr>
            <td class="column_label"><p class="label_text">条件メモ</p></td>
            <td class="colon"><p class="label_text">：</p></td>
             <td class="column_value">
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
            		<?php echo nl2br($this->escape($this->data['sales_condition_memo'])); ?>
            	</div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<textarea name="sales_condition_memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['sales_condition_memo']); ?></textarea>
				</div>
            </td>
        </tr> 
	</table>
	</form>

    <?php
    /* 原価 */
    $categoryId = 4;
    ?>
    <form id="form_category_<?php echo $categoryId; ?>">
    <table class="list_default" style="margin-bottom:0px;">
        <tr>
            <th class="border-left border-top border-bottom"><p class="label_text strong">原価</p></th>
            <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                <span>×</span>
                </a>
            </th>
            <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
            </th>
        </tr>
    </table>
    <table class="list_default" style="margin-bottom:13px;">
        <tr>
            <td class="column_label"><p class="label_text">EC小売原価</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p><?php echo nl2br($this->escape('(連動)')); ?></p>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">EC卸原価</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p><?php echo nl2br($this->escape('(連動)')); ?></p>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">国内卸輸送ロット</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p><?php echo nl2br($this->escape('(連動)')); ?></p>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">海外卸輸送ロット</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<p><?php echo nl2br($this->escape('(連動)')); ?></p>
            </td>
        </tr>
        
        <tr>
            <td class="column_label"><p class="label_text">原価メモ</p></td>
            <td class="colon"><p class="label_text">：</p></td>
            <td class="column_value">
            	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
            		<?php echo nl2br($this->escape($this->data['cost_memo'])); ?>
            	</div>
            	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					<textarea name="cost_memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['cost_memo']); ?></textarea>
				</div>
            </td>
        </tr>
    </table>
	</form>
    
    
    <?php
    /* 仕入購入条件 */
    $categoryId = 5;
    ?>
    
    <?php /*
    <form id="form_category_<?php echo $categoryId; ?>">
    <table class="list_default" style="margin-bottom:0px;">
        <tr>
            <th class="border-left border-top border-bottom"><p class="label_text strong">仕入購入条件</p></th>
            <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
                <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                <span>×</span>
                </a>
            </th>
            <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
            </th>
        </tr>
    </table>
    <table class="list_default" style="margin-bottom:0;">
    	<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
	        <?php if (!empty($this->data['purchasing_list'])) { ?>
		        <?php foreach ($this->data['purchasing_list'] as $each) { ?>
		        <tr id="<?php echo $each['id']; ?>">
		        	<td class="td_count">
		        		<p><?php echo $each['id']; ?></p>
		        	</td>
		            <td class="column_value">
		            	<div class="clearfix">
			            	<div style="float:left;width:160px;">
				            	<div class="condition_label multi_rows_padding">購入ロット：</div>
				            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['lot_amount']); ?></p>
				            	<input type="text" class="edit_value_<?php echo $categoryId; ?>" style="display:none;float:left;width:70px" name="<?php echo $each['id']; ?>_lot_amount" value="<?php echo $this->escape($each['lot_amount']); ?>" />
			            	</div>
			            	<div style="float:left;width:190px;">
				            	<div class="condition_label multi_rows_padding">ロット単位<span id="<?php echo $each['id']; ?>_help_lot_unit">&nbsp;<i class="icon-help-circled"></i></span>：</div>
				            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['lot_unit']); ?></p>
				            	<input type="text" class="edit_value_<?php echo $categoryId; ?>" style="display:none;float:left;width:90px" name="<?php echo $each['id']; ?>_lot_unit" value="<?php echo $this->escape($each['lot_unit']); ?>" placeholder="例：kg. pcs" />
							</div>
							<div style="float:left;width:230px;">
				            	<div class="condition_label multi_rows_padding">仕入単価(税別)：</div>
				            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['unit_price']); ?></p>
				            	<input type="text" class="edit_value_<?php echo $categoryId; ?>" style="display:none;float:left;width:110px" name="<?php echo $each['id']; ?>_unit_price" value="<?php echo $this->escape($each['unit_price']); ?>" />
							</div>
							<div style="float:left;width:244px;">
				            	<div class="condition_label multi_rows_padding">仕入価格総額(税別)：</div>
				            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['total_price']); ?></p>
				            	<input type="text" class="edit_value_<?php echo $categoryId; ?>" style="display:none;float:left;width:110px" name="<?php echo $each['id']; ?>_total_price" value="<?php echo $this->escape($each['total_price']); ?>" />
							</div>
		            	</div>
		            	<div class="clearfix">
							<div style="float:left;width:220px;">
				            	<div class="condition_label multi_rows_padding">物流費　　：</div>
				            	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['delivery_cost']); ?></p>
				            	<input type="text" class="edit_value_<?php echo $categoryId; ?>" style="display:none;float:left;width:110px" name="<?php echo $each['id']; ?>_delivery_cost" value="<?php echo $this->escape($each['delivery_cost']); ?>" />
		            		</div>
		            	</div>
		            	<div class="clearfix" style="margin-bottom:8px">
		            		<p class="condition_label" style="float:left;width:72px;">条件メモ　:</p>
		            		<div style="float:left;width:895px;">
		            			<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo nl2br($this->escape($each['purchasing_memo'])); ?></div>
		            			<textarea class="edit_value_<?php echo $categoryId; ?>" name="<?php echo $each['id']; ?>_purchasing_memo" style="display:none;height:50px;"></textarea>
		            		</div>
		            	</div>
		            </td>
		            <td class="td_action">
		            	<div class="delete_btn_frame edit_value_<?php echo $categoryId; ?>" style="display:none;">
		            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row="<?php echo $each['id']; ?>"><i class="icon-cancel"></i></a>
		            	</div>
		            </td>
		        </tr>
		        <?php } ?>
	        <?php } ?>
		</tbody>
    </table>
	<div class="edit_value_<?php echo $categoryId; ?>" style="border-bottom:1px solid #ccc;height:34px;display:none;">
    	<p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
    </div>
	<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="purchasing_list" value="" />	
    </form>
        
    <!-- copy base -->
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base_<?php echo $categoryId; ?>">
        	<td class="td_count">
        		<p>##</p>
        	</td>
            <td class="column_value">
            	<div class="clearfix">
	            	<div style="float:left;width:160px;">
						<div class="condition_label multi_rows_padding">購入ロット：</div>
            			<input type="text" style="float:left;width:70px" class="lot_amount" name="##_lot_amount" value="" />
	            	</div>
	            	<div style="float:left;width:190px;">
		            	<div class="condition_label multi_rows_padding">ロット単位<span class="help_lot_unit">&nbsp;<i class="icon-help-circled"></i></span>：</div>
		            	<input type="text" style="float:left;width:90px" class="lot_unit" name="##_lot_unit" value="" placeholder="例：kg. pcs" />
					</div>
					<div style="float:left;width:230px;">
		            	<div class="condition_label multi_rows_padding">仕入単価(税別)：</div>
		            	<input type="text" style="float:left;width:110px" class="unit_price"  name="##_unit_price" value="" />
					</div>
					<div style="float:left;width:244px;">
		            	<div class="condition_label multi_rows_padding" class="condition_label">仕入価格総額(税別)：</div>
		            	<input type="text" style="float:left;width:110px" class="total_price"  name="##_total_price" value="" />
					</div>
            	</div>
            	<div class="clearfix">
					<div style="float:left;width:220px;">
		            	<div class="condition_label multi_rows_padding">物流費　　：</div>
		            	<input type="text" style="float:left;width:110px" class="delivery_cost" name="##_delivery_cost" value="" />
            		</div>
            	</div>
            	<div class="clearfix" style="margin-bottom:8px">
            		<p class="condition_label" style="float:left;width:72px;">条件メモ　:</p>
            		<div style="float:left;width:895px;">
            			<textarea class="purchasing_memo" name="##_purchasing_memo" style="height:50px;"></textarea>
            		</div>
            	</div>
            </td>
            <td class="td_action">
            	<div class="delete_btn_frame edit_value_<?php echo $categoryId; ?>" style="display:none;">
            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row="<?php echo $each['id']; ?>"><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>    
	<!-- copy base -->
    */ ?>

	</table>
	</form>
	
        
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;"><div class="menu_frame"><div id="data_area"></div></div></div>
</div>
</div>
</div>

