<?php
$productClassList         = Shared_Model_Code::codes('product_class');
$productSalesStatusList   = Shared_Model_Code::codes('product_sales_status');
?>

<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong>商品管理</strong></span>
    </div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<div class="condition_items clearfix">
		<form id="product_condition_form" action="#" method="get">
			<p class="search_condition_title">検索条件</p>
			
			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">区分：</p>
                    <select id="user_id_in_charge" name="stock_status">
                        <option value="">---</option>
                    	<?php foreach ($stockStatusList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ($key == $this->conditions['stock_status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>

				<div class="condition_item">
					<p class="condition_label">分類：</p>
                    <select id="user_id_in_charge" name="status">
                        <option value="">---</option>
                    	<?php foreach ($statusList as $key => $value) { ?>
                            <option value="<?php echo $eachUser['id']; ?>" <?php if ($key == $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">販売可能範囲：</p>
                    <select id="user_id_in_charge" name="stock_status">
                        <option value="">---</option>
                    	<?php foreach ($stockStatusList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ($key == $this->conditions['stock_status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">販売状況：</p>
                    <select id="user_id_in_charge" name="stock_status">
                        <option value="">---</option>
                    	<?php foreach ($stockStatusList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ($key == $this->conditions['stock_status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
			</div>
			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">調達方法：</p>
                    <select id="user_id_in_charge" name="stock_status">
                        <option value="">---</option>
                    	<?php foreach ($stockStatusList as $key => $value) { ?>
                            <option value="<?php echo $key; ?>" <?php if ($key == $this->conditions['stock_status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">キーワード：</p>
					<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
				</div>
			</div>
			<input type="button" value="検索" />
		
		</form>
	</div>
</div>	

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:13%;">
				<p>商品ID</p>
			</th>

			<th style="width:18%;">
				<p>区分<i class="icon-info-circle"></i></p>
			</th>
			
			<th style="width:12%;">
				<p>販売状況</p>
			</th>
				
			<th>
				<p>商品名<i class="icon-info-circle"></i></p>
			</th>
			
			<th style="width:8%;">
				<p>選択</p>
			</th>
		</tr>
		
		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>

				<tr id="<?php echo $each['id']; ?>" <?php if ($each['product_sales_status'] == Shared_Model_Code::PRODUCT_SALES_STATUS_FINISHED) { echo 'class="deleted"'; } ?>>
					<td>
						<p><?php echo $this->escape($each['display_id']); ?></p>
					</td>

                	<?php
                		$selected = array();
                		$productClasses = unserialize($each['product_classes']);
                		if (!empty($productClasses)) {
                			foreach ($productClassList as $key => $val) {
		                		foreach($productClasses as $eachSelected) {
		                			if ($eachSelected === (string)$key) {
										if ($key == Shared_Model_Code::PRODUCT_CLASS_OTHER) {
					                		$selected[] .= $val . '　（' . $each['product_class_other_text'] . '）';
					                	} else {
					                		$selected[] .= $val;
				                		}
				                	}
		                		}
	                		}
	                	}
                	?>
					<td class="desc" all-content="<?php echo $this->escape(implode(' / ', $selected)); ?>">
						<p><?php echo $this->escape($this->roundText(implode(' / ', $selected), 15)); ?></p>
					</td>
					
					<td>
						<p><?php echo $productSalesStatusList[$each['product_sales_status']] ?></p>
					</td>
					
					<td class="desc" all-content="<?php echo $this->escape($each['item_name']); ?>">
						<p><?php echo $this->escape($this->roundText($each['item_name'], 44)); ?></a></p>
					</td>
					
					<td>
						<a class="option" href="javascript:selectProduct('<?php echo $each['id']; ?>', '<?php echo $this->escape($each['item_name']); ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="7">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding: 2.0em 0 5.0em;">
    <?php echo $this->pager() ?>
    </div>
            
</div>

