<?php
?>
<link rel="stylesheet" type="text/css" href="/resource/js/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css" />
<script type="text/javascript" src="/resource/js/jquery.imgareaselect-0.9.10/scripts/jquery.imgareaselect.pack.js"></script>

<script type="text/javascript"><!--
var reloadFlag  = false;
var deletedFlag = false;

$(function() {
    $(document).ready(function(){
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->posTop; ?>);
        <?php } ?>
    });
});
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td{background-color: #fff;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p.column_label {border-right:none;width:90px;float:left;font-weight:bold;}
table.list_default tr td.column_value p.colon {width:20px;float:left;font-weight:bold;}
table.list_default tr td.column_value p.value {padding-left:10px;padding-bottom:3px;float:left;width:280px;}
table.list_default tr td.column_value div.value {padding-left:10px;padding-bottom:3px;float:left;width:280px;}
table.list_default tr td.column_value input[type="text"] {width:240px;display:block;float:left;}
table.list_default tr td textarea{width:280px;height:60px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.multi_rows_padding {padding:4px 0 0 10px;float:left;}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
a.btn_setting#btn_download {padding:1px 8px 0px;float:left;margin-left:20px;margin-top:5px;margin-bottom:0;float:left;}

.order_btn_frame {float:left;margin:6px 0 0 14px;}
.order_btn_frame .icon-up-dir-1 {font-size:14px;color:#000;line-height:1;display:block;}
.order_btn_frame .icon-down-dir-1 {font-size:14px;margin-top:-6px;color:#000;line-height:1;display:block;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>商品管理 - <?php echo $this->escape($this->data['item_name']); ?></strong></span>
        </div>
    	<?php
            echo $this->partial('product/menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->id,
    			'direct'    => $this->direct,
    		));
        ?>
    </div>

    <div class="clearfix">

	    <?php
        /* 入手見積 */
        $categoryId = 1;
        ?>
		<form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th style="border-left:1px solid #ddd;border-top:1px solid #ddd;border-bottom:1px solid #ddd;"><p class="label_text strong">入手見積</p></th>
                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                    <span>×</span>
                    </a>
                </th>
                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
                </th>
            </tr>
        </table>
        <table class="list_default" style="margin-bottom:0;">
        	<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
        	
        	
			        <tr id="<?php echo $this->escape($each['id']); ?>">
			        	<td class="column_value" style="width:150px;">
			        
			        				
			        				<div class="clearfix">
										<p>ファイル<br></p>
										<p class="display_value_<?php echo $categoryId; ?>">あああああああああああ.pdf</p>
										<a class="btn_setting display_value_<?php echo $categoryId; ?>" id="btn_download" href="javascript:void(0);">ダウンロード</a>
									</div>
						</td>		
			        
		                <td class="column_value">
		                	<div class="clearfix">
								<div style="float:left;width:460px;">
									<div class="clearfix">
										<p class="column_label">入手見積書日付</p>
										<p class="colon">：</p>
										<p class="value display_value_<?php echo $categoryId; ?>"><?php  ?></p>
										<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_department" style="width:100px" value="" maxlength="" />
					                    </div>
									</div>
									<div class="clearfix" style="margin-bottom:5px">
										<p class="column_label">見積条件備考</p>
										<p class="colon">：</p>
										<div class="value display_value_<?php echo $categoryId; ?> multi_rows_padding">あいうえおかきくけこあいうえおかきくけこあいうえおかきくけこあいうえおかきくけこあいうえおかきくけこ<br></div>
										<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="float:left;display:none;">
					                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_department" style="width:100px" value="<?php echo $this->escape($each['stuff_department']); ?>" maxlength="" />
					                    </div>
									</div>
								</div>
								<div style="float:left;">

									<div class="clearfix" style="margin-bottom:5px">
										<p class="column_label">見積メモ</p>
										<p class="colon">：</p>
										<div class="value display_value_<?php echo $categoryId; ?> multi_rows_padding">あいうえおかきくけこあいうえおかきくけこあいうえおかきくけこあいうえおかきくけこあいうえおかきくけこ</div>
										<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="float:left;display:none;">
					                    	<textarea name="<?php echo $this->escape($each['id']); ?>_stuff_memo"><?php echo $this->escape($each['stuff_memo']); ?></textarea>
					                    </div>
									</div>						
								</div>
							</div>
		                </td>
	                    <td class="td_action">
		                	<div class="delete_btn_frame edit_value_<?php echo $categoryId; ?>" style="display:none;">
		                		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row=""><i class="icon-cancel"></i></a>
		                	</div>
		                    <div class="order_btn_frame edit_value_<?php echo $categoryId; ?>"  style="display:none;">
		                        <i class="icon-up-dir-1"></i>
		                        <i class="icon-down-dir-1"></i>
		                    </div>
	                    </td>
	            	</tr>
		        <?php if (!empty($this->staffList)) { ?>
			        <?php foreach ($this->staffList as $each) { ?>
			        <tr id="<?php echo $this->escape($each['id']); ?>">
		                <td class="column_value">
		                	<div class="clearfix">
								<div style="float:left;width:280px;">
									<p class="display_value_<?php echo $categoryId; ?>"><strong><?php echo $this->escape($each['stuff_name']); ?></strong></p>
									<p class="display_value_<?php echo $categoryId; ?>" style="margin-bottom:8px;"><?php echo $this->escape($each['stuff_name_kana']); ?></p>
									<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="margin-left:8px;display:none;">
				                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_name" placeholder="氏名" value="<?php echo $this->escape($each['stuff_name']); ?>" maxlength="" />
				                    </div>
				                    <div class="edit_value_<?php echo $categoryId; ?> clearfix" style="margin-left:8px;display:none;">
				                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_name_kana" placeholder="氏名カナ" value="<?php echo $this->escape($each['stuff_name_kana']); ?>" maxlength="" />
				                    </div>
								</div>
								<div style="float:left;">
									<div class="clearfix">
										<p class="column_label">部署</p>
										<p class="colon">：</p>
										<p class="value display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['stuff_department']); ?></p>
										<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_department" style="width:618px" value="<?php echo $this->escape($each['stuff_department']); ?>" maxlength="" />
					                    </div>
									</div>
									<div class="clearfix">
										<div style="float:left;width:380px;">
											<p class="column_label">役職</p>
											<p class="colon">：</p>
											<p class="value display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['stuff_position']); ?></p>
											<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_position" value="<?php echo $this->escape($each['stuff_position']); ?>" maxlength="" />
						                    </div>
										</div>
									</div>
									
									<div class="clearfix">
										<div style="float:left;width:380px;">
											<p class="column_label">電話番号</p>
											<p class="colon">：</p>
											<p class="value display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['stuff_tel']); ?></p>
											<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_tel" value="<?php echo $this->escape($each['stuff_tel']); ?>" maxlength="" />
						                    </div>
						                </div>
						                <div style="float:left;width:380px;">
							                <p class="column_label">FAX番号</p>
											<p class="colon">：</p>
											<p class="value display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['stuff_fax']); ?></p>
											<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_fax" value="<?php echo $this->escape($each['stuff_fax']); ?>" maxlength="" />
						                    </div>
										</div>
									</div>

									<div class="clearfix">
										<p class="column_label">メールアドレス</p>
										<p class="colon">：</p>
										<p class="value display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['stuff_mail']); ?></p>
										<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_mail" value="<?php echo $this->escape($each['stuff_mail']); ?>" maxlength="" />
					                    </div>
									</div>
									
									<div class="clearfix" style="margin-bottom:5px">
										<p class="column_label">メモ</p>
										<p class="colon">：</p>
										<div class="value display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo nl2br($this->escape($each['stuff_memo'])); ?></div>
										<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
					                    	<textarea name="<?php echo $this->escape($each['id']); ?>_stuff_memo"><?php echo $this->escape($each['stuff_memo']); ?></textarea>
					                    </div>
									</div>
									
								</div>
							</div>
		                </td>
	                    <td class="td_action">
		                	<div class="delete_btn_frame edit_value_<?php echo $categoryId; ?>" style="display:none;">
		                		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row=""><i class="icon-cancel"></i></a>
		                	</div>
		                    <div class="order_btn_frame edit_value_<?php echo $categoryId; ?>"  style="display:none;">
		                        <i class="icon-up-dir-1"></i>
		                        <i class="icon-down-dir-1"></i>
		                    </div>
	                    </td>
	            	</tr>
			        <?php } ?>
		        <?php } ?>
		    </tbody>
        </table>
        <div class="edit_value_<?php echo $categoryId; ?>" style="border-bottom:1px solid #dfdfdf;height:34px;display:none">
            <p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
        </div>
    	<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="staff_list" value="" />
        </form>
	
        <table class="list_default" style="display:none;">
            <tr class="column_copy_base_<?php echo $categoryId; ?>" id="">
                <td class="column_value">
                	<div class="clearfix">
						<div style="float:left;width:280px;">
							<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="margin-left:8px">
		                    	<input type="text" class="stuff_name" name="" placeholder="氏名" value="" maxlength="" />
		                    </div>
		                    <div class="edit_value_<?php echo $categoryId; ?> clearfix" style="margin-left:8px;">
		                    	<input type="text" class="stuff_name_kana" name="" placeholder="氏名カナ" value="" maxlength="" />
		                    </div>
						</div>
						<div style="float:left;">
							<div class="clearfix">
								<p class="column_label">部署</p>
								<p class="colon">：</p>
								<div class="edit_value_<?php echo $categoryId; ?> clearfix">
			                    	<input type="text" style="width:618px" class="stuff_department" name="" value="" maxlength="" />
			                    </div>
							</div>
							<div class="clearfix">
								<div style="float:left;width:380px;">
									<p class="column_label">役職</p>
									<p class="colon">：</p>
									<div class="edit_value_<?php echo $categoryId; ?> clearfix">
				                    	<input type="text" class="stuff_position" name="" value="" maxlength="" />
				                    </div>
								</div>
							</div>
							
							<div class="clearfix">
								<div style="float:left;width:380px;">
									<p class="column_label">電話番号</p>
									<p class="colon">：</p>
									<div class="edit_value_<?php echo $categoryId; ?> clearfix">
				                    	<input type="text" class="stuff_tel" name="" value="" maxlength="" />
				                    </div>
								</div>
								<div style="float:left;width:380px;">
									<p class="column_label">FAX番号</p>
									<p class="colon">：</p>
									<div class="edit_value_<?php echo $categoryId; ?> clearfix">
				                    	<input type="text" class="stuff_fax" name="" value="" maxlength="" />
				                    </div>
				                </div>
							</div>

							<div class="clearfix">
								<p class="column_label">メールアドレス</p>
								<p class="colon">：</p>
								<div class="edit_value_<?php echo $categoryId; ?> clearfix">
			                    	<input type="text" class="stuff_mail" name="" value="" maxlength="" />
			                    </div>
							</div>
							
							<div class="clearfix" style="margin-bottom:5px">
								<p class="column_label">メモ</p>
								<p class="colon">：</p>
								<p class="value display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($each['stuff_mail']); ?></p>
								<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
			                    	<input type="text" name="<?php echo $this->escape($each['id']); ?>_stuff_mail" value="<?php echo $this->escape($each['stuff_mail']); ?>" maxlength="" />
			                    </div>
							</div>
						</div>
					</div>
                </td>
                <td class="added_row td_action">
                	<div class="delete_btn_frame edit_value_<?php echo $categoryId; ?>" style="display:none;">
                		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row=""><i class="icon-cancel"></i></a>
                	</div>
                    <div class="order_btn_frame edit_value_<?php echo $categoryId; ?>">
                        <i class="icon-up-dir-1"></i>
                        <i class="icon-down-dir-1"></i>
                    </div>
                </td>
                
            </tr>
        </table>
        			
</div><!-- clearfix -->	                
</div>
</div>
</div>
</div>

