<?php
$productNameTypeList      = Shared_Model_Code::codes('product_name_type');
$productMarketList        = Shared_Model_Code::codes('product_market');
$productSalesStatusList   = Shared_Model_Code::codes('product_sales_status');
$supplyMethodList         = Shared_Model_Code::codes('supply_method');
$productionProcessList    = Shared_Model_Code::codes('production_process');
$strategyList             = Shared_Model_Code::codes('strategy');
?>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){
    });

	$(document).on('change', '#category_id', function () {
	    $('div.category_sub').html('');
	    $('div.category_third').html('');
	    $('div.category_fourth').html('');
	    showSpinner();
    	$.ajax({
            type:'GET',
            dataType:'html',
            data:null,
            success:function(res){
            	stopSpinner();

                $('.category_sub').html(res);
                return;
            },
            error:function(){
            	stopSpinner();
            	$.alert({
				    title:'',
				    content:'予期せぬエラーが発生しました',
				    buttons:{confirm: {text:'OK',btnClass:'btn-blue'}},
				});
            },
            url:'/product/load-sub-category?category_id=' + $(this).val(),
		});
    });
    
    $(document).on('change', '#sub_category_id', function () {
	    $('div.category_third').html('');
	    $('div.category_fourth').html('');
	    showSpinner();
    	$.ajax({
            type:'GET',
            dataType:'html',
            data:null,
            success:function(res){
            	stopSpinner();

                $('.category_third').html(res);
                return;
            },
            error:function(){
            	stopSpinner();
                $.alert({
				    title:'',
				    content:'予期せぬエラーが発生しました',
				    buttons:{confirm: {text:'OK',btnClass: 'btn-blue'}},
				});
            },
            url:'/product/load-third-category?sub_category_id=' + $(this).val(),
		});
    });

    $(document).on('change', '#third_category_id', function () {
	    $('div.category_fourth').html('');
	    showSpinner();
    	$.ajax({
            type:'GET',
            dataType:'html',
            data:null,
            success:function(res){
            	stopSpinner();

                $('.category_fourth').html(res);
                return;
            },
            error:function(){
            	stopSpinner();
                $.alert({
				    title:'',
				    content:'予期せぬエラーが発生しました',
				    buttons:{confirm: {text:'OK',btnClass: 'btn-blue'}},
				});
            },
            url:'/product/load-fourth-category?third_category_id=' + $(this).val(),
		});
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = '/product/gs-basic?id=<?php echo $this->escape($this->id); ?>&direct=<?php echo $this->escape($this->direct); ?>';
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
	                        reloadFlag = true;                         
                            jAlert('登録しました', '　');
                    		return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/product/gs-item-add-post?id=<?php echo $this->escape($this->id); ?>',
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
           location.href = '/product/gs-basic?id=<?php echo $this->escape($this->id); ?>&direct=<?php echo $this->escape($this->direct); ?>';
        }
    });


	// 連携方法
    $('#connect_method').change(function() {
		if ($(this).val() == '1') {
			$('.row_create').hide();
			$('.row_connect').show();
		} else {
			$('.row_create').show();
			$('.row_connect').hide();
		}
    }); 
});
--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;margin-right:12px;}
.multi_rows_padding {padding:5px 0 5px 10px}
.product_name {background-color:#ed8c14;color:#fff;padding:3px 0.2em 1px 0.2em}
.import_name {background-color:#008cff;color:#fff;padding:3px 0.2em 1px 0.2em}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}

.column_value select {width:98%;}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>商品管理 - 新規登録</strong></span>
        </div>
    </div>
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
                    <p class="label_text strong">基本情報</p>
                </th>
            </tr>
		</table>     	
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">連携方法<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<select class="short" id="connect_method" name="connect_method">
						<option value="1">goosa商品管理番号を入力</option>
						<option value="2">新規作成</option>
                	</select>
                </td>
            </tr>


            <tr class="row_create" style="display:none;">
                <td class="column_label"><p class="label_text">goosa内カテゴリ<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<div class="clearfix" style="padding-bottom:10px;">
						<div style="float:left;width:200px">
							<p class="category_label">メインカテゴリ：<span class="require">&nbsp;＊</span></p>
	                        <select id="category_id" name="category_id" class="category">
		                        <option value="">---</option>
			                    <?php foreach ($this->mainCategoryList as $each) { ?>
				                    <optgroup label="<?php echo $this->escape($each['name']); ?>">
				                    	<?php foreach ($each['items'] as $eachCategory) { ?>
				                        	<option value="<?php echo $this->escape($eachCategory['id']); ?>"><?php echo $this->escape($eachCategory['category_name']); ?></option>
				                        <?php } ?>
				                    </optgroup>
			                    <?php } ?>
	                        </select>
						</div>
						<div style="float:left;width:200px">
							<p class="category_label">サブカテゴリ：</p>
							<div class="category_sub">
								<p>&nbsp;</p>
							</div>
						</div>
						<div style="float:left;width:200px">
							<p class="category_label">第3カテゴリ：</p>
							<div class="category_third">
								<p>&nbsp;</p>
							</div>
						</div>
						
						<div style="float:left;width:200px">
							<p class="category_label">第4カテゴリ：</p>
							<div class="category_fourth">
								<p>&nbsp;</p>
							</div>
						</div>
					</div>
                </td>
            </tr>
                        
            <tr class="row_create" style="display:none;">
                <td class="column_label"><p class="label_text">商品名<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="" maxlength="" />
                </td>
            </tr>
            
            <tr class="row_create" style="display:none;">
                <td class="column_label"><p class="label_text">商品名（ふりがな）</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name_en" value="" maxlength="" />
                </td>
            </tr>


            <tr class="row_connect">
                <td class="column_label"><p class="label_text">goosa商品管理番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="short" name="gs_display_id" value="" maxlength="" />
                </td>
            </tr>
		</table>
		
	</div><!-- clearfix -->	
    </form>
                
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;"><div class="menu_frame"><div id="data_area"></div></div></div>
</div>
</div>
</div>


