<?php
$productMarketList        = Shared_Model_Code::codes('product_market');
$productSalesStatusList   = Shared_Model_Code::codes('product_sales_status');
$supplyMethodList         = Shared_Model_Code::codes('supply_method');
$productionProcessList    = Shared_Model_Code::codes('production_process');
?>
<style type="text/css">
.product_name {background-color:#ed8c14;color:#fff;padding:3px 0.2em 1px 0.2em}
.import_name {background-color:#008cff;color:#fff;padding:3px 0.2em 1px 0.2em}
</style>

<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong>商品管理</strong></span>
    </div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<div class="condition_items clearfix">
		<form id="product_condition_form" action="javascript:$('#search_product').click();" method="get">
			<p class="search_condition_title">検索条件</p>
			
			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">商品区分：</p>
                    <select id="product_category" name="product_category">
                        <option value="">---</option>
                    	<?php foreach ($this->productCategoryList as $each) { ?>
                            <option value="<?php echo $this->escape($each['id']); ?>" <?php if ($each['id'] == $this->conditions['product_category']) echo 'selected="selected"';?>><?php echo $this->escape($each['name']); ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">販売状況：</p>
                    <select id="product_sales_status" name="product_sales_status">
                        <option value="">---</option>
                    	<?php foreach ($productSalesStatusList as $key => $value) { ?>
                            <option value="<?php echo $this->escape($key); ?>" <?php if ($key == $this->conditions['product_sales_status']) echo 'selected="selected"';?>><?php echo $this->escape($value); ?></option>
                        <?php } ?>
                    </select>
				</div>
				
				<div class="condition_item">
					<p class="condition_label">販売可能範囲：</p>
                    <select id="product_market" name="product_market">
                        <option value="">---</option>
                    	<?php foreach ($productMarketList as $key => $value) { ?>
                            <option value="<?php echo $this->escape($key); ?>" <?php if ($key == $this->conditions['product_market']) echo 'selected="selected"';?>><?php echo $this->escape($value); ?></option>
                        <?php } ?>
                    </select>
				</div>
			</div>
			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">キーワード：<span class="popup_help" id="help_keyword">&nbsp;<i class="icon-help-circled"></i></span></p>
					<input type="text" name="keyword" value="<?php echo $this->escape($this->conditions['keyword']); ?>" />
				</div>
			</div>
			
			<div style="text-align:center">
				<input type="submit" id="search_product" style="display:inline-block;width:150px;" value="検索">
			</div>
		
		</form>
	</div>
</div>	

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:9%;"><p>商品ID</p></th>
			<th style="width:15%;"><p>調達製造区分<i class="icon-info-circle"></i></p></th>
			<th style="width:18%;"><p>商品区分<i class="icon-info-circle"></i></p></th>
			<th style="width:11%;"><p>販売状況</p></th>
			<th><p>商品名<i class="icon-info-circle"></i></p></th>
			<th style="width:8%;"><p>選択</p></th>
		</tr>
		
		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>

				<tr id="<?php echo $each['id']; ?>" <?php if ($each['product_sales_status'] == Shared_Model_Code::PRODUCT_SALES_STATUS_FINISHED) { echo 'class="deleted"'; } ?>>
					<td>
						<p><?php echo $this->escape($each['display_id']); ?></p>
					</td>

                	<?php
                		$selected = array();
                		$productClasses = unserialize($each['product_classes']);
                		if (!empty($productClasses)) {
                			foreach ($this->productClassList as $eachItem) {
		                		foreach($productClasses as $eachSelected) {
		                			if ($eachSelected === (string)$eachItem['id']) {
					                	$selected[] .= $eachItem['name'];
				                	}
		                		}
	                		}
	                		foreach($productClasses as $eachSelected) {
		                		if ($eachSelected == Shared_Model_Code::PRODUCT_CLASS_OTHER) {
			                		$selected[] .= Shared_Model_Code::PRODUCT_CLASS_OTHER_TITLE . '　（' . $each['product_class_other_text'] . '）';
			                	}
		                	}
     	
	                	}
                	?>
					<td class="desc" all-content="<?php echo $this->escape(implode(' / ', $selected)); ?>">
						<p><?php echo $this->escape($this->roundText(implode(' / ', $selected), 15)); ?></p>
					</td>

                	<?php
                		$selected = array();
                		$productCategories = unserialize($each['product_categories']);
                		if (!empty($productCategories)) {
                			foreach ($this->productCategoryList as $eachItem) {
		                		foreach($productCategories as $eachSelected) {
		                			if ($eachSelected === (string)$eachItem['id']) {
					                	$selected[] .= $eachItem['name'];
				                	}
		                		}
	                		}
	                		foreach($productCategories as $eachSelected) {
		                		if ($eachSelected == Shared_Model_Code::PRODUCT_CATEGORY_OTHER) {
			                		$selected[] .= Shared_Model_Code::PRODUCT_CATEGORY_OTHER_TITLE . '　（' . $each['product_category_other_text'] . '）';
			                	}
		                	}
     	
	                	}
                	?>
					<td class="desc" all-content="<?php echo $this->escape(implode(' / ', $selected)); ?>">
						<p><?php echo $this->escape($this->roundText(implode(' / ', $selected), 15)); ?></p>
					</td>
					
					<td>
						<?php if ($each['product_sales_status'] === (string)Shared_Model_Code::PRODUCT_SALES_STATUS_PREPARE) { ?>
							<p class="red"><strong><?php echo $productSalesStatusList[$each['product_sales_status']] ?></strong></p>
						<?php } else if ($each['product_sales_status'] === (string)Shared_Model_Code::PRODUCT_SALES_STATUS_ON_SALE) { ?>
							<p class="status_active"><?php echo $productSalesStatusList[$each['product_sales_status']] ?></p>
						<?php } else { ?>
							<p><?php echo $productSalesStatusList[$each['product_sales_status']] ?></p>
						<?php } ?>
					</td>

					<?php 
					$allName = '';
					if (!empty($each['item_name'])) {
						$allName .= "<span class='product_name'>商品名</span>&nbsp;" . str_replace("'", '&quot;', $this->escape($each['item_name'])) . '<br />';
					}
					
					if (!empty($each['buying_item_name'])) {
						$allName .= "<span class='import_name'>仕入名</span>&nbsp;" . str_replace("'", '&quot;', $this->escape($each['buying_item_name'])) . '<br />';
					}
					?>
					<td class="desc" all-content="<?php echo $allName; ?>">
						<div class="multi_rows_padding">
							<?php if (!empty($each['item_name'])) { ?>
							<span class="product_name">商品名</span>&nbsp;<?php echo $this->escape($this->roundText($each['item_name'], 32)); ?><br />
							<?php } ?>
							<?php if (!empty($each['buying_item_name'])) { ?>
							<span class="import_name">仕入名</span>&nbsp;<?php echo $this->escape($this->roundText($each['buying_item_name'], 32)); ?><br />
							<?php } ?>
						</div>
					</td>
					
					<td>
						<a class="option" href="javascript:selectProduct('<?php echo $each['id']; ?>', '<?php echo $this->escape($each['display_id']); ?>', '<?php echo $this->escape($each['item_name']); ?>', '<?php echo $this->escape($each['buying_item_name']); ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="7">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding: 2.0em 0 5.0em;">
    <?php echo $this->pager() ?>
    </div>
            
</div>

