<?php
$projectList = Shared_Model_Code::codes('rakuten_project');
?>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){

    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/rakuten";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/rakuten/add-post'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/rakuten';
        }
    });
   
});
--></script>
<style type="text/css"><!--
.main_menu h1 a img {display:none;}
table.list_default tr th {background-color:#444;color:#fff;border-right:none;}
table.list_default tr td {background-color:#000;color:#fff;border-right:none;}
table.list_default tr th p, table.list_default tr td p, table.list_default tr td a {padding-left:10px;color:#fff;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
div.main_menu {background-color:#444;}
body {background-color:#000;}
div#page_fotter{background-color:#000}
div.page_title span{color:#fff}
body input[type="text"],
body input[type="password"],
body textarea {border:1px solid #ccc;background-color:#111;color:#fff;}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>楽天商品ページ登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th>
                    <p class="label_text strong">管理情報</p>
                </th>
            </tr>
		</table>
         
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">プロジェクト<span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<select id="customer_id" name="customer_id" style="width:280px;margin-left:0px;margin-top:5px;display:block;float:left;margin-right:10px;">
                    	<option value="">---</option>
                    	<?php foreach ($projectList as $key => $val) { ?>
                            <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
                                
            <tr>
                <td class="column_label"><p class="label_text">タイトル</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="title" value="" maxlength="" />
                </td>
            </tr>
            
		</table>

	</div><!-- clearfix -->	
    </form>
                
</div>
</div>
</div>
</div>

