<?php

?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){

    });
});    
</script>
<style type="text/css"><!--
.main_menu h1 a img {display:none;}
.main_category {display:none;}
table p {font-size: 14px;}
table.list_default tr td.column_value {border-bottom:none;}
table.list_default tr th {background-color: #444;color:#fff;}
table.list_default tr th p, table.list_default tr td p, table.list_default tr td a {padding-left:10px;color:#fff;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
div.main_menu {background-color:#444;}
body {background-color:#000;}
div#page_fotter{background-color:#000}
div.page_title span{color:#fff}
body input[type="text"],
body input[type="password"],
body textarea {border:1px solid #ccc;background-color:#111;}
--></style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:76px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/rakuten/add">新規登録</a>
            </p>
	        <span style=""><strong>楽天商品ページ</strong></span>
	    </div>
	</div>

<!--
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form action="#" method="get">
				<p class="search_condition_title">検索条件</p>
				
				<div class="condition_items_row clearfix">		
					<div class="condition_item">
						<p class="condition_label">キーワード：</p>
						<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
					</div>

					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="user_id_in_charge" name="status">
                            <option value="">---</option>
                        	<?php foreach ($statusList as $key => $value) { ?>
                                <option value="<?php echo $eachUser['id']; ?>" <?php if ($key == $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">在庫状況：</p>
                        <select id="user_id_in_charge" name="stock_status">
                            <option value="">---</option>
                        	<?php foreach ($stockStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ($key == $this->conditions['stock_status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
				</div>
				
				<input type="submit" value="検索" />
			
			</form>
		</div>
	</div>
-->

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:10%;">
					<p>ID</p>
				</th>
				
				<th>
					<p>タイトル</p>
				</th>
				
				<th style="width:12%;">
					<p>PC用商品説明文</p>
				</th>				
				
				<th style="width:12%;">
					<p style="text-align:center;padding-left:0">SP用商品説明文</p>
				</th>
				
				<th style="width:12%;">
					<p style="text-align:center;padding-left:0">PC用販売説明文</p>
				</th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>">
						<td>
							<p><?php echo $this->escape($each['id']); ?></p>
						</td>

						<td>
							<p><?php echo $this->escape($each['title']); ?></p>
						</td>

						<td>
							<p>
								<a href="/rakuten/detail?id=<?php echo $each['id']; ?>&type=pc_product_text">編集</a>
							</p>
						</td>

						<td>
							<p>
								<a href="/rakuten/detail?id=<?php echo $each['id']; ?>&type=sp_product_text">編集</a>
							</p>
						</td>
						
						<td>
							<p>
								<a href="/rakuten/detail?id=<?php echo $each['id']; ?>&type=pc_sales_text">編集</a>
							</p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="7">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

