<?php
$yearList          = Shared_Model_Code::getYearListFromRelease();
$monthList         = Shared_Model_Code::getMonthList();
$statusList        = Shared_Model_Code::codes('payable_payment_status_search');
$payingMethodList  = Shared_Model_Code::codes('payable_paying_method_all');
$paymentStatusList = Shared_Model_Code::codes('receivable_payment_status');
?>
<script type="text/javascript">

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

var referenceTargetRow = '';

$(function () {
	$(document).ready(function(){

	});
});
  
</script>
<style type="text/css">
table.list_default tr th, table.list_default tr td {border-bottom:1px solid #ccc;}
table.list_default tr th p, table.list_default tr td p {padding-left:5px;}
table.list_default tr th {background-color:#d6f3ff}
table.list_default tr th.bg_gray {background-color:#555;color:#fff;font-size:1.2em;}
table.list_default tr th p.align_right, table.list_default tr td p.align_right {text-align:right;padding-left:0;padding-right:5px;}
table.list_default tr th p.align_center, table.list_default tr td p.align_center {text-align:center;padding-left:0;}

h2 {text-align:left;margin:0;padding-left:12px;margin-bottom:0.3em;color:#004bd6}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
<?php
	$groupTable      = new Shared_Model_Data_AccountTotalingGroup();
	$payableTable    = new Shared_Model_Data_AccountPayable();
	$receivableTable = new Shared_Model_Data_AccountReceivable();

	//var_dump($this->sumType);
	//var_dump($this->from);
	//var_dump($this->to);
		
	$groupData = $groupTable->getById($this->adminProperty['management_group_id'], $this->rowData['content']);
	
	// receivable
	$selectObj = $receivableTable->select();
	$selectObj->joinLeft('frs_connection', 'frs_account_receivable.target_connection_id = frs_connection.id', array($receivableTable->aesdecrypt('company_name', false) . 'AS company_name'));
	$selectObj->joinLeft('frs_user', 'frs_account_receivable.created_user_id = frs_user.id',array($receivableTable->aesdecrypt('user_name', false) . 'AS user_name'));
	$selectObj->joinLeft('frs_invoice', 'frs_account_receivable.invoice_id = frs_invoice.id', array('display_id AS invoice_display_id'));
	$selectObj->where('frs_account_receivable.management_group_id = ?', $this->adminProperty['management_group_id']);
	$selectObj->where('frs_account_receivable.account_totaling_group_id = ?', $groupData['id']);
	
	
	if ($this->sumType === 'settlement') {
    	if (!empty($this->from)) {
	    	$selectObj->where('frs_account_receivable.receive_plan_date >= ?', $this->from);
    	}

    	if (!empty($this->to)) {
	    	$selectObj->where('frs_account_receivable.receive_plan_date <= ?', $this->to);
    	}
	} else {
    	if (!empty($this->from)) {
	    	$selectObj->where('frs_account_receivable.accrual_date >= ?', $this->from);
    	}

    	if (!empty($this->to)) {
	    	$selectObj->where('frs_account_receivable.accrual_date <= ?', $this->to);
    	}
	}

	$selectObj->order('frs_account_receivable.receive_plan_date ASC');
	$selectObj->order('frs_account_receivable.id ASC');
	$receivableItems = $selectObj->query()->fetchAll();

	// payable
    $selectObj = $payableTable->select();
    $selectObj->joinLeft('frs_connection', 'frs_account_payable.target_connection_id = frs_connection.id', array($payableTable->aesdecrypt('company_name', false) . 'AS company_name'));
    $selectObj->joinLeft('frs_user', 'frs_account_payable.created_user_id = frs_user.id',array($payableTable->aesdecrypt('user_name', false) . 'AS user_name'));
	$selectObj->where('frs_account_payable.status = ' . Shared_Model_Code::PAYABLE_STATUS_APPROVED
		        . ' OR frs_account_payable.status = ' . Shared_Model_Code::PAYABLE_STATUS_ADDED_FROM_HISTORY);

	$selectObj->where('frs_account_payable.payment_status != ' . Shared_Model_Code::PAYABLE_PAYMENT_STATUS_PENDDING
	           . ' AND frs_account_payable.payment_status != ' . Shared_Model_Code::PAYABLE_PAYMENT_STATUS_CANCELED);
    	            
	$selectObj->where('frs_account_payable.account_totaling_group_id = ?', $groupData['id']);

								
	if ($this->sumType === 'settlement') {
    	if (!empty($this->from)) {
	    	$selectObj->where('frs_account_payable.paying_plan_date >= ?', $this->from);
    	}

    	if (!empty($this->to)) {
	    	$selectObj->where('frs_account_payable.paying_plan_date <= ?', $this->to);
    	}
	} else {
    	if (!empty($this->from)) {
	    	$selectObj->where('frs_account_payable.purchased_date >= ?', $this->from);
    	}

    	if (!empty($this->to)) {
	    	$selectObj->where('frs_account_payable.purchased_date <= ?', $this->to);
    	}
	}

	$selectObj->order('frs_account_payable.paying_plan_date ASC');
	$selectObj->order('frs_account_payable.id ASC');
	
	$payableItems = $selectObj->query()->fetchAll();
	
	
	
	
	//$payableItems = $payableTable->getItemsWithTotalingGroupId($this->adminProperty['management_group_id'], $groupData['id']);
	/*
	if (!empty($payableItems)) {
		foreach ($payableItems as $eachPayable) {
			$total += (int)$eachPayable['total_amount'];
		}
	}
	
	
	$receivableItems = $receivableTable->getItemsWithTotalingGroupId($this->adminProperty['management_group_id'], $groupData['id']);
	if (!empty($receivableItems)) {
		foreach ($receivableItems as $eachReceivable) {
			$total += (int)$eachReceivable['total_amount'];
		}
	}
	*/
	
?>





	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <span><strong>採算 - <?php echo $this->escape($this->categoryData['category_name']); ?> - <?php echo $this->escape($groupData['title']); ?> 明細</strong></span>
	    </div>
	</div>
    
	<div class="col-sm-12 clearfix">
		<form id="register_form" action="#" method="post">
			
			<?php
				$total = 0;
			?>
							
			<h2>収入の部</h2>			
			<table class="list_default">
				<tr>
					<th style="width:9%;"><p>発生日</p></th>
					<th style="width:9%;"><p>入金予定日</p></th>
					<th style="width:8%;"><p>ステータス</p></th>
					
					<th style="width:3.5%;"><p class="align_center">毎月</p></th>
					<th style="width:7%;"><p>会計科目&nbsp;<i class="icon-info-circle"></i></p></th>
					<th style="width:9%;"><p>摘要&nbsp;<i class="icon-info-circle"></i></p></th>
					<th style="width:7%;"><p>採算コ&nbsp;<i class="icon-info-circle"></i></p></th>
					<th style="width:6%;"><p class="align_center">通貨単位</p></th>
					<th style="width:9%;"><p>金額</p></th>
					<th><p>支払元&nbsp;<i class="icon-info-circle"></i></p></th>
					<th style="width:9%;"><p>対象請求書ID</p></th>
					<th style="width:7%;"><p>登録者&nbsp;<i class="icon-info-circle"></i></p></th>
					<th style="width:5%;"><p class="align_center">詳細</p></th>
				</tr>
					
				<?php if (!empty($receivableItems)) { ?>
					<?php foreach ($receivableItems as $each) { ?>
						<?php
							$grayOut = '';
							if ($each['payment_status'] === (string)Shared_Model_Code::RECEIVABLE_PAYMENT_STATUS_CANCELED) {
								$grayOut = 'class="gray_out"';
							}
						?>
						<tr <?php echo $grayOut; ?>>
							<td>
								<p><?php
									if (!empty($each['accrual_date'])) {
										echo date('Y-m-d', strtotime($each['accrual_date']));
									} else {
										echo '---';
									}
								 ?></p>
							</td>
							
							<td>
								<p><?php echo date('Y-m-d', strtotime($each['receive_plan_date'])); ?></p>
							</td>
							
							<td>
								<?php if ($each['payment_status'] === (string)Shared_Model_Code::RECEIVABLE_PAYMENT_STATUS_RECEIVED) { ?>
									<p><strong><?php echo $paymentStatusList[$each['payment_status']]; ?></strong></p>
								<?php } else { ?>
									<p><?php echo $paymentStatusList[$each['payment_status']]; ?></p>
								<?php } ?>
							</td>
	
							<td>
								<p class="align_center"><?php if ($each['type'] === (string)Shared_Model_Code::RECEIVABLE_TYPE_MONTHLY) { echo '●'; } ?></p>
							</td>
							
							<td class="desc" all-content="<?php echo $this->escape($this->accountTitleList[$each['account_title_id']]['title']); ?>">
								<p style="padding-left:5px"><?php echo $this->roundText($this->escape($this->accountTitleList[$each['account_title_id']]['title']), 4); ?></p>
							</td>
	
							<td class="desc" all-content="<?php echo $this->escape($each['memo']); ?>">
								<p style="padding-left:5px"><?php echo $this->roundText($this->escape($each['memo']), 6); ?></p>
							</td>
							
							
							<?php
							$groupTitle = '---';
							if (array_key_exists($each['account_totaling_group_id'], $this->groupList)) {
								$groupTitle = $this->groupList[$each['account_totaling_group_id']];
							}
							?>
							<td class="desc" all-content="<?php echo $this->escape($groupTitle); ?>">
								<p style="padding-left:5px"><?php echo $this->escape($this->roundText($groupTitle, 4)); ?></p>
							</td>
							
							<td>
								<p class="align_center"><?php if (!empty($each['currency_id'])) { echo $this->escape($this->currencyList[$each['currency_id']]['name']); } ?></p>
							</td>
							
							<td>
								<?php
									$totaltext = '';
									if (!empty($each['total_amount'])) {
										$totaltext = $this->escape(number_format($each['total_amount']));
									}	
								?>
								<p class="align_right"><?php echo $totaltext; ?></p>
							</td>
	
							<td class="desc" all-content="<?php echo $this->escape($each['company_name']); ?>">
								<p><?php echo $this->roundText($this->escape($each['company_name']), 7); ?></p>
							</td>
							
							<td>
								<p><?php echo $this->escape($each['invoice_display_id']); ?></p>
							</td>
	
							<td class="desc" all-content="<?php echo $this->escape($each['user_name']); ?>">
								<p><?php echo $this->roundText($this->escape($each['user_name']), 5); ?></p>
							</td>
	
							<td>
								<p class="align_center"><a href="/transaction-recieved/detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
							</td>
						</tr>
					<?php } ?>
				<?php } else { ?>
					<tr>
						<td colspan="13">
							<p style="text-align:center;">データがありません</p>
						</td>
					</tr>
				<?php } ?>
			</table>
			
			<h2>支出の部</h2>
			
			<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
				<table class="list_default">
					<tr>
						<th style="width:9%;"><p>発生日</p></th>
						<th style="width:9%;"><p>支払予定日</p></th>
						<th style="width:10%;"><p>ステータス</p></th>
						<th style="width:4.5%;"><p class="align_center">毎月</p></th>
		
						<th style="width:7%;"><p>会計科目&nbsp;<i class="icon-info-circle"></i></p></th>
						<th style="width:10%;"><p>摘要&nbsp;<i class="icon-info-circle"></i></p></th>
						<th style="width:10%;"><p>採算コ&nbsp;<i class="icon-info-circle"></i></p></th>
						
						<th style="width:6%;"><p class="align_center">通貨単位</p></th>	
						<th style="width:10%;"><p>金額</p></th>
						<th><p>支払先&nbsp;<i class="icon-info-circle"></i></p></th>
						<th style="width:7%;"><p>登録者&nbsp;<i class="icon-info-circle"></i></p></th>
						<th style="width:5%;"><p class="align_center">詳細</p></th>
					</tr>
		
					<?php if (!empty($payableItems)) { ?>
						<?php foreach ($payableItems as $each) { ?>
							<?php
								$grayOut = '';
								if ($each['payment_status'] === (string)Shared_Model_Code::PAYABLE_PAYMENT_STATUS_CANCELED) {
									$grayOut = 'class="gray_out"';
								}
							?>
							<tr id="<?php echo $each['id']; ?>" <?php echo $grayOut; ?>>
								<td>
									<p><?php
										if (!empty($each['purchased_date'])) {
											echo date('Y-m-d', strtotime($each['purchased_date']));
										} else {
											echo '---';
										}
									 ?></p>
								</td>
						
								<td>
									<p><?php if (!empty($each['paying_plan_date'])) { echo date('Y-m-d', strtotime($each['paying_plan_date'])); } else { echo '---'; } ?></p>
								</td>
		
								<td>
									<?php if ($each['payment_status'] == (string)Shared_Model_Code::PAYABLE_PAYMENT_STATUS_PAID) { ?>
										<p><strong><?php echo $statusList[$each['payment_status']]; ?></strong></p>
									<?php } else { ?>
										<p><?php echo $statusList[$each['payment_status']]; ?></p>
									<?php } ?>
								</td>
		
								<td>
									<p class="align_center"><?php if (!empty($each['template_id'])) { echo '●'; } ?></p>
								</td>
								
								<td class="desc" all-content="<?php echo $this->escape($this->accountTitleList[$each['account_title_id']]['title']); ?>">
									<p style="padding-left:5px"><?php echo $this->roundText($this->escape($this->accountTitleList[$each['account_title_id']]['title']), 4); ?></p>
								</td>
		
								<td class="desc" all-content="<?php echo $this->escape($each['memo']); ?>">
									<p style="padding-left:5px"><?php echo $this->roundText($this->escape($each['memo']), 6); ?></p>
								</td>
		
								<?php
								$groupTitle = '---';
								if (array_key_exists($each['account_totaling_group_id'], $this->groupList)) {
									$groupTitle = $this->groupList[$each['account_totaling_group_id']];
								}
								?>
								<td class="desc" all-content="<?php echo $this->escape($groupTitle); ?>">
									<p style="padding-left:5px"><?php echo $this->escape($this->roundText($groupTitle, 7)); ?></p>
								</td>
		
								<td>
									<p class="align_center"><?php if (!empty($each['currency_id'])) { echo $this->escape($this->currencyList[$each['currency_id']]['name']); } ?></p>
								</td>
								
								<td>
									<?php
										$totaltext = '';
										if (!empty($each['total_amount'])) {
											$totaltext = $this->escape(number_format($each['total_amount']));
										}	
									?>
									<p class="align_right"><?php echo $totaltext; ?></p>
								</td>
		
								<td class="desc" all-content="<?php echo $this->escape($each['company_name']); ?>">
									<p><?php echo $this->roundText($this->escape($each['company_name']), 10); ?></p>
								</td>
		
								<td class="desc" all-content="<?php echo $this->escape($each['user_name']); ?>">
									<p><?php echo $this->roundText($this->escape($each['user_name']), 5); ?></p>
								</td>
								
								<td>
									<p class="align_center"><a href="/transaction-paid/invoice-detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
								</td>
							</tr>
						<?php } ?>
					<?php } else { ?>
						<tr>
							<td colspan="12">
								<p style="text-align:center;">データがありません</p>
							</td>
						</tr>
					<?php } ?>
				</table>
			</div>
		</form>

	</div>


</div>
</div>
</div>
</div>


