<?php
?>
<script type="text/javascript">
$(function () {
	$(document).ready(function(){
	    $('#sortable_column td').each(function(){
            $(this).css('width', $(this).width() +'px');
        });
        
        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	$(document).on('click', '.edit_content_order', function () {
        $('.display_value').hide();
        $('.edit_value').show();
    
        // ×,保存ボタン
        $(this).removeClass('edit_content_order').addClass('save_content_order');
        $(this).html('並び順保存');

        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	
	$(document).on('click', '.save_content_order', function () {
        var button = $(this);
        var $form = $('#register_form');
        var params = $form.serializeArray();
		
		var apiUrl = '';

        $.ajax({
            type:'POST',
            dataType:'json',
            data: params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url: '/financial-totaling/category-update-order',
        });
	});

    $(document).on('click', '#popup_ok', function () {
        location.href = '/financial-totaling/category-list?category_id=1<?php echo $this->escape($this->id); ?>&pos=' + $(window).scrollTop();
    });
    
    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });
});    
</script>
<style type="text/css">
table.list_default tr:hover td {background:#deeeff;}
a.edit_item {display:block;background-color:#64bd63;color:#fff;padding:2px 3px;text-decoration:none;border-radius:5px;width:80px;text-align:center;margin:3px 0 0 3px;float:left;cursor:pointer;}
a.layout_item {display:block;background-color:#ffbe00;color:#fff;padding:2px 3px;text-decoration:none;border-radius:5px;width:100px;text-align:center;margin:3px 0 0 0.6em;float:left;cursor:pointer;}
.multi_rows_padding {padding:5px 10px 5px 10px;}
.order_btn_frame {float:left;margin:6px 0 0 14px;}
.order_btn_frame .icon-up-dir-1 {font-size:14px;color:#000;line-height:1;display:block;}
.order_btn_frame .icon-down-dir-1 {font-size:14px;margin-top:-6px;color:#000;line-height:1;display:block;}
a.btn_setting.save_content_order {background-color:#64bd63}
.sortable_column tr td {background-color:#fff;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
		    <?php if (!empty($this->adminProperty['allow_editing_accounting_title'])) { ?>
			<p style="position:absolute;width:230px;right:0;">
				<a class="btn_setting edit_content_order" style="display:block;float:left;width:92px;padding:5px 0;margin:0;border:none;margin-right:5px" href="javascript:void(0);">並び順変更</a>
                <a class="btn_setting" style="display:block;float:left;width:132px;padding:5px 0;margin:0;border:none;" href="/financial-totaling/category-edit">新規採算グループ登録</a>
            </p>
            <?php } ?>
	        <span style=""><strong>採算管理 - 設定</strong></span>
	    </div>
	</div>
    
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<form id="register_form" action="#" method="post"> 
		<table class="list_default">
			<tr>
				<th>
					<p>採算グループ名</p>
				</th>
				
				<?php if (!empty($this->adminProperty['allow_editing_accounting_title'])) { ?>
					<th style="width:11%;">
						<p>レイアウト</p>
					</th>		
				<?php } ?>
				<th style="width:5%;">
					<p>詳細</p>
				</th>
			</tr>
			<tbody class="sortable_column" id="sortable_column">
				<?php if (!empty($this->items)) { ?>
					<?php foreach ($this->items as $each) { ?>
						<tr id="<?php echo $this->escape($each['id']); ?>">
							<td>
								<p><?php echo $this->escape($each['category_name']); ?></p>
							</td>
							
							<?php if (!empty($this->adminProperty['allow_editing_accounting_title'])) { ?>
							<td>
								<a class="layout_item" href="/financial-totaling/category-layout?category_id=<?php echo $this->escape($each['id']); ?>">レイアウト編集</a>
							</td>
							<?php } ?>
							
							<td>
								<div class="display_value">
									<a class="edit_item" href="/financial-totaling/category-detail?category_id=<?php echo $this->escape($each['id']); ?>">詳細</a>
								</div>
								<div class="edit_value">
				                    <div class="order_btn_frame edit_value" style="display:none;">
				                        <i class="icon-up-dir-1"></i>
				                        <i class="icon-down-dir-1"></i>
				                    </div>
								</div>
							</td>
						</tr>
					<?php } ?>
				<?php } else { ?>
					<tr>
						<td colspan="<?php if (!empty($this->adminProperty['allow_editing_accounting_title'])) { ?>3<?php } else { ?>2<?php } ?>">
							<p style="text-align:center;">データがありません</p>
						</td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
		<input type="hidden" id="hidden_contents_order" name="item_list" value="">
		</form>
	</div>

</div>
</div>
</div>
</div>


