<div class="col-xs-12 clearfix" style="margin-bottom:0.3em;">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>

        
       
		<?php if ($this->lock) { ?>
		    <?php $selectedCategoryData = NULL; ?>
	        <?php foreach ($this->categoryList as $each) { ?>
	        	<?php if ($this->categoryId === $each['id']) { ?>
	        		<span><strong>採算コード選択　グループ：<?php echo $this->escape($each['category_name']); ?></strong></span>
				<?php } ?>
			<?php } ?>
        <?php } else { ?>
        	<span style="display:block;float:left;margin-right:0.6em;"><strong>採算コード選択　グループ：</strong></span>
		    <?php $selectedCategoryData = NULL; ?>
	        <select style="display:block;float:left;margin-top:-2px;width:300px;" id="account_totaling_group_category_id" name="account_totaling_group_category_id">
		        <?php foreach ($this->categoryList as $each) { ?>
		        	<option value="<?php echo $this->escape($each['id']); ?>" <?php if ($this->categoryId === $each['id']) { echo 'selected="selected"';$selectedCategoryData = $each; } ?> ><?php echo $this->escape($each['category_name']); ?></option>
				<?php } ?>
	        </select>
	    <?php } ?>

    </div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<form id="register_form" action="#" method="post"> 
	<table class="list_default">
		<tr>
			<th style="width:35%"><p>採算コード名</p></th>
			<th><p>説明</p></th>
			<th style="width:9%;"><p>選択</p></th>
		</tr>
		<tbody class="sortable_column" id="sortable_column">
		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>
				<tr id="<?php echo $this->escape($each['id']); ?>">
					<td>
						<div class="multi_rows_padding"><?php echo $this->escape($each['title']); ?></div>
					</td>
					
					<td>
						<div class="multi_rows_padding"><?php echo nl2br($this->escape($each['memo'])); ?></div>
					</td>
					
					<td>
						<a class="option" href="javascript:selectAccountTotalingGroup('<?php echo $each['id']; ?>', '<?php echo $this->escape($selectedCategoryData['category_name']);?>', '<?php echo $this->escape($each['title']); ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="5">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
	<input type="hidden" id="hidden_contents_order" name="item_list" value="">
	</form>
            
</div>



