<?php
$typeList              = Shared_Model_Code::codes('item_type');
$warehouseItemTypeList = Shared_Model_Code::codes('warehouse_item_type_for_select');
?>
<link rel="stylesheet" type="text/css" href="/resource/js/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css" />
<script type="text/javascript" src="/resource/js/jquery.imgareaselect-0.9.10/scripts/jquery.imgareaselect.pack.js"></script>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){

    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/stock/list/<?php echo $this->escape($this->type); ?>";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/stock/add-post/<?php echo $this->escape($this->type); ?>'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/stock/list/<?php echo $this->escape($this->type); ?>';
        }
    });

    $('#target_type').change(function() {
		if ($(this).val() == '<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM; ?>'
		 || $(this).val() == '<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT; ?>'
		 || $(this).val() == '<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE; ?>') {
			$('#select_target_row').show();
			$('#name_row').hide();
		} else if ($(this).val() == '<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_OTHER; ?>') {
			$('#select_target_row').hide();
			$('#name_row').show();
		} else {
			$('#select_target_row').hide();
			$('#name_row').hide();
		}
    });
    
    // 調達管理 ポップアップ
	$(document).on('click', '#select_reference', function () {
		var targetType = $('#target_type').val();

    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);

		if (targetType == '<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM; ?>') {
			$('#data_area').load('/product/list-select');
			
		} else if (targetType == '<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT; ?>') {
			$('#data_area').load('/supply-product/list-select');
			
		} else if (targetType == '<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE; ?>') {
			$('#data_area').load('/supply-fixture/list-select');
			
		}
		
	});

    // 商品選択 条件検索
    $(document).on('click', '#search_product', function () {
		updateProductList(1);
    });
    
	// 調達管理・原料製品 条件検索
    $(document).on('click', '#search_supply_product', function () {
		updateSupplyProductList(1);
    });

	// 調達管理・備品資材 条件検索
    $(document).on('click', '#search_supply_fixture', function () {
		updateSupplyFixtureList(1);
    });

    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': 0});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// -------------------------------------------------------------------
// 商品一覧ページ切り替え
function pageProduct(pageNo) {
	updateProductList(pageNo)
}
// 商品一覧更新
function updateProductList (pageNo) {
    var $form = $('#product_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/product/list-select?page=' + pageNo,
    });
}
// 商品選択完了
function selectProduct(id, itemId, name, buyingName) {
	$('#reference_title').html('<strong>商品 ' + itemId + '</strong>　' + name);
	$('#reference_target_id').val(id);
	$('.btn_close').click();
}
// -------------------------------------------------------------------
// 調達管理・原料製品 ページ切り替え
function pageSupplyProduct(pageNo) {
	updateSupplyProductList(pageNo)
}
// 調達管理・原料製品 一覧更新
function updateSupplyProductList (pageNo) {
    var $form = $('#supply_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/supply-product/list-select?page=' + pageNo,
    });
}
// 調達管理・原料製品 選択完了
function selectSupplyProduct(id, itemId, name) {
	$('#reference_title').html('<strong>原料製品 ' + itemId + '</strong>　' + name);
	$('#reference_target_id').val(id);
	$('.btn_close').click();
}
// -------------------------------------------------------------------
// 調達管理・備品資材 ページ切り替え
function pageSupplyFixture(pageNo) {
	updateSupplyFixtureList(pageNo)
}
// 調達管理・備品資材 一覧更新
function updateSupplyFixtureList (pageNo) {
    var $form = $('#supply_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/supply-fixture/list-select?page=' + pageNo,
    });
}
// 調達管理・備品資材 選択完了
function selectSupplyFixture(id, itemId, name) {
	$('#reference_title').html('<strong>備品資材 ' + itemId + '</strong>　' + name);
	$('#reference_target_id').val(id);
	$('.btn_close').click();
}

--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:280px;}

#reference_title {float:left;}
a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:right;font-size:12px;margin:1px 3px 0 0;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}


.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1100px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}

.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}
.quote {margin:10px;padding:10px;background-color:#e3f2ff}
table.list_default tr td .quote p {padding:6px 0 8px 12px;height:auto;}

.menu_frame table.list_default tr td.column_value {border-right:none;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:120px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {float:left;width:20px;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding {width:280px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding.long {width:740px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value input[type="text"] {width:240px;display:block;float:left;}
.menu_frame table.list_default tr td textarea{width:620px;height:60px;}
.menu_frame table.list_default tr td.td_action {width:56px;border-right:none;padding-right:5px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
.menu_frame table.list_default .multi_rows_padding {padding:5px 10px 5px 10px;}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>在庫資材管理 - <?php echo $typeList[$this->typeCode]; ?>登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">管理情報</p>
                </th>
            </tr>
		</table>

        <table class="list_default" style="margin-bottom:0;">

            <?php if ((string)$this->typeCode === (string)Shared_Model_Code::ITEM_TYPE_PRODUCT) { ?>
            	<tr>
	            	<td class="column_label"><p class="label_text">引用対象<span class="require">&nbsp;＊</span></p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
		                <p>商品</p>
	                    <input type="hidden" id="target_type" name="target_type" value="<?php echo Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM; ?>">
	                </td>
	            </tr>
            <?php } else { ?>
	            <tr>
	                <td class="column_label"><p class="label_text">引用対象<span class="require">&nbsp;＊</span></p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                    <select id="target_type" name="target_type" style="width:280px;">
		                	<option value="">---</option>
		                	<?php foreach ($warehouseItemTypeList as $key => $value) { ?>
		                		<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
		                	<?php } ?>
		                </select>
	                </td>
	            </tr>
            <?php } ?>
            
            <tr id="select_target_row" style="<?php if ((string)$this->typeCode !== (string)Shared_Model_Code::ITEM_TYPE_PRODUCT) { ?>display:none;<?php } ?>">
                <td class="column_label"><p class="label_text">対象<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="clearfix">
	                	<p id="reference_title">---</p>
	                    <a class="option" id="select_reference">選択</a>
	                    <input type="hidden" id="reference_target_id" name="reference_target_id" value="">
	                </div>
                </td>
            </tr>
            
            <tr id="name_row" style="display:none;">
                <td class="column_label"><p class="label_text">資材名<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <input type="text" name="stock_name" value="">
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">棚卸数量単位</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<select class="short" id="unit_type" name="unit_type">
                            <option value="">---</option>
                            <?php foreach ($this->unitTypeList as $each) { ?>
                                <option value="<?php echo $each['id']; ?>"><?php echo $each['symbol'] . '（' . $this->escape($each['name']) . '）'; ?></option>
                            <?php } ?>
                    	</select>
                    </div>
                </td>
            </tr>
            
		</table>

	</div><!-- clearfix -->	
    </form>
                
            
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;"><div class="menu_frame"><div id="data_area"></div></div></div>
</div>
</div>
</div>


