<?php
$itemTypeList    = Shared_Model_Code::codes('item_type');
$statusList      = Shared_Model_Code::codes('is_active');
$stockStatusList = Shared_Model_Code::codes('stock_status');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
    });
});    
</script>
<style type="text/css">
table.list_default tr td {height:70px;}
table.list_default tr td p {height:auto;line-height:1.6;}
table.list_default tr td p.align_right {text-align:right;padding-right:12px;}
table.list_default tr td .multi_rows_padding {padding:5px 10px 5px 10px;}
.photo_image {padding:5px;width:90%;display:block;margin:0 auto;}
.safety {color:#00a2ff;font-weight: bold;}
.minimum{color:#ff00d2;font-weight: bold;}
.is_safety {color:#00c486;font-weight:bold;}
.is_caution {color:#ffba00;font-weight:bold;}
.is_warning {color:#ff0000;font-weight:bold;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <span><strong>在庫資材管理(全リスト)</strong></span>
	    </div>
	</div>


	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:7%;"><p>管理ID</p></th>
				<th style="width:7%;"><p>種別</p></th>
				<th style="width:5%;"><p>画像</p></th>
				<th style="width:6%;"><p>ステータス</p></th>
				<th><p>在庫資材名</p></th>
				<th style="width:9%;text-align:center;"><p>棚卸単価（円）</p></th>
				<th style="width:14%;"><p style="text-align:center;padding-left:0">最低在庫数 / 安全在庫数</p></th>
				<th style="width:11%;"><p style="text-align:center;padding-left:0">理論在庫数</p></th>
				<th style="width:7%;"><p style="text-align:center;padding-left:0">数量単位</p></th>
				<th style="width:5%;"><p style="text-align:center;padding-left:0">詳細</p></th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $this->escape($each['id']); ?>">
						<td>
							<p><?php echo $this->escape($each['id']); ?></p>
						</td>
						
						<td>
							<div class="multi_rows_padding">
								<?php echo $this->escape($each['stock_type']); ?><br>
								<?php echo $itemTypeList[$each['stock_type']]; ?>
							</div>
						</td>
						
						<td>
							<img class="photo_image" src="<?php echo Shared_Model_Resource_WarehouseItem::getResourceUrl($each['id'], $each['image_key']); ?>">
						</td>
						
						<td>
							<?php if ($each['status'] === (string)Shared_Model_Code::CONTENT_STATUS_ACTIVE) { ?>
								<p class="status_active"><?php echo $statusList[$each['status']]; ?></p>
							<?php } else { ?>
								<p><?php echo $statusList[$each['status']]; ?></p>
							<?php } ?>
						</td>

						<td>
							<?php if ($each['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM) { ?>
								<div class="multi_rows_padding"><?php echo $this->escape($each['item_name']); ?></div>
							<?php } else if ($each['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT) { ?>
								<div class="multi_rows_padding"><?php echo $this->escape($each['supply_product_name']); ?></div>
							<?php } else if ($each['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE) { ?>
								<div class="multi_rows_padding"><?php echo $this->escape($each['supply_fixture_name']); ?></div>
							<?php } else { ?>
								<div class="multi_rows_padding"><?php echo $this->escape($each['stock_name']); ?></div>
							<?php } ?>
						</td>
						
						<td>
			                <p class="align_right">
			                	<?php if ((float)$each['unit_price'] !== (float)0) { echo $this->numberFormat($each['unit_price']); } else { echo '---'; } ?>
		                	</p>
						</td>
						
						<td>
							<p style="text-align:center;padding-left:0">
								<span class="minimum"><?php echo $this->numberFormat($each['minimum_count']); ?></span>
								&nbsp;/&nbsp;
								<span class="safety"><?php echo $this->numberFormat($each['safety_count']); ?></span>
							</p>
						</td>
						
						<td>
							<?php
								$class = 'is_safety';
								if ((int)$each['stock_count'] < (int)$each['minimum_count']) { 
									$class = 'is_warning';
								} else if ((int)$each['stock_count'] < (int)$each['safety_count']) {
									$class = 'is_caution';
								}
							
							?>
						
							<p style="font-size:1.6em;text-align:right;padding-right:12px" class="<?php echo $class; ?>"><?php echo $this->numberFormat($each['stock_count']); ?></p>
						</td>
						
						<td>
							<p style="text-align:center;padding-left:0;"><?php echo $this->unitTypeList[$each['unit_type']]['symbol']; ?></p>
						</td>
						
						<td>
							<p><a href="/stock/basic?id=<?php echo $this->escape($each['id']); ?>">編集</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="8">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

