<?php
//$statusList            = Shared_Model_Code::codes('item_status');
$statusList            = Shared_Model_Code::codes('warehouse_item_status');
$yesNoList             = Shared_Model_Code::codes('yes_no');
$itemTypeCodeList      = Shared_Model_Code::codes('item_type_code');
$itemTypeList          = Shared_Model_Code::codes('item_type');
$warehouseItemTypeList = Shared_Model_Code::codes('warehouse_item_type');
?>
<link rel="stylesheet" type="text/css" href="/resource/js/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css" />
<script type="text/javascript" src="/resource/js/jquery.imgareaselect-0.9.10/scripts/jquery.imgareaselect.pack.js"></script>
<script type="text/javascript">
var reloadFlag  = false;
var deletedFlag = false;

function dragover(e) {
    e.preventDefault();
}
					
function drop(e) {
	<?php if ($this->allowEditing === true) { ?>
		$('#add_image_box').removeClass('over');
		
		e.preventDefault();
		var files = e.dataTransfer.files;
	  
		if (files.length > 1) {
	  		jAlert('画像は一枚ずつドロップしてください。', 'エラー');
	 	 	return;
		}
	
	    // アップロード処理へ
	    fileUpload(files[0]);
    <?php } ?>
}

function fileUpload(fd) {
    var formData = new FormData();
    formData.append('image', fd);

    $.ajax({
      async:true,
      type:'POST',
      contentType:false,
      processData:false,
      url:'/stock/upload-image?id=<?php echo $this->escape($this->data['id']); ?>',
      data:formData,
      dataType:'json'
    }).done(function(res){
        var obj = res;
        if (obj.result == 'timeout') {
            location.href = '/login';
            return;
            
        } else if(obj.result == true) {
        	$('#add_image_box').removeClass('over');
			$('#photo_image').attr({'src':obj.image_url});
        }
    });
}

$(function() {
    $(document).ready(function(){
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->escape($this->posTop); ?>);
        <?php } ?>
        
        Tipped.create('#help_shelf_no', "4文字以下。アルファベットも可能。");
        
        // ファイルのドロップ時エフェクト
		var targetE = document.getElementById('add_image_box');
		var innerFlag = false;
		
		targetE.addEventListener('dragenter', function () {
		    innerFlag = true;
		}, false);
		
		targetE.addEventListener('dragover', function () {
		    innerFlag = false;
		    targetE.className = 'over';
		}, false);
		
		targetE.addEventListener('dragleave', function () {
		    if (innerFlag) {
		        innerFlag = false;
		    } else {
		        targetE.className = '';
		    }
		}, false);
    });

    // 編集
    $(document).on('click', '.btn_edit_category', function () {
        var categoryId = $(this).attr('category_id');
        
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
    
        // ×,保存ボタン
        $('#cancel_category_' + categoryId).show();
        $('th#edit_category_' + categoryId).addClass('edit_mode');
        $(this).removeClass('btn_edit_category').addClass('btn_save_category');
        $('#btn_edit_label_' + categoryId).html('保存');
    });
    
    // 保存
    $(document).on('click', '.btn_save_category', function () {
        var button = $(this);
        var categoryId = $(this).attr('category_id');
        var $form = $('#form_category_' + categoryId);
        var params = $form.serializeArray();
		var apiUrl = '';
		
		if (categoryId == '1') {
			apiUrl = '/stock/update-basic?id=<?php echo $this->escape($this->id); ?>';
		} else if (categoryId == '2') {
			apiUrl = '/stock/update-image?id=<?php echo $this->escape($this->id); ?>';
		} else {
			return;
		}
		
        $.ajax({
            type:'POST',
            dataType:'json',
            data:params,
            success:function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error:function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url:apiUrl,
        });
    });
    
    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
        	if (deletedFlag == true) {
        		location.href = '/stock/list/<?php echo $itemTypeCodeList[$this->data['stock_type']]; ?>&from=<?php echo $this->escape($this->from); ?>';
        	} else {
            	location.href = '/stock/basic?id=<?php echo $this->escape($this->id); ?>&from=<?php echo $this->escape($this->from); ?>&pos=' + $(window).scrollTop();
            }
        }
    });

    // 編集中止
    $(document).on('click', '.btn_cancel_category', function () {
        location.href = '/stock/basic?id=<?php echo $this->escape($this->id); ?>&from=<?php echo $this->escape($this->from); ?>&pos=' + $(window).scrollTop();
    });

    // 削除
    $(document).on('click', '.btn_delete_menu', function () {
       jConfirm('本当に削除しますか', '　', function(r) {
        	if(r) {
        	   $.ajax({
                    type:'POST',
                    dataType:'html',
                    data:'id=<?php echo $this->escape($this->id); ?>',
                    success:function(res){
                        reloadFlag = true;
                        deletedFlag = true;
                        jAlert('削除しました', '　');
                    },
                    error:function(){
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url:'/stock/delete'
                });
        	} else {
        	    return false;
        	}
        });
    });
});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:250px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>在庫管理 - <?php echo $itemTypeList[$this->data['stock_type']]; ?>詳細</strong></span>
        </div>
        
        <div class="clearfix">
	        <div style="float:left;width:82px;">
				<img src="<?php echo Shared_Model_Resource_WarehouseItem::getResourceUrl($this->data['id'], $this->data['image_key']); ?>" style="display:block;margin-top:5px;height:82px;border:2px solid #ddd;">
	        </div>
	        <div style="float:right;width:1164px;">
		        <div class="item_title clearfix">
		        	<p class="item_name">
						<?php if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM) { ?>
							<?php echo $this->escape($this->data['item_name']); ?>
						<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT) { ?>
							<?php echo $this->escape($this->data['supply_product_name']); ?>
						<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE) { ?>
							<?php echo $this->escape($this->data['supply_fixture_name']); ?>
						<?php } else { ?>
							<?php echo $this->escape($this->data['stock_name']); ?>
						<?php } ?>
		        	</p>
		        	<p class="stock">（単位：<?php echo $this->unitTypeList[$this->data['unit_type']]['symbol']; ?>）</p>
		        	<?php /* <p class="stock">引当可能在庫数：<?php echo $this->numberFormat($this->data['useable_count']); ?></p> */ ?>
		        	<p class="stock">理論在庫数：<?php echo $this->numberFormat($this->data['stock_count']); ?></p>
		        </div>
		    	<?php
		            echo $this->partial('stock/menu.phtml', array(
		    			'action'     => $this->action,
		    			'id'         => $this->data['id'],
		    			'stockType'  => $this->data['stock_type'],
		    			'from'       => $this->from,
		    		));
		        ?>  
	        </div>
        </div> 
    </div>

    <div class="clearfix">

	    <?php
        /* 基本情報 */
        $categoryId = 1;
        ?>
		<form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th class="border-left border-top border-bottom  <?php if ($this->allowEditing !== true) { echo 'border-right'; } ?>"><p class="label_text strong">基本情報</p></th> 
                <?php if ($this->allowEditing === true) { ?>
	                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php } ?>
            </tr>
        </table>
        <table class="list_default" style="margin-bottom:13px;">            
            <tr>
                <td class="column_label"><p class="label_text">在庫資材種別</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $itemTypeList[$this->data['stock_type']]; ?></p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">在庫資材名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>">
                		<?php if (!empty($this->data['stock_name'])) { echo $this->data['stock_name']; } else { echo '---'; } ?>
                	</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" name="stock_name" value="<?php echo $this->escape($this->data['stock_name']); ?>" maxlength="">
                    </div>
	                
	                <?php /*
         			<?php if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM) { ?>
						<div class="multi_rows_padding"><?php echo $this->escape($this->data['item_name']); ?></div>
					<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT) { ?>
						<div class="multi_rows_padding"><?php echo $this->escape($this->data['supply_product_name']); ?></div>
					<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE) { ?>
						<div class="multi_rows_padding"><?php echo $this->escape($this->data['supply_fixture_name']); ?></div>
					<?php } else { ?>
						<div class="multi_rows_padding"><?php echo $this->escape($this->data['stock_name']); ?></div>
					<?php } ?>
					*/ ?>
                </td>
            </tr>
            
            <tr id="select_target_row">
                <td class="column_label"><p class="label_text">対象商品</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="multi_rows_padding">
	         			<?php if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM) { ?>
							<strong>商品&nbsp;<?php echo $this->escape($this->data['item_display_id']); ?></strong>　<?php echo $this->escape($this->data['item_name']); ?>
						<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT) { ?>
							<strong>原料製品&nbsp;<?php echo $this->escape($this->data['supply_product_display_id']); ?></strong>　<?php echo $this->escape($this->data['supply_product_name']); ?>
						<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE) { ?>
							<strong>備品資材&nbsp;<?php echo $this->escape($this->data['supply_fixture_display_id']); ?></strong>　<?php echo $this->escape($this->data['supply_fixture_name']); ?>
						<?php } else { ?>
							引用なし
						<?php } ?>
	                </div>
	                <?php /*
	                <div class="edit_value_<?php echo $categoryId; ?> clearfix">
	                	<p id="reference_title">---</p>
	                    <a class="option" id="select_reference">選択</a>
	                    <input type="hidden" id="reference_target_id" name="reference_target_id" value="">
	                </div>
	                */ ?>
                </td>
            </tr>
            
			<?php /*
            <tr>
                <td class="column_label"><p class="label_text">アイテム名(英語)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['item_name_en']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="item_name_en" value="<?php echo $this->escape($this->data['item_name_en']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>
			*/ ?>

            <tr>
                <td class="column_label"><p class="label_text">在庫管理ステータス</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>">
                		<?php echo $statusList[$this->data['status']]; ?>
                	</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<select class="short" id="status" name="status" style="width:280px">
                            <option value="">---</option>
                            <?php foreach ($statusList as $key => $val) { ?>
                                <option value="<?php echo $this->escape($key); ?>" <?php if ((string)$this->data['status'] === (string)$key) { echo 'selected="selected"'; }?>><?php echo $this->escape($val); ?></option>
                            <?php } ?>
                    	</select>
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">検品用棚番号<span class="popup_help" id="help_shelf_no">&nbsp;<i class="icon-help-circled"></i></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>">
                		<?php if (!empty($this->data['shelf_no'])) { echo $this->data['shelf_no']; } else { echo '---'; } ?>
                	</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" name="shelf_no" value="<?php echo $this->escape($this->data['shelf_no']); ?>" maxlength="">
                    </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">棚卸単価</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <p class="display_value_<?php echo $categoryId; ?>">
	                	<?php if ((float)$this->data['unit_price'] !== (float)0) { echo $this->numberFormat($this->data['unit_price']); } else { echo '---'; } ?>&nbsp;円
                	</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" style="float:left;width:150px;text-align:right;" name="unit_price" value="<?php if ((float)$this->data['unit_price'] !== (float)0) { echo $this->numberFormat($this->data['unit_price']); } ?>" maxlength="">
                    	<p style="float:left;">円</p>
                    </div>	
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">棚卸数量単位</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p>
                		<?php
	                		echo $this->unitTypeList[$this->data['unit_type']]['symbol'] . '（' . $this->unitTypeList[$this->data['unit_type']]['name'] . '）';
                		?>
                	</p>
                	<?php /*
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<select class="short" id="unit_type" name="unit_type">
                            <option value="">---</option>
                            <?php foreach ($this->unitTypeList as $each) { ?>
                                <option value="<?php echo $each['id']; ?>" <?php if ((string)$this->data['unit_type'] === (string)$each['id']) { echo 'selected="selected"'; }?>><?php echo $each['symbol'] . '（' . $this->escape($each['name']) . '）'; ?></option>
                            <?php } ?>
                    	</select>
                    </div>
                    */ ?>
                </td>
            </tr>

			<tr>
                <td class="column_label"><p class="label_text">警告基準期間</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->numberFormat($this->data['minimum_base_month']); ?>&nbsp;カ月</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" style="float:left;width:5em;" name="minimum_base_month" value="<?php echo $this->numberFormat($this->data['minimum_base_month']); ?>" maxlength="">
						<p style="float:left;">&nbsp;カ月</p>
                    </div>
                </td>
            </tr>
            
			<tr>
                <td class="column_label"><p class="label_text">注意基準期間</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->numberFormat($this->data['safety_base_month']); ?>&nbsp;カ月</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" style="float:left;width:5em;" name="safety_base_month" value="<?php echo $this->numberFormat($this->data['safety_base_month']); ?>" maxlength="">
						<p style="float:left;">&nbsp;カ月</p>
                    </div>
                </td>
            </tr> 

            <tr>
                <td class="column_label"><p class="label_text">直近１ヶ月 出荷数(自動計算)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="multi_rows_padding">
                	    <?php echo $this->numberFormat(floor($this->data['shipped_last_month'])); ?><br>
                	    (2日前〜32日前出荷数)
                	</div>
                </td>
            </tr> 
            
            <tr>
                <td class="column_label"><p class="label_text">直近3ヶ月 月平均出荷数(自動計算)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="multi_rows_padding">
                	    <?php echo $this->numberFormat(floor($this->data['shipped_3_month_average'])); ?><br>
                	    (2日前〜92日前出荷数 / 3)
                	</div>
                </td>
            </tr>  

            <tr>
                <td class="column_label"><p class="label_text">最低在庫数(自動計算)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->numberFormat($this->data['minimum_count']); ?></p>
                </td>
            </tr>  
            
            <tr>
                <td class="column_label"><p class="label_text">安全在庫数(自動計算)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->numberFormat($this->data['safety_count']); ?></p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">DM便利用</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $yesNoList[$this->data['use_dm']]; ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
	                    <select name="use_dm" style="width:300px;">
	                        <?php foreach ($yesNoList as $key => $val) { ?>
	                        	<option value="<?php echo $this->escape($key); ?>" <?php if ($this->data['use_dm'] === (string)$key) { echo 'selected="selected"'; } ?>><?php echo $this->escape($val); ?></option>
	                        <?php } ?>
	                    </select>
                    </div>
                </td>
            </tr>
                    
            <?php /*
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">商品内容</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>" style="height:auto;margin-bottom:12px;line-height:1.6;"><?php if (!empty($this->data['memo'])) { echo nl2br($this->data['memo']); } else { echo '---'; } ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<textarea name="memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['memo']); ?></textarea>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">配送向け内容品表記(日本語)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['delivery_item_name']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="delivery_item_name" value="<?php echo $this->escape($this->data['delivery_item_name']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">配送向け内容品表記(英語)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['delivery_item_name_en']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="delivery_item_name_en" value="<?php echo $this->escape($this->data['delivery_item_name_en']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">アラート在庫数</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>">
                        <?php
                    	if (!empty($this->data['alert_count'])) {
                    		echo $this->escape($this->data['alert_count']);
                    	} else {
                    		echo '---';
                    	}
                    	?>
                	</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="short" name="alert_count" value="<?php echo $this->escape($this->data['alert_count']); ?>" maxlength="" />
                    </div>
                </td>
            </tr>
            */ ?> 
		</table>
		</form>


	    <?php
        /* 写真 */
        $categoryId = 2;
        ?>
		<form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-top border-bottom border-left border-right">
                	<p class="label_text strong" style="float:left;">在庫資材写真</p>
                	<?php if ($this->allowEditing === true) { ?>
                		<p style="float:right;padding-right:13px;">写真を変更するには画像ファイルをドラッグ&amp;ドロップ</p>
                	<?php } ?>
                </th>
            </tr>
        </table>
		<div id="add_image_box" ondragover="dragover(event)" ondrop="drop(event)" style="margin-bottom:13px;">
			<img id="photo_image" style="max-width:300px;" src="<?php echo Shared_Model_Resource_WarehouseItem::getResourceUrl($this->data['id'], $this->data['image_key']); ?>" />
		</div>
		</form>
				
	</div><!-- clearfix -->	                

</div>
</div>
</div>
</div>

