<?php
$statusList      = Shared_Model_Code::codes('is_active');
$stockStatusList = Shared_Model_Code::codes('stock_status');
$typeList        = Shared_Model_Code::codes('item_type');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
    });
});    
</script>
<style type="text/css">
table.list_default tr td {height:110px;}
table.list_default tr td p {height:auto;line-height:1.6;}
table.list_default tr td p.align_right {text-align:right;padding-right:12px;}
table.list_default tr td .multi_rows_padding {padding:5px 10px 5px 10px;}
.photo_image {padding:5px;width:90%;display:block;margin:0 auto;}
.safety {color:#00a2ff;font-weight: bold;}
.minimum{color:#ff00d2;font-weight: bold;}
.is_safety {color:#00c486;font-weight:bold;}
.is_caution {color:#ffba00;font-weight:bold;}
.is_warning {color:#ff0000;font-weight:bold;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
		    <?php if ($this->allowEditing === true) { ?>
				<p style="position:absolute;width:76px;right:0;">
	                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/stock/add/<?php echo $this->escape($this->type); ?>">新規登録</a>
	            </p>
            <?php } ?>
	        <span><strong>在庫資材管理 - <?php echo $typeList[$this->typeCode]; ?></strong></span>
	    </div>
	    
	    <div class="menu_list clearfix">
			<a class="menu <?php if($this->action == 'list') echo "selected"; ?>" href="/stock/list/<?php echo $this->escape($this->type); ?>">在庫数</a>
			<a class="menu <?php if($this->action == 'list-analytics') echo "selected"; ?>" href="/stock/list-analytics/<?php echo $this->escape($this->type); ?>">分析</a>
		</div>
	</div>
	
	<div style="background-color:#cceaf6;color:#2f7cf6;font-weight:bold;padding:0.4em 1.0em;">
		2日前から31日間：<?php echo $this->oneMonthAgo; ?>&nbsp;〜&nbsp;<?php echo $this->twoDaysAgo; ?>　　4週間前時点の31日間：<?php echo $this->twoMonthAgo; ?>&nbsp;〜&nbsp;<?php echo $this->fourWeekAgo; ?>
	</div>
	
	<?php $consumptionTable  = new Shared_Model_Data_ItemStockConsumption(); ?>
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $this->escape($each['id']); ?>">
						<td>
							<div class="clearfix" style="float:left;border-right:1px dotted #ccc;margin-top:5px;">
								<div style="float:left;width:80px;height:80px;">
									<img style="width:80px;padding-top:5px;" src="<?php echo Shared_Model_Resource_WarehouseItem::getResourceUrl($each['id'], $each['image_key']); ?>">
								</div>
								<div style="float:left;width:300px;">
									<p style="padding-right:0.8em;"><strong>
									<?php if ($each['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM) { ?>
										<?php echo $this->escape($each['item_name']); ?>
									<?php } else if ($each['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT) { ?>
										<?php echo $this->escape($each['supply_product_name']); ?>
									<?php } else if ($each['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE) { ?>
										<?php echo $this->escape($each['supply_fixture_name']); ?>
									<?php } else { ?>
										<?php echo $this->escape($each['stock_name']); ?>
									<?php } ?></strong>
									</p>


									<?php
										$thisMonth = $consumptionTable->getTermCount($each['id'], $this->oneMonthAgo, $this->twoDaysAgo);
										$lastMonth = $consumptionTable->getTermCount($each['id'], $this->twoMonthAgo, $this->fourWeekAgo);
										$saftyCount = round($thisMonth * $each['safety_base_month'], 1);
										$minimumCount = round($thisMonth * $each['minimum_base_month'], 1);
									?>
									
								
									<p><?php /*
										最低在庫数：<span class="minimum"><?php echo $this->numberFormat($each['minimum_count']); ?></span>
										&nbsp;/&nbsp;
										安全在庫数：<span class="safety"><?php echo $this->numberFormat($each['safety_count']); ?></span>
									*/ ?></p>

									<?php
										$class = 'is_safety';
										
										
										if ((int)$each['stock_count'] < (int)$minimumCount) { 
											$class = 'is_warning';
											
										} else if ((int)$each['stock_count'] < (int)$saftyCount) {
											$class = 'is_caution';
										}
					
									?>
								
									<p style="font-size:1.6em;width:270px;text-align:right;padding-right:12px" class="<?php echo $class; ?>">
										<?php echo $this->numberFormat($each['stock_count']); ?><?php echo $this->unitTypeList[$each['unit_type']]['symbol']; ?><br>
										(<?php if (!empty($thisMonth)) { echo $this->numberFormat(floor($each['stock_count'] / $thisMonth * 100) / 100) . '&nbsp;ヶ月分'; } else { echo '計算不可'; } ?>)
									</p>
								</div>
							</div>
							<div class="clearfix" style="float:left;padding-top:14px;padding-left:10px;width:250px;">
								2日前から31日間出荷数：<?php echo $this->numberFormat($thisMonth); ?><br>
								4週間前時点の31日間出荷数：<?php echo $this->numberFormat($lastMonth); ?><br>
								<span style="font-size:1.2em;font-weight:bold;color:#2960f6">1ヶ月間での出荷増加率：<?php if ($lastMonth > 0) { echo round(($thisMonth - $lastMonth) / $lastMonth, 2) * 100 . '&nbsp;%'; } else { echo '---'; } ?></span><br>
							</div>
							<div class="clearfix" style="float:left;padding-top:14px;padding-left:10px;width:170px;">
								注意基準期間：<?php echo $this->numberFormat($each['safety_base_month']); ?>&nbsp;月<br>
								警告基準期間：<?php echo $this->numberFormat($each['minimum_base_month']); ?>&nbsp;月
							</div>
							<div class="clearfix" style="float:left;padding-top:14px;padding-left:10px;width:190px;">
								注意安全在庫数：<span class="safety"><?php echo $saftyCount; ?></span><br>
								警告最低必須在庫数：<span class="minimum"><?php echo $minimumCount; ?></span><br>
							</div>
						</td>
	
						<td>
							<p><a href="/stock/basic?id=<?php echo $this->escape($each['id']); ?>&from=list-analytics">詳細</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="8">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

