<?php
$statusList      = Shared_Model_Code::codes('is_active');
$stockStatusList = Shared_Model_Code::codes('stock_status');
$typeList        = Shared_Model_Code::codes('item_type');
?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){

    });
});    
</script>
<style type="text/css"><!--
table.list_default tr td {height:110px;}
table.list_default tr td p {height:auto;line-height:1.6;}
table.list_default tr td p.align_right {text-align:right;padding-right:12px;}
table.list_default tr td .multi_rows_padding {padding:5px 10px 5px 10px;}
.photo_image {padding:5px;height:100px;display:block;margin:0 auto;}
.safety {color:#00a2ff;font-weight: bold;}
.minimum{color:#ff00d2;font-weight: bold;}
.is_safety {color:#00c486;font-weight:bold;}
.is_caution {color:#ffba00;font-weight:bold;}
.is_warning {color:#ff0000;font-weight:bold;}
--></style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:76px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/stock/add/<?php echo $this->escape($this->type); ?>">新規登録</a>
            </p>
	        <span style=""><strong>在庫資材管理</strong></span>
	    </div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form action="#" method="get">
				<p class="search_condition_title">検索条件</p>
				
				<div class="condition_items_row clearfix">		
					<div class="condition_item">
						<p class="condition_label">キーワード：</p>
						<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
					</div>

					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="user_id_in_charge" name="status">
                            <option value="">---</option>
                        	<?php foreach ($statusList as $key => $value) { ?>
                                <option value="<?php echo $eachUser['id']; ?>" <?php if ($key == $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">在庫状況：</p>
                        <select id="user_id_in_charge" name="stock_status">
                            <option value="">---</option>
                        	<?php foreach ($stockStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ($key == $this->conditions['stock_status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
				</div>
				
				<input type="submit" value="検索" />
			
			</form>
		</div>
	</div>
	
	<div class="legend">
		<img style="display:block;margin:10px auto;" src="/resource/img/stock_legend.png" />
	</div>
	

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th>
					<p>在庫資材名</p>
				</th>			

				<th style="width:8%;">
					<p>棚番号</p>
				</th>
				
			</tr>
			
			<?php if (!empty($this->itemList)) { ?>
				<?php foreach ($this->itemList as $each) { ?>

					<tr id="<?php echo $each['id']; ?>">
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['item_name']); ?></div>
						</td>

						<td>
							<p style="text-align:center;padding-left:0;"><?php echo $each['shelf_no']; ?></p>
						</td>

					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="8">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

