<?php
?>
<script type="text/javascript"><!--
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:150px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
table.list_default tr td table.product_code_item {margin:5px 0;}
table.list_default tr td table.product_code_item tr td {height:auto;padding:0 0 0 12px;}
table.list_default tr td table.product_code_item tr td.column_label {width:134px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>在庫管理 - <?php echo $itemTypeList[$this->data['stock_type']]; ?>詳細</strong></span>
        </div>
        <div class="item_title clearfix">
        	<p class="item_name">
				<?php if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_ITEM) { ?>
					<?php echo $this->escape($this->data['item_name']); ?>
				<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_PRODUCT) { ?>
					<?php echo $this->escape($this->data['supply_product_name']); ?>
				<?php } else if ($this->data['target_type'] === (string)Shared_Model_Code::WAREHOUSE_ITEM_TARGET_TYPE_SUPPLY_FIXTURE) { ?>
					<?php echo $this->escape($this->data['supply_fixture_name']); ?>
				<?php } else { ?>
					<?php echo $this->escape($this->data['stock_name']); ?>
				<?php } ?>
        	</p>
        	<p class="stock">（単位：<?php echo $this->unitTypeList[$this->data['unit_type']]['symbol']; ?>）</p>
        	<p class="stock">引当可能在庫数：<?php echo $this->numberFormat($this->data['useable_count']); ?></p>
        	<p class="stock">理論在庫数：<?php echo $this->numberFormat($this->data['stock_count']); ?></p>
        </div>
        <div>
        	<?php
	            echo $this->partial('stock/menu.phtml', array(
        			'action'    => $this->action,
        			'id'        => $this->data['id'],
        			'stockType'  => $this->data['stock_type'],
        		));
	        ?>   		
        </div>
    </div>
    
    <div class="clearfix">

        <div>
    	    <?php
            /* 在庫履歴 */
            $categoryId = 2;
            ?>
			
			<?php /*
			<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
				<div class="condition_items clearfix">
					<form action="#" method="get">
						<p class="search_condition_title">検索条件</p>
						
						<div class="condition_items_row clearfix">		
							<div class="condition_item">
								<p class="condition_label">アクション：</p>
		                        <select id="add_action" name="add_action">
		                            <option value="">---</option>
		                        	<?php foreach ($addActionList as $key => $value) { ?>
		                                <option value="<?php echo $key; ?>" <?php if ($key == $this->conditions['add_action']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
		                            <?php } ?>
		                        </select>
							</div>
							
							<div class="condition_item">
								<p class="condition_label">日時(From)：</p>
		                        <input type="text" name="from" id="from" class="datepicker" value="" />
							</div>
							
							<div class="condition_item">
								<p class="condition_label">日時(To)：</p>
		                        <input type="text" name="to" id="to" class="datepicker" value="" />
							</div>
						</div>
						
						<input type="submit" value="検索" />
					
					</form>
				</div>
			</div>
			*/ ?>
			
			<?php
			$sumCount = 0;
			foreach ($this->stockItems as $each) {
				$sumCount += $each['amount'];
			}
			?>
			
			<p><?php echo '入庫：' . $sumCount; ?></p>
			
			<?php
			$subCount = 0;
			foreach ($this->stockConsumptionItems as $each) {
				$subCount += $each['sub_count'];
			}
			?>
			
			<p><?php echo '出庫：' . $subCount; ?></p>
			
			<p><?php echo '現在庫：' . ($sumCount - $subCount); ?></p>
			
		</div><!-- right -->
		
	</div><!-- clearfix -->	                
</div>
</div>
</div>
</div>
