<?php
$bankAccountType = Shared_Model_Code::codes('bank_account_type');
?>
<script type="text/javascript">
$(function() {
    $(document).ready(function(){
    });

	<?php 
		$confirmMessage = '登録しますか';
		$succeedMessage = '登録しました';
		$backmessage    = '登録せずに中止しますか';
		if (!empty($this->id)) {
			$confirmMessage = '保存しますか';
			$succeedMessage = '保存しました';
			$backmessage    = '保存せずに中止しますか';
        }
	?>
			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
       jConfirm('<?php echo $backmessage; ?>', '　', function(r) {
            if(r) {
               location.href = "/financial/bank-list";
            } else {
                return false;
            }
        });
	});
		
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('<?php echo $confirmMessage; ?>', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var params = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data:params,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if (obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('<?php echo $succeedMessage; ?>', '　'); 
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error:function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url:'/financial/bank-update<?php if (!empty($this->id)) echo '?id=' . $this->escape($this->id); ?>'
                });
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/financial/bank-list';
        }
    });
      
});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
#horizontalwrap {display:inline;white-space:nowrap;}
span.note {display:block;margin:4px 0 3px;padding:0 4px;}
table.list_default tr td.column {border-right:none;}
table.list_default tr td.column p {padding-left:12px;}
table.list_default tr td.column input {width:99%}
table.list_default tr td.column select.short {width:200px}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>銀行口座 - <?php if (!empty($this->id)) { echo '編集'; } else { echo '登録'; } ?></strong></span>
        </div>
    </div>
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #ccc;background-color:#f1f1f1;">
                    <p class="label_text strong">口座情報</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">金融機関コード<span class="require">＊</span>：</p></td>
                <td class="column">
                	<input type="text" style="width:200px;" name="bank_code" value="<?php echo $this->escape($this->data['bank_code']); ?>" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column" style="width:200px;"><p class="label_text">金融機関名<span class="require">＊</span>：</p></td>
                <td class="column">
                	<input type="text" style="width:400px;" name="bank_name" value="<?php echo $this->escape($this->data['bank_name']); ?>" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column" style="width:200px;"><p class="label_text">支店コード<span class="require">＊</span>：</p></td>
                <td class="column">
                	<input type="text" style="width:200px;" name="branch_code" value="<?php echo $this->escape($this->data['branch_code']); ?>" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">支店名<span class="require">＊</span>：</p></td>
                <td class="column">
                	<input type="text" style="width:400px;" name="branch_name" value="<?php echo $this->escape($this->data['branch_name']); ?>" maxlength="" />
                </td>
            </tr>
 
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">口座種別<span class="require">＊</span>：</p></td>
                <td class="column">
                	<select class="short" id="account_type" name="account_type">
                		<option value="">---</option>
                        <?php foreach ($bankAccountType as $key => $val) { ?>
                            <option value="<?php echo $this->escape($key); ?>" <?php if ($this->data['account_type'] == (string)$key) echo 'selected="selected"'; ?>><?php echo $this->escape($val); ?></option>
                        <?php } ?>
                	</select>
                </td>
            </tr>

            <tr>
                <td class="column" style="width:200px;"><p class="label_text">口座番号<span class="require">＊</span>：</p></td>
                <td class="column">
                	<input type="text" style="width:200px;" name="account_no" value="<?php echo $this->escape($this->data['account_no']); ?>" maxlength="" />
                </td>
            </tr>
  
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">口座名義<span class="require">＊</span>：</p></td>
                <td class="column">
                	<input type="text" style="width:400px;" name="account_name" value="<?php echo $this->escape($this->data['account_name']); ?>" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">口座名義(カナ)<span class="require">＊</span>：</p></td>
                <td class="column">
                	<input type="text" style="width:400px;" name="account_name_kana" value="<?php echo $this->escape($this->data['account_name_kana']); ?>" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">略名(5文字以内)：</p></td>
                <td class="column">
                	<input type="text" style="width:400px;" name="short_name" value="<?php echo $this->escape($this->data['short_name']); ?>" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">GMOアカウント：</p></td>
                <td class="column">
                	<div class="clearfix">
						<select class="short" id="gmo_account_id" name="gmo_account_id">
                            <option value="0">---</option>
                            <?php foreach ($this->gmoAccountList as $each) { ?>
                                <option value="<?php echo $this->escape($each['id']); ?>" <?php if ($each['id'] == $this->data['gmo_account_id']) echo 'selected="selected"'; ?>><?php echo $this->escape($each['name']); ?></option>
                            <?php } ?>
                    	</select>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column" style="width:200px;"><p class="label_text">GMO口座ID：</p></td>
                <td class="column">
                	<div class="clearfix">
						<p><?php echo $this->escape($this->data['gmo_bank_account_id']); ?></p>
					</div>
                </td>
            </tr>
        </table>

	</div><!-- clearfix -->
    </form>

</div>
</div>
</div>
</div>
