<?php
$statusList   = Shared_Model_Code::codes('item_status');
$typeList     = Shared_Model_Code::codes('item_type');
?>
<link rel="stylesheet" type="text/css" href="/resource/js/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css" />
<script type="text/javascript" src="/resource/js/jquery.imgareaselect-0.9.10/scripts/jquery.imgareaselect.pack.js"></script>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){

    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/item/list/<?php echo $this->escape($this->type); ?>";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/item/add-post/<?php echo $this->escape($this->type); ?>'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/item/list/<?php echo $this->escape($this->type); ?>';
        }
    });
   
});
--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:280px;}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>在庫管理 - <?php echo $typeList[$this->typeCode]; ?>登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
                    <p class="label_text strong">管理情報</p>
                </th>
            </tr>
		</table>
         
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">アイテム名<span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="item_name" value="<?php echo $this->escape($this->data['item_name']); ?>" maxlength="" />
                </td>
            </tr>        
            
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">ステータス<span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<select id="status" name="status" style="width:280px;margin-left:0px;margin-top:5px;display:block;float:left;margin-right:10px;">
                    	<option value="">---</option>
                    	<?php foreach ($statusList as $key => $val) { ?>
                            <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
                                
            <tr>
                <td class="column_label"><p class="label_text">JANコード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" name="jan_code" class="short" value="<?php echo $this->escape($this->data['jan_code']); ?>" maxlength="" />
                </td>
            </tr>
            
		</table>

	</div><!-- clearfix -->	
    </form>
                
</div>
</div>
</div>
</div>

