<?php
$statusList   = Shared_Model_Code::codes('item_status');
$typeCodeList = Shared_Model_Code::codes('item_type_code');
$typeList     = Shared_Model_Code::codes('item_type');
$monthList    = Shared_Model_Code::getMonthListFromRelease();
?>
<script src="/resource/js/Chart.js/Chart.js"></script>
<script type="text/javascript">
var chartData = {
    type   : 'bar',
    labels : [<?php 
            foreach($this->dataList as $eachDate) {
                echo "'" . $eachDate['day'] . "',";
            }
            ?>],
    scaleShowGridLines : false,
    datasets : [
        {
            fillColor       : "rgba(24, 181, 22, 1.0)",
            strokeColor     : "rgba(24, 181, 22, 1.0)",
            highlightFill   : "rgba(24, 181, 22, 1.0)",
            highlightStroke : "rgba(24, 181, 22, 1.0)",
            data : [<?php 
            foreach($this->dataList as $eachDate) {
                echo "'" . $eachDate['count'] . "',";
            }
            ?>]
        }
    ]  
};
 
window.onload = function(){
    var ctx = document.getElementById("canvas").getContext("2d");
    window.myBar = new Chart(ctx).Bar(chartData, {
        responsive : true,
        tooltipTemplate:" <%= value %> ",
    });
}
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:150px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>在庫管理 - <?php echo $typeList[$this->data['item_type']]; ?>詳細</strong></span>
        </div>
        <div class="item_title clearfix">
        	<p class="item_name"><?php echo $this->escape($this->data['item_name']); ?></p>
        	<p class="stock">引当可能在庫数：<?php echo $this->escape($this->data['useable_count']); ?></p>
        	<p class="stock">実在庫数：<?php echo $this->escape($this->data['stock_count']); ?></p>
        </div>
    	<?php
            echo $this->partial('item/menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->data['id'],
    			'itemType'  => $this->data['item_type'],
    		));
        ?>
    </div>

    <div class="clearfix">

        <div class="item_header clearfix">
            <span style="display:block;float:left;padding:11px 0 0 12px;height:15px;line-height:1;font-weight:bold;">概要</span>
        </div>

		<table class="list_default">
			<tr>
				<td><p>１日出荷数</p></td>
				<td><p>（過去1ヶ月平均）：6.5</p></td>
				<td><p>（過去3ヶ月平均）：7.7</p></td>
			</tr>
			<tr>
				<td><p>週間出荷数</p></td>
				<td><p>（過去1ヶ月平均）：38.5</p></td>
				<td><p>（過去3ヶ月平均）：32.6</p></td>
			</tr>
			<tr>
				<td><p>月間出荷数</p></td>
				<td><p>（過去1ヶ月平均）：103.5</p></td>
				<td><p>（過去3ヶ月平均）：104.6</p></td>
			</tr>	
		</table>

        
        <div class="item_header clearfix">
            <span style="display:block;float:left;padding:11px 0 0 12px;height:15px;line-height:1;font-weight:bold;">月間出荷数</span>
            <select id="month_list" name="month_list" style="width:150px;margin-right:4px;margin-top:4px;display:block;float:right;height:26px;">
                <?php foreach ($monthList as $key => $each) { ?>
                    <option value="<?php echo $key; ?>" <?php if ($this->tagetMonth == $key) { echo 'selected="selected"'; } ?>><?php echo $each; ?></option>
                <?php } ?>
        	</select>
        </div>
	
	    <div style="padding: 0 12px 20px 27px; position:relative;">
	        <div style="margin: 3px;">
	            <canvas id="canvas" height="360" width="694"></canvas>  
	        </div>
	        <p style="position:absolute;top:196px;left:-40px;text-align:center; width:10em; font-size:0.92em; transform: rotate( 270deg ); ">出荷数</p>
	        <p style="position:absolute;bottom:5px; eft:auto;text-align:center; width:100%; font-size:0.92em;">（日）</p>
	    </div>
								
	</div><!-- clearfix -->	                
</div>
</div>
</div>
</div>
