<?php
$statusList   = Shared_Model_Code::codes('item_status');
$typeList     = Shared_Model_Code::codes('item_type');
$actionList   = Shared_Model_Code::codes('stock_sub_input');
$hourList     = Shared_Model_Code::getHourList();
$minuteList   = Shared_Model_Code::getMinuteList();
?>
<link rel="stylesheet" type="text/css" href="/resource/js/jquery.imgareaselect-0.9.10/css/imgareaselect-default.css" />
<script type="text/javascript" src="/resource/js/jquery.imgareaselect-0.9.10/scripts/jquery.imgareaselect.pack.js"></script>
<script type="text/javascript"><!--
var reloadFlag = false;

$(function() {
    $(document).ready(function(){
		$('.datepicker').datepicker();
        $('.datepicker').datepicker("option", "dateFormat", "yy/mm/dd");
        $('.datepicker').datepicker("option", "yearSuffix", '年');
        $('.datepicker').datepicker("option", "monthNames", ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']);
		$('.datepicker').datepicker("option", "showMonthAfterYear", true);
        $('.datepicker').datepicker("option", "dayNames", ['日', '月', '火', '水', '木', '金', '土']);
        $('.datepicker').datepicker("option", "dayNamesMin", ['日', '月', '火', '水', '木', '金', '土']);
        
        $("#action_time_day").datepicker("setDate", "<?php echo date('Y/m/d', strtotime($this->today)); ?>"); 
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/item/stock-warehouse?id=<?php echo $this->escape($this->id); ?>";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/item/stock-consumption-add-post?item_id=<?php echo $this->id; ?>&stock_id=<?php echo $this->escape($this->stockId); ?>'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/item/stock-warehouse?id=<?php echo $this->escape($this->id); ?>';
        }
    });
   
});
--></script>
<style type="text/css"><!--
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:280px;}
--></style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
        <div class="page_title">
            <span><strong>在庫管理 - <?php echo $typeList[$this->data['item_type']]; ?>詳細</strong></span>
        </div>
        <div class="item_title clearfix">
        	<p class="item_name"><?php echo $this->escape($this->data['item_name']); ?></p>
        	<p class="stock">引当可能在庫数：<?php echo $this->escape($this->data['useable_count']); ?></p>
        	<p class="stock">実在庫数：<?php echo $this->escape($this->data['stock_count']); ?></p>
        </div>
    	<?php
            echo $this->partial('item/menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->data['id'],
    			'itemType'  => $this->data['item_type'],
    		));
        ?>
	</div>
                
    <div class="clearfix">
  
	    <form id="register_form" action="#" method="post"> 
	    <div class="clearfix">
	
			<table class="list_default" style="margin-bottom:0;">
	            <tr>
	                <th style="border-left:1px solid #ddd;border-top:1px solid #ddd;border-bottom:1px solid #ddd;">
	                    <p class="label_text strong">在庫調整入力</p>
	                </th>
	                <th class="edit_category edit_mode">
	                    <a class="btn_save_category btn_save" href="javascript:void(0);"><span>登録</span></a>
	                </th> 
	            </tr>
			</table>
	         
	        <table class="list_default" style="margin-bottom:13px;">
	            <tr>
	                <td class="column_label"><p class="label_text" style="padding-left:12px;">対象在庫：<span class="require">＊</span></p></td>
	                <td class="column_value">
	                	<p>在庫管理ID：<?php echo $this->stockData['id']; ?>　倉庫:フレスコ　入庫：<?php echo $this->stockData['add_count']; ?>　残量：<?php echo $this->stockData['last_count']; ?></p>
	                </td>
	            </tr>
	        
	            <tr>
	                <td class="column_label"><p class="label_text" style="padding-left:12px;">日時：<span class="require">＊</span></p></td>
	                <td class="column_value">
                        <div class="clearfix" style="width:230px;float:left;">
                            <input type="text" class="datepicker" id="action_time_day" name="action_time_day" value="" maxlength="10" style="width: 99px; margin-right:10px; dispaly:block; float:left;" />
                            <?php
                            	$defaultHour = date('H', strtotime($this->today));
                            	$defaultMin  = date('i', strtotime($this->today));
                            ?>
                            <select class="hour_min" name="action_time_hour" style="dispaly:block;float:left;width:50px;">
                                <option value="">---</option>
                                <?php foreach ($hourList as $key => $eachHour) { ?>
                                    <option value="<?php echo $eachHour; ?>" <?php if ($defaultHour == $eachHour) { echo 'selected="selected"'; } ?>><?php echo $eachHour; ?></option>
                                <?php } ?>
                            </select>
                            <p class="hour_min" style="float:left;wiidth:15px;text-align:center;padding-left:0;">：</p>
                            <select class="hour_min" name="action_time_min" style="dispaly:block;float:left;width:50px;">
                                <option value="">---</option>
                                <?php foreach ($minuteList as $key => $eachMinute) { ?>
                                    <option value="<?php echo $eachMinute; ?>" <?php if ($defaultMin == $eachMinute) { echo 'selected="selected"'; } ?> ><?php echo $eachMinute; ?></option>
                                <?php } ?>
                            </select>
                        </div>
	                </td>
	            </tr>
	            
	            <tr>
	                <td class="column_label"><p class="label_text" style="padding-left:12px;">アクション：<span class="require">＊</span></p></td>
	                <td class="column_value">
	                	<select id="consumption_action" name="consumption_action" style="width:280px; margin-left:0px; margin-top:5px; display:block; float:left; margin-right:10px;">
		                	<option value="">---</option>
		                	<?php foreach ($actionList as $key => $val) { ?>
		                        <option value="<?php echo $key; ?>"><?php echo $val; ?></option>
		                    <?php } ?>
	                    </select>
	                </td>
	            </tr> 
	            
	            <tr>
	                <td class="column_label"><p class="label_text">数量：</p></td>
	                <td class="column_value">
	                    <input type="text" name="amount" class="short" value="" maxlength="" />
	                </td>
	            </tr>
			</table>
	
	
		</div><!-- clearfix -->	
	    </form>

    </div>
    
</div>
</div>
</div>
</div>
