<?php
$exportTypeList = Shared_Model_Code::codes('export_type');
?>
<script type="text/javascript">
var reloadFlag = false;
var editing = 0;
var pos = 0;
function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

$(function() {
    $(document).ready(function(){
		Tipped.create('#help_products_quantity', "輸出する商品数");
		Tipped.create('#help_quantity_per_box', "1箱あたりの入り数");
		Tipped.create('#help_box_quantity', "出荷する箱の総数");
		Tipped.create('#help_volume_per_box', "1箱あたりの体積");
		Tipped.create('#help_total_volume', "体積総計");
		
		Tipped.create('#help_weight_per_box', "1箱あたりの重さ");
		Tipped.create('#help_total_weight', "重量総計");
		Tipped.create('#help_ex_works_unit_price', "EX-Works単価");
		Tipped.create('#help_ex_works_amount', "EX-Works総額");
		Tipped.create('#help_fob_amount', "FOB総額（FOBは船のみ）");
		Tipped.create('#help_fob_unit_price', "FOB単価");
		Tipped.create('#help_fob_index', "FOB単価 / EX-Works単価");
		Tipped.create('#help_transport_cost', "海上運賃");
		Tipped.create('#help_rate_insurance_coverage', "保険金額に余裕を持たせて、少し多めにとる。<br>事故時は金利損や追加費用も請求される可能性があるため。");
		Tipped.create('#help_rate_exchange_diffrence', "入金日と支払日の差額の金利");
		Tipped.create('#help_export_cif_cip_amount', "CIF/CIP総額（CIFは船。CIPは航空時）");
		Tipped.create('#help_export_cif_cip_unt_price', "CIF/CIP単価");
		Tipped.create('#help_export_cif_cip_index', "CIF・CIP単価 / EX-Works単価");
		Tipped.create('#help_rate', "輸出国通貨額　×　為替レート　＝　輸入国通貨額　とする<br>（例）日本からアメリカに輸出するとき、1ドル100円であれば、0.01が入力すべき為替レート");
		Tipped.create('#help_insurance_coverage_amount', "為替レートで割り戻す");
		Tipped.create('#help_ddp_index', "DDP単価 / EX-Works単価");
    });

    // 編集
    $(document).on('click', '.btn_edit_category', function () {
    	if (editing == true) {
    		jAlert('複数のカテゴリを同時に編集することはできません', 'エラー');
    		return false;
    	}
    
        var categoryId = $(this).attr('category_id');
        
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
    
        // ×,保存ボタン
        $('#cancel_category_' + categoryId).show();
        $('th#edit_category_' + categoryId).addClass('edit_mode');
        $(this).removeClass('btn_edit_category').addClass('btn_save_category');
        $('#btn_edit_label_' + categoryId).html('保存');
	    
	    editing = true;
    });
    
	// 保存
    $(document).on('click', '.btn_save_category', function () {
        var button = $(this);
        var categoryId = $(this).attr('category_id');
        var $form = $('#form_category_' + categoryId);
        var params = $form.serializeArray();
		
		var apiUrl = '/price-expense/export-update-table?id=<?php echo $this->escape($this->id); ?>&version_id=<?php echo $this->escape($this->versionId); ?>';		

		showSpinner();
        $.ajax({
            type:'POST',
            dataType:'json',
            data: params,
            success: function(res){
            	stopSpinner();
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
            	stopSpinner();
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url: apiUrl,
        });
    });
    
    $(document).on('click', '#popup_ok', function () {
    	if (reloadFlag) {
    		location.href = '/price-expense/export-detail-version?id=<?php echo $this->escape($this->id); ?>&version_id=<?php echo $this->escape($this->versionId); ?>&pos=' + $(window).scrollTop();
    	}
    });

    // 編集中止
    $(document).on('click', '.btn_cancel_category', function () {
        var categoryId = $(this).attr('category_id');
        location.href = '/price-expense/export-detail-version?id=<?php echo $this->escape($this->id); ?>&version_id=<?php echo $this->escape($this->versionId); ?>&pos=' + $(window).scrollTop();
    });

    // 通貨単位
  	$('input.input_unit').on('input', function(e) {
		var exportUnit = $('input[name="export_unit"]').val();
		$('span.export_unit').html(exportUnit);

		var importUnit = $('input[name="import_unit"]').val();
		$('span.import_unit').html(importUnit);

		$('span.exchange_unit').html(importUnit + ' / ' + exportUnit);
  	});
  	
    // 自動計算
  	$('table.detail input[type="text"]').on('input', function(e) {
		updateTable();
  	});
});

function separate(num){
    return String(num).replace( /(\d)(?=(\d\d\d)+(?!\d))/g, '$1,');
}
function isNumber(n) { return /^-?[\d.]+(?:e-?\d+)?$/.test(n); } 
function initValue(value) {
	if (isNumber(value)) {
		return parseInt(value);
	}
	return 0;
}

function updateTable() {
	for (var i = 1;  i <= 5;  i++) {
		var products_quantity   = initValue($('input[name="products_quantity_' + i +'"]').val()); // 製品数量
		var ex_works_unit_price = initValue($('input[name="ex_works_unit_price_' + i +'"]').val()); // 工場倉庫出荷単価
		var packing_cost        = initValue($('input[name="packing_cost_' + i + '"]').val()); // 梱包費用
		var delivery_cost       = initValue($('input[name="delivery_cost_' + i + '"]').val()); // 国内輸送費
		var export_expense_1    = initValue($('input[name="export_expense_1_' + i + '"]').val()); // 輸出諸掛1
		var export_expense_2    = initValue($('input[name="export_expense_2_' + i + '"]').val()); // 輸出諸掛2
		var export_expense_3    = initValue($('input[name="export_expense_3_' + i + '"]').val()); // 輸出諸掛3
		
		// 工場倉庫出荷総額
		$('#ex_works_amount_' + i).html(separate(products_quantity * ex_works_unit_price));
		$('input[name="ex_works_amount_' + i + '"]').val(separate(products_quantity * ex_works_unit_price));
		
		// 本船渡し総額
		var fobAmount = (products_quantity * ex_works_unit_price) + packing_cost + delivery_cost + export_expense_1 + export_expense_2 + export_expense_3;
		
		$('#fob_amount_' + i).html(separate(fobAmount));
		$('input[name="fob_amount_' + i + '"]').val(separate(fobAmount));
		
		// 本船渡し単価
		var fobUnit = fobAmount / products_quantity;
		$('#fob_unit_price_' + i).html(separate(fobUnit.toFixed(0)));
		$('input[name="fob_unit_price_' + i + '"]').val(separate(fobUnit.toFixed(0)));
		
		// FOB指数
		var fobIndex = fobUnit / ex_works_unit_price;
		$('#fob_index_' + i).html(separate(fobIndex.toFixed(2)));
		$('input[name="fob_index_' + i + '"]').val(separate(fobIndex.toFixed(2)));
		
		
		var transport_cost           = initValue($('input[name="transport_cost_' + i +'"]').val()); // 海上輸送費
		var transport_charge_1       = initValue($('input[name="transport_charge_1_' + i +'"]').val()); // その他輸送諸掛1
		var rate_insurance_coverage  = parseFloat($('input[name="rate_insurance_coverage_' + i +'"]').val()); // 保険対象増幅率
		var rate_insurance           = parseFloat($('input[name="rate_insurance_' + i +'"]').val()); // 保険率
		var rate_exchange_diffrence  = parseFloat($('input[name="rate_exchange_diffrence_' + i +'"]').val()); // 金利利率
		
		// 保険適用額
		var insuranceCoverageAmount = (fobAmount + transport_cost + transport_charge_1) * rate_insurance_coverage * 0.01; 
		$('#insurance_coverage_amount_' + i).html(separate(insuranceCoverageAmount.toFixed(0)));
		$('input[name="insurance_coverage_amount_' + i + '"]').val(separate(insuranceCoverageAmount.toFixed(0)));
		
		// 保険料
		var insurance_price = insuranceCoverageAmount * rate_insurance * 0.01;
		$('#insurance_price_' + i).html(separate(insurance_price.toFixed(0)));
		$('input[name="insurance_price_' + i + '"]').val(separate(insurance_price.toFixed(0)));
		
		// 金利
		var exchange_diffrence = (fobAmount + transport_cost + transport_charge_1 + insurance_price) * rate_exchange_diffrence * 0.01; 
		$('#exchange_diffrence_' + i).html(separate(exchange_diffrence.toFixed(0)));
		$('input[name="exchange_diffrence_' + i + '"]').val(separate(exchange_diffrence.toFixed(0)));
		
		// 運賃保険料込み総額
		var export_cif_cip_amount = fobAmount + transport_cost + transport_charge_1 + insurance_price + exchange_diffrence;
		$('#export_cif_cip_amount_' + i).html(separate(export_cif_cip_amount.toFixed(0)));
		$('input[name="export_cif_cip_amount_' + i + '"]').val(separate(export_cif_cip_amount.toFixed(0)));

		// 運賃保険料込み単価
		var export_cif_cip_unt_price = export_cif_cip_amount / products_quantity;
		$('#export_cif_cip_unt_price_' + i).html(separate(export_cif_cip_unt_price.toFixed(0)));
		$('input[name="export_cif_cip_unt_price_' + i + '"]').val(separate(export_cif_cip_unt_price.toFixed(0)));

		// CIF指数
		var export_cif_cip_index = export_cif_cip_unt_price / ex_works_unit_price;
		$('#export_cif_cip_index_' + i).html(separate(export_cif_cip_index.toFixed(2)));
		$('input[name="export_cif_cip_index_' + i + '"]').val(separate(export_cif_cip_index.toFixed(2)));

		if (i == 1) {
			console.log('products_quantity:' + products_quantity);
			console.log('ex_works_unit_price:' + ex_works_unit_price);
			console.log('packing_cost:' + packing_cost);
			console.log('delivery_cost:' + delivery_cost);
			console.log('export_expense_1:' + export_expense_1);
			console.log('export_expense_3:' + export_expense_2);
			console.log('export_expense_3:' + export_expense_3);
			console.log('fob_amount:' + fobAmount);
			console.log('rate_exchange_diffrence:' + rate_exchange_diffrence);
		}
	}
}


</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;font-weight:bold;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1;}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}
.product_name {background-color:#ed8c14;color:#fff;padding:3px 0.2em 1px 0.2em}
.import_name {background-color:#008cff;color:#fff;padding:3px 0.2em 1px 0.2em}
.private_memo {margin-top:20px;padding:40px 50px 50px;background-color:#e0feff;border:1px solid #32918c;}
.private_memo p {font-size:1.4em;color:#32918c;font-weight:bold;margin-bottom:0.8em}

table.detail tr th, table.detail tr td {border:1px solid #000;padding:0;height:45px}
table.detail tr th {background-color:#bae0ff;font-weight:normal;border-right:none;}
table.detail tr th p {line-height:1.4;padding-left:10px;font-size:1.1em}
table.detail tr th p.name{margin-top:9px}
table.detail tr th input{margin-top:2px;width:227px}

table.detail tr td {width:9%;padding:0;}
table.detail tr td.td_unit {width:15%;padding:0 0 0 10px;}
table.detail tr td.gray {background-color:#bbb}
table.detail tr td p {padding-left:8px;padding-right:8px;/*margin-bottom:0;height:22px;padding-top:10px;*/}
table.detail tr td select.unit {display:inline-block;margin-top:2px;width:90px;height:28px;}
table.detail tr td input[type="text"]{border:none;width:100%;padding-left:8px;padding-right:8px;height:45px;}
table.detail tr td textarea{border:none;width:100%;}

.align_right {text-align:right;}
.align_center {text-align:center;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong><?php echo $this->escape($this->parentData['title']); ?>　バージョン：<?php echo $this->escape($this->data['version_id']); ?></strong></span>
        </div>
    </div>
    
    <div class="clearfix">
	    <?php
        /* 5. 輸出国費用 */
        $categoryId = 5;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
		<table class="list_default" style="margin-bottom:13px;;">
            <tr>
                <th class="border-left border-top border-bottom"><p class="label_text strong">物流費計算表</p></th>
                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                    <span>×</span>
                    </a>
                </th>
                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
                </th>
            </tr>
		</table>
		
		
        <table class="detail">
            <tr>
            	<th><p>製品数量<span class="popup_help" id="help_products_quantity">&nbsp;<i class="icon-help-circled"></i></span><br>Products quantity</p></th>
            	<td class="td_unit">
            		&nbsp;
            	</td>
            	<?php $key = 'products_quantity_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
            	<th><p>箱入り数<span class="popup_help" id="help_quantity_per_box">&nbsp;<i class="icon-help-circled"></i></span><br>Quantity / box</p></th>
            	<td class="td_unit">
            		&nbsp;
            	</td>
            	<?php $key = 'quantity_per_box_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
            	<th><p>箱数<span class="popup_help" id="help_box_quantity">&nbsp;<i class="icon-help-circled"></i></span><br>Box quantity</p></th>
            	<td class="td_unit">
            		&nbsp;
            	</td>
            	<?php $key = 'box_quantity_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
            	<th><p>箱当たり荷量<span class="popup_help" id="help_volume_per_box">&nbsp;<i class="icon-help-circled"></i></span><br>Volume / box</p></th>
            	<td class="td_unit">
            		&nbsp;
            	</td>
            	<?php $key = 'volume_per_box_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
            	<th><p>全体荷量<span class="popup_help" id="help_total_volume">&nbsp;<i class="icon-help-circled"></i></span><br>Total volume</p></th>
            	<td class="td_unit">
            		&nbsp;
            	</td>
            	<?php $key = 'total_volume_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
            	<th><p>箱当たり重量<span class="popup_help" id="help_weight_per_box">&nbsp;<i class="icon-help-circled"></i></span><br>Weight / box</p></th>
            	<td class="td_unit">
            		&nbsp;
            	</td>
            	<?php $key = 'weight_per_box_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
            	<th><p>箱全重量<span class="popup_help" id="help_total_weight">&nbsp;<i class="icon-help-circled"></i></span><br>Total Waight</p></th>
            	<td class="td_unit">
            		&nbsp;
            	</td>
            	<?php $key = 'total_weight_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>              
       </table>
       
       
       
       
       
       
       
		<div class="clearfix" style="margin-bottom:5px;">
	    	<h2 style="float:left;width:446px;margin-top:0.8em;margin-bottom:0.3em;padding-left:10px;">輸出国費用</h2>
	    	<p style="float:left;padding-top:0.8em;">輸出国通貨単位：</p>
	       
	   		<div style="float:left;width:200px;">
        		<div class="display_value_<?php echo $categoryId; ?>">
        			<p style="padding-top:0.8em;padding-left:8px"><?php echo $this->escape($this->data['export_unit']); ?></p>
        		</div>
        		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
        			<input type="text" class="input_unit" style="width:80px;" name="export_unit" value="<?php echo $this->escape($this->data['export_unit']); ?>" />
        		</div>
	    		
	    	</div>
		</div>
       
		<table class="detail">
            <tr>
                <th><p>工場倉庫出荷単価<span class="popup_help" id="help_ex_works_unit_price">&nbsp;<i class="icon-help-circled"></i></span><br>EX-Works unit price</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'ex_works_unit_price_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>工場倉庫出荷総額<span class="popup_help" id="help_ex_works_amount">&nbsp;<i class="icon-help-circled"></i></span><br>EX-Works amount</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'ex_works_amount_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>梱包費用<br>packing cost</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'packing_cost_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>国内輸送費<br>delively cost</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'delivery_cost_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
            	<?php $key = 'export_expense_1_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸出諸掛1<br>Export expense 1</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
                
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	
            	<?php $key = 'export_expense_1_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
            	<?php $key = 'export_expense_2_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸出諸掛2<br>Export expense 2</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	
             	<?php $key = 'export_expense_2_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
            	<?php $key = 'export_expense_3_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸出諸掛3<br>Export expense 3</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
                
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	
             	<?php $key = 'export_expense_3_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>本船渡し総額<span class="popup_help" id="help_fob_amount">&nbsp;<i class="icon-help-circled"></i></span><br>FOB amount</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
             	<?php $key = 'fob_amount_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>本船渡し単価<span class="popup_help" id="help_fob_unit_price">&nbsp;<i class="icon-help-circled"></i></span><br>FOB unit price</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'fob_unit_price_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>FOB指数<span class="popup_help" id="help_fob_index">&nbsp;<i class="icon-help-circled"></i></span><br>FOB index</p></th>
            	<td class="td_unit">
            		単位：<span class"export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'fob_index_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>


            <tr>
                <th><p>海上輸送費<span class="popup_help" id="help_transport_cost">&nbsp;<i class="icon-help-circled"></i></span></p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'transport_cost_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>その他輸送諸掛1<br>Transport charge1</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'transport_charge_1_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>保険対象増幅率<span class="popup_help" id="help_rate_insurance_coverage">&nbsp;<i class="icon-help-circled"></i></span><br>Increase rate of insurance coverage amount</p></th>
            	<td class="td_unit">
            		単位：%
            	</td>
            	<?php $key = 'rate_insurance_coverage_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>保険適用額<br>Insurance coverage amount</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'insurance_coverage_amount_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>保険率<span class="popup_help" id="help_rate_exchange_diffrence">&nbsp;<i class="icon-help-circled"></i></span></p></th>
            	<td class="td_unit">
            		単位：%
            	</td>
            	<?php $key = 'rate_insurance_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>保険料</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'insurance_price_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>金利利率</p></th>
            	<td class="td_unit">
            		単位：%
            	</td>
            	<?php $key = 'rate_exchange_diffrence_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>金利</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'exchange_diffrence_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>運賃保険料込み総額<span class="popup_help" id="help_export_cif_cip_amount">&nbsp;<i class="icon-help-circled"></i></span><br>CIF/CIP amount</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'export_cif_cip_amount_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>運賃保険料込み単価<span class="popup_help" id="help_export_cif_cip_unt_price">&nbsp;<i class="icon-help-circled"></i></span><br>CIF/CIP unit price</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'export_cif_cip_unt_price_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>CIF指数<span class="popup_help" id="help_export_cif_cip_index">&nbsp;<i class="icon-help-circled"></i></span><br>CIF/CIP index</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"></span>
            	</td>
            	<?php $key = 'export_cif_cip_index_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
		</table>







		<div class="clearfix" style="margin-bottom:5px;">
	    	<h2 style="float:left;width:446px;margin-top:0.8em;margin-bottom:0.3em;padding-left:10px;">輸入国費用</h2>
	    	<p style="float:left;padding-top:0.8em;">輸入国通貨単位：</p>
	       
	   		<div style="float:left;width:200px;">
        		<div class="display_value_<?php echo $categoryId; ?>">
        			<p style="padding-top:0.8em;padding-left:8px"><?php echo $this->escape($this->data['import_unit']); ?></p>
        		</div>
        		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
        			<input type="text" class="input_unit" style="width:80px;" name="import_unit" value="<?php echo $this->escape($this->data['import_unit']); ?>" />
        		</div>
	    		
	    	</div>
		</div>
	    
        <table class="detail">
            <tr>
            	<th><p>為替レートの根拠</p></th>
            	<td class="td_unit">
            	</td>
	        	<td colspan="5">
            		<div class="display_value_<?php echo $categoryId; ?>">
            			<p><?php echo $this->escape($this->data['basis_rate']); ?></p>
            		</div>
            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
            			<input type="text" name="basis_rate" placeholder="(例) MUFG<?php echo date('Y'); ?>年1月～6月の平均レート" value="<?php echo $this->escape($this->data['basis_rate']); ?>" />
            		</div>
	        	</td>
            </tr>

            <tr>
            	<th><p>為替レート<span class="popup_help" id="help_rate">&nbsp;<i class="icon-help-circled"></i></span></p></th>
            	<td class="td_unit">
            		単位：<span class="exchange_unit"><?php echo $this->escape($this->data['import_unit']) . ' / ' . $this->escape($this->data['export_unit']); ?></span>
            	</td>
	        	<td colspan="5">
            		<div class="display_value_<?php echo $categoryId; ?>">
            			<p><?php echo $this->escape($this->data['rate']); ?></p>
            		</div>
            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
            			<input type="text" name="rate" value="<?php echo $this->escape($this->data['rate']); ?>" />
            		</div>
	        	</td>
            </tr>
            
            <tr>
                <th><p>運賃保険料込み単価<br>CIF/CIP unit price</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'import_cif_cip_unit_price_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>運賃保険料込み総額<br>CIF/CIP amount</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'import_cif_cip_amount_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
                <th><p>関税率<br>Duty rate</p></th>
            	<td class="td_unit">
            		単位：%
            	</td>
            	<?php $key = 'duty_rate_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>関税<br>Duty amount</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'duty_amount_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
            	<?php $key = 'import_expense_1_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸入諸掛1<br>Import expense 1</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'import_expense_1_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
            	<?php $key = 'import_expense_2_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸入諸掛2<br>Import expense 2</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'import_expense_2_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>

            <tr>
            	<?php $key = 'import_expense_3_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸入諸掛3<br>Import expense 3</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'import_expense_3_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
            	<?php $key = 'import_expense_4_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸入諸掛4<br>Import expense 4</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
                <?php $key = 'import_expense_4_label'; ?>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'import_expense_4_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
            	<?php $key = 'import_expense_5_label'; ?>
                <th>
                	<p style="float:left;width:200px;">輸入諸掛5<br>Import expense 5</p>
                	<div style="float:left;width:227px;">
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="name"><?php echo $this->escape($this->data[$key]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input type="text" name="<?php echo $key; ?>" placeholder="項目名を入力" value="<?php echo $this->escape($this->data[$key]); ?>" />
	            		</div>
            		</div>
                </th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'import_expense_5_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>その他国内費用1<br>Other expense1</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'other_expense_1_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>その他国内費用2<br>Other expense2</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'other_expense_2_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<div class="display_value_<?php echo $categoryId; ?>">
	            			<p class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		</div>
	            		<div class="edit_value_<?php echo $categoryId; ?>" style="display:none;">
	            			<input class="align_right" type="text" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            		</div>
	            	</td>
            	<?php } ?>
            </tr>  

            <tr>
                <th><p>関税込み持ち込み渡し総額<br>DDP amount</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'ddp_amount_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>関税込み持ち込み渡し単価<span class="popup_help" id="help_insurance_coverage_amount">&nbsp;<i class="icon-help-circled"></i></span><br>DDP unit price</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'ddp_unit_price_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>関税込み持ち込み渡し単価（輸出国通貨）<br>DDP unit price (Export countriy rate)</p></th>
            	<td class="td_unit">
            		単位：<span class="export_unit"><?php echo $this->escape($this->data['export_unit']); ?></span>
            	</td>
            	<?php $key = 'ddp_unit_price_rated_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
            
            <tr>
                <th><p>DDP指数<span class="popup_help" id="help_ddp_index">&nbsp;<i class="icon-help-circled"></i></span><br>DDP index</p></th>
            	<td class="td_unit">
            		単位：<span class="import_unit"><?php echo $this->escape($this->data['import_unit']); ?></span>
            	</td>
            	<?php $key = 'ddp_index_'; ?>
            	<?php for ($count = 1; $count <= 5; $count++) { ?>
	            	<td>
	            		<p id="<?php echo $key . $count; ?>" class="align_right"><?php echo $this->escape($this->data[$key . $count]); ?></p>
	            		<input type="hidden" name="<?php echo $key . $count; ?>" value="<?php echo $this->escape($this->data[$key . $count]); ?>" />
	            	</td>
            	<?php } ?>
            </tr>
        </table>

        
	</div><!-- clearfix -->	
    </form>

    
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;"><div class="menu_frame"><div id="data_area"></div></div></div>
</div>
</div>
</div>

