<?php
$exportTypeList = Shared_Model_Code::codes('export_type');
?>
<script type="text/javascript">
$(function () {

});    
</script>
<style type="text/css">

</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:76px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/price-expense/export-add">新規登録</a>
            </p>
	        <span style=""><strong>原単位・輸出物流</strong></span>
	    </div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/connection/list" method="get">
				<p class="search_condition_title">検索条件</p>

				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">XXX：</p>
                        <select id="status" name="status">
                            <option value="">---</option>
                        	<?php foreach ($connectionStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">XXX：</p>
                        <select id="type" name="type">
                            <option value="">---</option>
                        	<?php foreach ($connectionTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">XXX：</p>
                        <select id="relation_type" name="relation_type">
                            <option value="">---</option>
                        	<?php foreach ($relationTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['relation_type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">XXX：</p>
                        <select id="sales_relation" name="sales_relation">
                            <option value="">---</option>
                        	<?php foreach ($salesRelationList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['sales_relation']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
				</div>	

				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="button" class="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</form>
		</div>
	</div>
	
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:15%;"><p>区分&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:20%;"><p>顧客</p></th>
				<th style="width:20%;"><p>輸送業者</p></th>
				<th><p>案件名</p></th>
				<th style="width:5%;"><p>詳細</p></th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php
					$itemTable = new Shared_Model_Data_Item();
				?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>">
						<td class="desc" all-content="<?php echo $exportTypeList[$each['type']]; ?>">
							<p><?php echo $this->roundText($exportTypeList[$each['type']], 25); ?></p>
						</td>
						
						<td>
							<p><?php echo $each['client_name']; ?></p>
						</td>
						
						<td>
							<p><?php echo $each['delivery_name']; ?></p>
						</td>
						
						<td>
							<p><?php echo $each['title']; ?></p>
						</td>
						
						
						<td>
							<p><a href="/price-expense/export-detail?id=<?php echo $each['id'] ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="5">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

