<?php
?>
<script type="text/javascript">
$(function () {

});    
</script>
<style type="text/css">

</style>

<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong>原単位・送料</strong></span>
    </div>
</div>

	
<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<div class="condition_items clearfix">
		<form id="condition_form" action="/price-expense/postage" method="get">
			<p class="search_condition_title">検索条件</p>

			<div class="condition_items_row clearfix">
				<div class="condition_item">
					<p class="condition_label">キーワード：</p>
					<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
				</div>
				
				<div class="condition_item" style="width:400px;padding-top:23px;">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</div>
		</form>
	</div>
</div>

<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
	<table class="list_default">
		<tr>
			<th style="width:15%;"><p>最終更新日時</p></th>
			<th><p>名称</p></th>
			<th style="width:35%;"><p>標準サイズ</p></th>
			<th style="width:15%;"><p>原価計算用　一律送料</p></th>
			<th style="width:8%;"><p>詳細</p></th>
		</tr>
		
		<?php if (!empty($this->items)) { ?>
			<?php foreach ($this->items as $each) { ?>
				<tr id="<?php echo $each['id']; ?>">
					<td>
						<p><?php echo date('Y-m-d H:i', strtotime($each['updated'])); ?></p>
					</td>
					
					<td class="desc" all-content="<?php echo $this->escape($each['title']); ?>">
						<p><?php echo $this->roundText($this->escape($each['title']), 20); ?></p>
					</td>
					
					<td class="desc" all-content="<?php echo $this->escape($each['size']); ?>">
						<p><?php echo $this->roundText($this->escape($each['size']), 24); ?></p>
					</td>
					
					<td>
						<p style="text-align:right;padding-right:12px;"><?php echo number_format($this->escape($each['standard_price'])); ?>&nbsp;円</p>
					</td>
					
					<td>
						<a class="option" href="javascript:selectPostage('<?php echo $each['id']; ?>', '<?php echo $this->escape($each['title']); ?>', '<?php echo $this->escape($each['standard_price']); ?>');">選択</a>
					</td>
				</tr>
			<?php } ?>
		<?php } else { ?>
			<tr>
				<td colspan="3">
					<p style="text-align:center;">データがありません</p>
				</td>
			</tr>
		<?php } ?>
	</table>

    <div style="padding:2.0em 0;">
    <?php echo $this->pager() ?>
    </div>
            
</div>


