<?php
$payableTemplateTypeList = Shared_Model_Code::codes('payable_template_type');
$payingMethodList = Shared_Model_Code::codes('payable_paying_method_template');
$taxDivisionList = Shared_Model_Code::codes('tax_division');
$bankAccountType = Shared_Model_Code::codes('bank_account_type');
?>
<script type="text/javascript">
var reloadFlag = false;

$(function() {
    $(document).ready(function(){
		$('.datepicker').datepicker();
        $('.datepicker').datepicker("option", "dateFormat", "yy-mm-dd");
        $('.datepicker').datepicker("option", "yearSuffix", '年');
        $('.datepicker').datepicker("option", "monthNames", ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']);
		$('.datepicker').datepicker("option", "showMonthAfterYear", true);
        $('.datepicker').datepicker("option", "dayNames", ['日', '月', '火', '水', '木', '金', '土']);
        $('.datepicker').datepicker("option", "dayNamesMin", ['日', '月', '火', '水', '木', '金', '土']);
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/transaction-payable/template-history?id=<?php echo $this->escape($this->templateId); ?>";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
		jConfirm('登録しますか', '　', function(r) {
            if(r) {
				showSpinner();
		
		        var $form = $('#register_form');
		        var query = $form.serialize();
		        var param = $form.serializeArray();
		
		        $.ajax({
		            type:'POST',
		            dataType:'json',
		            data: param,
		            success: function(res){
		            	stopSpinner();
		                var obj = res;
		                if (obj.result == 'timeout') {
		                    location.href = '/login';
		                    return;
		                    
		                } else if(obj.result == 'OK') {
                            location.href = '/transaction-payable/history-detail?id=' + obj.id;
                            return;
		                    
		                } else {
		                    jAlert('' + obj.message, '　');
		                }
		            },
		            error: function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url: '/transaction-payable/history-add-post?template_id=<?php echo $this->escape($this->templateId); ?>'
				});
            } else {
                return false;
            }
        });
	});
});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:150px;}
table.list_default tr td.column_value select.short {width:300px;}
table.list_default tr td .multi_rows_padding {padding:5px 6px 5px 6px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:400px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>毎月支払管理 - 新規支払予定登録</strong></span>
        </div>
    </div>

    <form id="register_form" action="javascript:void(0);" method="post">
    <div class="clearfix">
	    <?php
        /* 支払予定 */
        $categoryId = 1;
        ?>
        
        <table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">毎月支払内容</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">支払種別</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <p class="display_value_<?php echo $categoryId; ?>">
                    	<?php echo $payableTemplateTypeList[$this->data['template_type']]; ?>
                    </p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">内容</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php echo nl2br($this->escape($this->data['description'])); ?>
                	</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">会計科目</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="account_title_name"><?php 
                		if (!empty($this->accountTitleData)) {
                			echo $this->escape($this->accountTitleData['title']);
                		} else {
                			echo '---';
                		}
                	?></p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">支払先取引先</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="connection_name"><?php 
                		if (!empty($this->connectionData)) {
                			echo $this->escape($this->connectionData['company_name']);
                		} else {
                			echo '---';
                		}
                	?></p>
                </td>
            </tr>
            <tr>
                <td class="column_label"><p class="label_text">支払方法<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	            	<div class="multi_rows_padding">
                		<?php
                			if (!empty($this->data['paying_method'])) {
                				echo $payingMethodList[$this->data['paying_method']];
                			}
                		?>
                	</div>
                </td>
            </tr>
            
            <tr class="paying_method_option paying_method_option_bank" style="<?php if ($this->data['paying_method'] !== (string)Shared_Model_Code::PAYABLE_PAYING_METHOD_BANK && $this->data['paying_method'] !== (string)Shared_Model_Code::PAYABLE_PAYING_METHOD_AUTO) {?>display:none<?php } ?>">
                <td class="column_label"><p class="label_text">支払元銀行口座<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php
                		$bankText = '---';
                		if (!empty($this->bankData)) {
                			$bankText = $this->escape($this->bankData['bank_name'] . '　' . $this->bankData['branch_name'] . '　' . $bankAccountType[$this->bankData['account_type']] . '　' . $this->bankData['account_no']);
                		}
                	?>
                	<p id="paying_bank_name"><?php echo $bankText; ?></p>
                </td>
            </tr>
             
            <tr class="paying_method_option paying_method_option_card" style="<?php if ($this->data['paying_method'] !== (string)Shared_Model_Code::PAYABLE_PAYING_METHOD_CREDIT) {?>display:none<?php } ?>">
                <td class="column_label"><p class="label_text">支払用クレジットカード<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php
                		$cardText = '---';
                		if (!empty($this->cardData)) {
                			$cardText = $this->escape($this->cardData['card_name'] . ' 下4ケタ: ' . $this->cardData['card_no_last4']);
                		}
                	?>
                	<p id="paying_card_name"><?php echo $cardText; ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">支払方法メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="multi_rows_padding">
                		<?php echo nl2br($this->escape($this->data['paying_method_memo'])); ?>
                	</div>
                </td>
            </tr>
        </table>
            
            
        <table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">支払予定</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">支払予定日<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" class="datepicker" id="paying_plan_date" name="paying_plan_date" value="" autocomplete="off" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">支払総額(税込)<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php if ($this->data['template_type'] == (string)Shared_Model_Code::PAYABLE_TEMPLATE_TYPE_FIXED) { ?>
                		<p><?php
                			$currencyText = '';
                			foreach ($this->currencyList as $eachCurrency) {
                				if ($this->data['currency_id'] == $eachCurrency['id']) {
                					$currencyText = $eachCurrency['name'];
                				}
                			}
                			
                			if (!empty($this->data['total_amount'])) {
                				echo number_format($this->data['total_amount']) . '&nbsp;' . $this->escape($currencyText);
                			} else {
                				echo '';
                			}
                		?></p>
                    <?php } else { ?>
		            	<input type="text" style="float:left;width:150px;text-align:right;" id="total_amount" name="total_amount" value="" />
	                    <select style="float:left;width:90px;margin-left:5px;" id="currency_id" name="currency_id">
	                        <option value="">(通貨単位)</option>
	                    	<?php foreach ($this->currencyList as $eachCurrency) { ?>
	                            <option value="<?php echo $eachCurrency['id']; ?>" <?php if ($this->data['currency_id'] == $eachCurrency['id']) { echo 'selected="selected"'; } ?>><?php echo $this->escape($eachCurrency['name']); ?></option>
	                        <?php } ?>
	                    </select>
                    <?php } ?>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">税区分<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php if ($this->data['template_type'] == (string)Shared_Model_Code::PAYABLE_TEMPLATE_TYPE_FIXED) { ?>
                		<p><?php if (!empty($this->data['tax_division'])) { echo $taxDivisionList[$this->data['tax_division']]; } ?></p>
                	<?php } else { ?>
	                    <select class="edit_value_<?php echo $categoryId; ?>" style="width:300px;" id="tax_division" name="tax_division">
	                        <option value="">---</option>
	                    	<?php foreach ($taxDivisionList as $key => $val) { ?>
	                            <option value="<?php echo $key; ?>" <?php if ($this->data['tax_division'] == $key) { echo 'selected="selected"'; } ?>><?php echo $this->escape($val); ?></option>
	                        <?php } ?>
	                    </select>
                    <?php } ?>
                </td>
            </tr>
 
             <tr>
                <td class="column_label"><p class="label_text">消費税</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php if ($this->data['template_type'] == (string)Shared_Model_Code::PAYABLE_TEMPLATE_TYPE_FIXED) { ?>
	                    <p><?php
	                		if (!empty($this->data['tax'])) {
	            				echo number_format($this->data['tax']) . '&nbsp;' . $currencyText;
	            			} else {
	            				echo '';
	            			}
	                    ?></p>
                    <?php } else { ?>
	                	<input type="text" style="float:left;width:150px;text-align:right;" id="tax" name="tax" value="" />
	                	<p style="float:left;"></p>
                	<?php } ?>
                </td>
            </tr>
		</table>

	</div><!-- clearfix -->	
    </form>
          
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

