<?php
$statusList   = Shared_Model_Code::codes('payable_status');
$payableTemplateTypeList = Shared_Model_Code::codes('payable_template_type');
$paymentStatusList   = Shared_Model_Code::codes('payable_payment_status');
?>
<script type="text/javascript">
$(function () {
    $(document).on('click', '.action_menu', function () {
	    var targetId = $(this).attr('target-id');
	    
	    if ($('#action_menu_frame_' + targetId).hasClass('selected')) {
		    $('#action_menu_frame_' + targetId).removeClass('selected');
	    } else {
		    $('.action_menu_frame').removeClass('selected');
		    $('#action_menu_frame_' + targetId).addClass('selected');
	    }
	});
	
    // 下書き
    $(document).on('click', '.update_to_draft', function () {
    	var targetId = $(this).attr('target-id');
		jConfirm('下書きに戻しますか', '　', function(r) {
			if(r) {
				showSpinner();
				$.ajax({
		            type:'POST',
		            dataType:'html',
		            data:'target_id=' + targetId,
		            success:function(res){
		            	stopSpinner();
		                reloadFlag = true;
		                jAlert('下書きに戻しました', '　');
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-payable/update-to-draft'
		        });
		        
			} else {
			    return false;
			}
		});
    });
    
    // 削除
    $(document).on('click', '.delete', function () {
    	var targetId = $(this).attr('target-id');
		jConfirm('本当に削除にしますか', '　', function(r) {
			if(r) {
				showSpinner();
				$.ajax({
		            type:'POST',
		            dataType:'html',
		            data:'target_id=' + targetId,
		            success:function(res){
		            	stopSpinner();
		                reloadFlag = true;
		                jAlert('削除しました', '　');
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-payable/delete'
		        });
		        
			} else {
			    return false;
			}
		});
    }); 
    
    $(document).on('click', '#popup_ok', function () {
    	if (reloadFlag) {
    		location.href = '/transaction-payable/template-history?id=<?php echo $this->escape($this->id); ?>&page=<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->current; ?>&pos=' + $(window).scrollTop();
    	}
    }); 
});    
</script>
<style type="text/css">
table.list_default tr td {overflow:inherit;}
table.list_default tr td a.btn_setting {margin:5px 0 0px 5px;padding:7px 15px 5px 15px;line-height:1;display:block;float:left;cursor:pointer;}
.align_center{text-align:center;margin-right:12px;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<?php if ($this->allowEditing === true && $this->data['status'] !== (string)Shared_Model_Code::PAYABLE_TEMPLATE_STATUS_FINISHED) { ?>
				<p style="position:absolute;width:114px;right:0;">
	                <a class="btn_setting" style="display:block;float:left;width:114px;padding:5px 0;margin:0;border:none;" href="/transaction-payable/history-add?template_id=<?php echo $this->escape($this->id); ?>">新規支払予定登録</a>
	            </p>
            <?php } ?>
	        <span style=""><strong>毎月支払管理 - 支払履歴</strong></span>
	    </div>
    	<?php
            echo $this->partial('transaction-payable/template-menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->id,
    			'data'      => $this->data,
    		));
        ?> 
	</div>

	<div class="clearfix">
		<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
    </div>
    
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:10%;"><p>支払予定日</p></th>
				<th style="width:17%;"><p>ステータス</p></th>
				
				<th style="width:20%;"><p>支払ステータス(支払完了日)</p></th>
				
				<th style="width:8%;"><p>通貨単位</p></th>
				<th><p>支払金額</p></th>
				<th style="width:24%;"><p>登録者名</p></th>
				<th style="width:5%;"><p>詳細</p></th>
			</tr>

			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr id="<?php echo $each['id']; ?>">
						<td>
							<p><?php if (!empty($each['paying_plan_date'])) { echo date('Y-m-d', strtotime($each['paying_plan_date'])); } else { echo '---'; } ?></p>
						</td>

						<td>
							<?php if ($each['status'] === (string)Shared_Model_Code::RECEIVABLE_STATUS_APPROVED) { ?>
								<p><strong><?php echo $statusList[$each['status']]; ?></strong></p>
							<?php } else { ?>
								<p><?php echo $statusList[$each['status']]; ?></p>
							<?php } ?>
						</td>

						<td>
							<?php if ($each['payment_status'] === (string)Shared_Model_Code::PAYABLE_PAYMENT_STATUS_UNPAID) { ?>
								<p><strong class="red"><?php echo $paymentStatusList[$each['payment_status']]; ?></strong></p>
							<?php } else if ($each['payment_status'] === (string)Shared_Model_Code::PAYABLE_PAYMENT_STATUS_PAID) { ?>
								<p><strong><?php echo $paymentStatusList[$each['payment_status']]; ?></strong><?php if (!empty($each['paid_date'])) { echo '(' . date('Y-m-d', strtotime($each['paid_date'])) . ')'; } ?></p>
							<?php } else { ?>
								<p><?php echo $paymentStatusList[$each['payment_status']]; ?></p>
							<?php } ?>
						</td>
						
						<td>
							<p class="align_center"><?php if (!empty($each['currency_id'])) { echo $this->escape($this->currencyList[$each['currency_id']]['name']); } ?></p>
						</td>
						
						<td>
							<?php
								$totaltext = '';
								if (!empty($each['total_amount'])) {
									$totaltext = $this->escape(number_format($each['total_amount']));
								}	
							?>
							<p class="align_right"><?php echo $totaltext; ?></p>
						</td>

						<td>
							<p></p>
						</td>
						
						<td style="position:relative;">
							<?php if (!empty($this->adminProperty['allow_delete_row_data'])) { ?>
								<div class="action_menu_frame" id="action_menu_frame_<?php echo $this->escape($each['id']); ?>">
									<a class="action_menu" target-id="<?php echo $this->escape($each['id']); ?>"><i class="icon-pencil"></i><i class="icon-down-dir-1"></i></a>
								    <ul>
									    <li><a class="update_to_draft" target-id="<?php echo $this->escape($each['id']); ?>">下書きに戻す</a></li>
								    	<li><a class="delete" target-id="<?php echo $this->escape($each['id']); ?>">削除</a></li>
								    </ul>
								</div>
							<?php } ?>
							<p><a href="/transaction-payable/history-detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="8">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>

