<div class="item_title clearfix">
	<p class="item_name"><?php echo $this->escape($this->data['description']); ?></p>
</div>
<?php if ($this->data['status'] == (string)Shared_Model_Code::PAYABLE_STATUS_APPROVED || $this->data['status'] == (string)Shared_Model_Code::PAYABLE_TEMPLATE_STATUS_FINISHED) { ?>
<div class="menu_list clearfix">
<a class="menu <?php if($this->action == 'template-detail') echo "selected"; ?>" href="/transaction-payable/template-detail?id=<?php echo $this->escape($this->id); ?>">支払内容詳細</a>
<a class="menu <?php if($this->action == 'template-history') echo "selected"; ?>" href="/transaction-payable/template-history?id=<?php echo $this->escape($this->id); ?>">支払履歴</a>
</div>
<?php } ?>