<div class="menu_list clearfix">

<a class="menu <?php if($this->action == 'performance') echo "selected"; ?>" href="/manufacture/performance?id=<?php echo $this->id; ?>">製造状況</a>
<a class="menu <?php if($this->action == 'history') echo "selected"; ?>" href="/manufacture/history?id=<?php echo $this->id; ?>">製造履歴</a>

<a class="menu <?php if($this->action == 'step') echo "selected"; ?>" href="/manufacture/step?id=<?php echo $this->id; ?>">製造工程</a>
</div>