<?php

?>
<script type="text/javascript"><!--
$(function() {
    $(document).ready(function(){

    });
});
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:180px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title" style="margin-bottom:9px;">
            <span><strong>製造管理 - 健骨・健歯・健康美　ライシア原粉末</strong></span>
        </div>
    	<?php
            echo $this->partial('manufacture/menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->data['id'],
    		));
        ?>   
    </div>

    <div class="clearfix">
		<table class="list_default">
			<tr>
				<th style="width:10%;">
					<p>工程番号</p>
				</th>

				<th>
					<p>工程名</p>
				</th>

				<th style="width:10%;">
					<p>目標</p>
				</th>
				
				<th style="width:30%;">
					<p>作業量目安</p>
				</th>
				
				<th style="width:5%;">
					<p>詳細</p>
				</th>
			</tr>
			
<?php

$items = array();

$items[] = array(
'step' => '1',
'target_number' => '50',
'title' => '瓶充填',
'standard_time' => '42個/時　84秒/個',
);


$items[] = array(
'step' => '2',
'target_number' => '50',
'title' => 'シール貼',
'standard_time' => '350個/時　9.6秒/個',
);

$items[] = array(
'step' => '3',
'target_number' => '50',
'title' => '緩衝材巻き',
'standard_time' => '200個/時　16秒/個',
);

$items[] = array(
'step' => '4',
'target_number' => '50',
'title' => 'ポリチャック蒸着',
'standard_time' => '500個/時　6秒/個',
);

$items[] = array(
'step' => '5',
'target_number' => '50',
'title' => '出荷',
'standard_time' => '10分',
);

$this->items = $items;

?>

			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>">
						<td>
							<p><?php echo $this->escape($each['step']); ?></p>
						</td>

						<td>
							<p><?php echo $this->escape($each['title']); ?></p>
						</td>
						
						<td>
							<p><?php echo $this->escape($each['target_number']); ?></p>
						</td>


						
						<td>
							<p><?php echo $this->escape($each['standard_time']); ?></p>
						</td>
						
						<td>
							<p>
								<a href="/manufacture/step-detail?id=<?php echo $each['id']; ?>">表示</a>
							</p>
						</td>

					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="7">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>
	</div><!-- clearfix -->
              

</div>
</div>
</div>
</div>

