<?php
$typeList              = Shared_Model_Code::codes('item_type');
$inventoryTypeList     = Shared_Model_Code::codes('inventory_type');
?>
<script type="text/javascript">
var pos = 0;
var reloadFlag = false;
var rowCount = 0;
var targetItemRow = '';

$(function() {
    $(document).ready(function(){
		$('.datepicker').datepicker();
        $('.datepicker').datepicker("option", "dateFormat", "yy-mm-dd");
        $('.datepicker').datepicker("option", "yearSuffix", '年');
        $('.datepicker').datepicker("option", "monthNames", ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']);
		$('.datepicker').datepicker("option", "showMonthAfterYear", true);
        $('.datepicker').datepicker("option", "dayNames", ['日', '月', '火', '水', '木', '金', '土']);
        $('.datepicker').datepicker("option", "dayNamesMin", ['日', '月', '火', '水', '木', '金', '土']);
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/stock-inventory/history";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
		jConfirm('登録しますか', '　', function(r) {
            if(r) {
				showSpinner();
		
		        var $form = $('#register_form');
		        var query = $form.serialize();
		        var param = $form.serializeArray();
		
		        $.ajax({
		            type:'POST',
		            dataType:'json',
		            data: param,
		            success: function(res){
		            	stopSpinner();
		                var obj = res;
		                if (obj.result == 'timeout') {
		                    location.href = '/login';
		                    return;
		                    
		                } else if(obj.result == 'OK') {
                            location.href = '/stock-inventory/form?id=' + obj.id;
                            return;
		                    
		                } else {
		                    jAlert('' + obj.message, '　');
		                }
		            },
		            error: function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url: '/stock-inventory/create-post'
				});
            } else {
                return false;
            }
        });
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/stock-inventory/history';
        }
    });

});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:150px;}
table.list_default tr td.column_value select.short {width:300px;}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:400px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>新規棚卸登録</strong></span>
        </div>
    </div>

    <form id="register_form" action="javascript:void(0);" method="post">
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">基本情報</p>
                </th>
            </tr>
		</table>   
        <table class="list_default" style="margin-bottom:13px;">            
            <tr>
                <td class="column_label"><p class="label_text">実施日<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <input type="text" class="datepicker" name="target_date" value="" autocomplete="off" maxlength="" />
                </td>
            </tr>
			
            <tr>
                <td class="column_label"><p class="label_text">種別<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <select id="inventory_type" name="inventory_type" style="width:280px;">
	                	<option value="">---</option>
	                	<?php foreach ($inventoryTypeList as $key => $value) { ?>
	                		<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
	                	<?php } ?>
	                </select>
                </td>
            </tr>
			
			
			
            <tr>
                <td class="column_label"><p class="label_text">在庫資材種別<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <select id="stock_type" name="stock_type" style="width:280px;">
	                	<option value="">---</option>
	                	<?php foreach ($typeList as $key => $value) { ?>
	                		<option value="<?php echo $key; ?>"><?php echo $value; ?></option>
	                	<?php } ?>
	                </select>
                </td>
            </tr>
		</table>
    </div>
	         
</div>
</div>
</div>
</div>

