<?php
$paymentStatusList   = Shared_Model_Code::codes('receivable_payment_status');
?>
<script type="text/javascript">
$(function () {
	$(".clear_form").bind("click", function(){
	    $(this.form).find('textarea, :text, :hidden:not("#view_type, #search, #page")').val("");
	    $(this.form).find('select option').removeAttr('selected');
	    $('.target_text').html('');
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
	});
	
    // 会計科目 選択ポップアップ表示
    $(document).on('click', '#select_account_title', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/office/accounting-select', null, function () {stopSpinner();});
    });
    
    // 会計科目 リセット
    $(document).on('click', '#reset_account_title', function () {
		$('#account_title_name_display').html('');
		$('#account_title_name').val('');
		$('#account_title_id').val('');
	});
	
	// 申請者 ポップアップ表示
    $(document).on('click', '#select_applicant_user', function () {
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/user/list-select', null, function () {stopSpinner();});
	});
    
	// 申請者 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    // 申請者 リセット
    $(document).on('click', '#reset_applicant_user', function () {
		$('#applicant_user_name_display').html('');
		$('#applicant_user_name').val('');
		$('#applicant_user_id').val('');
	});

    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });
    
    // 取引先 リセット
    $(document).on('click', '#reset_connection', function () {
		$('#connection_name_display').html('');
		$('#connection_name').val('');
		$('#connection_id').val('');
	});
	
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// 会計科目 選択完了
function selectAccountTitle(id, title) {
	$('#account_title_name_display').html(title);
	$('#account_title_name').val(title);
	$('#account_title_id').val(id);
	$('.btn_close').click();
}

// 申請者 一覧ページ切り替え
function pageUser(pageNo) {
	updateUserList(pageNo)
}

// 申請者 一覧更新
function updateUserList (pageNo) {
    var $form = $('#user_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/user/list-select?page=' + pageNo,
    });
}

// 申請者 選択完了
function selectUser(id, departmentName, name, departmentNameEn, nameEn) {
	$('#applicant_user_name_display').html(departmentName + '　' + name);
	$('#applicant_user_name').val(departmentName + '　' + name);
	$('#applicant_user_id').val(id);
	$('.btn_close').click();
}

// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form = $('#connection_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/connection/list-select?page=' + pageNo,
    });
}

// 取引先 選択完了
function selectConnection(id, displayId, name) {
	$('#connection_name_display').html(name);
	$('#connection_name').val(name);
	$('#connection_id').val(id);
	$('.btn_close').click();
}

</script>
<style type="text/css"><!--
table.list_default tr:hover td {background:#deeeff;}
table.list_default tr.gray_out td {background-color:#eee}
table.list_default tr.gray_out:hover td {background:#eee;}
table.list_default tr th p, table.list_default tr td p {padding-left:5px;}
table.list_default tr th p.align_right, table.list_default tr td p.align_right {text-align:right;padding-left:0;padding-right:5px;}
table.list_default tr th p.align_center, table.list_default tr td p.align_center {text-align:center;padding-left:0;}
.view_type_list {}
.view_type_list a.view_type {display:block;float:left;padding:11px 20px 0;height:22px;line-height:1;text-decoration:none;background-color: #c0f7fa;text-align:center;font-size: 1.1em;margin-right:5px;}
.view_type_list a.view_type.selected {background-color:#098d94;color:#fff;}
div.total {border:1px solid #ccc;background-color:#fafafa;padding:10px 11px;}
div.total p{font-size:1.2em;font-weight:bold;line-height:1.3}
div.total p.currency {float:left;width:50px;text-align:right}
div.total p.account_count {float:left;width:60px;text-align:right}
div.total p.total_amount {float:left;width:170px;text-align:right}
a.prev, a.next {text-decoration:none;background-color:#42adff;color:#fff;display:block;padding:5px 5px 3px;width:70px;text-align:center;float:left;font-weight:bold}
a.prev:visited, a.next:visited { color:#fff;}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin:5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:5px auto 10px;padding:7px 35px 5px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
--></style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	        <span><strong>入金完了確認</strong></span>
	    </div>
	</div>

	<div class="view_type_list clearfix">
        <a class="view_type <?php if ($this->viewType == 'history') { echo 'selected'; }?>" href="/transaction-recieved/list?view_type=history">全一覧表示</span></a>
        <a class="view_type <?php if ($this->viewType == 'monthly') { echo 'selected'; }?>" href="/transaction-recieved/list?view_type=monthly">月別表示</span></a>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/transaction-recieved/list" method="get">
				<input type="hidden" id="search" name="search" value="1">
				<input type="hidden" id="page" name="page" value="1">
				<input type="hidden" id="view_type" name="view_type" value="<?php echo $this->escape($this->viewType); ?>">
				
				<?php if ($this->viewType == 'monthly') { ?>
					<p class="search_condition_title" >対象月</p>
					<div class="condition_items_row clearfix" style="margin-bottom:10px;">
						<div class="condition_item clearfix" style="height:50px;width:650px">
							<a class="prev" href="<?php echo $this->escape($this->prevUrl); ?>">＜前月</a>
	                        <p style="font-size:2.4em;font-weight:bold;float:left;width:200px;text-align:center;"><?php echo $this->conditions['year'] . '-' . $this->conditions['month']; ?></p>
	                        
	                        <a class="next" href="<?php echo $this->escape($this->nextUrl); ?>">翌月＞</a>
	                        
	                        <?php /*<a class="next" href="<?php echo $this->escape($this->nextUrl); ?>">CSV</a>*/ ?>
						</div>
						
						<!--
						<div class="condition_item" style="height:32px;width:180px">
	                        <select id="year" name="year" style="width:90px">
	                        	<?php foreach ($yearList as $key => $value) { ?>
	                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['year']) echo 'selected="selected"';?>><?php echo $value; ?></option>
	                            <?php } ?>
	                        </select>
	                        <select id="month" name="month" style="width:60px">
	                        	<?php foreach ($monthList as $key => $value) { ?>
	                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['month']) echo 'selected="selected"';?>><?php echo $value; ?></option>
	                            <?php } ?>
	                        </select>
						</div>
						
						
						<div class="condition_item" style="height:32px;width:100px">
							<input type="submit" class="submit" style="display:inline-block;width:116px;" value="表示" />
						</div>
						-->
					</div>
				<?php } ?>
				<p class="search_condition_title">絞込条件</p>

				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="payment_status" name="payment_status">
                            <option value="">---</option>
                        	<?php foreach ($paymentStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['payment_status']) echo 'selected="selected"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">通貨単位：</p>
                        <select id="currency_id" name="currency_id">
                            <option value="">---</option>
                        	<?php foreach ($this->currencyList as $each) { ?>
                                <option value="<?php echo $each['id']; ?>" <?php if ((string)$each['id'] === $this->conditions['currency_id']) echo 'selected="selected"';?>><?php echo $each['name']; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">会計科目：</p>
						<div class="input_box_fake">
							<span class="target_text" id="account_title_name_display"><?php echo $this->conditions['account_title_name']; ?></span>
							<a class="reset_popup" id="reset_account_title" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_account_title" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="account_title_name" name="account_title_name" value="<?php echo $this->conditions['account_title_name']; ?>" />
						<input type="hidden" id="account_title_id" name="account_title_id" value="<?php echo $this->conditions['account_title_id']; ?>" />
					</div>
					
					<div class="condition_item">
						<p class="condition_label">申請者：</p>
						<div class="input_box_fake">
							<span class="target_text" id="applicant_user_name_display"><?php echo $this->conditions['applicant_user_name']; ?></span>
							<a class="reset_popup" id="reset_applicant_user" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_applicant_user" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="applicant_user_name" name="applicant_user_name" value="<?php echo $this->conditions['applicant_user_name']; ?>" />
						<input type="hidden" id="applicant_user_id" name="applicant_user_id" value="<?php echo $this->conditions['applicant_user_id']; ?>" />
					</div>	
				</div>

				<div class="condition_items_row clearfix">	
					<div class="condition_item">
						<p class="condition_label">支払元：</p>
						<div class="input_box_fake">
							<span class="target_text" id="connection_name_display"><?php echo $this->conditions['connection_name']; ?></span>
							<a class="reset_popup" id="reset_connection" href="javascript:void(0);"><span><i class="icon-cancel"></i></span></a>
							<a class="select_popup" id="select_connection" href="javascript:void(0);"><span>選択</span></a>
						</div>
						<input type="hidden" id="connection_name" name="connection_name" value="<?php echo $this->conditions['connection_name']; ?>" />
						<input type="hidden" id="connection_id" name="connection_id" value="<?php echo $this->conditions['connection_id']; ?>" />
					</div>
				</div>
				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="submit" class="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</form>
		</div>
	</div>


	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="total">			
			<div class="clearfix">
				<p style="float:left;width:200px"><?php if ($this->viewType == 'monthly') { ?>対象月<?php } ?>未入金件数：<?php echo $this->escape($this->unrecievedTotal['total_count']); ?>件</p>
				<p style="float:left;width:50px">総計：</p>
				<div style="float:left;width:500px">
					<?php foreach ($this->unrecievedTotal as $eachTotal) { ?>
						<?php if ($eachTotal['item_count'] > 0) { ?>
							<div class="clearfix">
								<p class="currency"><?php echo $this->escape($eachTotal['name']); ?></p>
								<p class="account_count"> (<?php echo $this->escape($eachTotal['item_count']); ?>件)</p>
								<p class="total_amount"><?php echo number_format($this->escape($eachTotal['total'])); ?></p>
							</div>
						<?php } ?>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
	
	
	<?php if ($this->viewType == 'monthly') { ?>
		<div class="clearfix">
			<p style="float:right;margin-bottom:13px;">全<?php echo number_format(count($this->items)); ?>件</p>
	    </div>
	<?php } else { ?>
		<div class="clearfix">
			<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
	    </div>
    <?php } ?>
    
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style="width:9%;"><p>発生日</p></th>
				<th style="width:9%;"><p>入金予定日</p></th>
				<th style="width:8%;"><p>ステータス</p></th>
				
				<th style="width:3.5%;"><p class="align_center">毎月</p></th>
				<th style="width:7%;"><p>会計科目&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:9%;"><p>摘要&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:7%;"><p>採算コ&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:6%;"><p class="align_center">通貨単位</p></th>
				<th style="width:9%;"><p>金額</p></th>
				<th><p>支払元&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:9%;"><p>対象請求書ID</p></th>
				<th style="width:8%;"><p>登録者&nbsp;<i class="icon-info-circle"></i></p></th>
				<th style="width:5%;"><p class="align_center">詳細</p></th>
			</tr>
				
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<?php
						$grayOut = '';
						if ($each['payment_status'] === (string)Shared_Model_Code::PAYABLE_TEMPLATE_STATUS_FINISHED) {
							$grayOut = 'class="gray_out"';
						}
					?>
					<tr <?php echo $grayOut; ?>>
						<td>
							<p><?php
								if (!empty($each['accrual_date'])) {
									echo date('Y-m-d', strtotime($each['accrual_date']));
								} else {
									echo '---';
								}
							 ?></p>
						</td>
						
						<td>
							<p><?php echo date('Y-m-d', strtotime($each['receive_plan_date'])); ?></p>
						</td>
						
						<td>
							<?php if ($each['status'] === (string)Shared_Model_Code::RECEIVABLE_STATUS_DRAFT) { ?>
								<p>下書き</p>
							<?php } else { ?>
								<?php if ($each['payment_status'] === (string)Shared_Model_Code::RECEIVABLE_PAYMENT_STATUS_RECEIVED) { ?>
									<p><strong><?php echo $paymentStatusList[$each['payment_status']]; ?></strong></p>
								<?php } else { ?>
									<p><?php echo $paymentStatusList[$each['payment_status']]; ?></p>
								<?php } ?>
							<?php } ?>
						</td>

						<td>
							<p class="align_center"><?php if ($each['type'] === (string)Shared_Model_Code::RECEIVABLE_TYPE_MONTHLY) { echo '●'; } ?></p>
						</td>
						
						<td class="desc" all-content="<?php echo $this->escape($this->accountTitleList[$each['account_title_id']]['title']); ?>">
							<p><?php echo $this->roundText($this->escape($this->accountTitleList[$each['account_title_id']]['title']), 4); ?></p>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['memo']); ?>">
							<p><?php echo $this->roundText($this->escape($each['memo']), 6); ?></p>
						</td>
						
						
						<?php
						$groupTitle = '---';
						if (array_key_exists($each['account_totaling_group_id'], $this->groupList)) {
							$groupTitle = $this->groupList[$each['account_totaling_group_id']];
						}
						?>
						<td class="desc" all-content="<?php echo $this->escape($groupTitle); ?>">
							<p style="padding-left:3px"><?php echo $this->escape($this->roundText($groupTitle, 4)); ?></p>
						</td>
						
						<td>
							<p class="align_center"><?php if (!empty($each['currency_id'])) { echo $this->escape($this->currencyList[$each['currency_id']]['name']); } ?></p>
						</td>
						
						<td>
							<?php
								$totaltext = '';
								if (!empty($each['total_amount'])) {
									$totaltext = $this->escape(number_format($each['total_amount']));
								}	
							?>
							<p class="align_right"><?php echo $totaltext; ?></p>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['company_name']); ?>">
							<p><?php echo $this->roundText($this->escape($each['company_name']), 7); ?></p>
						</td>
						
						<td>
							<p><?php echo $this->escape($each['invoice_display_id']); ?></p>
						</td>

						<td class="desc" all-content="<?php echo $this->escape($each['user_name']); ?>">
							<p><?php echo $this->roundText($this->escape($each['user_name']), 5); ?></p>
						</td>

						<td>
							<p class="align_center"><a href="/transaction-recieved/detail?id=<?php echo $this->escape($each['id']); ?>">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="13">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>
