<?php
$receivableTemplateTypeList = Shared_Model_Code::codes('receivable_template_type');
$payingMethodList = Shared_Model_Code::codes('payable_paying_method_template');
$taxDivisionList = Shared_Model_Code::codes('tax_division');
$bankAccountType = Shared_Model_Code::codes('bank_account_type');
?>
<script type="text/javascript">
var reloadFlag = false;

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

function dragover(e) {
    e.preventDefault();
}
					
function drop(id, e) {
	$('#' + id + '_add_image_box').removeClass('over');
	e.preventDefault();
	var files = e.dataTransfer.files;
  
	if (files.length > 1) {
  		jAlert('ファイルは一枚ずつドロップしてください。', 'エラー');
 	 	return;
	}

    // アップロード処理へ
    fileUpload(id, files[0]);
}

function fileUpload(id, fd) {
    var formData = new FormData();
    formData.append('file', fd);
	
	showSpinner();
	
    $.ajax({
      async: true,
      type: 'POST',
      contentType: false,
      processData: false,
      url: '/transaction-recieved/upload',
      data: formData,
      dataType :'json'
    }).done(function(res){
    	stopSpinner();
    	
        var obj = res;
        if (obj.result == 'timeout') {
            location.href = '/login';
            return;            
        } else if(obj.result == true) {
        	$('#' + id + '_file_name_text').html(obj.file_name);
        	$('#' + id + '_file_name').val(obj.file_name);
        	$('#' + id + '_temp_file_name').val(obj.temp_file_name);
        } else {
        	jAlert('予期せぬエラーが発生しました', 'エラー');
        }
    });
}

$(function() {
    $(document).ready(function(){
		$('.datepicker').datepicker();
        $('.datepicker').datepicker("option", "dateFormat", "yy-mm-dd");
        $('.datepicker').datepicker("option", "yearSuffix", '年');
        $('.datepicker').datepicker("option", "monthNames", ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']);
		$('.datepicker').datepicker("option", "showMonthAfterYear", true);
        $('.datepicker').datepicker("option", "dayNames", ['日', '月', '火', '水', '木', '金', '土']);
        $('.datepicker').datepicker("option", "dayNamesMin", ['日', '月', '火', '水', '木', '金', '土']);
        
        var result = $("#sortable_column_4").sortable("toArray");
	    $('input#hidden_contents_order_4').val(result);
	    
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/transaction-recieved/template-history?id=<?php echo $this->escape($this->templateId); ?>";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
		jConfirm('登録しますか', '　', function(r) {
            if(r) {
				showSpinner();
		
		        var $form = $('#register_form');
		        var query = $form.serialize();
		        var param = $form.serializeArray();
		
		        $.ajax({
		            type:'POST',
		            dataType:'json',
		            data: param,
		            success: function(res){
		            	stopSpinner();
		                var obj = res;
		                if (obj.result == 'timeout') {
		                    location.href = '/login';
		                    return;
		                    
		                } else if(obj.result == 'OK') {
                            location.href = '/transaction-recieved/history-detail?id=' + obj.id;
                            return;
		                    
		                } else {
		                    jAlert('' + obj.message, '　');
		                }
		            },
		            error: function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url: '/transaction-recieved/history-add-post?template_id=<?php echo $this->escape($this->templateId); ?>'
				});
            } else {
                return false;
            }
        });
	});
	
    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });

    // 行追加
    $(document).on('click', '.btn_add_column', function () {
    	var categoryId = $(this).attr('target-category');
    	if (categoryId == '4') {
	        var uuid = guid();
	        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', uuid + '_file_name_text').attr('name', uuid + '_file_name_text');
	        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', uuid + '_file_name').attr('name', uuid + '_file_name');
	        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', uuid + '_temp_file_name').attr('name', uuid + '_temp_file_name');
	        $('.column_copy_base_' + categoryId + ' .summary').attr('id', uuid + '_summary').attr('name', uuid + '_summary');
			$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', uuid + '_add_image_box').attr('ondrop', "drop('" + uuid + "',event)");
			$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);
			
	        var $clone = $('.column_copy_base_' + categoryId).clone(true);
	        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));
	        $('.column_copy_base_' + categoryId + ' .file_name_text').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .file_name').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .temp_file_name').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .summary').attr('id', '');
			$('.column_copy_base_' + categoryId + ' .add_image_box').attr('id', '');
	        
	        // ファイルのドロップ時エフェクト
			var targetE = document.getElementById(uuid + '_add_image_box');
			var innerFlag = false;
			
			targetE.addEventListener('dragenter', function () {
			    innerFlag = true;
			}, false);
			
			targetE.addEventListener('dragover', function () {
			    innerFlag = false;
			    targetE.className = 'add_image_box over';
			}, false);
			
			targetE.addEventListener('dragleave', function () {
			    if (innerFlag) {
			        innerFlag = false;
			    } else {
			        targetE.className = 'add_image_box';
			    }
			}, false);
		
	        $('.column_copy_base_' + categoryId + ' td.added_row').each(function(){
	            $(this).css('width', $(this).width() +'px');
	        });

	        var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
	    }
    });
    
    // 行削除
    $(document).on('click', '.delete_button', function () {
    	var categoryId = $(this).attr('target-category');
    	var targetId   = $(this).attr('target-row');
		$("#sortable_column_" + categoryId + ' tr#' + targetId).remove();
		
        var result = $("#sortable_column_" + categoryId).sortable("toArray");
        $('input#hidden_contents_order_' + categoryId).val(result);
    });
});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:150px;}
table.list_default tr td.column_value select.short {width:300px;}
table.list_default tr td .multi_rows_padding {padding:5px 6px 5px 6px;}

a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:400px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>毎月入金管理 - 新規入金予定登録</strong></span>
        </div>
    </div>

    <form id="register_form" action="javascript:void(0);" method="post">
    <div class="clearfix">
	    <?php
        /* 支払予定 */
        $categoryId = 1;
        ?>
        
        <table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">毎月入金内容</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">入金種別</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                    <p class="display_value_<?php echo $categoryId; ?>">
                    	<?php echo $receivableTemplateTypeList[$this->data['template_type']]; ?>
                    </p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">内容</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php echo nl2br($this->escape($this->data['description'])); ?>
                	</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">会計科目</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="account_title_name"><?php 
                		if (!empty($this->accountTitleData)) {
                			echo $this->escape($this->accountTitleData['title']);
                		} else {
                			echo '---';
                		}
                	?></p>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">採算コード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <?php
	                	$groupData = NULL;
	                	if (!empty($this->data['account_totaling_group_id'])) {
		                	$totalingGroupTable = new Shared_Model_Data_AccountTotalingGroup();
		                	$groupData = $totalingGroupTable->getById($this->adminProperty['management_group_id'], $this->data['account_totaling_group_id']);
		                }
			        ?>
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
	                	<?php
			                if (!empty($groupData)) {
			                	echo $this->escape($groupData['category_name'] . '　＞　' . $groupData['title']);
		                	} else {
			                	echo '---';
		                	}
		                ?>
	                </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">支払元取引先</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="connection_name"><?php 
                		if (!empty($this->connectionData)) {
                			echo $this->escape($this->connectionData['company_name']);
                		} else {
                			echo '---';
                		}
                	?></p>
                </td>
            </tr>
        </table>
            
            
        <table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">入金予定</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr class="paying_method_option paying_method_option_bank">
                <td class="column_label"><p class="label_text">入金予定口座<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php
                		$bankText = '---';
                		if (!empty($this->bankData)) {
                			$bankText = $this->escape($this->bankData['bank_name'] . '　' . $this->bankData['branch_name'] . '　' . $bankAccountType[$this->bankData['account_type']] . '　' . $this->bankData['account_no']);
                		}
                	?>
                	<p id="bank_name"><?php echo $bankText; ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">入金予定日<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" class="datepicker" id="receive_plan_date" name="receive_plan_date" value="" autocomplete="off" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">入金額(税込)<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php if ($this->data['template_type'] == (string)Shared_Model_Code::RECEIVABLE_TEMPLATE_TYPE_FIXED) { ?>
                		<p><?php
                			$currencyText = '';
                			foreach ($this->currencyList as $eachCurrency) {
                				if ($this->data['currency_id'] == $eachCurrency['id']) {
                					$currencyText = $eachCurrency['name'];
                				}
                			}
                			
                			if (!empty($this->data['total_amount'])) {
                				echo number_format($this->data['total_amount']) . '&nbsp;' . $this->escape($currencyText);
                			} else {
                				echo '';
                			}
                		?></p>
                    <?php } else { ?>
		            	<input type="text" style="float:left;width:150px;text-align:right;" id="total_amount" name="total_amount" value="" />
	                    <select style="float:left;width:90px;margin-left:5px;" id="currency_id" name="currency_id">
	                        <option value="">(通貨単位)</option>
	                    	<?php foreach ($this->currencyList as $eachCurrency) { ?>
	                            <option value="<?php echo $eachCurrency['id']; ?>" <?php if ($this->data['currency_id'] == $eachCurrency['id']) { echo 'selected="selected"'; } ?>><?php echo $this->escape($eachCurrency['name']); ?></option>
	                        <?php } ?>
	                    </select>
                    <?php } ?>
                </td>
            </tr>
		</table>

	    <?php
        /* 参考ファイルアップロード */
        $categoryId = 4;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
		<table class="list_default" style="margin-bottom:0;">
            <tr>
            	<?php if ($this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_DRAFT || $this->data['status'] == Shared_Model_Code::PAYABLE_STATUS_MOD_REQUEST) { ?>
	                <th class="border-left border-top border-bottom">
	                    <p class="label_text strong">参考ファイルアップロード</p>
	                </th>
	                <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php } else { ?>
	                <th class="border-left border-top border-bottom border-right">
	                    <p class="label_text strong">参考ファイルアップロード</p>
	                </th>
                <?php } ?>
            </tr>
		</table>   
        <table class="list_default" style="margin-bottom:0;">            
			<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
        	</tbody>
		</table>
		<div class="clearfix" style="border-bottom:1px solid #ccc;height:34px;">
            <p style="text-align:center;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
        </div>
		<input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="file_list" value="" />
		
	</div><!-- clearfix -->	
    </form>
	
	<!-- copy base -->
    <?php
    /* 参考ファイルアップロード */
    $categoryId = 4;
    ?>
    <table class="list_default" style="display:none;">
        <tr class="column_copy_base_<?php echo $categoryId; ?>" id="">
			<td class="column_value">
				<div class="clearfix">
					<div style="float:left;width:360px;">
						<div class="clearfix" style="margin-bottom:5px">
							<div style="float:left;width:50px;padding:15px 0 0 10px;">
								<i class="budicon-equal" style="color:#aaa;font-size:48px;"></i>
							</div>
							<div style="float:left;width:300px;">
								<div class="multi_rows_padding" style="padding-left:18px;"><span class="file_name_text" id="##_file_name_text">(ファイル名)</span></div>
								<input type="hidden" class="file_name" id="##_file_name" name="##_file_name" value="" />
								<input type="hidden" class="temp_file_name" id="##_temp_file_name" name="##_temp_file_name" value="" />  
							</div>
						</div>
						<div class="add_image_box" id="##_add_image_box" ondragover="dragover(event)" ondrop="drop(##,event)" style="margin-bottom:13px;">
							<i class="icon-upload-cloud" style="font-size:60px;color:#888;"></i><br>ファイルをドラッグ&amp;ドロップしてください
						</div>
					</div>
					<div style="float:left;margin-left:10px;width:670px;">
						<p>メモ:</p>
						<textarea class="summary" name="##_summary" style="margin-top:9px;height:176px;margin-bottom:6px;"><?php echo $this->escape($this->documentData['summary']); ?></textarea>
					</div>
				</div>
			</td>
            <td class="td_action">
            	<div class="delete_btn_frame">
            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row=""><i class="icon-cancel"></i></a>
            	</div>
            </td>
        </tr>
    </table>    
	<!-- copy base -->

  
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

