<?php
$taxDivisionList    = Shared_Model_Code::codes('tax_division');
$receivableTypeList = Shared_Model_Code::codes('receivable_type');
$paymentStatusList  = Shared_Model_Code::codes('receivable_payment_status');
$bankAccountType    = Shared_Model_Code::codes('bank_account_type');
?>
<script type="text/javascript">
var pos = 0;
var editing = false;
var reloadFlag = false;
var rowCount = 0;
var targetOrderRow = '';

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

function dragover(e) {
    e.preventDefault();
}
					
function drop(id, e) {
	$('#' + id + '_add_image_box').removeClass('over');
	e.preventDefault();
	var files = e.dataTransfer.files;
  
	if (files.length > 1) {
  		jAlert('ファイルは一枚ずつドロップしてください。', 'エラー');
 	 	return;
	}

    // アップロード処理へ
    fileUpload(id, files[0]);
}

function fileUpload(id, fd) {
    var formData = new FormData();
    formData.append('file', fd);
	
	showSpinner();
	
    $.ajax({
      async: true,
      type: 'POST',
      contentType: false,
      processData: false,
      url:'/transaction-recieved/upload',
      data:formData,
      dataType:'json'
    }).done(function(res){
    	stopSpinner();
    	
        var obj = res;
        if (obj.result == 'timeout') {
            location.href = '/login';
            return;            
        } else if(obj.result == true) {
        	$('#' + id + '_file_name_text').html(obj.file_name);
        	$('#' + id + '_file_name').val(obj.file_name);
        	$('#' + id + '_temp_file_name').val(obj.temp_file_name);
        } else {
        	jAlert('予期せぬエラーが発生しました', 'エラー');
        }
    });
}

$(function() {
    $(document).ready(function(){
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->posTop; ?>);
        <?php } ?>
        
		$('.datepicker').datepicker();
        $('.datepicker').datepicker("option", "dateFormat", "yy-mm-dd");
        $('.datepicker').datepicker("option", "yearSuffix", '年');
        $('.datepicker').datepicker("option", "monthNames", ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']);
		$('.datepicker').datepicker("option", "showMonthAfterYear", true);
        $('.datepicker').datepicker("option", "dayNames", ['日', '月', '火', '水', '木', '金', '土']);
        $('.datepicker').datepicker("option", "dayNamesMin", ['日', '月', '火', '水', '木', '金', '土']);
        
        Tipped.create('#help_memo', "記載例：<br>・〇〇株式会社 A氏とカフェにて打ち合わせ<br>・タクシー　梅田〜新大阪<br>・〇〇社接待　居酒屋XX<br>・東京出張のため新幹線チケット購入 営業部2名<br>・80円切手　30枚<br>・ウイルス対策ソフト　5ライセンス購入");
        
        <?php if (!empty($this->data['accrual_date'])) { ?>
        $("#accrual_date").datepicker("setDate", "<?php echo date('Y-m-d', strtotime($this->data['accrual_date'])); ?>");
        <?php } ?> 
        
        <?php if (!empty($this->data['receive_plan_date'])) { ?>
        $("#receive_plan_date").datepicker("setDate", "<?php echo date('Y-m-d', strtotime($this->data['receive_plan_date'])); ?>");
        <?php } ?>

        <?php if (!empty($this->data['received_date'])) { ?>
        $("#received_date").datepicker("setDate", "<?php echo date('Y-m-d', strtotime($this->data['received_date'])); ?>");
        <?php } ?>
    });			    

    
    // 編集
    $(document).on('click', '.btn_edit_category', function () {
    	if (editing == true) {
    		jAlert('複数のカテゴリを同時に編集することはできません', 'エラー');
    		return false;
    	}
    
        var categoryId = $(this).attr('category_id');
        
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
    
        // ×,保存ボタン
        $('#cancel_category_' + categoryId).show();
        $('th#edit_category_' + categoryId).addClass('edit_mode');
        $(this).removeClass('btn_edit_category').addClass('btn_save_category');
        $('#btn_edit_label_' + categoryId).html('保存');
       
        //if (categoryId =='2' || categoryId =='4') {
        //	var result = $("#sortable_column_" + categoryId).sortable("toArray");
	    //    $('input#hidden_contents_order_' + categoryId).val(result);
	    //}
	    
	    editing = true;
    });
    
	// 保存
    $(document).on('click', '.btn_save_category', function () {
        var button = $(this);
        var categoryId = $(this).attr('category_id');
        var $form = $('#form_category_' + categoryId);
        var params = $form.serializeArray();
		
		var apiUrl = '';
		
		if (categoryId == '1') {
			apiUrl = '/transaction-recieved/update-basic?id=<?php echo $this->id ?>';
		} else if (categoryId == '2') {
			apiUrl = '/transaction-recieved/update-summary?id=<?php echo $this->id ?>';
		} else if (categoryId == '3') {
			apiUrl = '/transaction-recieved/update-payment?id=<?php echo $this->id ?>';
		} else {
			return;
		}
		
		showSpinner();
        $.ajax({
            type:'POST',
            dataType:'json',
            data:params,
            success:function(res){
            	stopSpinner();
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error:function(){
            	stopSpinner();
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url:apiUrl,
        });
    });

    $(document).on('click', '#popup_ok', function () {
    	if (reloadFlag) {
    		location.href = '/transaction-recieved/site-detail?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
    	}
    });
    
    // 編集中止
    $(document).on('click', '.btn_cancel_category', function () {
        var categoryId = $(this).attr('category_id');
        location.href = '/transaction-recieved/site-detail?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
    });
    
    $(".sortable_column").sortable({
        items:"tr:not(.not-sortable)",
        update:function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay:100,
        stop:function (event, ui) {},
        start:function (event, ui) {}
    });

    
    // 支払い方法
    $(document).on('change', '#paying_method', function () {
    	$('.paying_method_option').hide();
    	
		if ($(this).val() == '<?php echo Shared_Model_Code::PAYABLE_PAYING_METHOD_BANK; ?>') {
			$('.paying_method_option_bank').show();
			
		} else if ($(this).val() == '<?php echo Shared_Model_Code::PAYABLE_PAYING_METHOD_PAYMENT_FORM; ?>') {
			$('.paying_method_option_payment_form').show();
			
		} else if ($(this).val() == '<?php echo Shared_Model_Code::PAYABLE_PAYING_METHOD_CREDIT; ?>') {
			$('.paying_method_option_card').show();
		}
    });
    
    
    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });

    // 会計科目 選択ポップアップ表示
    $(document).on('click', '#select_account_title', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/office/accounting-select', null, function () {stopSpinner();});
    });

    // 採算コード 選択ポップアップ表示
    $(document).on('click', '#select_account_totaling_group', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/financial-totaling/item-select', null, function () {stopSpinner();});
    });
    
    // 採算コード グループ切り替え
    $(document).on('change', '#account_totaling_group_category_id', function () {
		updateAccountTotalingList($(this).val());
	});
	
	// 発注 条件検索
    $(document).on('click', '#search_order', function () {
		updateOrderList(1);
    });
    
    // 銀行口座 選択ポップアップ表示
    $(document).on('click', '#select_bank', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/financial/bank-list-select', null, function () {stopSpinner();});
    });
    
    // クレジットカード 選択ポップアップ表示
    $(document).on('click', '#select_card', function () {
   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/financial/card-list-select', null, function () {stopSpinner();});
    });
    
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });

});

// 取引先一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先一覧更新
function updateConnectionList (pageNo) {
    var $form  = $('#connection_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/connection/list-select?page=' + pageNo,
    });
}

// 取引先 選択完了
function selectConnection(id, displayId, name) {
	$('#connection_name').html(name);
	$('#target_connection_id').val(id);
	$('.btn_close').click();
}

// 発注 一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 発注 一覧更新
function updateOrderList (pageNo) {
    var $form  = $('#order_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/transaction-order/list-select?page=' + pageNo,
    });
}

// 発注 選択完了
function selectOrder(id, displayId, name) {
	console.log('selectOrder');
	$('#' + targetOrderRow + '_order_form_name').html('<strong>' + displayId + '</strong>&nbsp;' + name);
	$('#' + targetOrderRow + '_order_form_id').val(id);
	
	$('.btn_close').click();
}

// 会計科目 選択完了
function selectAccountTitle(id, title) {
	$('#account_title_name').html(title);
	$('#account_title_id').val(id);
	$('.btn_close').click();
}

// 採算コード 一覧更新
function updateAccountTotalingList (categoryId) {
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:null,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/financial-totaling/item-select?category_id=' + categoryId,
    });
}

// 採算コード 選択完了
function selectAccountTotalingGroup(id, groupName, title) {
	$('#account_totaling_group_name').html(groupName + '　＞　' + title);
	$('#account_totaling_group_id').val(id);
	$('.btn_close').click();
}

// 銀行口座 選択完了
function selectBank(id, bankName, branchName, accountType, accountNo) {
	$('#bank_name').html(bankName + ' ' + branchName + ' ' + accountType + ' ' + accountNo);
	$('#bank_id').val(id);
	$('.btn_close').click();
}

</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.datepicker[type="text"]{width:150px;}
table.list_default tr td.column_value select.short {width:300px;}
table.list_default tr td.column_value select.monthly {width:60px;float:left;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.payment_select {padding-top:6px;padding-left:1px;}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
table.list_default tr td.td_count {border-right:none;background-color:#bae0ff;width:30px;}
table.list_default tr td.td_item_info {border-right:none;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
a.btn_setting#btn_copy {padding:1px 8px 0px;float:left;margin-left:20px;margin-top:5px;margin-bottom:0}
table.list_default tr td p.industory_category {background-color:#bae0ff;padding:11px 0 9px 12px}
table.list_default tr td .multi_rows_padding {padding:5px 6px 5px 6px;}
a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:3px auto;padding:5px 35px 3px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1100px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}

.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.menu_frame table.list_default tr:hover td {background:#deeeff;}

a.btn_back_list {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;color:#FFF !important;display:inline-block;float:left;
font-size:14px;margin-bottom:10px;margin-right:4px;padding:8px 20px;text-shadow:none;transition:all 200ms ease-in 0s;margin-top:0;text-decoration:none;
}
.quote {margin:10px;padding:10px;background-color:#e3f2ff}
table.list_default tr td .quote p {padding:6px 0 8px 12px;height:auto;}

.menu_frame table.list_default tr td.column_value {border-right:none;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:120px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {float:left;width:20px;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding {width:280px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value div.multi_rows_padding.long {width:740px;padding:4px 0 0 12px;float:left;word-wrap:break-word;word-break:break-all;}
.menu_frame table.list_default tr td.column_value input[type="text"] {width:240px;display:block;float:left;}
.menu_frame table.list_default tr td textarea{width:620px;height:60px;}
.menu_frame table.list_default tr td.td_action {width:56px;border-right:none;padding-right:5px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
.menu_frame table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
.menu_frame table.list_default.connection_base tr th {background-color:#bae0ff}
.menu_frame table.list_default.connection_base tr:hover td {background:#fff;}
.menu_frame table.list_default .multi_rows_padding {padding:5px 10px 5px 10px;}
.private_memo {margin-top:20px;padding:40px 50px 50px;background-color:#e0feff;border:1px solid #32918c;}
.private_memo p {font-size:1.4em;color:#32918c;font-weight:bold;margin-bottom:0.8em}

a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:right;font-size:12px;margin:3px auto;padding:4px 35px 2px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:400px;margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>サイト連動入金完了確認 - 詳細</strong></span>
        </div>
    </div>

    <div class="clearfix">
	    <?php
        /* 基本情報 */
        $categoryId = 1;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0;">
            <tr>
        	    <th class="border-left border-top border-bottom <?php if ($this->allowEditing === false) { ?>border-right<?php } ?>">
                    <p class="label_text strong">基本情報</p>
                </th>
                <?php if ($this->allowEditing === true) { ?>
	                <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php } ?>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
			<?php /*
            <tr>
                <td class="column_label"><p class="label_text">最終更新日時</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo date('Y-m-d H:i:s', strtotime($this->data['updated'])); ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">最終更新者(利用者ID)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->escape($this->lastUpdatedUser['user_name']); ?>　（<?php echo $this->escape($this->lastUpdatedUser['display_id']); ?>）</p>
                </td>
            </tr>
            */ ?>
            <tr>
                <td class="column_label"><p class="label_text">登録日</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo date('Y-m-d H:i:s', strtotime($this->data['created'])); ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">登録者(利用者ID)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->escape($this->createdUser['user_name']); ?>　（<?php echo $this->escape($this->createdUser['display_id']); ?>）</p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">会計科目<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
	                	<?php
	                		if (!empty($this->accountTitleData)) {
	                			echo $this->escape($this->accountTitleData['title']);
	                		} else {
	                			echo '---';
	                		}
		                ?>
	                </div>
	                <div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
	                	<p id="account_title_name" style="float:left;width:690px;"><?php 
	                		if (!empty($this->accountTitleData)) {
	                			echo $this->escape($this->accountTitleData['title']);
	                		} else {
	                			echo '---';
	                		}
	                	?></p>
						<input type="hidden" id="account_title_id" name="account_title_id" value="<?php echo $this->escape($this->data['account_title_id']); ?>">
						<a class="option" id="select_account_title">選択</a>
	                </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">摘要<span class="popup_help" id="help_memo">&nbsp;<i class="icon-help-circled"></i></span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php echo nl2br($this->escape($this->data['memo'])); ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<textarea name="memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['memo']); ?></textarea>
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">採算コード<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <?php
	                	$groupData = NULL;
	                	if (!empty($this->data['account_totaling_group_id'])) {
		                	$totalingGroupTable = new Shared_Model_Data_AccountTotalingGroup();
		                	$groupData = $totalingGroupTable->getById($this->adminProperty['management_group_id'], $this->data['account_totaling_group_id']);
		                }
			        ?>
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
	                	<?php
			                if (!empty($groupData)) {
			                	echo $this->escape($groupData['category_name'] . '　＞　' . $groupData['title']);
		                	} else {
			                	echo '---';
		                	}
		                ?>
	                </div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<p id="account_totaling_group_name" style="float:left;width:690px;">
						<?php
							if (!empty($groupData)) {
			                	echo $this->escape($groupData['category_name'] . '　＞　' . $groupData['title']);
		                	} else {
			                	echo '---';
		                	}
		                ?>
						</p>
						<input type="hidden" id="account_totaling_group_id" name="account_totaling_group_id" value="<?php echo $this->escape($this->data['account_totaling_group_id']); ?>">
						<a class="option" id="select_account_totaling_group">選択</a>
					</div>
                </td>
            </tr>
		</table>
		</form>
		
	    <?php
        /* 概要 */
        $categoryId = 2;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0;">
            <tr>
        	    <th class="border-left border-top border-bottom border-right">
                    <p class="label_text strong">概要</p>
                </th>
                <?php if ($this->allowEditing === true) { ?>
	                <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php }  ?>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">登録種別</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $receivableTypeList[$this->data['type']]; ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">対象請求書ID</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value ">
	                <?php if (!empty($this->data['relational_display_id'])) { ?>
						<p><?php echo $this->escape($this->data['relational_display_id']); ?>（goosa収支管理＞入金予定）</p>
	                <?php } else if (!empty($this->data['invoice_id'])) { ?>
		                <div class="clearfix">
	                		<p style="float:left;"><?php echo $this->escape($this->data['invoice_display_id']); ?></p>
							<a class="option" href="/transaction-invoice/confirm?id=<?php echo $this->escape($this->data['invoice_id']); ?>&direct=1" target="_blank">表示</a>
		                </div>
	                <?php } else { ?>
	                	<p>---</p>
	                <?php } ?>
                </td>
            </tr>
                 
            <tr>
                <td class="column_label"><p class="label_text">支払元取引先</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="connection_name"><?php 
                		if (!empty($this->connectionData)) {
                			echo $this->escape($this->connectionData['company_name']);
                			if (!empty($this->connectionData['company_name'])) {
	                			echo '　（' . $this->escape($this->connectionData['company_name_kana']) . '）';
                			}
                		} else {
                			echo '---';
                		}
                	?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">bank_sender_name</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p id="connection_name"><?php 
                		if (!empty($this->data['bank_sender_name'])) {
                			echo $this->escape($this->data['bank_sender_name']);
                		} else {
                			echo '---';
                		}
                	?></p>
                </td>
            </tr>
            
            
            
            <tr>
                <td class="column_label "><p class="label_text">発生日&nbsp;<span class="require">＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php
                			if (!empty($this->data['accrual_date'])) {
                				echo date('Y-m-d', strtotime($this->data['accrual_date']));
                			} else {
                				echo '---';
                			}
                		?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="datepicker" id="accrual_date" name="accrual_date" value="" maxlength="">
                    </div>
                </td>
            </tr>
		</table>
		</form>
		
		
	    <?php
        /* 入金予定 */
        $categoryId = 3;
        ?>
        <form id="form_category_<?php echo $categoryId; ?>">
		<table class="list_default" style="margin-bottom:0;">
            <tr>
        	    <th class="border-left border-top border-bottom border-right">
                    <p class="label_text strong">入金状況</p>
                </th>
                <?php  if ($this->allowEditing === true) { ?>
	                <th class="cancel_category" id="cancel_category_<?php echo $categoryId; ?>">
	                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);">
	                    <span>×</span>
	                    </a>
	                </th>
	                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
	                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
	                </th>
                <?php } ?>
            </tr>
		</table>   
		<table class="list_default" style="margin-bottom:13px;">
            <tr class="paying_method_option paying_method_option_bank">
                <td class="column_label"><p class="label_text">受取銀行口座&nbsp;<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php
                		$bankText = '---';
                		if (!empty($this->bankData)) {
                			$bankText = $this->escape($this->bankData['bank_name'] . ' ' . $this->bankData['branch_name'] . ' ' . $bankAccountType[$this->bankData['account_type']] . ' ' . $this->bankData['account_no']);
                		}
                	?>
                	<p id="bank_name" style="float:left;width:600px;"><?php echo $bankText; ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<a class="option" id="select_bank">金融機関選択</a>
                    	<input type="hidden" id="bank_id" name="bank_id" value="<?php echo $this->escape($this->data['bank_id']); ?>">
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">入金ステータス&nbsp;<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $paymentStatusList[$this->data['payment_status']]; ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
		            	<select id="payment_status" name="payment_status" style="width:300px;">
		                    <option value="">---</option>
		                	<?php foreach ($paymentStatusList as $key => $value) { ?>
		                        <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->data['payment_status']) echo 'selected="selected"';?>><?php echo $value; ?></option>
		                    <?php } ?>
		                </select>
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">入金予定日&nbsp;<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php
                			if (!empty($this->data['receive_plan_date'])) {
                				echo date('Y-m-d', strtotime($this->data['receive_plan_date']));
                			} else {
                				echo '---';
                			}
                		?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="datepicker" id="receive_plan_date" name="receive_plan_date" value="" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">入金完了日</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php
                			if (!empty($this->data['received_date'])) {
                				echo date('Y-m-d', strtotime($this->data['received_date']));
                			} else {
                				echo '---';
                			}
                		?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
                    	<input type="text" class="datepicker" id="received_date" name="received_date" value="" autocomplete="off" maxlength="">
                    </div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">入金額(税込)<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <div class="multi_rows_padding">
	                	<?php
                			$currencyText = '';
                			foreach ($this->currencyList as $eachCurrency) {
                				if ($this->data['currency_id'] == $eachCurrency['id']) {
                					$currencyText = $eachCurrency['name'];
                				}
                			}
                			
                			if (!empty($this->data['total_amount'])) {
                				echo number_format($this->data['total_amount']) . '&nbsp;' . $this->escape($currencyText);
                			} else {
                				echo '';
                			}
                		?>
	                </div>
	                
	            	<?php /*<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">*/ ?>

                	<?php /*
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
		            	<input type="text" style="float:left;width:150px;text-align:right;" id="total_amount" name="total_amount" value="<?php echo $this->escape($this->data['total_amount']); ?>" />
	                    <select style="float:left;width:90px;margin-left:5px;" id="currency_id" name="currency_id">
	                        <option value="">(通貨単位)</option>
	                    	<?php foreach ($this->currencyList as $eachCurrency) { ?>
	                            <option value="<?php echo $eachCurrency['id']; ?>" <?php if ($this->data['currency_id'] == $eachCurrency['id']) { echo 'selected="selected"'; } ?>><?php echo $this->escape($eachCurrency['name']); ?></option>
	                        <?php } ?>
	                    </select>
                    </div>
                    */ ?>
                </td>
            </tr>
		</table>
		</form>
		
	    <?php
        /* 入金状況 */
        $categoryId = 4;
        ?>
		<table class="list_default" style="margin-bottom:0;">
            <tr>
        	    <th class="border-left border-top border-bottom border-right">
                    <p class="label_text strong">割当情報</p>
                </th>
            </tr>
		</table>  
		<table class="list_default">
			<tr>
				<th style="width:12%;"><p>取込キー</p></th>
				<th style="width:7%;"><p>行番号</p></th>
				<th style="width:10%;"><p>取引日</p></th>
				<th><p>利用先</p></th>
				<th style="width:8%"><p>通貨</p></th>
				<th style="width:14%"><p>入金額</p></th>
				<th style="width:5%"><p>詳細</p></th>
			</tr>
			
			<?php if (!empty($this->historyItems)) { ?>
				<?php foreach ($this->historyItems as $each) { ?>
					<tr>
						<td>
							<p><?php echo $this->escape($each['import_key']); ?></p>
						</td>
						
						<td>
							<p><?php echo $this->escape($each['row_count']); ?></p>
						</td>
						
						<td>
							<p><?php echo $each['target_date']; ?></p>
						</td>
						
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['name']); ?></div>
						</td>
						
						<td>
							<p class="align_center"><?php echo $this->escape($each['currency_name']); ?></p>
						</td>
						
						<td>
							<p class="align_right"><?php if (!empty($each['received_amount'])) { echo number_format($each['received_amount']); } else { echo '---'; } ?></p>
						</td>
						
						<td>
							<p><a href="/transaction-bank/import-detail?id=<?php echo $this->escape($each['bank_history_id']); ?>&target_row=<?php echo $this->escape($each['row_count']); ?>&direct=1" target="_blank">表示</a></p>
						</td>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="7">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

		

	         
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

