<?php
$statusList   = Shared_Model_Code::codes('invoice_status_search');
?>
<script type="text/javascript">
var estimateId = 0;
var reloadFlag = false;
var pos = 0;
var targetRowDirectOrder = 0;

function getTimeStamp() {
	var date = new Date();
	return String(date.getFullYear()) + ("0"+(date.getMonth() + 1)).slice(-2) + ("0"+(date.getDate() + 1)).slice(-2)
                            	+ '_' + ("0"+(date.getHours() + 1)).slice(-2) + ("0"+(date.getMinutes() + 1)).slice(-2) + ("0"+(date.getSeconds() + 1)).slice(-2);
}

function guid() {
	function s4() {
		return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
	}
	return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

$(function() {
    $(document).ready(function(){
        var result3 = $("#sortable_column_3").sortable("toArray");
	    $('input#hidden_contents_order_3').val(result3);
    });

    // 受注管理 編集
	$(document).on('click', '.edit_ref', function () {
        var categoryId = $(this).attr('category-id');
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
        $(this).hide();
    });

    $(".sortable_column").sortable({
        items: ".sortable_frame:not(.not-sortable)",
        update: function(event, ui){
        	var categoryId = $(this).attr('target-category');
            var result = $("#sortable_column_" + categoryId).sortable("toArray");
            $('input#hidden_contents_order_' + categoryId).val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });

    // カラム追加
    $(document).on('click', '.btn_add_column', function () {
    	var categoryId = $(this).attr('target-category');
		
		if (categoryId == '3') {
			var uuid = guid();
			
			$('.column_copy_base_' + categoryId + ' .direct_order_name').attr('id', uuid + '_direct_order_name');
			$('.column_copy_base_' + categoryId + ' .direct_order_id').attr('id', uuid + '_direct_order_id').attr('name', uuid + '_direct_order_id');
			$('.column_copy_base_' + categoryId + ' .select_order_recieved').attr('id', uuid + '_select_order_recieved').attr('name', uuid + '_select_order_recieved').attr('target-row', uuid);
			$('.column_copy_base_' + categoryId + ' .clear_order_recieved').attr('id', uuid + '_clear_order_recieved').attr('name', uuid + '_clear_order_recieved').attr('target-row', uuid);
			
	        var $clone = $('.column_copy_base_' + categoryId).clone(true);
	        $('#sortable_column_' + categoryId).append($clone.attr('class', 'sortable_frame').attr('id', uuid).css('display', ''));
	        
	        
	        $('.column_copy_base_' + categoryId + ' .direct_order_name').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .direct_order_id').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .select_order_recieved').attr('id', '');
	        $('.column_copy_base_' + categoryId + ' .clear_order_recieved').attr('id', '');
	        
	        var result = $("#sortable_column_" + categoryId).sortable("toArray");
	        $('input#hidden_contents_order_' + categoryId).val(result);
		}
    });

    // カラム削除
    $(document).on('click', '.delete_button', function () {
    	var categoryId = $(this).attr('target-category');
    	var targetId   = $(this).attr('target-row');
		$("#sortable_column_" + categoryId + ' tr#' + targetId).remove();

        var result = $("#sortable_column_" + categoryId).sortable("toArray");
        $('input#hidden_contents_order_' + categoryId).val(result);
	        
		if (categoryId == '1') {   
	        // 番号振り直し
	        var countUp = 0;
	    	$('#sortable_column_' + categoryId + ' tr').each(function(){
	    		countUp++;
	    		$('#sortable_column_' + categoryId + ' tr#' + $(this).attr('id') + ' .count').html(countUp);
	    	});
	    	rowCount = countUp;
	    	calculate();
    	}
    	updateEdited (true);
    });

   
    // 受注管理 ポップアップ表示
    $(document).on('click', '.select_order_recieved', function () {
    	var connectionId = $('#target_connection_id').val();
    	if (!connectionId) {
    		jAlert('取引先を選択しましてください', '　');
    		return;
    	}
		
		targetRowDirectOrder = $(this).attr('target-row');
		
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/transaction-order-recieved/list-select?connection_id=' + connectionId, null, function () {stopSpinner();});
    });
    
	// 受注管理 条件検索
    $(document).on('click', '#search_order_received', function () {
		updateOrderRecievedList(1);
    });

	// 受注管理 選択解除
    $(document).on('click', '.clear_order_recieved', function () {
	    targetRowDirectOrder = $(this).attr('target-row');
	    
		$('#' + targetRowDirectOrder + '_direct_order_name').html('');
		$('#' + targetRowDirectOrder + '_direct_order_id').val('');
    });
    
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(pos);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });

    $('.save_ref').click( function(){
        jConfirm('受注管理引用を保存しますか', '　', function(r) {
            if(r) {
				showSpinner();
		
                var $form = $('#form_category_3');
                var query = $form.serialize();
                var param = $form.serializeArray();
                
		        $.ajax({
		            type:'POST',
		            dataType:'json',
		            data:param,
		            success:function(res){
		            	stopSpinner();
		                var obj = res;
		                if (obj.result == 'timeout') {
		                    location.href = '/login';
		                    return;
		                    
		                } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('保存しました', '　');
		                    return;
		                    
		                } else {
		                    jAlert('' + obj.message, '　');
		                }
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-invoice/update-reference?id=<?php echo $this->escape($this->id); ?>'
				});
            } else {
                return false;
            }
        });	
	});
	
    // PDFプレビュー
    $('.btn_preview, .btn_estimate_preview').click( function(){
    	<?php if ($this->data['status'] === (string)Shared_Model_Code::INVOICE_STATUS_APPROVED || $this->data['status'] == (string)Shared_Model_Code::INVOICE_STATUS_SUBMITTED) { ?>
    	window.open('/transaction-invoice/preview/<?php echo $this->escape($this->id); ?>/請求書_<?php echo $this->escape($this->data['display_id']); ?>.pdf', '_blank');
    	<?php } else { ?>
    	window.open('/transaction-invoice/preview/<?php echo $this->escape($this->id); ?>/請求書プレビュー_<?php echo $this->escape($this->data['display_id']); ?>.pdf', '_blank');
    	<?php } ?>
    });
    
    // 修正依頼
    $('.btn_mod_request').click( function(){
        jConfirm('修正依頼しますか？', '　', function(r) {
            if(r) {
				showSpinner();
		
                var $form  = $('#register_form');
                var query  = $form.serialize();
                var params = $form.serializeArray();
                
		        $.ajax({
		            type:'POST',
		            dataType:'json',
		            data:params,
		            success:function(res){
		            	stopSpinner();
		                var obj = res;
		                if (obj.result == 'timeout') {
		                    location.href = '/login';
		                    return;
		                    
		                } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('修正依頼しました', '　');
		                    return;
		                    
		                } else {
		                    jAlert('' + obj.message, '　');
		                }
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-invoice/mod-request?approval_id=<?php echo $this->escape($this->approvalId); ?>&id=<?php echo $this->escape($this->id); ?>'
				});
            } else {
                return false;
            }
        });
    });
    
    //
    // 承認
    //
    $('.btn_save').click( function(){
        jConfirm('この内容で承認しますか', '　', function(r) {
            if(r) {
				showSpinner();
		
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
                
		        $.ajax({
		            type:'POST',
		            dataType:'json',
		            data:param,
		            success:function(res){
		            	stopSpinner();
		                var obj = res;
		                if (obj.result == 'timeout') {
		                    location.href = '/login';
		                    return;
		                    
		                } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('承認しました', '　');
		                    return;
		                    
		                } else {
		                    jAlert('' + obj.message, '　');
		                }
		            },
		            error:function(){
		            	stopSpinner();
		                jAlert('予期せぬエラーが発生しました', 'エラー');
		            },
		            url:'/transaction-invoice/approve?approval_id=<?php echo $this->escape($this->approvalId); ?>&id=<?php echo $this->escape($this->id); ?>'
				});
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
	        <?php if ($this->data['status'] === (string)Shared_Model_Code::INVOICE_STATUS_PENDING) { ?>
	        	location.href = '/approval/list';
	        <?php } else { ?>
	        	location.href = '/transaction-invoice/confirm?id=<?php echo $this->escape($this->id); ?>';
	        <?php } ?>
            
        }
    });
});

// 受注管理 一覧ページ切り替え
function pageOrderRecieved(pageNo) {
	updateOrderRecievedList(pageNo)
}

// 受注管理 一覧更新
function updateOrderRecievedList (pageNo) {
    var $form  = $('#order_recieved_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/transaction-order-recieved/list-select?page=' + pageNo,
    });
}

// 受注管理 選択完了
function selectOrderRecieved(id, displayId, name) {
	$('#' + targetRowDirectOrder + '_direct_order_name').html('<strong>' + displayId + '</strong> ' + name);
	$('#' + targetRowDirectOrder + '_direct_order_id').val(id);
	
	$('.btn_close').click();
}
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
#from_logo {width:200px;}
.from p {margin-bottom:0.4em;}
.from p.company_name {font-size:1.3em}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {border-right:none;}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}

table.stamp {width:auto;float:right;}
table.stamp tr td {border:1px solid #000;text-align:center;width:60px;padding:0;}
table.estimate_form tr td {padding:0;border-top:1px solid #000;border-bottom:1px solid #000;border-right:1px dotted #000;border-left:1px dotted #000;vertical-align:top}
table.estimate_form tr td input[type="text"]{border:none;width:100%;}
table.estimate_form tr td textarea{border:none;width:100%;}
table.estimate_form tr td.td_item_action {width:50px;border-left:none;border-bottom:none;border-top:none;}
table.estimate_form tr td.td_item_action .item_btn_frame {float:left;margin:8px 0 0 18px;}
table.estimate_form tr td.td_item_action .item_btn_frame a {text-decoration:none;color:#000;font-size:1.6em;}
table.estimate_form tr td.td_action {width:50px;border-right:none;border-bottom:none;border-top:none;}
table.estimate_form tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.estimate_form tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
textarea.flex {resize: none;padding: 8px;line-height: 20px;}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin:5px 8px 0px;padding:7px 15px 5px 15px;line-height:1}
.align_right {text-align:right;}
.align_center {text-align:center;}
a.option {
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;float:left;font-size:12px;margin:5px auto 10px;padding:7px 35px 5px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}
.add_row_button_frame {height:34px;margin-left:50px;margin-right:50px;}
a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}
.private_memo {margin-top:20px;padding:40px 50px 50px;background-color:#e0feff;border:1px solid #32918c;}
.private_memo p {font-size:1.4em;color:#32918c;font-weight:bold;margin-bottom:0.8em}
.multi_rows_padding {padding:5px 10px 5px 10px}
.quote {margin:0 0 10px;padding:5px;background-color:#e3f2ff}
.quote p {padding:6px 0 8px 12px;height:auto;}
p.reference_title {float:left;width:700px;margin-top:15px;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left base_frame">
	
	<?php if (empty($this->approvalId)) { ?>
		<p style="padding:15px;">ステータス：<?php echo $statusList[$this->data['status']] ?></p>
	<?php } ?>

    <?php
    /* copy base */
    $categoryId = 3;
    ?>
	<div class="column_copy_base_<?php echo $categoryId; ?>" id="" style="display:none;">
		<div class="clearfix" id="">
			<p class="reference_title"><span class="direct_order_name"></span></p>
			<input type="hidden" class="direct_order_id" id="" name="" value="" />
			<div class="clearfix" style="float:right;width:280px;">
				<a class="option select_order_recieved" id="" style="margin-left:12px;margin-right:6px;width:120px;text-align:center;padding:7px 0 5px 0;">受注管理引用</a>
				<a class="option clear_order_recieved" id="" style="width:120px;text-align:center;padding:7px 0 5px 0;">引用解除</a>
			</div>
		</div>
	</div>
	
    <?php
    /* copy base */
    $categoryId = 3;
    ?>
    <a class="btn_setting edit_ref" category-id="<?php echo $categoryId; ?>">受注管理引用を編集する</a>
	<a class="btn_setting save_ref edit_value_<?php echo $categoryId; ?>" category-id="<?php echo $categoryId; ?>" style="display:none;">保存する</a>
	<form id="form_category_<?php echo $categoryId; ?>" action="javascript:void(0);" method="post">
	<div class="quote clearfix">
		<div class="" style="float:left;width:200px;">
			<p class="reference_title" style="margin-bottom:15px;"><strong>受注管理引用：</strong></p>
		</div>
		<div style="float:left;width:1050px;margin-bottom:10px;">
			<div class="sortable_column clearfix" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
				<?php $directOrderTable = new Shared_Model_Data_DirectOrder(); ?>
				<?php if (!empty($this->data['direct_order_ids'])) { ?>
					<?php foreach ($this->data['direct_order_ids'] as $eachOrderId) { ?>
						<?php 
							$orderData = $directOrderTable->getById($this->adminProperty['management_group_id'], $eachOrderId);
							$directOrderName = '';
							if (!empty($orderData)) {
									$text = '';
									if (!empty($orderData['items'])) {
										$textList = array();
										foreach ($orderData['items'] as $eachItem) {
											$exploded = explode("\n", $eachItem['item_name']);
											if (!empty($exploded[0])) {
												$textList[] = str_replace("\n", '', $exploded[0]);
											}
										}
										
										$text = $this->escape(implode(" / ", $textList));
									}
									$text = $this->escape($text);
									
									$directOrderName = '<strong>' . $orderData['display_id'] . '</strong> '. $text;
							}
							
						?>
						<div class="select_order_frame sortable_frame clearfix" id="direct_order_<?php echo $this->escape($orderData['id']); ?>">
							<p class="reference_title"><span id="direct_order_<?php echo $this->escape($orderData['id']); ?>_direct_order_name"><?php echo $directOrderName; ?></span></p>
							<input type="hidden" id="direct_order_<?php echo $this->escape($orderData['id']); ?>_direct_order_id" name="direct_order_<?php echo $this->escape($orderData['id']); ?>_direct_order_id" value="<?php echo $this->escape($orderData['id']); ?>" />
							<div class="clearfix" style="float:right;width:280px;">
								<a class="option select_order_recieved edit_value_<?php echo $categoryId; ?>" id="direct_order_<?php echo $this->escape($orderData['id']); ?>_select_order_recieved" target-row="direct_order_<?php echo $this->escape($orderData['id']); ?>" style="margin-left:12px;margin-right:6px;width:120px;text-align:center;padding:7px 0 5px 0;display:none;">受注管理引用</a>
								<a class="option clear_order_recieved edit_value_<?php echo $categoryId; ?>" id="direct_order_<?php echo $this->escape($orderData['id']); ?>_clear_order_recieved" target-row="direct_order_<?php echo $this->escape($orderData['id']); ?>" style="width:120px;text-align:center;padding:7px 0 5px 0;display:none;">引用解除</a>
							</div>
						</div>
					<?php } ?>
				<?php } ?>
			</div>
	        <div class="add_row_button_frame edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;height:auto;">
	            <p class="align_center"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" style="padding-top:0.7em;margin-bottom:0.3em;" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
	            <input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="direct_order_id_list" value="" />
	        </div>
	        <input type="hidden" id="target_connection_id" name="target_connection_id" value="<?php echo $this->escape($this->data['target_connection_id']); ?>">
		</div>
	</div>
	</form>
		  
    <form id="register_form" action="javascript:void(0);" method="post">
	    
	    <?php if ($this->data['invoice_type'] === (string)Shared_Model_Code::INVOICE_TYPE_CREATE) { ?>
		    <div style="border:1px solid #000;margin:0 120px 10px;">
		    	<div class="clearfix" style="padding:50px 50px 40px 50px;">
		    		<div class="clearfix" style="float:left;width:400px;">
		    			<p style="float:left;font-size:1.5em;width:100%;"><?php echo nl2br($this->escape($this->data['to_name'])); ?></p>
		    		</div>
	
		    		<?php 
		    			$companyName = $this->groupData['organization_name'];
		    			$address     = '〒' . $this->groupData['postal_code'] . ' ' . $this->groupData['prefecture'] . $this->groupData['city'] . $this->groupData['address'];
		    			$tel = $this->groupData['tel'];
		    			$fax = $this->groupData['fax'];
		    			
		    			$numberLabel = '請求書管理番号';
		    			
		    			if ($this->data['language'] == Shared_Model_Code::LANGUAGE_EN) {
		    				$companyName = $this->groupData['organization_name_en'];
		    				$address = $this->groupData['address_en'] . ' ' . $this->groupData['city_en'] . ", " . $this->groupData['prefecture_en'] . ' JAPAN'. ' (Zip: ' . $this->groupData['postal_code'] . ')';
			    			$tel = $this->groupData['tel_int'];
			    			$fax = $this->groupData['fax_int'];
			    			
			    			$numberLabel = 'INVOICE No.';
		    			}
		    		?>
		    		
		    		<div class="from" style="float:right;">
						<div class="clearfix" style="margin:0 auto 10px;text-align:right;">
							<p style="margin-bottom:0;">
							<?php
								if (!empty($this->data['invoice_date'])) {
									if ($this->data['language'] == Shared_Model_Code::LANGUAGE_EN) {
						    			echo date('F d, Y', strtotime($this->data['invoice_date']));
						    		} else {
						    			echo date('Y年m月d日', strtotime($this->data['invoice_date']));
						    		}
					    		} else {
					    			echo '---';
					    		}
					    	?>
							</p>
						</div>
		    			<img id="from_logo" src="/resource/logo_group/logo.png" style="margin-bottom:10px;" />
	
						<div class="clearfix">
							<p class="company_name"><?php echo $this->escape($companyName); ?></p>
						</div>
						<div class="clearfix">
							<p><?php echo $this->escape($address); ?></p>
						</div>
						<div class="clearfix">
							<p>TEL <?php echo $this->escape($tel); ?>　　FAX <?php echo $this->escape($fax); ?></p>
						</div>
						<div class="clearfix" style="padding-top:2px;">
							<p style="float:left;padding-top:5px;" id="creater_user_name">
								<?php
			                		if (!empty($this->createdUser)) {
			                			if ($this->data['language'] == Shared_Model_Code::LANGUAGE_EN) {
			                				echo 'PIC: ' . $this->escape($this->createdUser['department_name_en']) . '　' . $this->escape($this->createdUser['user_name_en']);
			                			} else {
			                				echo '担当者: ' . $this->escape($this->createdUser['department_name']) . '　' . $this->escape($this->createdUser['user_name']);
			                			}
			                		} else {
			                			echo '---';
			                		}
								?>
							</p>
						</div>
			    		<?php 
			    			$author   = '作成';
			    			$approval = '承認';
			    			
			    			if ($this->data['language'] == Shared_Model_Code::LANGUAGE_EN) {
			    				$author   = 'PIC';
			    				$approval = 'approval';
			    			}
			    			
			    		?>
		    			<div class="clearfix" style="margin-top:10px">
		    				<table class="stamp">
		    					<tr>
		    						<td><?php echo $author; ?></td>
		    						<td><?php echo $approval; ?></td>
		    					</tr>
		    					<tr>
		    						<td style="height:60px;">&nbsp;</td>
		    						<td>&nbsp;</td>
		    					</tr>
		    				</table>
		    			</div>
		    		</div>
		    	</div>
		    	
				<div style="margin:0 auto 10px;width:650px;">
					<div style="border-bottom:3px solid #000;">
						<p class="estimate_title" style="text-align:center;margin:0 auto 10px;font-size:1.8em;"><?php echo $this->escape($this->data['title']); ?></p>		
					</div>
					<div class="clearfix" style="padding:0 0 30px;">
						<div style="float:right;text-align:right;padding-right:5px">
		    				<?php echo $numberLabel; ?>：<?php echo $this->escape($this->data['display_id']); ?>
		    			</div>
		    		</div>
				</div>
				
				<div style="padding-bottom:10px;">
					<div class="clearfix" style="margin-left:50px;margin-right:50px;border-bottom:2px solid #000;">
						&nbsp;
					</div>
					<div>
						<table class="estimate_form" style="margin:0;">
							<thead>
								<tr>
									<td class="td_item_action">&nbsp;</td>
									<td style="width:40px;"><div class="multi_rows_padding"><?php echo $this->data['labels']['label_1']; ?></div></td>
									<td><div class="multi_rows_padding"><?php echo $this->data['labels']['label_2']; ?></div></td>
									<td style="width:90px;"><div class="multi_rows_padding align_center"><?php echo $this->escape($this->data['labels']['label_4']); ?></div></td>
									<td style="width:70px;"><div class="multi_rows_padding align_center"><?php echo $this->escape($this->data['labels']['label_5']); ?></div></td>
									<td style="width:90px;"><div class="multi_rows_padding align_center"><?php echo $this->escape($this->data['labels']['label_6']); ?></div></td>
									<td class="td_action">&nbsp;</td>
								</tr>
							</thead>
	
							<tbody class="sortable_column" id="sortable_column">
								<?php if (!empty($this->data['item_list'])) { ?>
								<?php foreach ($this->data['item_list'] as $each) {?>
								<tr id="<?php echo $this->escape($each['id']); ?>">
									<td class="td_item_action">&nbsp;</td>
									<td><div class="multi_rows_padding align_right"><?php echo $this->escape($each['id']); ?></div></td>
									<td><div class="multi_rows_padding"><?php echo nl2br($this->escape($each['item_name'])); ?></div></td>
									<td><div class="multi_rows_padding align_right"><?php if (!empty($each['unit_price'])) { echo number_format($each['unit_price']); } else { echo '0';} ?></div></td>
									<td><div class="multi_rows_padding align_right"><?php if (!empty($each['amount'])) { echo $this->numberFormat($this->escape($each['amount'])); } else { echo '0';} ?></div></td>
									<td><div class="multi_rows_padding align_right"><?php if (!empty($each['price'])) { echo number_format($each['price']); } else { echo '0';} ?></div></td>
						            <td class="td_action">&nbsp;</td>
								</tr>
								<?php } ?>
								<?php } ?>
							</tbody>
						</table>
				        <div class="add_row_button_frame" style="border-top:2px solid #000;">
				        	&nbsp;
				        </div>
				        <?php 
			    			$subTotalLabel = '合計（税別）';
			    			$taxLabel      = '消費税';
			    			$totalLabel    = '合計（税込）';
			    			
			    			if ($this->data['language'] == Shared_Model_Code::LANGUAGE_EN) {
			    				$subTotalLabel = 'SUB TOTAL';
			    				$taxLabel      = 'TAX';
			    				$totalLabel    = 'GRAND TOTAL';
			    			}
			    		?>
						<?php if (!empty($this->data['including_tax'])) { ?>
							<div class="clearfix" style="margin-left:50px;margin-right:50px;">
								<div class="clearfix" style="padding-top:5px;border-bottom:2px solid #000;">
									<div id="total_with_tax_text" style="width:150px;float:right;font-size:1.3em;text-align:right;margin-right:6px;"><?php if (!empty($this->data['total_with_tax'])) { echo $this->escape($this->currencyData['symbol']) . ' ' . number_format($this->escape($this->data['total_with_tax'])); } else { echo '0'; } ?></div>
									<div style="width:150px;float:right;font-size:1.3em;text-align:left"><?php echo $totalLabel; ?></div>
									<input type="hidden" id="total_with_tax" name="total_with_tax" value="<?php echo number_format($this->data['total_with_tax']); ?>" />
								</div>
							</div>
						<?php } else { ?>
							<div class="clearfix" style="margin-left:50px;margin-right:50px;">
								<div class="clearfix" style="padding-top:5px;border-bottom:2px solid #000;">
									<div id="subtotal_text" style="width:150px;float:right;font-size:1.3em;text-align:right;margin-right:6px;"><?php if (!empty($this->data['subtotal'])) { echo $this->escape($this->currencyData['symbol']) . ' ' . number_format($this->escape($this->data['subtotal'])); } else { echo '0'; } ?></div>
									<div style="width:150px;float:right;font-size:1.3em;text-align:left;padding-top:0.2em"><?php echo $subTotalLabel; ?></div>
								</div>
								<div class="clearfix" style="padding-top:5px;">
									<div id="tax_text" style="width:150px;float:right;font-size:1.3em;text-align:right;margin-right:6px;"><?php if (!empty($this->data['tax'])) { echo $this->escape($this->currencyData['symbol'])  . ' ' . number_format($this->escape($this->data['tax'])); } else { echo '0'; } ?></div>
									<div style="width:150px;float:right;font-size:1.3em;text-align:left"><?php echo $taxLabel; ?>（<?php echo $this->escape($this->data['tax_percentage']); ?>%）</div>
								</div>
								<div class="clearfix" style="padding-top:5px;">
									<div id="total_with_tax_text" style="width:150px;float:right;font-size:1.3em;text-align:right;margin-right:6px;"><?php if (!empty($this->data['total_with_tax'])) { echo $this->escape($this->currencyData['symbol']) . ' ' . number_format($this->escape($this->data['total_with_tax'])); } else { echo '0'; } ?></div>
									<div style="width:150px;float:right;font-size:1.3em;text-align:left"><?php echo $totalLabel; ?></div>
									<input type="hidden" id="total_with_tax" name="total_with_tax" value="<?php echo $this->escape($this->data['total_with_tax']); ?>" />
								</div>
							</div>
						<?php } ?>
					</div>
				</div>
				
				<div style="padding:0 50px 50px 50px;">
					<div class="multi_rows_padding"><?php echo nl2br($this->escape($this->data['memo'])); ?></div>
				</div>
		    </div>
	    <?php } else { ?>
		    <div class="col-xs-12">
		        <div class="page_title">
		            <span><strong>請求書内容</strong></span>
		        </div>
		    </div>

			<table class="list_default" style="margin-bottom:0;">
	            <tr>
	                <th style="border:1px solid #cfcfcf;background-color:#f1f1f1;">
	                    <p class="label_text strong">基本情報</p>
	                </th>
	            </tr>
			</table>
	        <table class="list_default" style="margin-bottom:13px;">
	            <tr>
		            <td class="column_label"><p class="label_text">請求書管理番号</p></td>
		            <td class="colon"><p class="label_text">：</p></td>
		            <td class="column_value">
		            	<p><?php echo $this->escape($this->data['display_id']); ?></p>
		            </td>
	            </tr>

	            <tr>
	                <td class="column_label"><p class="label_text">内容<span class="require">＊</span></p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
						<div class="multi_rows_padding" style="padding-left:6px;"><?php echo nl2br($this->escape($this->data['title'])); ?></textarea>
	                </td>
	            </tr>
	            
	            <tr>
	                <td class="column_label"><p class="label_text">提出先<span class="require">＊</span></p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                	<p class="connection_name"><?php echo $this->escape($this->connectionData['company_name']); ?></p>
	                </td>
	            </tr>
	            
	            <tr>
		            <td class="column_label"><p class="label_text">注文書発行日<span class="require">＊</span></p></td>
		            <td class="colon"><p class="label_text">：</p></td>
		            <td class="column_value">
		            	<p><?php echo date('Y-m-d', strtotime($this->data['invoice_date'])); ?></p>
		            </td>
	            </tr>
	            
	            <tr>
	                <td class="column_label"><p class="label_text">担当者<span class="require">＊</span></p></td>
	                <td class="colon"><p class="label_text">：</p></td>
	                <td class="column_value">
	                	<p id="creater_user_name"><?php echo $this->escape($this->createdUser['department_name']) . '　' . $this->escape($this->createdUser['user_name']); ?></p>
	                </td>
	            </tr>
	            
	            
	            <?php
	            	$currencyText = '';
	            	foreach ($this->currencyList as $eachCurrency) {
	            		if ($this->data['currency_id'] == $eachCurrency['id']) {
	            			$currencyText = $eachCurrency['name'];
	            		}
	            	}
	            ?>
	            <tr>
		            <td class="column_label"><p class="label_text">合計金額(税別)</p></td>
		            <td class="colon"><p class="label_text">：</p></td>
		            <td class="column_value">
                        <p style="width:220px;padding-left:0;text-align:right;">
                        	<?php if (!empty($this->data['subtotal'])) { ?>
                        		<?php echo number_format($this->escape($this->data['subtotal'])); ?>&nbsp;<?php echo $this->escape($currencyText); ?>
                        	<?php } else { ?>
                        		---
                        	<?php } ?>
                        </p>
		            </td>
	            </tr>
            
	            <tr>
		            <td class="column_label"><p class="label_text">税率・税額</p></td>
		            <td class="colon"><p class="label_text">：</p></td>
		            <td class="column_value">
		            	<div class="clearfix" style="width:220px">
		            		<p style="float:left;width:60px;"><?php echo $this->escape($this->data['tax_percentage']); ?>&nbsp;%</p>
			            	<p style="float:right;padding-left:0;width:140px;text-align:right;">
	                        	<?php if (!empty($this->data['tax'])) { ?>
	                        		<?php echo number_format($this->escape($this->data['tax'])); ?>&nbsp;<?php echo $this->escape($currencyText); ?>
	                        	<?php } else { ?>
	                        		---
	                        	<?php } ?>
			            	</p>
			            </div>
		            </td>
	            </tr>
	            
	            <tr>
		            <td class="column_label"><p class="label_text">合計金額(税込)<span class="require">＊</span></p></td>
		            <td class="colon"><p class="label_text">：</p></td>
		            <td class="column_value">
		            	<p style="width:220px;padding-left:0;text-align:right;">
                        	<?php if (!empty($this->data['total_with_tax'])) { ?>
                        		<?php echo number_format($this->escape($this->data['total_with_tax'])); ?>&nbsp;<?php echo $this->escape($currencyText); ?>
                        	<?php } else { ?>
                        		---
                        	<?php } ?>
		            	</p>
		            </td>
	            </tr>
	        </table>
	    <?php } ?>
	    
	    
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-top border-bottom border-right">
                    <p class="label_text strong">添付資料</p>
                </th>
            </tr>
		</table>
		<table class="list_default" style="margin-bottom:13px;">
			<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
		        <?php if (!empty($this->data['file_list'])) { ?>
			        <?php foreach ($this->data['file_list'] as $each) { ?>
				        <tr id="<?php echo $this->escape($each['id']); ?>">
							<td class="column_value">
								<div class="clearfix">
									<div style="float:left;width:360px;">
										<div class="clearfix" style="margin-bottom:5px">
											<div style="float:left;width:50px;padding:15px 0 0 10px;">
												<i class="budicon-equal" style="color:#aaa;font-size:48px;"></i>
											</div>
											<div style="float:left;width:300px;">
												<div class="multi_rows_padding" style="padding-left:18px;"><span class="file_name_text" id="<?php echo $this->escape($each['id']); ?>_file_name_text"><?php echo $this->escape($each['file_name']); ?></span></div>
												<p style="padding-left:18px;">file size：<?php echo $this->byteFormat(Shared_Model_Resource_Invoice::getFileSize($this->data['id'], $each['file_name']), 2); ?></p>
												
											</div>
										</div>
										<div>
											<a class="btn_setting" style="margin-left:12px;" target="_blank" href="<?php echo Shared_Model_Resource_Invoice::getResourceUrl($this->data['id'], $each['file_name']); ?>">ダウンロード</a>
										</div>
									</div>
									<div style="float:left;margin-left:10px;width:670px;">
										<p>概要:</p>
					                	<div class="multi_rows_padding" style="padding-left:6px;">
					                		<?php echo nl2br($this->escape($each['summary'])); ?>
					                	</div>	
									</div>
								</div>
							</td>
				            <td class="td_action">
				            	<div class="edit_value_<?php echo $categoryId; ?> delete_btn_frame clearfix" style="display:none;">
				            		<a class="delete_button" href="javascript:void(0);" target-category="<?php echo $categoryId; ?>" target-row="<?php echo $this->escape($each['id']); ?>"><i class="icon-cancel"></i></a>
				            	</div>
				            </td>
				        </tr>
			        <?php } ?>
		        <?php } else { ?>
			        <tr id="<?php echo $this->escape($each['id']); ?>">
						<td class="column_value">
							<p style="padding-left:12px;">---</p>
						</td>
			        </tr>
		        <?php } ?>
        	</tbody>
    	</table>
 
	    
	    
    	
	    <?php if (!empty($this->approvalId)) { ?>
		    <div class="private_memo">
		    	<p>社内共有メモ</p>
		    	<textarea class="flex_other" name="memo_private" style="height:150px;width:1000px;"><?php echo $this->escape($this->data['memo_private']); ?></textarea>
		    </div>
		    
		    <div class="private_memo">
		    	<p>修正依頼／却下コメント</p>
		    	<textarea class="flex_other" name="approval_comment" style="height:150px;width:1000px;"><?php echo $this->escape($this->data['approval_comment']); ?></textarea>
		    </div>
		    
	    <?php } else { ?>
	    	<div class="private_memo">
	    		<p>社内共有メモ</p>
	    		<div class="multi_rows_padding"><?php echo nl2br($this->escape($this->data['memo_private'])); ?></div>
	    	</div>

	    	<?php if (!empty($this->data['approval_comment'])){ ?>
		    	<div class="private_memo">
		    		<p>修正依頼コメント</p>
		    		<div class="multi_rows_padding"><?php echo nl2br($this->escape($this->data['approval_comment'])); ?></div>
		    	</div>
	    	<?php } ?>
	    <?php } ?>
	    
    </form>
                   
</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>



