<?php
$startTypeList       = Shared_Model_Code::codes('progress_start_type');
$importanceList      = Shared_Model_Code::codes('progress_importance');
$possibilityList     = Shared_Model_Code::codes('progress_possibility');
?>
<script type="text/javascript">
var pos = 0;
var reloadFlag = false;
var targetItemRow = '';

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) * 0x10000).toString(16).substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
}

$(function() {
    $(document).ready(function(){
	    Tipped.create('#help_start_type', "A 創造　　　⇒　自らゼロから開拓した新規顧客の営業案件<br>B1クロス　　⇒　既存顧客に新しく取引実績のないものを営業するクロスセス案件<br>B2 受け新規　⇒　最初のきっかけが受動的だった新規顧客の営業案件<br>C 既存取引　　⇒　リピート購入・再販案件や過去受注経験のある既存取引案件");
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/connection-progress";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/connection-progress/add-post'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/connection-progress';
        }
    });

    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
        	var categoryId = $(this).attr('target-category');
            var result = $("#sortable_column_" + categoryId).sortable("toArray");
            $('input#hidden_contents_order_' + categoryId).val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });
    
    // カラム追加
    $(document).on('click', '.btn_add_column', function () {
    	var categoryId = $(this).attr('target-category');
		console.log(categoryId);
        var uuid = guid();

		$('.column_copy_base_' + categoryId + ' .item_name').attr('id', uuid + '_item_name');
    	$('.column_copy_base_' + categoryId + ' .item_id').attr('id', uuid + '_item_id').attr('name', uuid + '_item_id');
    	
    	$('.column_copy_base_' + categoryId + ' .select_item').attr('target-row', uuid);
    	$('.column_copy_base_' + categoryId + ' .delete_button').attr('target-row', uuid);
    	
    	
    	
        var $clone = $('.column_copy_base_' + categoryId).clone(true);
        $('tbody#sortable_column_' + categoryId).append($clone.attr('class', '').attr('id', uuid).css('display', ''));
        
        $('.column_copy_base_' + categoryId + ' .item_name').attr('id', '');
		$('.column_copy_base_' + categoryId + ' .item_id').attr('id', '').attr('name', '');
		
        $('td.added_row').each(function(){
            $(this).css('width', $(this).width() +'px');
        });
             
        var result = $("#sortable_column_" + categoryId).sortable("toArray");
        $('input#hidden_contents_order_' + categoryId).val(result); 
    });
     	
    // カラム削除
    $(document).on('click', '.delete_button', function () {
    	var targetId   = $(this).attr('target-row');
		$('tr#' + targetId).remove();
		
        var result = $("#sortable_column_1").sortable("toArray");
        $('input#hidden_contents_order_1').val(result);
    });
    
    
	// 商品区分
    $('.has_no_task').change(function() {
		if ($(this).prop('checked')) {
			$('#task').prop("disabled", true);
		} else {
			$('#task').prop("disabled", false);
		}
    });
    
    // 自社担当 ポップアップ表示
    $(document).on('click', '#select_user', function () {
    	showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/user/list-select', null, function () {stopSpinner();});
    });
    
	// 自社担当 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    
    // 取引先 選択ポップアップ表示
    $(document).on('click', '#select_connection', function () {
	    showSpinner();
    	pos = $(window).scrollTop();
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/list-select', null, function () {stopSpinner();});
    });
    
	// 取引先 条件検索
    $(document).on('click', '#search_connection', function () {
		updateConnectionList(1);
    });

    // 取引先担当者 ポップアップ表示
    $(document).on('click', '#select_staff', function () {
	    var connectionId = $('#connection_id').val();
    	if (!connectionId) {
    		jAlert('先に「取引先」を選択してください', '　');
    		return;
    	}
	    showSpinner();
    	pos = $(window).scrollTop();
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection/staff-select?connection_id=' + connectionId, null, function () {stopSpinner();});
    });
    
	// 取引先担当者 条件検索
    $(document).on('click', '#search_user', function () {
		updateUserList(1);
    });
    
    
    // 営業エリア 選択ポップアップ表示
    $(document).on('click', '#select_area', function () {
	    showSpinner();
	    pos = $(window).scrollTop();
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection-progress/area-list-select', null, function () {stopSpinner();});
    });
    
	// 営業エリア 条件検索
    $(document).on('click', '#search_area', function () {
		updateConnectionList(1);
    });

    // 商品 選択 ポップアップ表示
    $(document).on('click', '.select_item', function () {
    	targetItemRow = $(this).attr('target-row');

   		showSpinner();
    	pos = $(window).scrollTop();
    	$('#data_area').html('');
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);

		$('#data_area').load('/product/list-select', null, function () {stopSpinner();});
    });
    
    // 商品 選択 条件検索
    $(document).on('click', '#search_product', function () {
		updateProductList(1);
    });
    
    // 発足名称 選択ポップアップ表示
    $(document).on('click', '#select_start', function () {
	    showSpinner();
	    pos = $(window).scrollTop();
    	$('body').addClass('body_fixed').css({'top': 0});
		$('#glayLayer').show();
		$('#overBoxLayer').show();
		$('.menu_frame').css('height', window.innerHeight - 80);
		$('#data_area').load('/connection-progress/start-list-select', null, function () {stopSpinner();});
    });
    
	// 発足名称 条件検索
    $(document).on('click', '#search_tag', function () {
		updateTagList(1);
    });
    
    // ポップアップを閉じる
    $(document).on('click', '.btn_close', function () {
    	$('body').removeClass('body_fixed').css({'top': pos});
    	$('html,body').scrollTop(0);
		$('#glayLayer').hide();
		$('#overBoxLayer').hide();
    });
});

// 自社担当 一覧ページ切り替え
function pageUser(pageNo) {
	updateUserList(pageNo)
}

// 自社担当 一覧更新
function updateUserList (pageNo) {
    var $form  = $('#user_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/user/list-select?page=' + pageNo,
    });
}

// 自社担当 選択完了
function selectUser(id, departmentName, name, departmentNameEn, nameEn) {
	$('#user_name').html(departmentName + '　' + name);
	$('#user_id').val(id);
	$('.btn_close').click();
}

// 取引先 一覧ページ切り替え
function pageConnection(pageNo) {
	updateConnectionList(pageNo)
}

// 取引先 一覧更新
function updateConnectionList (pageNo) {
    var $form  = $('#connection_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success:function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/connection/list-select?page=' + pageNo,
    });
}

// 取引先 選択
function selectConnection(id, displayId, name) {
	$('#connection_name').html(name);
	$('#connection_id').val(id);
	$('.btn_close').click();
}

// 取引先担当者一覧更新
function updateConnectionStaffList (connectionId) {
    var $form  = $('#connection_condition_form');
    var query  = $form.serialize();
    var params = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data:params,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error:function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url:'/connection/staff-select?connection_id=' + connectionId,
    });
}

// 取引先担当者 選択
function selectStaff(connectionId, companyName, staffId, staffName) {
	$('#staff_name').html(staffName);
	$('#staff_id').val(staffId);
	$('.btn_close').click();
}

// 営業エリア 一覧ページ切り替え
function pageArea(pageNo) {
	updateAreaList(pageNo)
}
// 営業エリア 一覧更新
function updateAreaList (pageNo) {
    var $form = $('#area_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/connection-progress/area-list-select?page=' + pageNo,
    });
}

// 営業エリア 選択
function selectArea(id, name) {
	$('#area_name').html(name);
	$('#area_id').val(id);
	$('.btn_close').click();
}

// 商品 一覧ページ切り替え
function pageProduct(pageNo) {
	updateProductList(pageNo)
}

// 商品 一覧更新
function updateProductList (pageNo) {
    var $form = $('#product_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
        	stopSpinner();
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/product/list-select?page=' + pageNo,
    });
}

// 商品 選択完了
function selectProduct(id, itemId, name, buyingName) {
	$('#' + targetItemRow + '_item_name').html(name);
	$('#' + targetItemRow + '_item_id').val(id);
	$('.btn_close').click();
}

// 発足名称 一覧ページ切り替え
function pageTag(pageNo) {
	updateTagList(pageNo)
}

// 発足名称 一覧更新
function updateTagList (pageNo) {
    var $form = $('#tag_condition_form');
    var query = $form.serialize();
    var param = $form.serializeArray();
    $('#data_area').html('');
    showSpinner();
    $.ajax({
        type:'POST',
        dataType:'html',
        data: param,
        success: function(res){
        	stopSpinner();
			$('#data_area').html(res);
        },
        error: function(){
            jAlert('予期せぬエラーが発生しました', 'エラー');
        },
        url: '/connection-progress/start-list-select?page=' + pageNo,
    });
}

// タグ 選択完了
function selectTag(id, name) {
	$('#start_name').html(name);
	$('#start_tag_id').val(id);
	$('.btn_close').click();
}

</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default.main tr td {border-right:none}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
table.list_default tr td.column_select {width:120px;}
table.list_default tr td.td_action {width:40px;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}

a.option {
float:right;
background:none repeat scroll 0 0 #00469b;border:medium none;border-radius:0;box-shadow:none;cursor:pointer;
color:#fff !important;display:block;font-size:12px;margin:3px 9px;padding:3px 35px 1px 35px;text-shadow:none;transition:all 200ms ease-in 0s;text-decoration:none;
}

a.btn_add_column {display:block;padding-top:8px;width:200px;margin:0 auto;font-size:1.6em;}

table.list_default tr td.td_action {width:56px;border-right:none;}
table.list_default tr td.td_action .delete_btn_frame {float:left;margin:8px 0 0 12px;}
table.list_default tr td.td_action .delete_btn_frame a {text-decoration:none;color:#ff0000;font-size:1.6em;}
a.btn_setting#btn_copy {padding:1px 8px 0px;float:left;margin-left:20px;margin-top:5px;margin-bottom:0}
table.list_default tr td p.industory_category {background-color:#bae0ff;padding:11px 0 9px 12px}

.overlay_menu {position:fixed;}
.menu_frame {background-color:#fff;width:1000px;margin:40px auto;padding:0 50px;overflow:auto;}
.menu_frame .page_title {padding-top:2.0em;}
.menu_frame div.condition_items div.condition_item {width:239px}
.menu_frame a.option {margin: 5px 8px 0px;padding:7px 15px 5px 15px;line-height:1;}
.menu_frame table.list_default tr:hover td {background:#deeeff;}
.menu_frame table.list_default.base tr:hover td {background:#fff;}
.menu_frame table.list_default tr td.column_value p.column_label {border-right:none;width:85px;float:left;}
.menu_frame table.list_default tr td.column_value p.colon {width:20px;float:left;}
.menu_frame p.select_type_title {padding:1.4em 0;margin:0;text-align:center;line-height:1;font-size:1.3em;}
.menu_frame a.select_type {padding:1.4em 0;margin:0 1px 1px 1px;text-align:center;display:block;background-color:#444;color:#fff;font-weight:bold;text-decoration:none;font-size:1.3em;}
.menu_frame a.select_type:hover{background-color:#63b02d;color:#fff;}
.menu_frame a.btn_close.select_type_close {padding:1.0em 0;margin:0 1px 1px 1px;text-align:center;display:block;text-decoration:none;font-size:1.3em;}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>営業案件管理 - 新規案件登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post"> 
    <div class="clearfix">
		
		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-top border-bottom border-right">
                    <p class="label_text strong">案件情報</p>
                </th>
            </tr>
		</table>

	    <?php
        /* 案件情報 */
        $categoryId = 1;
        ?> 
        <table class="list_default main" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">管理シート<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <select name="sheet_id" style="width:300px;">
		                <option value="">---</option>
		                <?php foreach ($this->sheetList as $eachSheet) { ?>           
		                    <option value="<?php echo $this->escape($eachSheet['id']); ?>"><?php echo $this->escape($eachSheet['sheet_name']); ?></option>
	                    <?php } ?>
                    </select>
                </td>
            </tr>
	        
            <tr>
                <td class="column_label"><p class="label_text">自社担当<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<div class="clearfix">
						<p id="user_name" style="float:left;width:690px;">---</p>
						<input type="hidden" id="user_id" name="user_id" value="">
						<a class="option" id="select_user">選択</a>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">取引先<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<div class="clearfix">
						<p id="connection_name" style="float:left;width:690px;">---</p>
						<input type="hidden" id="connection_id" name="connection_id" value="">
						<a class="option" id="select_connection">選択</a>
					</div>
                </td>
            </tr>
            

            <tr>
                <td class="column_label"><p class="label_text">取引先 担当者</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<div class="clearfix">
						<p id="staff_name" style="float:left;width:690px;">---</p>
						<input type="hidden" id="staff_id" name="staff_id" value="">
						<a class="option" id="select_staff">選択</a>
					</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">営業エリア</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<div class="clearfix">
						<p id="area_name" style="float:left;width:690px;">---</p>
						<input type="hidden" id="area_id" name="area_id" value="">
						<a class="option" id="select_area">選択</a>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">対象商品</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<table class="list_default main" style="margin-bottom:0;">
						<tbody class="sortable_column" id="sortable_column_<?php echo $categoryId; ?>" target-category="<?php echo $categoryId; ?>">
			            </tbody>
			        </table>
			        <div class="" style="height:34px;">
			            <p style="text-align:center;padding:0;height:auto;"><a class="btn_add_column" target-category="<?php echo $categoryId; ?>" href="javascript:void(0);"><i class="icon-plus"></i></a></p>
			        </div>
			        <input type="hidden" id="hidden_contents_order_<?php echo $categoryId; ?>" name="item_list" value="" />
			        
					<!--new column add -->
			        <table style="display:none;">
			            <tr class="column_copy_base_<?php echo $categoryId; ?>" id="">
			                <td class="added_row">
				                <p class="label_text item_name"></p>
				                <input type="hidden" class="item_id" value="">
				            </td>
			                <td class="added_row column_select">
				            	<a class="option select_item" target-row="$$$">選択</a>
			                </td>
			                <td class="added_row td_action">
			                	<div class="delete_btn_frame">
			                		<a class="delete_button" href="javascript:void(0);" target-row="$$$"><i class="icon-cancel"></i></a>
			                	</div>
			                </td>
			            </tr>
			        </table>
			        <!--new column add -->
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">発足区分<span class="popup_help" id="help_start_type">&nbsp;<i class="icon-help-circled"></i></span><span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <select name="start_type" style="width:300px;">
		                <option value="">---</option>
		                <?php foreach ($startTypeList as $key => $val) { ?>           
		                    <option value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($val); ?></option>
	                    <?php } ?>
                    </select>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">発足名称<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
					<div class="clearfix">
						<p id="start_name" style="float:left;width:690px;">---</p>
						<input type="hidden" id="start_tag_id" name="start_tag_id" value="">
						<a class="option" id="select_start">選択</a>
					</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">重要度<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <select name="importance" style="width:300px;">
		                <option value="">---</option>
		                <?php foreach ($importanceList as $key => $val) { ?>           
		                    <option value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($val); ?></option>
	                    <?php } ?>
                    </select>
                </td>
            </tr>  

            <tr>
                <td class="column_label"><p class="label_text">可能性<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <select name="possibility" style="width:300px;">
		                <option value="">---</option>
		                <?php foreach ($possibilityList as $key => $val) { ?>           
		                    <option value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($val); ?></option>
	                    <?php } ?>
                    </select>
                </td>
            </tr>


            <tr>
                <td class="column_label"><p class="label_text">実績</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php foreach ($this->progressList as $each) { ?>
	                	<div class="checkbox_item relation_type_item">
		                	<label>
		                		<input type="checkbox" name="progress[]" value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['title']); ?>
		                    </label>
	                    </div>
                    <?php } ?> 
                </td>
            </tr>  

            <tr>
                <td class="column_label"><p class="label_text">見積後ヒア</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php foreach ($this->afterList as $each) { ?>
	                	<div class="checkbox_item relation_type_item">
		                	<label>
		                		<input type="checkbox" name="after[]" value="<?php echo $this->escape($each['id']); ?>"><?php echo $this->escape($each['title']); ?>
		                    </label>
	                    </div>
                    <?php } ?> 
                </td>
            </tr>  

            <tr>
                <td class="column_label"><p class="label_text">宿題<span class="require">&nbsp;＊</span></p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
                		<div class="checkbox_item relation_type_item">
		                	<label>
		                    	<input type="checkbox" class="has_no_task" name="has_no_task">宿題なし
		                    </label>
	                    </div>
					</div>
					<div class="clearfix">
	                   <textarea id="task" name="task" style="height:300px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>
                   
            <tr>
                <td class="column_label"><p class="label_text">進捗詳細</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <textarea name="details" style="height:500px;margin-bottom:6px;"></textarea>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">その他展望等</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
	                <textarea name="other_memo" style="height:300px;margin-bottom:6px;"></textarea>
                </td>
            </tr>
            
        </table>
        
	</div><!-- clearfix -->	
    </form>


</div>
<div id="glayLayer" style="display:none;"><div>&nbsp;</div></div>
<div id="overBoxLayer" style="display:none;">
    <div class="menu_frame">
		<div id="data_area">
		
		</div>
    </div><!-- menu_frame -->
</div>
</div>
</div>
</div>

