<div class="menu_list clearfix">
<a class="menu <?php if($this->action == 'detail') echo "selected"; ?>" href="/connection-progress/detail?id=<?php echo $this->escape($this->id); ?>&direct=<?php echo $this->direct; ?>">案件情報</a>
<a class="menu <?php if($this->action == 'record') echo "selected"; ?>" href="/connection-progress/record?id=<?php echo $this->escape($this->id); ?>&direct=<?php echo $this->direct; ?>">議事録／資料</a>
</div>
