<?php
$connectionStatusList  = Shared_Model_Code::codes('connection_status');
$connectionTypeList    = Shared_Model_Code::codes('connection_type');
$relationTypeList      = Shared_Model_Code::codes('relation_type');
$salesRelationList     = Shared_Model_Code::codes('sales_relation');
$connectionTypeList    = Shared_Model_Code::codes('connection_type');


$startTypeList       = Shared_Model_Code::codes('progress_start_type');
$importanceList      = Shared_Model_Code::codes('progress_importance');
$supplierList        = Shared_Model_Code::codes('supplier_type');
$targetbusinessList  = Shared_Model_Code::codes('target_business');
$openList			 = Shared_Model_Code::codes('progress_open_status');
$willingList	     = Shared_Model_Code::codes('willing_status');
$adsList	         = Shared_Model_Code::codes('ads_status');



?>
<script type="text/javascript">
$(function () {
    $(document).ready( function(){
   		Tipped.create('#help_keyword', "取引先ID / 企業・機関名 / 企業・機関名カナ / 事業内容 / 企業URL / 本社(郵便番号・都道府県・市区町村・丁番地・建物名・階／号室) <br> 代表者名 / FAX番号 / 担当者名");

        Tipped.create('#help_gs', "goosa サプライヤー");
        Tipped.create('#help_gb', "goosa バイヤー");
        Tipped.create('#help_gcs', "GOOSCA サプライヤー");
    });

	$(".clear_form").bind("click", function(){
	    $(this.form).find("textarea, :text, select").val("").end().find(":checked").prop("checked", false);
	});
	$(document).on('click', '.submit', function () {
		showSpinner();
		$('#condition_form').submit();
	});
});    
</script>
<style type="text/css">
table.list_default tr th{position:relative;}
table.list_default tr th i{position:absolute;right:10px;margin-left:5px;font-size:1.2em}
table.list_default tr:hover td {background:#deeeff;}
table.list_default tr.deleted td {background:#ccc}
table.list_default tr.deleted:hover td {background:#bbb;}
table.list_default tr td p {height:auto;}
table.list_default tr td p.imported {color:#f00;}
table.list_default tr td a.option{
	background-color: #00469b;
    border: medium none;
    border-radius: 0;
    box-shadow: none;
    cursor: pointer;
    color: #fff !important;
    display: inline-block;
    font-size: 12px;
    margin: 1px 3px 0 0;
    padding: 5px 10px 3px 10px;
    text-shadow: none;
    transition: all 200ms ease-in 0s;
    text-decoration: none;
    line-height: 1.4;
}


table.list_default tr td .btn_list_delete{
	background-color: #d90034 !important;
}

.multi_rows_padding {
    padding: 0 0 0 3px;
    float: left;
    line-height: 1.6;
}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
			<p style="position:absolute;width:162px;right:0;">
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin-right:10px;border:none;" href="/open/add-goosa">新規登録</a>
                <a class="btn_setting" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;" href="/open/import">取込</a>
            </p>
	        <span style=""><strong>取引先一覧</strong></span>
	    </div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<form id="condition_form" action="/management/list" method="get">
				<p class="search_condition_title">検索条件</p>

				<input type="hidden" id="search" name="search" value="1" />
				<input type="hidden" id="page" name="page" value="1" />
				
				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">ステータス：</p>
                        <select id="status" name="status">
                            <option value="">---</option>
                        	<?php foreach ($connectionStatusList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['status']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">種別：</p>
                        <select id="type" name="type">
                            <option value="">---</option>
                        	<?php foreach ($connectionTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>

					<div class="condition_item">
						<p class="condition_label">当社との取引関係：</p>
                        <select id="relation_type" name="relation_type">
                            <option value="">---</option>
                        	<?php foreach ($relationTypeList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['relation_type']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
					
					<div class="condition_item">
						<p class="condition_label">当社に対する先方役割：</p>
                        <select id="sales_relation" name="sales_relation">
                            <option value="">---</option>
                        	<?php foreach ($salesRelationList as $key => $value) { ?>
                                <option value="<?php echo $key; ?>" <?php if ((string)$key === $this->conditions['sales_relation']) echo 'selected="selectd"';?>><?php echo $value; ?></option>
                            <?php } ?>
                        </select>
					</div>
				</div>	
						
				<div class="condition_items_row clearfix">
					<div class="condition_item">
						<p class="condition_label">業種：</p>
                        <select id="industry_type" name="industry_type">
                            <option value="">---</option>
	                		<?php foreach ($this->industryCategoryList as $eachCatgory) { ?>
		                		<optgroup label="<?php echo $this->escape($eachCatgory['name']); ?>">
			                		<?php foreach ($eachCatgory['items'] as $each) { ?>
					                	<option value="<?php echo $each['id']; ?>" <?php if ($each['id'] == $this->conditions['industry_type']) echo 'selected="selectd"';?>><?php echo $each['name']; ?></option>
				                    <?php } ?>
			                   	</optgroup>
		                    <?php } ?>
                        </select>
					</div>
								
					<div class="condition_item">
						<p class="condition_label">キーワード：<span class="popup_help" id="help_keyword">&nbsp;<i class="icon-help-circled"></i></span></p>
						<input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>" />
					</div>
					

				</div>
				
				<div style="text-align:center">
					<input type="button" class="clear_form" style="display:inline-block;width:150px;" value="リセット" />
					<input type="button" class="submit" style="display:inline-block;width:150px;" value="検索" />
				</div>
			</form>
		</div>
	</div>

	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<div class="condition_items clearfix">
			<div class="condition_items_row clearfix">
				<div class="clearfix" style="float:left;width:200px;">
					<div class="clearfix" style="padding:10px;">
	                    <a class="button" style="float:left;padding:5px 35px 4px;margin-bottom:0;" href="/management/export">出力用データ検索</a>
					</div>
				</div>
			</div>
		</div>
	</div>
				
	<div class="clearfix">
		<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
    </div>
    
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<table class="list_default">
			<tr>
				<th style=""><p>出店営業ID</p></th>
				<th style=""><p>ステータス/先方意欲</p></th>
				<th style=""><p>カテゴリ/商材点数</p></th>
				<th style=""><p>営業メモ</p></th>
				<th style=""><p>取引先ID/企業・機関名</p></th>
				<th style=""><p>対象事業/発足名称/サプライヤー種別</p></th>
				<th style=""><p>先方担当者</p></th>
				<th style=""><p>営業商材ページURL</p></th>
				<th style=""><p>現在獲得営業担当者名</p></th>
				<th style=""><p>最終更新</p></th>
			</tr>
			
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>

					<tr id="<?php echo $each['id']; ?>" <?php if ($each['status'] == Shared_Model_Code::CONNECTION_STATUS_REMOVE) { echo 'class="deleted"'; } ?>>
						
						<td>
							<div class="multi_rows_padding">
								<?php echo $this->escape($each['business_id']); ?><br>
								<a class="option show_detail" href="/open/goosa-detail?id=<?php echo $this->escape($each['id']); ?>">表示</a>
								<a class="option btn_list_delete" style="margin-bottom:5px;" target-id="<?php echo $this->escape($each['id']); ?>">削除</a>
							</div>
						</td>
						
						<td>
							<?php
								$stataus = $openList[$each['status']];
								$willing = $willingList[$each['willing_status']];
							?>
							<div class="multi_rows_padding">
								<span><?php echo $this->escape($stataus); ?></span><br>
								<span><?php echo $this->escape($willing); ?></span>
							</div>
						</td>
                		
                		<td>
							<div class="multi_rows_padding">
								<span><?php echo $this->escape($each['main_product_name']); ?></span><br>
								<span><?php echo $this->escape($each['product_point']); ?></span>
							</div>
						</td>
                		
                		<td  class="desc" all-content="<?php echo $this->escape($each['business_mode']); ?>">
							<div class="multi_rows_padding"><?php echo $this->roundText($this->escape($each['business_mode']), 10); ?></div>
						</td>
						
						<td>
							<div class="multi_rows_padding">
								<span><?php echo $this->escape($each['display_id']); ?></span><br>
								<span><?php echo $this->roundText($this->escape($each['connection_company_name']), 18); ?></span>
							</div>
						</td>
					
						<td>
							<?php 
							
								$target_business_arr = explode(',', $each['target_business_arr']);
								$business_arr = array();
								foreach($target_business_arr as $target_business_id)
								{
									$t_business = $targetbusinessList[$target_business_id];
									array_push($business_arr, $t_business);
								}
							
								$supplier_type_arr = explode(',', $each['supplier_type_arr']);
								$supplier_arr = array();
								foreach($supplier_type_arr as $supplier_type)
								{
									$s_type = $supplierList[$supplier_type];
									array_push($supplier_arr, $s_type);
								}
							?>
							<div class="multi_rows_padding">
								<span><?php echo $this->escape(implode(',', $business_arr)); ?></span><br>
								<span><?php echo $this->escape($each['tag_name']); ?></span><br>
								<?php echo $this->escape(implode(',', $supplier_arr)); ?>
							</div>
						</td>
						
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['first_staff']['staff_name']); ?></div>
						</td>
						
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['business_product_url']); ?></div>
						</td>
						
						<td>
							<div class="multi_rows_padding"></div>
						</td>
						
						<td>
							<div class="multi_rows_padding"><?php echo date('Y-m-d H:i:s', strtotime($this->escape($each['updated']))); ?></div>
						</td>
						
					</tr>
					
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="10">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
		</table>

        <div style="padding:2.0em 0;">
        <?php echo $this->pager() ?>
        </div>
	            
	</div>

</div>
</div>
</div>
</div>


