<?php
$bankAccountType = Shared_Model_Code::codes('bank_account_type');
?>
<script type="text/javascript">
var reloadFlag = false;

$(function() {
    $(document).ready(function(){
        
    });
    			    
    //
    // 中止
    //
    $(".btn_back").click(function(){
		jConfirm('登録せずに中止しますか', '　', function(r) {
            if(r) {
               location.href = "/connection/relational?id=<?php echo $this->escape($this->connectionId); ?>";
            } else {
                return false;
            }
        });
	});
	
    //
    // 保存
    //
    $('.btn_save').click( function(){
        jConfirm('登録しますか', '　', function(r) {
            if(r) {
                var $form = $('#register_form');
                var query = $form.serialize();
                var param = $form.serializeArray();
        		
        		showSpinner();
        		
                $.ajax({
                    type:'POST',
                    dataType:'json',
                    data: param,
                    success: function(res){
                    	stopSpinner();
                        var obj = res;
                        if (obj.result == 'timeout') {
                            location.href = '/login';
                            return;
                            
                        } else if(obj.result == 'OK') {
                            reloadFlag = true;
                            jAlert('登録しました', '　');
                            return;
                            
                        } else {
                            jAlert('' + obj.message, '　');
                        }
                    },
                    error: function(){
                    	stopSpinner();
                        jAlert('予期せぬエラーが発生しました', 'エラー');
                    },
                    url: '/connection/bank-add-post'
				});
        
            } else {
                return false;
            }
        });	
	});

    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
            location.href = '/connection/relational?id=<?php echo $this->escape($this->connectionId); ?>';
        }
    });
});
</script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:265px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:6px;}
table.list_default tr td.column_value input[type="text"]{width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"]{width:300px;}
table.list_default tr td.column_value select.short {width:300px;}
</style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="margin-bottom:500px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title">
            <span><strong>取引先 金融機関 - 新規登録</strong></span>
        </div>
    </div>
    
    
    <form id="register_form" action="#" method="post">
    <input type="hidden" name="connection_id" value="<?php echo $this->escape($this->connectionId); ?>">
    <div class="clearfix">

		<table class="list_default" style="margin-bottom:0;">
            <tr>
                <th class="border-left border-right border-top border-bottom">
                    <p class="label_text strong">金融機情報</p>
                </th>
            </tr>
		</table>
         
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">取引先名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p><?php echo $this->escape($this->connectionData['company_name']); ?></p>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">金融機関コード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" style="width:200px;" name="bank_code" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">金融機関名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" style="width:400px;" name="bank_name" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">支店コード</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" style="width:200px;" name="branch_code" value="" maxlength="" />
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">支店名</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" style="width:400px;" name="branch_name" value="" maxlength="" />
                </td>
            </tr>
 
            <tr>
                <td class="column_label"><p class="label_text">口座種別</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<select class="short" id="account_type" name="account_type">
                		<option value="">---</option>
                        <?php foreach ($bankAccountType as $key => $val) { ?>
                            <option value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($val); ?></option>
                        <?php } ?>
                	</select>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">口座番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" style="width:200px;" name="account_no" value="" maxlength="" />
                </td>
            </tr>
  
            <tr>
                <td class="column_label"><p class="label_text">口座名義：</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" style="width:400px;" name="account_name" value="" maxlength="" />
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">口座名義(カナ)</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<input type="text" style="width:400px;" name="account_name_kana" value="" maxlength="" />
                </td>
            </tr>
            
 			<tr>
                <td class="column_label"><p class="label_text">備考</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="clearfix">
						<textarea name="memo" style="height:100px;margin-bottom:6px;"></textarea>
					</div>
                </td>
            </tr>
             
		</table>
		
	</div><!-- clearfix -->	
    </form>


</div>
</div>
</div>
</div>

