<?php
$invFinTypeList       = Shared_Model_Code::codes('inv_fin_type');
$accountTypeList      = Shared_Model_Code::codes('bank_account_type');
?>

<script type="text/javascript"><!--
var reloadFlag  = false;
var deletedFlag = false;
var editing = false;

$(function() {
    $(document).ready(function(){
        <?php if (!empty($this->posTop)) { ?>
        $(window).scrollTop(<?php echo $this->posTop; ?>);
        <?php } ?>
    });

    // 編集
    $(document).on('click', '.btn_edit_category', function () {
    	if (editing == true) {
    		jAlert('複数のカテゴリを同時に編集することはできません', 'エラー');
    		return false;
    	}
    	
        var categoryId = $(this).attr('category_id');
        
        $('.display_value_' + categoryId).hide();
        $('.edit_value_' + categoryId ).show();
    
        // ×,保存ボタン
        $('#cancel_category_' + categoryId).show();
        $('th#edit_category_' + categoryId).addClass('edit_mode');
        $(this).removeClass('btn_edit_category').addClass('btn_save_category');
        $('#btn_edit_label_' + categoryId).html('保存');
        
        editing = true;
    });
    
    // 保存
    $(document).on('click', '.btn_save_category', function () {
        var button = $(this);
        var categoryId = $(this).attr('category_id');
        var $form = $('#form_category_' + categoryId);
        var params = $form.serializeArray();
		
		var apiUrl = '';
		
		if (categoryId == '1') {
			apiUrl = '/connection/update-investment-info?id=<?php echo $this->id ?>';
		} else if (categoryId == '2') {
			apiUrl = '/connection/update-investment-account?id=<?php echo $this->id ?>';
		} else {
			return;
		}
		
        $.ajax({
            type:'POST',
            dataType:'json',
            data: params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url: apiUrl,
        });
    });
    
    $(document).on('click', '#popup_ok', function () {
        if (reloadFlag) {
        	if (deletedFlag == true) {
        		location.href = '<?php echo $this->backUrl; ?>';
        	} else {
            	location.href = '/connection/investment-info?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
            }
        }
    });

    // 編集中止
    $(document).on('click', '.btn_cancel_category', function () {
        var categoryId = $(this).attr('category_id');
        location.href = '/connection/investment-info?id=<?php echo $this->id; ?>&pos=' + $(window).scrollTop();
    });
    
});
--></script>
<style type="text/css">
body input, body textarea, body select {color:#000;font-size:12px;}
table.list_default tr td.column_label {border-right:none;width:180px;}
table.list_default tr td.colon {border-right:none;width:20px;}
table.list_default tr td.column_value {}
table.list_default tr td.column_value p {padding-left:10px;}
table.list_default tr td.column_value input[type="text"] {width:99%;display:block;}
table.list_default tr td.column_value input.short[type="text"] {width:280px;}
table.list_default tr td.column_value select.short {width:280px;}
.checkbox_item {float:left;height:28px;padding-top:6px;padding-left:1px;}
.relation_type_item {margin-right:12px}
.multi_rows_padding {padding:5px 0 5px 10px}
</style>

<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title" style="margin-bottom:9px;">
            <span><strong>取引先 - <?php echo $this->escape($this->data['company_name']); ?></strong></span>
        </div>
    	<?php
            echo $this->partial('connection/menu.phtml', array(
    			'action'    => $this->action,
    			'id'        => $this->id,
    			'direct'    => $this->direct,
    		));
        ?>   
    </div>

    <div class="clearfix">

	    <?php
        /* 投融資情報 */
        $categoryId = 1;
        ?>
		<form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th style="border-left:1px solid #ddd;border-top:1px solid #ddd;border-bottom:1px solid #ddd;"><p class="label_text strong">投融資情報</p></th>
                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                    <span>×</span>
                    </a>
                </th>
                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
                </th>
            </tr>
        </table>
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">主要投融資関係</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<?php
                		$displayString = '';
                		foreach ($invFinTypeList as $key => $val) {
                			if (!empty($this->data['inv_fin_relation'])) {
		                		foreach($this->data['inv_fin_relation'] as $eachSelected) {
			                		if ($eachSelected == $key) {
			                			$displayString .= $val . '<br>';
			                		}
		                		}
	                		}
	                	}
                	?>
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding"><?php echo $displayString; ?></div>
                	
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
	                	<div class="clearfix">
	                		<?php foreach ($invFinTypeList as $key => $val) { ?>
			                	<div class="checkbox_item relation_type_item">
				                	<label>
				                    	<input type="checkbox" name="inv_fin_relation[]" value="<?php echo $this->escape($key); ?>" <?php if (in_array($key, $this->data['inv_fin_relation'])) { echo 'checked="checked"'; } ?> value="<?php echo $this->escape($key); ?>"><?php echo $this->escape($val); ?>
				                    </label>
			                    </div>
		                    <?php } ?> 
						</div>
					</div>
                </td>
            </tr>
	
            <tr>
                <td class="column_label"><p class="label_text" style="padding-left:12px;">メモ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<div class="display_value_<?php echo $categoryId; ?> multi_rows_padding">
                		<?php if (!empty($this->data['inv_fin_memo'])) { echo nl2br($this->data['inv_fin_memo']); } ?>
                	</div>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<textarea name="inv_fin_memo" style="height:100px;margin-bottom:6px;"><?php echo $this->escape($this->data['inv_fin_memo']); ?></textarea>
					</div>
                </td>
            </tr>
        </table>
        </form>

	    <?php
        /* 指定振込先 */
        $categoryId = 2;
        ?> 
		<form id="form_category_<?php echo $categoryId; ?>">
        <table class="list_default" style="margin-bottom:0px;">
            <tr>
                <th style="border-left:1px solid #ddd;border-top:1px solid #ddd;border-bottom:1px solid #ddd;"><p class="label_text strong">指定振込先</p></th>
                <th class="cancel_category"  id="cancel_category_<?php echo $categoryId; ?>">
                    <a class="btn_cancel_category" id="btn_cancel_category_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" style="" href="javascript:void(0);">
                    <span>×</span>
                    </a>
                </th>
                <th class="edit_category" id="edit_category_<?php echo $categoryId; ?>">
                    <a class="btn_edit_category" id="btn_edit_<?php echo $categoryId; ?>" category_id="<?php echo $categoryId; ?>" href="javascript:void(0);"><span id="btn_edit_label_<?php echo $categoryId; ?>"><i class="budicon-setting" style="margin-top:-3px; padding-left:1px; font-size:20px; color:#FFF; line-height: 1; display:block;"></i></span></a>
                </th>
            </tr>
        </table>
        <table class="list_default" style="margin-bottom:13px;">
            <tr>
                <td class="column_label"><p class="label_text">金融機関名（本支店名）</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['inv_fin_account_bank']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="inv_fin_account_bank" value="<?php echo $this->escape($this->data['inv_fin_account_bank']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">預金種別</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>">
                	<?php
                		if (array_key_exists($this->data['inv_fin_account_type'], $accountTypeList)) {
                			echo $accountTypeList[$this->data['inv_fin_account_type']];
                		}
                	?>
                	</p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<select class="short" id="inv_fin_account_type" name="inv_fin_account_type" style="float:left;margin-right:20px;">
                            <option value="0">---</option>
                            <?php foreach ($accountTypeList as $key => $val) { ?>
                                <option value="<?php echo $key; ?>" <?php if ($key == $this->data['inv_fin_account_type']) echo 'selected="selected"'; ?>><?php echo $val; ?></option>
                            <?php } ?>
                    	</select>
                	</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">口座番号</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['inv_fin_account_no']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="inv_fin_account_no" value="<?php echo $this->escape($this->data['inv_fin_account_no']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>

            <tr>
                <td class="column_label"><p class="label_text">口座名義</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['inv_fin_account_name']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="inv_fin_account_name" value="<?php echo $this->escape($this->data['inv_fin_account_name']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>
            
            <tr>
                <td class="column_label"><p class="label_text">口座名義カナ</p></td>
                <td class="colon"><p class="label_text">：</p></td>
                <td class="column_value">
                	<p class="display_value_<?php echo $categoryId; ?>"><?php echo $this->escape($this->data['inv_fin_account_name_kana']); ?></p>
                	<div class="edit_value_<?php echo $categoryId; ?> clearfix" style="display:none;">
						<input type="text" name="inv_fin_account_name_kana" value="<?php echo $this->escape($this->data['inv_fin_account_name_kana']); ?>" maxlength="" />
                	</div>
                </td>
            </tr>             
        </table>
        </form>
          

	</div><!-- clearfix -->	                

</div>
</div>
</div>
</div>

