<div class="col-xs-12">
    <div class="page_title" style="position:relative;">
		<p style="position:absolute;width:76px;right:0;">
            <a class="btn_setting btn_close" style="display:block;float:left;width:76px;padding:5px 0;margin:0;border:none;background-color:#f00;">キャンセル</a>
        </p>
        <span style=""><strong>取引先担当者選択</strong></span>
    </div>
</div>


<div class="clearfix">
    <?php if (!empty($this->departmentList)) { ?>
	<?php foreach ($this->departmentList as $eachDepartment) { ?>
        <table class="list_default department" style="margin-bottom:0px;">
            <tr>
                <th class="border-left border-top border-bottom"><p class="label_text strong"><?php echo $this->escape($eachDepartment['department_name']); ?></p></th>
            </tr>
        </table>

		<table class="list_default" style="margin-bottom:13px;">
			<?php if (!empty($eachDepartment['items'])) { ?>
	        <?php foreach ($eachDepartment['items'] as $each) { ?>
		        <tr id="<?php echo $this->escape($each['id']); ?>" <?php if ($each['status'] == Shared_Model_Code::CONNECTION_STAFF_STATUS_OLD || $each['status'] == Shared_Model_Code::CONNECTION_STAFF_STATUS_RETIRED) { ?>class="inactive"<?php } ?>>
	                <td class="column_value" style="width:1000px">
	                	<div class="clearfix">
							<div style="float:left;width:240px;">
		                    	<?php
		                    		if ($each['status'] == Shared_Model_Code::CONNECTION_STAFF_STATUS_OLD) {
		                    			echo '<p style="margin-bottom:8px;"><span class="inactive">旧情報</span></p>';
		                    		} else if ($each['status'] == Shared_Model_Code::CONNECTION_STAFF_STATUS_RETIRED) {
		                    			echo '<p style="margin-bottom:8px;"><span class="inactive">退職</span></p>';
		                    		}
		                    	?>
								<div class="multi_rows_padding" style="width:223px;"><strong><?php echo $this->escape($each['staff_name']); ?></strong>&nbsp;</div>
								<div class="multi_rows_padding" style="width:223px;"><?php echo $this->escape($each['staff_name_kana']); ?>&nbsp;</div>	
							</div>
							<div style="float:left;">
								<div class="clearfix">
									<div style="float:left;width:280px;">
										<p class="column_label">登録日</p>
										<p class="colon">：</p>
										<p class="value" style="width:140px"><?php echo date('Y-m-d', strtotime($each['created'])); ?></p>
					                </div>
					                <div style="float:left;width:400px;">
						                <p class="column_label">名刺交換日</p>
										<p class="colon">：</p>
										<p class="value"><?php echo $this->escape($each['card_exchange_date']); ?></p>
									</div>
								</div>
								
								<div class="clearfix">
									<p class="column_label">役職</p>
									<p class="colon">：</p>
									<div class="multi_rows_padding" style="width:609px;"><?php echo $this->escape($each['staff_position']); ?></div>
								</div>
								
								<div class="clearfix">
									<div style="float:left;width:280px;">
										<p class="column_label">電話番号</p>
										<p class="colon">：</p>
										<p class="value" style="width:140px"><?php echo $this->escape($each['staff_tel']); ?></p>
					                </div>
					                <div style="float:left;width:400px;">
						                <p class="column_label">FAX番号</p>
										<p class="colon">：</p>
										<p class="value"><?php echo $this->escape($each['staff_fax']); ?></p>
									</div>
								</div>

								<div class="clearfix">
									<div style="float:left;width:280px;">
										<p class="column_label">携帯</p>
										<p class="colon">：</p>
										<p class="value" style="width:140px"><?php echo $this->escape($each['staff_mobile']); ?></p>
					                </div>
					                <div style="float:left;width:400px;">
										<p class="column_label">メールアドレス</p>
										<p class="colon">：</p>
										<div class="multi_rows_padding"><?php echo $this->escape($each['staff_mail']); ?></div>
									</div>
								</div>
							</div>
						</div>
	                </td>
                    <td class="td_action" style="width:78px;">
                    	<a class="option" href="javascript:selectStaff('<?php echo $this->data['id'] ?>', '<?php echo $this->escape($this->data['company_name']); ?>', '<?php echo $each['id']; ?>', '<?php echo $this->escape($each['staff_name']); ?>');">選択</a>
                    </td>
            	</tr>
		    <?php } ?>
	        <?php } ?>
	</table>

    <?php } ?>
    <?php } ?>
</div><!-- clearfix -->	                


