<?php
$payementMonthlyList = Shared_Model_Code::getPayementMonthlyList();
?>
<script type="text/javascript">
$(function () {
	$("#clear_form").bind("click", function(){
	    $(this.form).find("textarea, :text, select").val("").end().find(":checked").prop("checked", false);
	});
	
	$(document).ready(function(){
	    $('#sortable_column td').each(function(){
            $(this).css('width', $(this).width() +'px');
        });
        
        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	$(document).on('click', '.edit_content_order', function () {
        $('.display_value').hide();
        $('.edit_value').show();
    
        // ×,保存ボタン
        $(this).removeClass('edit_content_order').addClass('save_content_order');
        $(this).html('並び順保存');

        var result = $("#sortable_column").sortable("toArray");
        $('input#hidden_contents_order').val(result);
	});
	
	$(document).on('click', '.save_content_order', function () {
        var button = $(this);
        var $form = $('#register_form');
        var params = $form.serializeArray();
		
		var apiUrl = '';

        $.ajax({
            type:'POST',
            dataType:'json',
            data: params,
            success: function(res){
                var obj = res;
                if (obj.result == 'timeout') {
                    location.href = '/login';
                    return;
                } else if (obj.result == 'OK') {
                    reloadFlag = true;
                    jAlert('保存しました', '　');
                } else {
                    jAlert('' + obj.message, '　');
                }
            },
            error: function(){
                jAlert('予期せぬエラーが発生しました', 'エラー');
            },
            url: '/connection-progress/start-update-order',
        });
	});

    $(document).on('click', '#popup_ok', function () {
        location.href = '/connection-progress/start-list?type=<?php echo $this->escape($this->type); ?>&pos=' + $(window).scrollTop();
    });
    
    $(".sortable_column").sortable({
        items: "tr:not(.not-sortable)",
        update: function(event, ui){
            var result = $("#sortable_column").sortable("toArray");
            $('input#hidden_contents_order').val(result);
        },
        handle:'.order_btn_frame',
        delay: 100,
        stop: function (event, ui) {},
        start: function (event, ui) {}
    });
});    
</script>
<style type="text/css"><!--
a.edit_item {display:block;background-color:#64bd63;color:#fff;padding:2px 3px;text-decoration:none;border-radius:5px;width:80px;text-align:center;margin:3px 0 0 3px;float:left;cursor:pointer;}
.multi_rows_padding {padding:5px 12px 5px 12px;}
.order_btn_frame {float:left;margin:6px 0 0 14px;}
.order_btn_frame .icon-up-dir-1 {font-size:14px;color:#000;line-height:1;display:block;}
.order_btn_frame .icon-down-dir-1 {font-size:14px;margin-top:-6px;color:#000;line-height:1;display:block;}
a.btn_setting.save_content_order {background-color:#64bd63}
.sortable_column tr td {background-color:#fff;}
--></style>
<div class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px;margin-bottom:100px;">
<div class="row text-left">

	<div class="col-xs-12">
	    <div class="page_title" style="position:relative;">
	    	<?php if (!empty($this->adminProperty['allow_connection_progress_tag'])) { ?>
	    		<?php if ($this->conditions['type'] === 'general') { ?>
	    			<p style="position:absolute;width:189px;right:0;">
		    			<a class="btn_setting edit_content_order" style="display:block;float:left;width:92px;padding:5px 0;margin:0;border:none;margin-right:5px" href="javascript:void(0);">並び順変更</a>
						<a class="btn_setting" style="display:block;float:left;width:92px;padding:5px 0;margin:0;border:none;" href="/connection-progress/start-detail">新規登録</a>
					</p>
	    		<?php } else { ?>
					<p style="position:absolute;width:92px;right:0;">
		                <a class="btn_setting" style="display:block;float:left;width:92px;padding:5px 0;margin:0;border:none;" href="/connection-progress/start-detail">新規登録</a>
		            </p>
	    		<?php } ?>
            <?php } ?>
            
	        <span><strong>発足名称管理</strong></span>
	    </div>
	</div>

	<div class="menu_list clearfix">
	<a class="menu <?php if($this->conditions['type'] == 'general') echo "selected"; ?>" href="/connection-progress/start-list?type=general">汎用</a>
	<a class="menu <?php if($this->conditions['type'] == 'individual') echo "selected"; ?>" href="/connection-progress/start-list?type=individual">個別</a>
	</div>

	<?php if ($this->conditions['type'] !== 'general') { ?>
		<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
			<div class="condition_items clearfix">
				<form id="tag_condition_form" action="/connection-progress/start-list" method="get">
					<input type="hidden" name="search" value="1">
					<p class="search_condition_title">検索条件</p>
		
					<div class="condition_items_row clearfix">
						
						<input type="hidden" name="type" value="individual">
						
						<div class="condition_item">
							<p class="condition_label">キーワード：</p>
		                    <input type="text" name="keyword" value="<?php echo $this->conditions['keyword']; ?>">
						</div>
		
						<div class="condition_item" style="padding-top:23px;">
							<input type="button" id="clear_form" style="display:inline-block;width:116px;" value="リセット">
							<input type="submit" id="search_tag" style="display:inline-block;width:116px;" value="検索">
						</div>
					</div>
				</form>
			</div>
		</div>

		<div class="clearfix">
			<p style="float:right;margin-bottom:13px;">全<?php echo number_format($this->getHelper('Pager')->getPaginator()->getPages()->totalItemCount); ?>件 (<?php echo $this->getHelper('Pager')->getPaginator()->getPages()->pageCount; ?>ページ)</p>
	    </div>
	<?php } ?>
	

    
	<div class="col-sm-12 clearfix" style="margin-bottom:13px;">
		<form id="register_form" action="#" method="post"> 
		<table class="list_default">
			<tr>
				<th style="width:30%;"><p>発足名称</p></th>
				<th><p>検索ワードリスト</p></th>
				<?php if (!empty($this->adminProperty['allow_connection_progress_tag'])) { ?>
					<th style="width:9%;"><p>編集</p></th>
				<?php } ?>
			</tr>
			<tbody class="sortable_column" id="sortable_column">
			<?php if (!empty($this->items)) { ?>
				<?php foreach ($this->items as $each) { ?>
					<tr id="<?php echo $this->escape($each['id']); ?>">
						<td>
							<div class="multi_rows_padding"><?php echo $this->escape($each['tag_name']); ?></div>
						</td>
						
						<td>
							<?php $serachWordsList = unserialize($each['search_words_list']); ?>
							<div class="multi_rows_padding"><?php echo $this->escape(implode(' / ', $serachWordsList)); ?></div>
						</td>
						
						<?php if (!empty($this->adminProperty['allow_connection_progress_tag'])) { ?>
							<td>
								<div class="display_value">
									<a class="edit_item" href="/connection-progress/start-detail?id=<?php echo $this->escape($each['id']); ?>">編集</a>
								</div>
								<div class="edit_value">
				                    <div class="order_btn_frame edit_value" style="display:none;">
				                        <i class="icon-up-dir-1"></i>
				                        <i class="icon-down-dir-1"></i>
				                    </div>
								</div>
							</td>
						<?php } ?>
					</tr>
				<?php } ?>
			<?php } else { ?>
				<tr>
					<td colspan="<?php if (!empty($this->adminProperty['allow_connection_progress_tag'])) { ?>3<?php } else { ?>2<?php } ?>">
						<p style="text-align:center;">データがありません</p>
					</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
		<input type="hidden" id="hidden_contents_order" name="item_list" value="">
		
		<?php if ($this->conditions['type'] !== 'general') { ?>
	        <div style="padding:2.0em 0;">
	        <?php echo $this->pager() ?>
	        </div>
        <?php } ?> 
		</form>
	</div>

</div>
</div>
</div>
</div>

