<div id="contact" class="section anchor">
<div class="light-wrapper">
<div class="container inner" style="min-height:900px">
<div class="row text-left">
        
    <div class="col-xs-12">
        <div class="page_title" style="margin:1em auto; text-align:center;">
            <span style=""><strong><?php echo $this->title ?></strong></span>
        </div>
    </div>
    
    <div class="clearfix" style="text-align:center">
    <?php foreach ($this->messages as $message) : ?>
      <p class="message"><?php echo $this->escape($message) ?></p>
    <?php endforeach ?>
    </div><!-- clearfix -->
            
</div>
</div>
</div>
</div>

